<div class="l-row header report-details">
        <div class="l-two-third-column">
        
                <a href="/petroleum/reports.cfm">&lsaquo; See All Petroleum & Other Liquids Reports</a>
                <h2><?php echo "$headtitle"?></h2>

                <div class="release-dates">
                        <div class="label-series"><?php echo "$data_series"?></div>
                        <div class="date-container">
                                <div class="label">Release Date:</div>
                                <div class="date"><?php echo "$release"?></div>
                        </div>
                        <div class="date-container">
                                <div class="label">Re-release Date:</div>
                                <div class="date"><?php echo "$rerelease"?></div>
                        </div>
                        <div class="date-container">
                                <div class="label">Next Release Date:</div>
                                <div class="date"><?php echo "$next"?></div>
                        </div>
                        </div>
                </div>
        </div>
        <div class="l-one-third-column gradient">
                <span class="form-container-outer">
                        <h4>Previous Issues</h4>
                        <span class="form-container-inner">
                                <form name="form" id="form">
                                        <label>Year:</label>
                                        <select name="jumpMenu" id="jumpMenu">
                                                <option value="/petroleum/storagecapacity/archive/2017/2017_03_31/preliminary/storcap_03_31_2017prel.php"  selected="selected">March 2017</option>
                                                <option value="/petroleum/storagecapacity/archive/2016/2016_09_30/final/storcap_09_30_2016.php">September 2016</option>
                                                <option value="/petroleum/storagecapacity/archive/2016/2016_03_31/final/storcap_03_31_2016.php">March 2016</option>
                                                <option value="/petroleum/storagecapacity/archive/2015/2015_09_30/final/storcap_09_30_2015.php">September 2015</option>
                                                <option value="/petroleum/storagecapacity/archive/2015/2015_03_31/final/storcap_03_31_2015.php">March 2015</option>
                                                <option value="/petroleum/storagecapacity/archive/2014/2014_09_30/final/storcap_09_30_2014.php">September 2014</option>
                                                <option value="/petroleum/storagecapacity/archive/2014/2014_03_31/final/storcap_03_31_2014.php">March 2014</option>
                                                <option value="/petroleum/storagecapacity/archive/2013/2013_09_30/final/storcap_09_30_2013.php">September 2013</option>
                                                <option value="/petroleum/storagecapacity/archive/2013/2013_03_31/final/storcap_03_31_2013.php">March 2013</option>
                                                <option value="/petroleum/storagecapacity/archive/2012/2012_09_30/final/storcap_09_30_2012.php">September 2012</option>
                                                <option value="/petroleum/storagecapacity/archive/2012/2012_03_31/final/storcap_03_31_2012.php">March 2012</option>
                                                <option value="/petroleum/storagecapacity/archive/2011/2011_09_30/final/storcap_09_30_2011.php">September 2011</option>
                                                <option value="/petroleum/storagecapacity/archive/2011/2011_03_31/final/storcap_03_31_2011.php">March 2011</option>
                                                <option value="/petroleum/storagecapacity/archive/2010/2010_09_30/final/storcap_09_30_2010.php">September 2010</option>
                                        </select>
                                        <input type="button" name="go_button" class="arrow_go" id="go_button" value="Go" />
                                </form>
                        </span>
                </span>
        </div>
</div>

