


<!-- diff -->

<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="sub-header">Crude oil imports from Persian Gulf 2016</a> (discontinued)</li>
        <li class="sub-header">Explanatory notes</a></li>
        <li class="sub-header">Sources</strong> &nbsp;- U.S. Energy Information Administration (EIA) petroleum imports data are available at the company level. The data source is the Form EIA-814, &quot;Monthly Imports Report.&quot;</li>
        <li class="header"><h2>Related Links</h2></li>
        <li class="sub-header">Petroleum Supply Monthly</a></li>
        <li class="sub-header">U.S. Crude Import Tracking Tool</a></li>
    </ul>
</div>





<div class="content-container faq">
    <ul>
        <li class="header"><h2><a href="/tools/faqs/faq.cfm?id=32&t=6 ">How dependent is the United States on foreign oil?</a></h2></li>
        <li class="sub-header">Read all crude oil FAQs</a></li>
    </ul>
</div>
