<div class="l-row header report-details">
        <
a href="/petroleum/reports.cfm">&lsaquo; See All Petroleum & Other Liquids Reports</a>
                <h2><?php echo "$headtitle"?></h2>

                <div class="release-dates">
                        <div class="date-container">
<div class="label-series"><?php echo "$data_series"?></div>
                        </div>
                        <div class="date-container">
                                <div class="label">Release Date:</div><div class="date"><?php echo "$release"?></div>
                        </div>
                        <div class="date-container">
                                <div class="label">Next Release Date:</div>
                                <div class="date"><?php echo "$next"?></div>
</div>
<div class="download-container">
        
        <a href="data/import.xlsx"><i class="ico xls">XLS</i></a>
                                </div>
                        </div>
                </div>
        </div>
        <div class="l-split-narrow gradient">
                <span class="form-wrapper-outer">
                        <h4>Previous Issues</h4>
                        <span class="form-wrapper-inner">
                                <form name="form" id="form">
                                        <label>Month:</label>
                                        <select name="jumpMenu" id="jumpMenu">
                                                <option value="/petroleum/imports/companylevel/archive/2017/2017_06/data/import.xlsx" selected="selected">June 2017</option>
                                                <option value="/petroleum/imports/companylevel/archive/2017/2017_05/data/import.xlsx">May 2017</option>
                                                <option value="/petroleum/imports/companylevel/archive/2017/2017_04/data/import.xlsx">April 2017</option>
                                                <option value="/petroleum/imports/companylevel/archive/2017/2017_03/data/import.xlsx">March 2017</option>
                                                <option value="/petroleum/imports/companylevel/archive/2017/2017_02/data/import.xlsx">February 2017</option>
                                                <option value="/petroleum/imports/companylevel/archive/2017/2017_01/data/import.xlsx">January 2017</option>
                                                <option value="/petroleum/imports/companylevel/archive/2016/2016_12/data/import.xls">December 2016</option>
                                                <option value="/petroleum/imports/companylevel/archive/2016/2016_11/data/import.xls">November 2016</option>
                                                <option value="/petroleum/imports/companylevel/archive/2016/2016_10/data/import.xls">October 2016</option>
                                                <option value="/petroleum/imports/companylevel/archive/2016/2016_09/data/import.xls">September 2016</option>
                                                <option value="/petroleum/imports/companylevel/archive/2016/2016_08/data/import.xls">August 2016</option>
                                                <option value="/petroleum/imports/companylevel/archive/2016/2016_07/data/import.xls">July 2016</option>
                                                <option value="/petroleum/imports/companylevel/archive/">previous issues</option>
                                        </select>
                                        <input type="button" name="go_button" class="arrow_go" id="go_button" value="Go" />
                                </form>
                        </span>
                </span>
        </div>
</div>

