<?php /*h1>Hurricane Season 2011</h1>
      <p>The National Oceanic and Atmospheric Administration's  (NOAA) <em>Atlantic Hurricane Season Outlook</em>, released on May 19, 2011,  predicts that the Atlantic basin likely will experience above-normal tropical  weather activity during this year's hurricane season  (June 1 &mdash; November 30). NOAA  projects that 12 to 18 named storms will form within the Atlantic Basin over  the next 6 months, including 6 to 10 hurricanes of which 3 to 6 will be  intense.
      </p*/ ?>
      

      <h1>Energy Infrastructure Maps</h1>
<p><img src="/special/images/map_thumb.jpg" class="left" /> Explore our interactive maps! </p>
      
	  <?php /* FANCYBOX and popup */ ?>
<div id="dwrap" style="display:none;width:100%;height:100%;"><div id="outerShowGraphicDiv" style="width:100%; height:100%; position:relative;">

</div>
</div>
<script language="javascript">
$(document).ready(function(){
		$(".showGraphicLink").fancybox({
		  'width' : 975, 'height' : 875, 'autoScale' : false, 
		  'transitionIn' : 'none', 'transitionOut' : 'none', 'type' : 'iframe'
		  		});	

  	 //$("div#outerShowGraphicDiv").load("/special/east_coast/includes/ec_map.cfm", function(){$('.showGraphicLink').click();
	 //$('.showGraphicLink').trigger('click');
 });

</script>
<?php /* INSERT IMAGE HERE */ ?>

<a href="/special/gulf_of_mexico/map.cfm">View Gulf of Mexico map &gt;
</a> <br />
<a class="showGraphicLink" href="/special/gulf_of_mexico/includes/ec_map.cfm">View East Coast map &gt;</a>


<?php /*p><a href="/special/gulf_of_mexico/map.cfm">View the Gulf of Mexico map &gt;</a></p>
      <p><a href="/special/disruptions/hurricane_ec/map.cfm">View the East Coast map &gt;</a></p*/ ?>
     <hr />
      <h1>Historical Distruptions</h1>
      
      <p>In previous   years, the U.S. Energy Information Administration has tracked and published the   following special reports of selected significant energy disruption events:      
<ul>
        <li><a href="/special/disruptions/hurricane/sandy/">Sandy</a> &mdash; Landfall October 29, 2012</li>
        <li><a href="/special/disruptions/hurricane/isaac/">Isaac</a> &mdash; Landfall August 29, 2012</li>
        <li><a href="http://www.eia.gov/todayinenergy/detail.cfm?id=2830">Irene</a> &mdash; Landfall August 27, 2011</li>
        <li><a href="/special/disruptions/hurricane/ike/">Ike</a> &mdash; Landfall September 13, 2008 </li>
        <li><a href="/special/disruptions/hurricane/gustav/">Gustav</a> &mdash; Landfall September 1,   2008 </li>
        <li><a href="/special/disruptions/hurricane/rita/">Rita</a> &mdash; Landfall September 23, 2005 </li>
        <li><a href="/special/disruptions/hurricane/katrina/">Katrina</a> &mdash; August 25, 2005 </li>
      </ul>
      </p>