<span class="grey_side blue_top">
<h4>Additional Resources</h4>
<p><a href="/special/gulf_of_mexico/">Gulf of Mexico Fact Sheet &rsaquo;</a></p>
<p><a href="http://www.gomr.boemre.gov/homepg/whatsnew/hurricane/index.html">Bureau of Ocean Energy Management, Regulation and Enforcement (BOEMRE) Hurricane Information &rsaquo;</a></p>
<p><a href="http://www.oe.netl.doe.gov/emergency_sit_rpt.aspx">DOE Emergency   Situation Reports &rsaquo;</a></p>
<p><a href="/outlooks/steo/special/pdf/2012_sp_01.pdf">EIA Hurricane Outlook (pdf) &rsaquo;</a></p>
<?php /*p><a href="/special/disruptions/hurricane_gc/">Current Hurricane Information  &rsaquo;</a> </p*/ ?>
<p class="no-border"><a href="http://www.nhc.noaa.gov/">NOAA National Hurricane Center &rsaquo;</a></p>
</span>
<?php /* Side Column */ ?>
