<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2014-10/fig_HL1coppwp2.png" class="lightbox"><img src="images/2014-10/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude Oil</h2>
            <ul>
                <li>July monthly average crude oil prices fell in all categories of sale. The average domestic crude oil fi rst purchase pricedecreased $2.02 (2.0 percent), to $96.68 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil declined $1.83 (1.9 percent), to $95.81 per barrel. Theaverage landed cost of foreign crude oil fell $1.75 (1.8 percent), to $97.39 per barrel.</li>
                <li>The average refi ner acquisition cost for domestic crude oil dropped 99 cents (1.0 percent), to $103.19 per barrel. Theaverage cost of imported crude oil declined $1.50 (1.5 percent), to $98.67 per barrel. The composite refi ner acquisitioncost for crude oil decreased $1.27 (1.2 percent), to $101.18 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>Monthly average prices for refi ner sales of motor gasoline decreased considerably during July. The average retail pricefell 14.1 cents to $3.124 per gallon, while the average wholesale price declined 14.4 cents to $2.857 per gallon.</li>
                <li>Overall, sales of fi nished motor gasoline by refi ners increased in July, with total sales rising 3.7 million gallons per day(1.2 percent) to an average of 315.1 million gallons per day. While retail sales remained fl at, wholesales rose 3.7 milliongallons per day (1.3 percent). DTW sales accounted for 7.7 percent of wholesales, while rack and bulk sales made up85.6 percent and 6.7 percent, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>Monthly average refi ner prices for No. 2 distillates continued on their downward path in July. The average sales pricefor No. 2 diesel fuel to end users declined 3.9 cents to $3.025 per gallon, while the average wholesale price fell 5.0cents to $2.923 per gallon. The average price for No. 2 fuel oil sales to end users decreased 6.5 cents to $3.428 pergallon, while the average wholesale price dropped 5.3 cents to $2.825 per gallon.</li>
                <li>Refi ner sales of No. 2 ultra-low sulfur diesel fuel fell 3.7 million gallons per day (2.3 percent) to an average of 154.1million gallons per day in July. No. 2 fuel oil sales declined 1.0 million gallons per day (19.1 percent) to an averageof 4.3 million gallons per day.</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>July monthly average prices for refi ner sales of residual fuel oil show mixed trends. Prices for low-sulfur residual fueloil increased 8.9 cents to $2.977 per gallon at retail, but fell 7.1 cents to $2.287 per gallon at wholesale. Prices forhigh-sulfur residual fuel oil rose 1.0 cent to $2.324 per gallon at retail, but declined 5.9 cents to $2.188 per gallon atwholesale.</li>
                <li>At 12.3 million gallons per day, refi ner sales of residual fuel oil were fl at in July. Low-sulfur residual fuel oil sales fell300,000 gallons per day (8.0 percent), while high-sulfur residual fuel oil sales rose 400,000 gallons per day (4.9percent).</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>Prices for the remaining surveyed products show a mix of changes during June.  Propane prices increased at retail, but declined at wholesale, while kerosene-type jet fuel prices fell at both levels.  The wholesale price for aviation gasoline rose firmly, while prices for kerosene and No. 1 distillate fell at the same level.</li>
                <li>Refiner sales of propane dropped at retail, but increased at wholesale, while kerosene-type jet fuel sales rose at both levels in June.  Aviation gasoline and No. 1 distillate sales fell at wholesale, while kerosene sales increased in the same category.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>*/ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a>