<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2017-02/fig_HL1coppwp2.png" class="lightbox"><img src="images/2017-02/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude oil</h2>
            <ul>
                <li>Crude oil monthly average prices fell in November. The average domestic crude oil first purchase price decreased $3.35 (7.4%), to $41.65 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil declined $2.77 (6.5%) to $39.60 per barrel. The average landed cost of foreign crude oil fell $2.53 (5.8%), to $41.34 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil declined $2.56 (5.3%), to $46.10 per barrel. The average cost of imported crude oil decreased $2.96 (6.6%), to $41.80 per barrel. The composite refiner acquisition cost for crude oil dropped $2.79 (6.0%), to $44.06 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>November monthly average prices for refiner sales of motor gasoline fell from October levels. The average retail price decreased 6.0 cents to $1.759 per gallon, while the average wholesale price declined 14.1 cents to $1.427 per gallon.</li>
                <li>Refiner sales of finished motor gasoline decreased in November. Total sales decreased 3.2 million gallons per day (1.0%) to an average of 324.6 million gallons per day. Retail sales fell 1.3 million gallons per day (5.0%), while wholesales dropped 1.9 million gallons per day (0.6%). DTW sales accounted for 7.5% of wholesales, while rack and bulk sales made up 86.4% and 6.1%, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>Monthly average prices for refiner sales of No. 2 distillates declined in November. The average price for No. 2 diesel fuel sold to end users fell 10.5 cents to $1.601 per gallon, while the average wholesale price decreased 12.3 cents to $1.469 per gallon. The average price for sales of No. 2 fuel oil sold to end users fell 15.4 cents to $1.787 per gallon, while the wholesale price for No. 2 fuel oil dropped 5.9 cents to $1.384 per gallon.</li>
                <li>Total refiner sales of No. 2 ultra-low sulfur diesel fuel decreased in November. While retail sales rose 200,000 gallons per day (1.6%), wholesales fell 1.7 million gallons per day (1.2%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Refiner monthly average residual fuel oil prices decreased in November. The wholesale price for low-sulfur residual fuel oil dropped 4.1 cents to 92.0 cents per gallon. Prices for high-sulfur residual fuel oil fell 5.1 cents to $1.040 per gallon at retail, while the wholesale price decreased 2.8 cents to 90.7 cents per gallon.</li>
                <li>Overall, sales of residual fuel oil by refiners declined in November. Retail sales decreased 900,000 gallons per day (20.5%), while wholesales rose 100,000 gallons per day (1.4%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>Average prices for refiner sales of the remaining surveyed products were generally on the decline in November. Propane and kerosene-type jet fuel prices fell at both the retail and wholesale levels, while prices for No. 1 distillate show mixed trends. Aviation gasoline and kerosene prices decreased at wholesale.</li>
                <li>The volume of refiner sales of products included in this section varied in November. Propane and No. 1 distillate sales increased at both the retail and wholesale levels, while sales of kerosene-type jet fuel rose at retail, but fell at wholesale. Aviation gasoline sales fell at the wholesale level, while kerosene sales increased in the same sales category.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div> */ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/petroleum/marketing/annual/archive/" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a></li>
    </ul>
</div>