<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2015-08/fig_HL1coppwp2.png" class="lightbox"><img src="images/2015-08/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude Oil</h2>
            <ul>
                <li>Monthly average crude oil prices continued to rise in May.  The average domestic crude oil first purchase price rose $5.08 (10.3%), to $54.38 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil increased $5.75 (11.9%) to $54.06 per barrel.  The average landed cost of foreign crude oil rose $5.12 (10.0%), to $56.51 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil increased $4.53 (8.3%), to $59.39 per barrel.  The average cost of imported crude oil climbed $6.03 (11.7%), to $57.66 per barrel.  The composite refiner acquisition cost for crude oil rose $5.15 (9.6%), to $58.66 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>Refiner monthly average prices for sales of motor gasoline climbed in May.  The average retail price increased 26.8 cents to $2.326 per gallon, while the average wholesale price rose 24.5 cents to $2.080 per gallon.</li>
                <li>Sales of finished motor gasoline by refiners fell during May.  Total sales declined 2.1 million gallons per day (0.6%) to an average of 325.5 million gallons per day.  Retail sales increased 400,000 gallons per day (1.6%), while wholesales decreased 2.5 million gallons per day (0.8%).  DTW sales accounted for 7.6% of wholesales, while rack and bulk sales made up 85.3% and 7.1%, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>Monthly average prices for sales of No. 2 distillates by refiners increased in May.  The average sales price for No. 2 diesel fuel to end users rose 14.6 cents to $2.085 per gallon, while the average wholesale price increased 16.8 cents to $1.973 per gallon.  The average No. 2 fuel oil wholesale price climbed 11.2 cents to $1.852 per gallon.</li>
                <li>Refiner sales of No. 2 ultra-low sulfur diesel fuel declined in May.  Retail sales decreased 800,000 gallons per day (6.6%), while wholesales fell 7.0 million gallons per day (4.7%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Refiner monthly average wholesale prices for residual fuel oil rose in May.  The wholesale price for low-sulfur residual fuel oil increased 7.5 cents to $1.199 per gallon, while the price for high-sulfur residual fuel oil rose 13.3 cents to $1.247 per gallon.</li>
                <li>Sales of residual fuel oil by refiners increased 700,000 gallons per day (9.2%) to an average of 8.3 million gallons per day at the wholesale level in May.</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>Prices for the remaining surveyed products were mostly on the rise during May.  Propane prices were the exception to the general upward trend with average retail and wholesale prices showing declines. Kerosene-type jet fuel prices increased at both the retail and wholesale levels, while prices for aviation gasoline, kerosene, No. 1 distillate, and No. 4 distillate increased at wholesale.</li>
                <li>Refiner sales of propane and kerosene-type jet fuel rose at retail, but declined at wholesale.  Aviation gasoline, kerosene, and No. 1 distillate sales fell at wholesale, while sales of No. 4 distillate were flat in the same category.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>*/ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/petroleum/marketing/annual/archive/" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a></li>
    </ul>
</div>