<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related Links</h2>
            <ul>
                <li><a href="/finance/genealogy/">Genealogy Of Major U.S. Refiners</a> A schematic showing mergers and acquisitions of major U.S. refiners.</li>
                <li><a href="/dnav/pet/pet_pnp_capwork_dcu_nus_a.htm">Working Storage Capacity at Operable Refineries</a> Historical Data 1982 - 2010</li>
                <li><a href="/dnav/pet/pet_pnp_capshell_dcu_nus_a.htm">Shell Storage Capacity at Operable Refineries</a> Historical Data 1982 - 2010</li>
            </ul>
        </li>
    </ul>
</div>





<div class="content-container faq">
    <ul>
        <li class="header"><h2><a href="/tools/faqs/faq.cfm?id=29&amp;t=6 ">When was the last refinery built in the United States?</a></h2></li>
        <li class="sub-header">Read all crude oil FAQs</a></li>
    </ul>
</div>





<div class="content-container">
    <ul>
        <li><strong>Note:</strong> The EIA-820 refinery capacity survey was not conducted for January 1, 1996 or January 1, 1998.</li>
        <li>The Refinery Capacity Report became a separate product in 2006, which includes tables in PDF format and an individual refinery XLS file.</li>
        <li>Individual refinery XLS files from 1994 - 2005 are available from the drop down menu above.</li>
        <li>Previous versions of the tables from 1995 - 2004 are available on the <a href="/petroleum/supply/annual/volume1/">Petroleum Supply Annual, Volume 1 Historical</a> page.</li>
    </ul>
</div>
