<div class="l-row header report-details">
        <div class="l-two-third-column">
        
                <a href="/petroleum/reports.cfm">&lsaquo; See All Petroleum & Other Liquids Reports</a>
                <h2><?php echo "$headtitle"?></h2>

                <div class="release-dates">
                        <div class="label-series"><?php echo "$data_series"?></div>
                        <div class="date-container">
                                <div class="label">Release Date:</div>
                                <div class="date"><?php echo "$release"?></div>
                        </div>
                        <div class="date-container">
                                <div class="label">Next Release Date:</div>
                                <div class="date"><?php echo "$next"?></div>
                        </div>
                        </div>
                </div>
        </div>
        <div class="l-one-third-column gradient">
                <span class="form-wrapper-outer">
                        <h4>Previous Issues</h4>
                        <span class="form-wrapper-inner">
                                <form name="form" id="form">
                                        <label>Year:</label>
                                        <select name="jumpMenu" id="jumpMenu">
                                                <option value="/petroleum/refinerycapacity/archive/2017/refcap2017.php" selected="selected">2017</option>
                                                <option value="/petroleum/refinerycapacity/archive/2016/refcap2016.php">2016</option>
                                                <option value="/petroleum/refinerycapacity/archive/2015/refcap2015.php">2015</option>
                                                <option value="/petroleum/refinerycapacity/archive/2014/refcap2014.php">2014</option>
                                                <option value="/petroleum/refinerycapacity/archive/2013/refcap2013.php">2013</option>
                                                <option value="/petroleum/refinerycapacity/archive/2012/refcap2012.php">2012</option>
                                                <option value="/petroleum/refinerycapacity/archive/2011/refcap2011.php">2011</option>
                                                <option value="/petroleum/refinerycapacity/archive/2010/refcap2010.html">2010</option>
                                                <option value="/petroleum/refinerycapacity/archive/2009/refcap2009.html">2009</option>
                                                <option value="/petroleum/refinerycapacity/archive/2008/refcap2008.html">2008</option>
                                                <option value="/petroleum/refinerycapacity/archive/2007/refcap2007.html">2007</option>
<!--option value="/petroleum/refinerycapacity/archive/2006/refcap2006.html">2006</option-->
<!--option value="/petroleum/refinerycapacity/archive/2005/refcap05.xls">2005</option-->
<!--option value="/petroleum/refinerycapacity/archive/2004/refcap04.xls">2004</option-->
<!--option value="/petroleum/refinerycapacity/archive/2003/refcap03.xls">2003</option-->
<!--option value="/petroleum/refinerycapacity/archive/2002/refcap02.xls">2002</option-->
<!--option value="/petroleum/refinerycapacity/archive/2001/refcap01.xls">2001</option-->
<!--option value="/petroleum/refinerycapacity/archive/2000/refcap00.xls">2000</option-->
<!--option value="/petroleum/refinerycapacity/archive/1999/refcap99.xls">1999</option-->
<!--option value="/petroleum/refinerycapacity/archive/1997/refcap97.xls">1997</option-->
<!--option value="/petroleum/refinerycapacity/archive/1995/refcap95.xls">1995</option-->
<!--option value="/petroleum/refinerycapacity/archive/1994/refcap94.xls">1994</option-->
                                                <option value="/petroleum/refinerycapacity/archive/">prior issues</option>
                                        </select>
                                        <input type="button" name="go_button" class="arrow_go" id="go_button" value="Go" />
                                </form>
                        </span>
                </span>
        </div>
</div>

