<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2015-07/fig_HL1coppwp2.png" class="lightbox"><img src="images/2015-07/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude Oil</h2>
            <ul>
                <li>Monthly average crude oil prices increased in April.  The average domestic crude oil first purchase price climbed $6.64 (15.6%), to $49.30 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil rose $4.65 (10.7%) to $48.22 per barrel.  The average landed cost of foreign crude oil increased $3.97 (8.5%), to $50.43 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil climbed $6.17 (12.7%), to $54.86 per barrel.  The average cost of imported crude oil increased $4.36 (9.2%), to $51.63 per barrel.  The composite refiner acquisition cost for crude oil rose $5.45 (11.3%), to $53.51 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>Refiner monthly average prices for sales of motor gasoline continued to rise in April.  The average retail price increased 0.4 cent to $2.058 per gallon, while the average wholesale price rose 6.7 cents to $1.837 per gallon.</li>
                <li>Sales of finished motor gasoline by refiners increased in April.  Total sales rose 10.7 million gallons per day (3.4%) to an average of 328.3 million gallons per day.  Retail sales increased 400,000 gallons per day (2.4%), while wholesales rose 10.1 million gallons per day (3.4%).  DTW sales accounted for 8.0% of wholesales, while rack and bulk sales made up 84.5% and 7.6%, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>Refiner monthly average prices for sales of No. 2 distillates declined in April.  The average sales price for No. 2 diesel fuel to end users fell 2.3 cents to $1.939 per gallon, while the average wholesale price dropped 1.1 cents to $1.804 per gallon.  The average wholesale price for No. 2 fuel oil decreased 10.7 cents to $1.740 per gallon.</li>
                <li>Overall, refiner sales of No. 2 ultra-low sulfur diesel fuel rose during April.  While retail sales declined 300,000 gallons per day (2.4%), wholesales increased 9.3 million gallons per day (6.6%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>The direction of monthly average prices for refiner sales of residual fuel oil varied in April.  The wholesale price for low-sulfur residual fuel oil increased 3.1 cents to $1.124 per gallon.  Prices for high-sulfur residual fuel oil rose 2.9 cents to $1.465 per gallon at retail, but fell 1.1 cents per gallon to $1.120 per gallon at wholesale.</li>
                <li>Sales of residual fuel oil by refiners increased in April.  Total sales climbed 1.0 million gallons per day (8.8%) to an average of 12.3 million gallons per day.</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>Prices for the remaining surveyed products show mixed trends in April.  Propane and kerosene-type jet fuel prices declined at both the retail and wholesale levels.  Prices for aviation gasoline, No. 1 distillate, and No. 4 distillate increased at wholesale, while the price for kerosene declined at the same level.</li>
                <li>During April, refiner propane sales were flat at retail, but fell at wholesale, while sales of kerosene-type jet fuel increased at both levels.  Aviation gasoline, kerosene, and No. 4 distillate sales rose at wholesale, while No. 1 distillate sales declined in the same category.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>*/ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/petroleum/marketing/annual/archive/" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a></li>
    </ul>
</div>