<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2017-08/fig_HL1coppwp2.png" class="lightbox"><img src="images/2017-08/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude oil</h2>
            <ul>
                <li>Monthly average crude oil prices show mixed movements in May. The average domestic crude oil first purchase price fell $2.04 (4.3%), to $45.19 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil rose $1.02 (2.3%) to $44.60 per barrel. The average landed cost of foreign crude oil increased 49 cents (1.1%), to $46.45 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil dropped $1.90 (3.7%), to $49.44 per barrel. The average cost of imported crude oil declined 53 cents (1.1%), to $46.94 per barrel. The composite refiner acquisition cost for crude oil decreased $1.23 (2.5%), to $48.24` per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>Refiner monthly average prices for motor gasoline continued to fall in May. The average retail price decreased 3.4 cents to $1.963 per gallon, while the average wholesale price declined 5.6 cents to $1.667 per gallon.</li>
                <li>Refiner sales of finished motor gasoline rose in May. Total sales climbed 3.3 million gallons per day (1.0%) to an average of 330.5 million gallons per day. Retail sales increased 600,000 gallons per day (2.5%), while wholesales rose 2.7 million gallons per day (0.9%). DTW sales accounted for 7.5% of wholesales, while rack and bulk sales made up 86.9% and 5.7%, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>Monthly average prices for refiner sales of No. 2 distillates were on the decline during May. The average price for No. 2 diesel fuel sold to end users fell 5.3 cents to $1.694 per gallon, while the average wholesale price declined 7.4 cents to $1.553 per gallon. The average wholesale price for No. 2 fuel oil decreased 5.4 cents to $1.445 per gallon.</li>
                <li>Refiner sales of No. 2 ultra-low sulfur diesel fuel increased 10.9 million gallons per day (7.4%) to 159.1 million gallons per day in May. Retail sales rose 300,000 gallons per day (2.6%), while wholesales increased 10.6 million gallons per day (7.8%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Refiner monthly average residual fuel oil prices show mixed trends in May. The wholesale price for low-sulfur residual fuel oil dropped 5.2 cents to $0.986 per gallon. The price for high-sulfur residual fuel oil rose 0.6 cent to $1.153 per gallon at retail, while the wholesale price increased 1.1 cents to $1.050 per gallon.</li>
                <li>Refiner residual fuel oil sales fell 300,000 gallons per day (3.0%) to 9.7 million gallons per day in May. Retail sales remained flat, while wholesales decreased 300,000 gallons per day (4.8%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>Refiner prices for the remaining surveyed products fell in May. Prices for propane and kerosene-type jet fuel fell at both the retail and wholesale levels. Prices for aviation gasoline, kerosene, and No. 1 distillate also declined at wholesale.</li>
                <li>Refiner propane sales rose at the retail level, but decreased at wholesale during May, while kerosene-type jet fuel sales increased in both categories. Sales of aviation gasoline and kerosene increased at the wholesale level, while No. 1 distillate sales fell in the same category.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>*/ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/petroleum/marketing/annual/archive/" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a></li>
    </ul>
</div>