<div class="l-row header report-details">
        <div class="l-full-width-column">
                <a href="/electricity/reports.cfm">&lsaquo; See All Electricity Reports</a>
                <h2><?php echo "$headtitle"?></h2>

                <div class="release-dates">
                        <div class="date-container">
<div class="label-series"><?php echo "$data_series"?></div>
<div class="label">Release Date:</div>
                                <div class="date"><?php echo "$release" ?></div>
</div>
</div>
</div>
</div>
