<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Supplemental Data</h2></li>
<.li>Annual Electric Utility data - EIA-861 data file, includes county service areas <a href="/electricity/data/eia861/" title="Annual Electric Utility data - EIA-861 data file, includes county service areas">dbf.xlsx</a></li>
<.li>1990 - 2015	Average Price by State by Provider (EIA-861) <a href="/electricity/data/state/avgprice_annual.xlsx"><i class="ico xls">XLS</i></a></li>
<.li>1990 - 2015	Number of Retail Customers by State by Sector (EIA-861) <a href="/electricity/data/state/customers_annual.xlsx"><i class="ico xls">XLS</i></a></li>
<.li>1990 - 2015	Retail Sales of Electricity by State by Sector by Provider (EIA-861) <a href="/electricity/data/state/sales_annual.xlsx"><i class="ico xls">XLS</i></a></li>
<.li>1990 - 2015	Revenue from Retail Sales of Electricity by State by Sector by Provider (EIA-861) <a href="/electricity/data/state/revenue_annual.xlsx"><i class="ico xls">XLS</i></a></li>
    </ul>
</div>
