<div class="content-container light-top-border-container grey-background">    <ul>
        <li><a href="/petroleum/archive/comparison7822010.pdf">Full report<i class="ico pdf">PDF</i></a></li>
        <li class="form-label">Previous editions</li>
        <li><form name="form" id="form">
<label>Year: </label>
<select name="jumpMenu" id="jumpMenu" style="width:110px">
<option value="/petroleum/archive/comparison7822009.pdf">1998 to 2007</option>
<option value="/petroleum/archive/comparison7822008.pdf">1994-2006</option>
<option value="/petroleum/archive/comparison7822007.pdf">1994-2005</option>
<option value="/petroleum/archive/article782.pdf">1995-2003</option>
<option value="/petroleum/archive/comparison782.pdf">1995-2001</option>
<option value="/petroleum/archive/art9912.pdf">1983-1998</option>
</select>
<input type="button" name="go_button" class="arrow_go" id= "go_button" value="Go" onclick="MM_jumpMenuGo('jumpMenu','parent',1)" />
</form></li>
    </ul>
</div>
