<div class="content-container light-top-border-container grey-background">    <ul>
        <li><a href="/petroleum/archive/art0509.pdf">Full report<i class="ico pdf">PDF</i></a></li>
        <li class="form-label">Previous editions</li>
        <li><form name="form" id="form">
<label>Year: </label>
<select name="jumpMenu" id="jumpMenu">
<option value="/petroleum/archive/art0406.pdf">1993-2002</option>
<option value="/petroleum/archive/art0012.pdf">1990-1999</option>
<option value="/petroleum/archive/art9907.pdf">1988-1997</option>
</select>
<input type="button" name="go_button" class="arrow_go" id= "go_button" value="Go" onclick="MM_jumpMenuGo('jumpMenu','parent',1)" />
</form></li>
    </ul>
</div>
