<div class="content-container light-top-border-container grey-background">
    <ul>
        <li><a href="/petroleum/archive/art0902.pdf">Full report<i class="ico pdf">PDF</i></a></li>
        <li class="form-label">Previous editions</li>
        <li><form name="form" id="form">
            <label>Year: </label>
            <select name="jumpMenu" id="jumpMenu">
            <option value="/petroleum/archive/art0804.pdf">2008</option>
            <option value="/petroleum/archive/art0703.pdf">2007</option>
            <option value="/petroleum/archive/art0510.pdf">2005</option>
            <option value="/petroleum/archive/art0410.pdf">2004</option>
            <option value="/petroleum/archive/art0310.pdf">2003</option>
            <option value="/petroleum/archive/art0209.pdf">2002</option>
            <option value="/petroleum/archive/art0110.pdf">2001</option>
            <option value="/petroleum/archive/art0010.pdf">2000</option>
            <option value="/petroleum/archive/art9912a.pdf">1999</option>
            <option value="/petroleum/archive/accpsd97.pdf">1998</option>
            <option value="/petroleum/archive/accpsd96.pdf">1997</option>
            </select>
            <input type="button" name="go_button" class="arrow_go" id= "go_button" value="Go" onclick="MM_jumpMenuGo('jumpMenu','parent',1)" />
            </form></li>
    </ul>
</div>
