<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong> Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2013-05/fig_HL1coppwp.jpg" class="lightbox"><img src="images/2013-05/fig_HL1_coppwp_sm.jpg" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3>Highlights</h3></li>
                <li><p>The daily spot price for West Texas Intermediate (WTI)crude oil at Cushing, Oklahoma trended downwardsduring February. After opening at its highest level for themonth, $97.65 per barrel, the price experienced modestdecreases until mid-month when weekly inventoryreports showing a drop in crude oil and refined productstocks underpinned a short-lived increase in the price'slevel. Wider economic factors along with slowerdemand for crude oil weighed on the price through theend of the month. Closing February at its lowest point,$92.03 per barrel, the price was $5.62 below its openinglevel. Averaging $95.31 per barrel for the month overall,the price was 55 cents (0.5 percent) lower than January'saverage of $94.76 per barrel. The February 2013 averageprice is also $6.89 (6.7 percent) less than the year-agoprice of $102.20 per barrel.  ...</p></li>
                <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>