<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2017-03/fig_HL1coppwp2.png" class="lightbox"><img src="images/2017-03/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude oil</h2>
            <ul>
                <li>Monthly average prices for crude oil increased in December. The average domestic crude oil first purchase price rose $5.47 (13.1%), to $47.12 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil increased $4.90 (12.3%) to $44.83 per barrel. The average landed cost of foreign crude oil rose $4.05 (9.6%), to $46.12 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil rose $4.28 (9.3%), to $50.38 per barrel. The average cost of imported crude oil climbed $4.92 (11.8%), to $46.72 per barrel. The composite refiner acquisition cost for crude oil increased $4.56 (10.3%), to $48.62 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>Refiner monthly average prices for motor gasoline were on the rise in December. The average retail price increased 8.9 cents to $1.848 per gallon, while the average wholesale price climbed 15.8 cents to $1.585 per gallon.</li>
                <li>Refiner sales of finished motor gasoline fell in December. Total sales decreased 1.8 million gallons per day (0.6%) to an average of 322.4 million gallons per day. Retail sales declined 500,000 gallons per day (2.0%), while wholesales decreased 1.3 million gallons per day (0.4%). DTW sales accounted for 7.6% of wholesales, while rack and bulk sales made up 86.2% and 6.2%, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>Monthly average prices for refiner sales of No. 2 distillates rose in December. The average price for No. 2 diesel fuel sold to end users increased 11.8 cents to $1.717 per gallon, while the average wholesale price rose 13.8 cents to $1.607 per gallon. The average price for sales of No. 2 fuel oil sold to end users climbed 21.0 cents to $1.997 per gallon, while the wholesale price for No. 2 fuel oil increased 12.1 cents to $1.507 per gallon.</li>
                <li>Total refiner sales of No. 2 ultra-low sulfur diesel fuel fell in December. Retail sales decreased 1.3 million gallons per day (10.1%), while wholesales declined 2.3 million gallons per day (1.6%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Refiner monthly average residual fuel oil prices increased in December. The wholesale price for low-sulfur residual fuel oil rose 10.4 cents to $1.024 per gallon. Prices for high-sulfur residual fuel oil climbed 16.4 cents to $1.204 per gallon at retail, while the wholesale price rose 12.4 cents to $1.031 per gallon.</li>
                <li>Sales of residual fuel oil by refiners increased in December. Retail sales rose 300,000 gallons per day (7.5%), while wholesales increased 400,000 gallons per day (5.6%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>Refiner prices for remaining surveyed products rose in December. Propane and kerosene-type jet fuel prices increased at both the retail and wholesale levels, while prices for aviation gasoline, kerosene, and No. 1 distillate prices climbed at wholesale.</li>
                <li>The volume of refiner sales of products included in this section were mostly on the rise during December. Propane sales increased at both the retail and wholesale levels, while sales of kerosene-type jet fuel fell at retail, but rose at wholesale. Sales of aviation gasoline, kerosene, and No. 1 distillate increased at the wholesale level.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div> */ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/petroleum/marketing/annual/archive/" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a></li>
    </ul>
</div>