<table class="data"><col width="30"/>
<col width="40"/>
<col width="40"/>
<col width="40"/>
<col width="40"/>
<col width="1"/>
<col width="20"/>
<col width="20"/>
<col width="10"/>
<tr>
<th colspan="9">
<span style="font-weight:normal; font-size:11px; color:grey; float:right; margin-top:-10px; margin-right:-10px">(also available in <a href="/dnav/pet/pet_cons_prim_a_EPM0_P00_Mgalpd_m.htm">thousand gallons per day</a>)</span>
</strong>
Prime supplier sales volumes of gasoline</a> by U.S. and PADD regions
</strong>
<span style="font-weight:normal">thousand gallons </span></th>
</tr>
<tr>
<td class="no-border">&nbsp;</td>
<td class="no-border">&nbsp;</td>
<td class="no-border">&nbsp;</td>
<td colspan="2" class="align-center"><strong>YTD</strong></td>
<td class="no-border" style="width:1px"> </td>
<td colspan="3" class="align-center"><strong>% change</strong><sup>1</sup></td>
</tr>
<tr>
<td><strong>Area</strong></td>
<td><strong>May 2017</strong></td>
<td><strong>June 2017</strong></td>
<td><strong>2016</strong></td>
<td><strong>2017</strong></td>
<td class="no-border" style="width:1px"> </td>
<td class="no-wrap"><strong>month</strong> ago</strong></td>
<td class="no-wrap"><strong>year</strong> ago</strong></td>
<td class="no-wrap"><strong>YTD</strong></td>
</tr>
<tr>
<td class="align-left">U.S.</td>
<td>11,901,057</td>
<td>11,807,911</td>
<td>66,844,513</td>
<td>67,235,392</td>
<td class="no-border" style="width:1px"> </td>
<td>2.5</td>
<td>1.0</td>
<td>1.1</td>
</tr>
<tr>
<td class="align-left">PADD 1</td>
<td>3,934,211</td>
<td>3,879,545</td>
<td>22,528,518</td>
<td>22,306,757</td>
<td class="no-border" style="width:1px"> </td>
<td>1.9</td>
<td>-1.4</td>
<td>-0.4</td>
</tr>
<tr>
<td class="align-left">PADD 2</td>
<td>3,279,135</td>
<td>3,301,615</td>
<td>18,273,068</td>
<td>18,344,905</td>
<td class="no-border" style="width:1px"> </td>
<td>4.0</td>
<td>2.6</td>
<td>0.9</td>
</tr>
<tr>
<td class="align-left">PADD 3</td>
<td>2,144,437</td>
<td>2,109,910</td>
<td>11,708,421</td>
<td>12,184,253</td>
<td class="no-border" style="width:1px"> </td>
<td>1.7</td>
<td>3.1</td>
<td>4.6</td>
</tr>
<tr>
<td class="align-left">PADD 4</td>
<td>475,179</td>
<td>482,043</td>
<td>2,546,852</td>
<td>2,635,665</td>
<td class="no-border" style="width:1px"> </td>
<td>4.8</td>
<td>3.3</td>
<td>4.1</td>
</tr>
<tr>
<td class="align-left">PADD 5</td>
<td>2,068,095</td>
<td>2,034,798</td>
<td>11,787,654</td>
<td>11,763,812</td>
<td class="no-border" style="width:1px"> </td>
<td>1.7</td>
<td>0.7</td>
<td>0.3</td>
</tr>
<tr>
<th colspan="9"></strong>Prime supplier sales volumes of gasoline by state </strong><span style="font-weight:normal">thousand gallons </span></th>
</tr>
<tr>
<td class="no-border">&nbsp;</td>
<td class="no-border">&nbsp;</td>
<td class="no-border">&nbsp;</td>
<td colspan="2" class="align-center"><strong>YTD</strong></td>
<td class="no-border" style="width:1px"> </td>
<td colspan="3" class="align-center"><strong>% change</strong><sup>1</sup></td>
</tr>
<tr>
<td colspan="1"><strong>State</strong></td>
<td><strong>May 2017</strong></td>
<td><strong>June 2017</strong></td>
<td><strong>2016</strong></td>
<td><strong>2017</strong></td>
<td style="width:1px"> </td>
<td class="no-wrap"><strong>month</strong> ago</strong></td>
<td class="no-wrap"><strong>year</strong> ago</strong></td>
<td class="no-wrap"><strong>YTD</strong></td>
</tr>
<tr>
<td class="align-left">Alaska</td>
<td>22,466</td>
<td>25,667</td>
<td>127,559</td>
<td>129,459</td>
<td style="width:1px"> </td>
<td>18.1</td>
<td>3.1</td>
<td>2.1</td>
</tr>
<tr>
<td class="align-left">Alabama</td>
<td>214,152</td>
<td>211,359</td>
<td>1,190,241</td>
<td>1,199,993</td>
<td style="width:1px"> </td>
<td>2.0</td>
<td>1.3</td>
<td>1.4</td>
</tr>
<tr>
<td class="align-left">Arkansas</td>
<td>125,419</td>
<td>124,704</td>
<td>709,986</td>
<td>699,339</td>
<td style="width:1px"> </td>
<td>2.7</td>
<td>0.4</td>
<td>-1.0</td>
</tr>
<tr>
<td class="align-left">Arizona</td>
<td>261,188</td>
<td>248,327</td>
<td>1,492,476</td>
<td>1,525,093</td>
<td style="width:1px"> </td>
<td>-1.8</td>
<td>1.8</td>
<td>2.7</td>
</tr>
<tr>
<td class="align-left">California</td>
<td>1,262,711</td>
<td>1,236,928</td>
<td>7,200,794</td>
<td>7,188,142</td>
<td style="width:1px"> </td>
<td>1.2</td>
<td>0.8</td>
<td>0.4</td>
</tr>
<tr>
<td class="align-left">Colorado</td>
<td>197,102</td>
<td>195,480</td>
<td>1,024,886</td>
<td>1,103,646</td>
<td style="width:1px"> </td>
<td>2.5</td>
<td>7.1</td>
<td>8.3</td>
</tr>
<tr>
<td class="align-left">Connecticut</td>
<td>131,687</td>
<td>133,962</td>
<td>801,079</td>
<td>736,399</td>
<td style="width:1px"> </td>
<td>5.1</td>
<td>1.3</td>
<td>-7.6</td>
</tr>
<tr>
<td class="align-left">D.C.</td>
<td>5,891</td>
<td>5,745</td>
<td>34,324</td>
<td>34,366</td>
<td style="width:1px"> </td>
<td>0.8</td>
<td>-3.4</td>
<td>0.7</td>
</tr>
<tr>
<td class="align-left">Delaware</td>
<td>41,011</td>
<td>38,742</td>
<td>220,076</td>
<td>224,875</td>
<td style="width:1px"> </td>
<td>-2.4</td>
<td>-6.4</td>
<td>2.7</td>
</tr>
<tr>
<td class="align-left">Florida</td>
<td>654,636</td>
<td>600,707</td>
<td>3,841,318</td>
<td>3,727,100</td>
<td style="width:1px"> </td>
<td>-5.2</td>
<td>-2.2</td>
<td>-2.4</td>
</tr>
<tr>
<td class="align-left">Georgia</td>
<td>424,117</td>
<td>416,720</td>
<td>2,502,656</td>
<td>2,437,421</td>
<td style="width:1px"> </td>
<td>1.5</td>
<td>-4.3</td>
<td>-2.1</td>
</tr>
<tr>
<td class="align-left">Hawaii</td>
<td>40,788</td>
<td>38,796</td>
<td>236,957</td>
<td>233,370</td>
<td style="width:1px"> </td>
<td>-1.7</td>
<td>0.0</td>
<td>-1.0</td>
</tr>
<tr>
<td class="align-left">Iowa</td>
<td>105,144</td>
<td>110,038</td>
<td>572,654</td>
<td>563,134</td>
<td style="width:1px"> </td>
<td>8.1</td>
<td>-4.1</td>
<td>-1.1</td>
</tr>
<tr>
<td class="align-left">Idaho</td>
<td>64,435</td>
<td>66,916</td>
<td>357,922</td>
<td>359,732</td>
<td style="width:1px"> </td>
<td>7.3</td>
<td>5.1</td>
<td>1.1</td>
</tr>
<tr>
<td class="align-left">Illinois</td>
<td>417,482</td>
<td>416,675</td>
<td>2,400,825</td>
<td>2,361,966</td>
<td style="width:1px"> </td>
<td>3.1</td>
<td>0.1</td>
<td>-1.1</td>
</tr>
<tr>
<td class="align-left">Indiana</td>
<td>279,195</td>
<td>282,313</td>
<td>1,568,863</td>
<td>1,584,833</td>
<td style="width:1px"> </td>
<td>4.5</td>
<td>3.2</td>
<td>1.6</td>
</tr>
<tr>
<td class="align-left">Kansas</td>
<td>140,309</td>
<td>141,744</td>
<td>779,303</td>
<td>794,836</td>
<td style="width:1px"> </td>
<td>4.4</td>
<td>4.2</td>
<td>2.6</td>
</tr>
<tr>
<td class="align-left">Kentucky</td>
<td>178,867</td>
<td>175,621</td>
<td>995,348</td>
<td>996,697</td>
<td style="width:1px"> </td>
<td>1.5</td>
<td>0.5</td>
<td>0.7</td>
</tr>
<tr>
<td class="align-left">Louisiana</td>
<td>246,244</td>
<td>232,336</td>
<td>1,318,684</td>
<td>1,368,738</td>
<td style="width:1px"> </td>
<td>-2.5</td>
<td>3.3</td>
<td>4.4</td>
</tr>
<tr>
<td class="align-left">Massachusetts</td>
<td>226,980</td>
<td>228,283</td>
<td>1,273,572</td>
<td>1,281,063</td>
<td style="width:1px"> </td>
<td>3.9</td>
<td>-2.2</td>
<td>1.1</td>
</tr>
<tr>
<td class="align-left">Maryland</td>
<td>183,559</td>
<td>176,578</td>
<td>1,017,631</td>
<td>1,031,285</td>
<td style="width:1px"> </td>
<td>-0.6</td>
<td>-2.5</td>
<td>1.9</td>
</tr>
<tr>
<td class="align-left">Maine</td>
<td>60,264</td>
<td>65,521</td>
<td>340,582</td>
<td>344,546</td>
<td style="width:1px"> </td>
<td>12.3</td>
<td>4.4</td>
<td>1.7</td>
</tr>
<tr>
<td class="align-left">Michigan</td>
<td>408,176</td>
<td>411,550</td>
<td>2,228,927</td>
<td>2,262,261</td>
<td style="width:1px"> </td>
<td>4.2</td>
<td>5.8</td>
<td>2.1</td>
</tr>
<tr>
<td class="align-left">Minnesota</td>
<td>195,677</td>
<td>211,528</td>
<td>1,180,617</td>
<td>1,130,258</td>
<td style="width:1px"> </td>
<td>11.7</td>
<td>-1.6</td>
<td>-3.7</td>
</tr>
<tr>
<td class="align-left">Missouri</td>
<td>257,875</td>
<td>260,886</td>
<td>1,381,778</td>
<td>1,424,258</td>
<td style="width:1px"> </td>
<td>4.5</td>
<td>5.7</td>
<td>3.6</td>
</tr>
<tr>
<td class="align-left">Mississippi</td>
<td>161,275</td>
<td>152,930</td>
<td>858,969</td>
<td>891,781</td>
<td style="width:1px"> </td>
<td>-2.0</td>
<td>-7.0</td>
<td>4.4</td>
</tr>
<tr>
<td class="align-left">Montana</td>
<td>65,468</td>
<td>70,961</td>
<td>350,937</td>
<td>348,923</td>
<td style="width:1px"> </td>
<td>12.0</td>
<td>0.2</td>
<td>0.0</td>
</tr>
<tr>
<td class="align-left">North Carolina</td>
<td>386,142</td>
<td>386,393</td>
<td>2,169,427</td>
<td>2,191,777</td>
<td style="width:1px"> </td>
<td>3.4</td>
<td>2.2</td>
<td>1.6</td>
</tr>
<tr>
<td class="align-left">North Dakota</td>
<td>38,906</td>
<td>36,067</td>
<td>193,324</td>
<td>203,231</td>
<td style="width:1px"> </td>
<td>-4.2</td>
<td>-2.4</td>
<td>5.7</td>
</tr>
<tr>
<td class="align-left">Nebraska</td>
<td>71,032</td>
<td>71,709</td>
<td>386,471</td>
<td>386,304</td>
<td style="width:1px"> </td>
<td>4.3</td>
<td>-0.4</td>
<td>0.5</td>
</tr>
<tr>
<td class="align-left">New Hampshire</td>
<td>46,670</td>
<td>52,977</td>
<td>281,742</td>
<td>272,715</td>
<td style="width:1px"> </td>
<td>17.3</td>
<td>10.7</td>
<td>-2.7</td>
</tr>
<tr>
<td class="align-left">New Jersey</td>
<td>330,781</td>
<td>318,116</td>
<td>1,989,476</td>
<td>1,851,388</td>
<td style="width:1px"> </td>
<td>-0.6</td>
<td>-11.8</td>
<td>-6.4</td>
</tr>
<tr>
<td class="align-left">New Mexico</td>
<td>85,506</td>
<td>86,550</td>
<td>481,790</td>
<td>481,912</td>
<td style="width:1px"> </td>
<td>4.6</td>
<td>2.0</td>
<td>0.6</td>
</tr>
<tr>
<td class="align-left">Nevada</td>
<td>98,357</td>
<td>100,802</td>
<td>554,335</td>
<td>563,708</td>
<td style="width:1px"> </td>
<td>5.9</td>
<td>4.4</td>
<td>2.3</td>
</tr>
<tr>
<td class="align-left">New York</td>
<td>469,340</td>
<td>482,079</td>
<td>2,769,687</td>
<td>2,671,505</td>
<td style="width:1px"> </td>
<td>6.1</td>
<td>-3.7</td>
<td>-3.0</td>
</tr>
<tr>
<td class="align-left">Ohio</td>
<td>419,932</td>
<td>411,424</td>
<td>2,326,352</td>
<td>2,347,268</td>
<td style="width:1px"> </td>
<td>1.2</td>
<td>1.5</td>
<td>1.5</td>
</tr>
<tr>
<td class="align-left">Oklahoma</td>
<td>181,294</td>
<td>180,377</td>
<td>1,048,638</td>
<td>1,037,863</td>
<td style="width:1px"> </td>
<td>2.8</td>
<td>4.0</td>
<td>-0.5</td>
</tr>
<tr>
<td class="align-left">Oregon</td>
<td>143,680</td>
<td>143,687</td>
<td>806,335</td>
<td>779,724</td>
<td style="width:1px"> </td>
<td>3.3</td>
<td>-4.0</td>
<td>-2.8</td>
</tr>
<tr>
<td class="align-left">Pennsylvania</td>
<td>294,966</td>
<td>294,531</td>
<td>1,465,827</td>
<td>1,668,859</td>
<td style="width:1px"> </td>
<td>3.2</td>
<td>12.5</td>
<td>14.5</td>
</tr>
<tr>
<td class="align-left">Rhode Island</td>
<td>54,436</td>
<td>55,168</td>
<td>313,435</td>
<td>309,342</td>
<td style="width:1px"> </td>
<td>4.7</td>
<td>-3.5</td>
<td>-0.8</td>
</tr>
<tr>
<td class="align-left">South Carolina</td>
<td>228,787</td>
<td>226,851</td>
<td>1,290,931</td>
<td>1,293,730</td>
<td style="width:1px"> </td>
<td>2.5</td>
<td>0.5</td>
<td>0.8</td>
</tr>
<tr>
<td class="align-left">South Dakota</td>
<td>39,013</td>
<td>41,374</td>
<td>201,816</td>
<td>206,915</td>
<td style="width:1px"> </td>
<td>9.6</td>
<td>0.9</td>
<td>3.1</td>
</tr>
<tr>
<td class="align-left">Tennessee</td>
<td>313,669</td>
<td>313,165</td>
<td>1,701,028</td>
<td>1,756,398</td>
<td style="width:1px"> </td>
<td>3.2</td>
<td>9.2</td>
<td>3.8</td>
</tr>
<tr>
<td class="align-left">Texas</td>
<td>1,311,841</td>
<td>1,302,031</td>
<td>7,148,751</td>
<td>7,542,490</td>
<td style="width:1px"> </td>
<td>2.6</td>
<td>5.0</td>
<td>6.1</td>
</tr>
<tr>
<td class="align-left">Utah</td>
<td>117,673</td>
<td>114,385</td>
<td>646,194</td>
<td>654,898</td>
<td style="width:1px"> </td>
<td>0.4</td>
<td>-1.4</td>
<td>1.9</td>
</tr>
<tr>
<td class="align-left">Virginia</td>
<td>305,022</td>
<td>305,285</td>
<td>1,722,420</td>
<td>1,720,041</td>
<td style="width:1px"> </td>
<td>3.4</td>
<td>-1.2</td>
<td>0.4</td>
</tr>
<tr>
<td class="align-left">Vermont</td>
<td>26,625</td>
<td>27,509</td>
<td>148,909</td>
<td>151,267</td>
<td style="width:1px"> </td>
<td>6.8</td>
<td>2.5</td>
<td>2.1</td>
</tr>
<tr>
<td class="align-left">Washington</td>
<td>238,905</td>
<td>240,591</td>
<td>1,369,198</td>
<td>1,344,316</td>
<td style="width:1px"> </td>
<td>4.1</td>
<td>0.2</td>
<td>-1.3</td>
</tr>
<tr>
<td class="align-left">Wisconsin</td>
<td>232,564</td>
<td>237,144</td>
<td>1,307,124</td>
<td>1,288,683</td>
<td style="width:1px"> </td>
<td>5.4</td>
<td>-0.2</td>
<td>-0.9</td>
</tr>
<tr>
<td class="align-left">West Virginia</td>
<td>63,297</td>
<td>64,378</td>
<td>345,426</td>
<td>359,078</td>
<td style="width:1px"> </td>
<td>5.1</td>
<td>3.7</td>
<td>4.5</td>
</tr>
<tr>
<td class="align-left">Wyoming</td>
<td>30,501</td>
<td>34,301</td>
<td>166,913</td>
<td>168,466</td>
<td style="width:1px"> </td>
<td>16.2</td>
<td>2.5</td>
<td>1.5</td>
</tr>
</table>
