<div class="content-container">
    <ul>
        <li>Full report<a href="/petroleum/marketing/prime/csv/PSRALL.csv"><i class="ico csv">CSV</i></a><a href="/petroleum/marketing/prime/pdf/PSRALL.pdf"><i class="ico pdf">PDF</i></a></li>
    </ul>
</div>
<div class="content-container grey-background">
<p>
The Prime Supplier Report presents data collected on <a href="http://www.eia.gov/survey/#eia-782c">Form EIA-782C, "Monthly Report of Prime Supplier Sales of Petroleum Products Sold for Local Consumption</a>." These data measure primary petroleum product deliveries into the States where they are locally marketed and consumed. </strong>
</p>
<p>
<a href="images/PSR-graphic-s.png" id="lightbox" class="lightbox"><img src="images/PSR-graphic-s.png" alt="diagram of Prime supplier report" width="174"/>
<span class="source">click to enlarge</span></a>
</p>
<p>
The EIA-782C respondent frame comprises approximately 202 prime suppliers representing producers, importers, and interstate resellers and retailers. Each month, respondents report their aggregated sales volumes (combined wholesale and retail) made during the reference month to local distributors, local retailers, and end users in each state where the product was delivered. To avoid double-counting volumes, respondents are instructed to exclude sales to other prime suppliers and traders. <a href="http://www.eia.gov/survey/form/eia_782c/exclusion_list.pdf">See exclusionary list.</a>
</p>
</div>
