<div class="l-row header report-details">
        <div class="l-two-third-column">
<div class="l-split-wide"> <a href="/petroleum/reports.php">&lsaquo; See All Petroleum & Other Liquids Reports</a>
                <h2><?php echo "$headtitle"?></h2>

                <div class="release-dates">
                        <div class="label-series"><?php echo "$data_series"?></div>
                        <div class="date-container">
                                <div class="label">Release Date:</div>
                                <div class="date"><?php echo "$release"?></div>
                        </div>
                        <div class="date-container">
                                <div class="label">Next Release Date:</div>
                                <div class="date"><?php echo "$next"?></div>
                        </div>
                </div>
        </div>
        <div class="l-split-narrow gradient">
                <span class="form-wrapper-outer">
                        <h4>Previous Issues</h4>
                        <span class="form-wrapper-inner">
                                <form name="form" id="form">
                                        <label>Month:</label>
<select name="jumpMenu" size="1" id="jumpMenu">
                                                <option value="/petroleum/marketing/prime/archive/#2016-2017" selected="selected">June 2017</option>
                                                <option value="/petroleum/marketing/prime/archive/#2016-2017">May 2017</option>
                                                <option value="/petroleum/marketing/prime/archive/#2016-2017">April 2017</option>
                                                <option value="/petroleum/marketing/prime/archive/#2016-2017">March 2017</option>
                                                <option value="/petroleum/marketing/prime/archive/#2016-2017">February 2017</option>
                                                <option value="/petroleum/marketing/prime/archive/#2016-2017">January 2017</option>
                                                <option value="/petroleum/marketing/prime/archive/#2016-2017">December 2016</option>
                                                <option value="/petroleum/marketing/prime/archive/#2016-2017">November 2016</option>
                                                <option value="/petroleum/marketing/prime/archive/#2016-2017">October 2016</option>
                                                <option value="/petroleum/marketing/prime/archive/#2016-2017">September 2016</option>
                                                <option value="/petroleum/marketing/prime/archive/#2016-2017">August 2016</option>
                                                <option value="/petroleum/marketing/prime/archive/#2016-2017">July 2016</option>
                                                <option value="/petroleum/marketing/prime/archive/#2016-2017">June 2016</option>
                                                <option value="/petroleum/marketing/prime/archive/#2016-2017">May 2016</option>
                                                <option value="/petroleum/marketing/prime/archive/#2016-2017">April 2016</option>
                                                <option value="/petroleum/marketing/prime/archive/#2016-2017">March 2016</option>
                                                <option value="/petroleum/marketing/prime/archive/#2016-2017">February 2016</option>
<!---                                                <option value="/petroleum/marketing/prime/archive/#2016-2017">January 2016</option>
                                                <option value="/petroleum/marketing/prime/archive/#2015-2016">December 2015</option>
                                                <option value="/petroleum/marketing/prime/archive/#2015-2016">November 2015</option>
                                                <option value="/petroleum/marketing/prime/archive/#2015-2016">October 2015</option>
                                                <option value="/petroleum/marketing/prime/archive/#2015-2016">September 2015</option>
                                                <option value="/petroleum/marketing/prime/archive/#2015-2016">August 2015</option>
                                                <option value="/petroleum/marketing/prime/archive/#2015-2016">July 2015</option>
                                                <option value="/petroleum/marketing/prime/archive/#2015-2016">June 2015</option>
                                                <option value="/petroleum/marketing/prime/archive/#2015-2016">May 2015</option>
                                                <option value="/petroleum/marketing/prime/archive/#2015-2016">April 2015</option>
                                                <option value="/petroleum/marketing/prime/archive/#2015-2016">March 2015</option>
                                                <option value="/petroleum/marketing/prime/archive/#2015-2016">February 2015</option>
                                                <option value="/petroleum/marketing/prime/archive/#2015-2016">January 2015</option>
                                                <option value="/petroleum/marketing/prime/archive/#2014-2015">December 2014</option>
                                                <option value="/petroleum/marketing/prime/archive/#2014-2015">November 2014</option>
                                                <option value="/petroleum/marketing/prime/archive/#2014-2015">October 2014</option>
                                                <option value="/petroleum/marketing/prime/archive/#2014-2015">September 2014</option>
                                                <option value="/petroleum/marketing/prime/archive/#2014-2015">August 2014</option>
                                                <option value="/petroleum/marketing/prime/archive/#2014-2015">July 2014</option>
                                                <option value="/petroleum/marketing/prime/archive/#2014-2015">June 2014</option>
                                                <option value="/petroleum/marketing/prime/archive/#2014-2015">May 2014</option>
                                                <option value="/petroleum/marketing/prime/archive/#2014-2015">April 2014</option>
                                                <option value="/petroleum/marketing/prime/archive/#2014-2015">March 2014</option>
                                                <option value="/petroleum/marketing/prime/archive/#2014-2015">February 2014</option>
                                                <option value="/petroleum/marketing/prime/archive/#2014-2015">January 2014</option>
                                                <option value="/petroleum/marketing/prime/archive/#2012-2013">December 2013</option>
                                                <option value="/petroleum/marketing/prime/archive/#2012-2013">November 2013</option>
                                                <option value="/petroleum/marketing/prime/archive/#2012-2013">October 2013</option> -->
                                                <option value="/petroleum/marketing/prime/archive/">prior issues</option>
                                        </select>
                                        <input type="button" name="go_button" class="arrow_go" id="go_button" value="Go" />
                                </form>
                        </span>
                </span>
        </div>
</div>
