<table class="data">
<!--
col width="30"/>
<col width="40"/>
<col width="40"/>
<col width="40"/>
<col width="40"/>
<col width="1"/>
<col width="20"/>
<col width="20"/>
<col width="10"/>
-->
<tr>
<th colspan="9">
<span style="font-weight:normal; font-size:11px; color:grey; float:right; margin-top:-10px; margin-right:-10px">(also available in <a href="/dnav/pet/pet_cons_prim_a_EPD2_P00_Mgalpd_m.htm">thousand gallons per day</a>)</span>
Prime supplier sales volumes of No. 2 distillate</a> by U.S. and PADD regions
<span style="font-weight:normal">thousand gallons </span></th>
</tr>
<tr>
<td class="no-border">&nbsp;</td>
<td class="no-border">&nbsp;</td>
<td class="no-border">&nbsp;</td>
<td colspan="2" class="align-center"><strong>YTD</strong></td>
<td class="no-border" style="width:1px"> </td>
<td colspan="3" class="align-center"><strong>% change</strong><sup>1</sup></td>
</tr>
<tr>
<td><strong>Area</strong></td>
<td><strong>May 2017</strong></td>
<td><strong>June 2017</strong></td>
<td><strong>2016</strong></td>
<td><strong>2017</strong></td>
<td class="no-border" style="width:1px"> </td>
<td class="no-wrap"><strong>month</strong> ago</strong></td>
<td class="no-wrap"><strong>year</strong> ago</strong></td>
<td class="no-wrap"><strong>YTD</strong></td>
</tr>
<tr>
<td class="align-left">U.S.</td>
<td>5,372,879</td>
<td>5,231,067</td>
<td>28,823,574</td>
<td>30,122,622</td>
<td class="no-border" style="width:1px"> </td>
<td>0.6</td>
<td>9.4</td>
<td>5.1</td>
</tr>
<tr>
<td class="align-left">PADD 1</td>
<td>1,412,996</td>
<td>1,309,590</td>
<td>8,667,973</td>
<td>8,744,661</td>
<td class="no-border" style="width:1px"> </td>
<td>-4.2</td>
<td>3.7</td>
<td>1.4</td>
</tr>
<tr>
<td class="align-left">PADD 2</td>
<td>1,659,918</td>
<td>1,664,199</td>
<td>8,452,460</td>
<td>8,907,170</td>
<td class="no-border" style="width:1px"> </td>
<td>3.6</td>
<td>9.2</td>
<td>6.0</td>
</tr>
<tr>
<td class="align-left">PADD 3</td>
<td>1,303,360</td>
<td>1,272,211</td>
<td>6,419,569</td>
<td>7,060,873</td>
<td class="no-border" style="width:1px"> </td>
<td>0.9</td>
<td>21.6</td>
<td>10.6</td>
</tr>
<tr>
<td class="align-left">PADD 4</td>
<td>287,940</td>
<td>277,085</td>
<td>1,504,214</td>
<td>1,569,179</td>
<td class="no-border" style="width:1px"> </td>
<td>-0.6</td>
<td>1.3</td>
<td>4.9</td>
</tr>
<tr>
<td class="align-left">PADD 5</td>
<td>708,665</td>
<td>707,982</td>
<td>3,779,358</td>
<td>3,840,739</td>
<td class="no-border" style="width:1px"> </td>
<td>3.2</td>
<td>4.8</td>
<td>2.2</td>
</tr>
<tr>
<th colspan="9"></strong>Prime supplier sales volumes of No. 2 distillate by state </strong> <span style="font-weight:normal">thousand gallons </span></th>
</tr>
<tr>
<td class="no-border">&nbsp;</td>
<td class="no-border">&nbsp;</td>
<td class="no-border">&nbsp;</td>
<td colspan="2" class="align-center"><strong>YTD</strong></td>
<td class="no-border" style="width:1px"> </td>
<td colspan="3" class="align-center"><strong>% change</strong><sup>1</sup></td>
</tr>
<tr>
<td><strong>State</strong></td>
<td><strong>May 2017</strong></td>
<td><strong>June 2017</strong></td>
<td><strong>2016</strong></td>
<td><strong>2017</strong></td>
<td style="width:1px"> </td>
<td class="no-wrap"><strong>month</strong> ago</strong></td>
<td class="no-wrap"><strong>year</strong> ago</strong></td>
<td class="no-wrap"><strong>YTD</strong></td>
</tr>
<tr>
<td class="align-left">Alaska</td>
<td>W</td>
<td>W</td>
<td>W</td>
<td>W</td>
<td style="width:1px"> </td>
<td>W</td>
<td>W</td>
<td>NA</td>
</tr>
<tr>
<td class="align-left">Alabama</td>
<td>92,300</td>
<td>W</td>
<td>W</td>
<td>W</td>
<td style="width:1px"> </td>
<td>0.0</td>
<td>W</td>
<td>NA</td>
</tr>
<tr>
<td class="align-left">Arkansas</td>
<td>71,757</td>
<td>73,759</td>
<td>W</td>
<td>W</td>
<td style="width:1px"> </td>
<td>6.2</td>
<td>9.5</td>
<td>NA</td>
</tr>
<tr>
<td class="align-left">Arizona</td>
<td>84,908</td>
<td>83,115</td>
<td>502,684</td>
<td>488,921</td>
<td style="width:1px"> </td>
<td>1.2</td>
<td>0.2</td>
<td>-2.2</td>
</tr>
<tr>
<td class="align-left">California</td>
<td>366,548</td>
<td>351,879</td>
<td>W</td>
<td>1,954,053</td>
<td style="width:1px"> </td>
<td>-0.8</td>
<td>4.8</td>
<td>NA</td>
</tr>
<tr>
<td class="align-left">Colorado</td>
<td>73,791</td>
<td>76,534</td>
<td>W</td>
<td>398,634</td>
<td style="width:1px"> </td>
<td>7.2</td>
<td>0.0</td>
<td>NA</td>
</tr>
<tr>
<td class="align-left">Connecticut</td>
<td>34,661</td>
<td>32,678</td>
<td>352,568</td>
<td>316,842</td>
<td style="width:1px"> </td>
<td>-2.6</td>
<td>-2.9</td>
<td>-9.6</td>
</tr>
<tr>
<td class="align-left">D.C.</td>
<td>1,462</td>
<td>1,347</td>
<td>W</td>
<td>W</td>
<td style="width:1px"> </td>
<td>-4.8</td>
<td>-0.6</td>
<td>NA</td>
</tr>
<tr>
<td class="align-left">Delaware</td>
<td>W</td>
<td>W</td>
<td>W</td>
<td>W</td>
<td style="width:1px"> </td>
<td>W</td>
<td>W</td>
<td>NA</td>
</tr>
<tr>
<td class="align-left">Florida</td>
<td>W</td>
<td>W</td>
<td>W</td>
<td>W</td>
<td style="width:1px"> </td>
<td>W</td>
<td>W</td>
<td>NA</td>
</tr>
<tr>
<td class="align-left">Georgia</td>
<td>150,176</td>
<td>142,499</td>
<td>854,814</td>
<td>847,187</td>
<td style="width:1px"> </td>
<td>-1.9</td>
<td>-3.8</td>
<td>-0.3</td>
</tr>
<tr>
<td class="align-left">Hawaii</td>
<td>23,185</td>
<td>22,751</td>
<td>123,431</td>
<td>126,521</td>
<td style="width:1px"> </td>
<td>1.4</td>
<td>43.9</td>
<td>3.1</td>
</tr>
<tr>
<td class="align-left">Iowa</td>
<td>94,707</td>
<td>90,503</td>
<td>476,059</td>
<td>477,643</td>
<td style="width:1px"> </td>
<td>-1.3</td>
<td>5.2</td>
<td>0.9</td>
</tr>
<tr>
<td class="align-left">Idaho</td>
<td>44,208</td>
<td>40,209</td>
<td>W</td>
<td>242,872</td>
<td style="width:1px"> </td>
<td>-6.0</td>
<td>-8.3</td>
<td>NA</td>
</tr>
<tr>
<td class="align-left">Illinois</td>
<td>188,950</td>
<td>189,990</td>
<td>1,022,921</td>
<td>1,044,953</td>
<td style="width:1px"> </td>
<td>3.9</td>
<td>6.7</td>
<td>2.7</td>
</tr>
<tr>
<td class="align-left">Indiana</td>
<td>154,668</td>
<td>151,041</td>
<td>798,916</td>
<td>846,483</td>
<td style="width:1px"> </td>
<td>0.9</td>
<td>7.9</td>
<td>6.5</td>
</tr>
<tr>
<td class="align-left">Kansas</td>
<td>87,340</td>
<td>100,704</td>
<td>482,440</td>
<td>546,327</td>
<td style="width:1px"> </td>
<td>19.1</td>
<td>2.9</td>
<td>13.9</td>
</tr>
<tr>
<td class="align-left">Kentucky</td>
<td>80,773</td>
<td>81,287</td>
<td>470,087</td>
<td>464,377</td>
<td style="width:1px"> </td>
<td>4.0</td>
<td>-0.3</td>
<td>-0.7</td>
</tr>
<tr>
<td class="align-left">Louisiana</td>
<td>W</td>
<td>W</td>
<td>W</td>
<td>W</td>
<td style="width:1px"> </td>
<td>W</td>
<td>W</td>
<td>NA</td>
</tr>
<tr>
<td class="align-left">Massachusetts</td>
<td>62,193</td>
<td>53,588</td>
<td>426,746</td>
<td>453,411</td>
<td style="width:1px"> </td>
<td>-11.0</td>
<td>19.9</td>
<td>6.8</td>
</tr>
<tr>
<td class="align-left">Maryland</td>
<td>57,327</td>
<td>W</td>
<td>W</td>
<td>W</td>
<td style="width:1px"> </td>
<td>0.0</td>
<td>W</td>
<td>NA</td>
</tr>
<tr>
<td class="align-left">Maine</td>
<td>31,751</td>
<td>28,868</td>
<td>261,174</td>
<td>266,837</td>
<td style="width:1px"> </td>
<td>-6.0</td>
<td>8.0</td>
<td>2.7</td>
</tr>
<tr>
<td class="align-left">Michigan</td>
<td>112,483</td>
<td>108,390</td>
<td>541,150</td>
<td>553,657</td>
<td style="width:1px"> </td>
<td>-0.4</td>
<td>7.9</td>
<td>2.9</td>
</tr>
<tr>
<td class="align-left">Minnesota</td>
<td>87,125</td>
<td>86,651</td>
<td>427,640</td>
<td>438,697</td>
<td style="width:1px"> </td>
<td>2.8</td>
<td>8.2</td>
<td>3.2</td>
</tr>
<tr>
<td class="align-left">Missouri</td>
<td>120,265</td>
<td>127,480</td>
<td>624,733</td>
<td>670,716</td>
<td style="width:1px"> </td>
<td>9.5</td>
<td>10.9</td>
<td>8.0</td>
</tr>
<tr>
<td class="align-left">Mississippi</td>
<td>W</td>
<td>W</td>
<td>W</td>
<td>W</td>
<td style="width:1px"> </td>
<td>W</td>
<td>W</td>
<td>NA</td>
</tr>
<tr>
<td class="align-left">Montana</td>
<td>55,898</td>
<td>55,229</td>
<td>289,147</td>
<td>304,983</td>
<td style="width:1px"> </td>
<td>2.1</td>
<td>1.8</td>
<td>6.1</td>
</tr>
<tr>
<td class="align-left">North Carolina</td>
<td>119,896</td>
<td>115,605</td>
<td>W</td>
<td>685,950</td>
<td style="width:1px"> </td>
<td>-0.4</td>
<td>0.0</td>
<td>NA</td>
</tr>
<tr>
<td class="align-left">North Dakota</td>
<td>63,345</td>
<td>58,074</td>
<td>288,381</td>
<td>297,877</td>
<td style="width:1px"> </td>
<td>-5.3</td>
<td>20.7</td>
<td>3.9</td>
</tr>
<tr>
<td class="align-left">Nebraska</td>
<td>68,439</td>
<td>74,610</td>
<td>345,952</td>
<td>366,438</td>
<td style="width:1px"> </td>
<td>12.7</td>
<td>3.7</td>
<td>6.5</td>
</tr>
<tr>
<td class="align-left">New Hampshire</td>
<td>18,178</td>
<td>16,460</td>
<td>166,876</td>
<td>162,040</td>
<td style="width:1px"> </td>
<td>-6.4</td>
<td>13.8</td>
<td>-2.4</td>
</tr>
<tr>
<td class="align-left">New Jersey</td>
<td>W</td>
<td>W</td>
<td>W</td>
<td>W</td>
<td style="width:1px"> </td>
<td>W</td>
<td>W</td>
<td>NA</td>
</tr>
<tr>
<td class="align-left">New Mexico</td>
<td>61,355</td>
<td>59,256</td>
<td>W</td>
<td>W</td>
<td style="width:1px"> </td>
<td>-0.2</td>
<td>4.3</td>
<td>NA</td>
</tr>
<tr>
<td class="align-left">Nevada</td>
<td>W</td>
<td>50,903</td>
<td>228,678</td>
<td>W</td>
<td style="width:1px"> </td>
<td>0.0</td>
<td>14.5</td>
<td>NA</td>
</tr>
<tr>
<td class="align-left">New York</td>
<td>142,736</td>
<td>128,806</td>
<td>955,073</td>
<td>952,248</td>
<td style="width:1px"> </td>
<td>-6.8</td>
<td>6.2</td>
<td>0.3</td>
</tr>
<tr>
<td class="align-left">Ohio</td>
<td>173,935</td>
<td>179,370</td>
<td>967,847</td>
<td>1,031,823</td>
<td style="width:1px"> </td>
<td>6.6</td>
<td>9.0</td>
<td>7.2</td>
</tr>
<tr>
<td class="align-left">Oklahoma</td>
<td>170,308</td>
<td>158,556</td>
<td>724,172</td>
<td>839,153</td>
<td style="width:1px"> </td>
<td>-3.8</td>
<td>22.1</td>
<td>16.5</td>
</tr>
<tr>
<td class="align-left">Oregon</td>
<td>68,233</td>
<td>W</td>
<td>W</td>
<td>W</td>
<td style="width:1px"> </td>
<td>0.0</td>
<td>W</td>
<td>NA</td>
</tr>
<tr>
<td class="align-left">Pennsylvania</td>
<td>175,455</td>
<td>163,347</td>
<td>1,087,087</td>
<td>1,095,456</td>
<td style="width:1px"> </td>
<td>-3.8</td>
<td>3.1</td>
<td>1.3</td>
</tr>
<tr>
<td class="align-left">Rhode Island</td>
<td>NA</td>
<td>NA</td>
<td>W</td>
<td>W</td>
<td style="width:1px"> </td>
<td>NA</td>
<td>NA</td>
<td>NA</td>
</tr>
<tr>
<td class="align-left">South Carolina</td>
<td>W</td>
<td>91,023</td>
<td>W</td>
<td>W</td>
<td style="width:1px"> </td>
<td>0.0</td>
<td>0.0</td>
<td>NA</td>
</tr>
<tr>
<td class="align-left">South Dakota</td>
<td>36,100</td>
<td>34,780</td>
<td>141,673</td>
<td>158,474</td>
<td style="width:1px"> </td>
<td>-0.4</td>
<td>18.4</td>
<td>12.5</td>
</tr>
<tr>
<td class="align-left">Tennessee</td>
<td>121,387</td>
<td>119,644</td>
<td>647,414</td>
<td>663,360</td>
<td style="width:1px"> </td>
<td>1.8</td>
<td>7.3</td>
<td>3.0</td>
</tr>
<tr>
<td class="align-left">Texas</td>
<td>758,652</td>
<td>W</td>
<td>W</td>
<td>W</td>
<td style="width:1px"> </td>
<td>0.0</td>
<td>W</td>
<td>NA</td>
</tr>
<tr>
<td class="align-left">Utah</td>
<td>68,337</td>
<td>57,414</td>
<td>343,020</td>
<td>351,234</td>
<td style="width:1px"> </td>
<td>-13.2</td>
<td>-1.8</td>
<td>3.0</td>
</tr>
<tr>
<td class="align-left">Virginia</td>
<td>124,731</td>
<td>116,098</td>
<td>641,372</td>
<td>686,925</td>
<td style="width:1px"> </td>
<td>-3.8</td>
<td>7.4</td>
<td>7.7</td>
</tr>
<tr>
<td class="align-left">Vermont</td>
<td>9,798</td>
<td>8,886</td>
<td>84,686</td>
<td>79,907</td>
<td style="width:1px"> </td>
<td>-6.3</td>
<td>-2.3</td>
<td>-5.1</td>
</tr>
<tr>
<td class="align-left">Washington</td>
<td>197,315</td>
<td>198,269</td>
<td>1,133,199</td>
<td>1,114,900</td>
<td style="width:1px"> </td>
<td>3.8</td>
<td>-0.2</td>
<td>-1.1</td>
</tr>
<tr>
<td class="align-left">Wisconsin</td>
<td>100,093</td>
<td>103,119</td>
<td>493,075</td>
<td>507,192</td>
<td style="width:1px"> </td>
<td>6.5</td>
<td>15.6</td>
<td>3.4</td>
</tr>
<tr>
<td class="align-left">West Virginia</td>
<td>37,050</td>
<td>W</td>
<td>W</td>
<td>W</td>
<td style="width:1px"> </td>
<td>0.0</td>
<td>W</td>
<td>NA</td>
</tr>
<tr>
<td class="align-left">Wyoming</td>
<td>45,706</td>
<td>47,699</td>
<td>W</td>
<td>271,456</td>
<td style="width:1px"> </td>
<td>7.8</td>
<td>0.0</td>
<td>NA</td>
</tr>
</table>
