<table class="data">
<col width="30"/>
<col width="40"/>
<col width="40"/>
<col width="40"/>
<col width="40"/>
<col width="1"/>
<col width="20"/>
<col width="20"/>
<col width="10"/>
<tr>
<th colspan="9">
<span style="font-weight:normal; font-size:11px; color:grey; float:right; margin-top:-10px; margin-right:-10px">(also available in <a href="/dnav/pet/pet_cons_prim_a_EPLLPA_P00_Mgalpd_m.htm">thousand gallons per day</a>)</span>
Prime supplier sales volumes of propane</a> by U.S. and PADD regions <span style="font-weight:normal">thousand gallons </span></th>
</tr>
<tr>
<td class="no-border">&nbsp;</td>
<td class="no-border">&nbsp;</td>
<td class="no-border">&nbsp;</td>
<td colspan="2" class="align-center"><strong>YTD</strong></td>
<td class="no-border" style="width:1px"> </td>
<td colspan="3" class="align-center"><strong>% change</strong><sup>1</sup></td>
</tr>
<tr>
<td><strong>Area</strong></td>
<td><strong>%v.date1% %v.date2%</strong></td>
<td><strong>%v.date3% %v.date4%</strong></td>
<td><strong>%v.date5%</strong></td>
<td><strong>%v.date6%</strong></td>
<td class="no-border" style="width:1px"> </td>
<td class="no-wrap"><strong>month</strong> ago</strong></td>
<td class="no-wrap"><strong>year</strong> ago</strong></td>
<td class="no-wrap"><strong>YTD</strong></td>
</tr>
<tr>
<td class="align-left">U.S.</td>
<td>%v.r1c1%</td>
<td>%v.r1c2%</td>
<td>%v.r1c3%</td>
<td>%v.r1c4%</td>
<td class="no-border" style="width:1px"> </td>
<td>%v.r1c5%</td>
<td>%v.r1c6%</td>
<td>%v.r1c7%</td>
</tr>
<tr>
<td class="align-left">PADD 1</td>
<td>%v.r2c1%</td>
<td>%v.r2c2%</td>
<td>%v.r2c3%</td>
<td>%v.r2c4%</td>
<td class="no-border" style="width:1px"> </td>
<td>%v.r2c5%</td>
<td>%v.r2c6%</td>
<td>%v.r2c7%</td>
</tr>
<tr>
<td class="align-left">PADD 2</td>
<td>%v.r3c1%</td>
<td>%v.r3c2%</td>
<td>%v.r3c3%</td>
<td>%v.r3c4%</td>
<td class="no-border" style="width:1px"> </td>
<td>%v.r3c5%</td>
<td>%v.r3c6%</td>
<td>%v.r3c7%</td>
</tr>
<tr>
<td class="align-left">PADD 3</td>
<td>%v.r4c1%</td>
<td>%v.r4c2%</td>
<td>%v.r4c3%</td>
<td>%v.r4c4%</td>
<td class="no-border" style="width:1px"> </td>
<td>%v.r4c5%</td>
<td>%v.r4c6%</td>
<td>%v.r4c7%</td>
</tr>
<tr>
<td class="align-left">PADD 4</td>
<td>%v.r5c1%</td>
<td>%v.r5c2%</td>
<td>%v.r5c3%</td>
<td>%v.r5c4%</td>
<td class="no-border" style="width:1px"> </td>
<td>%v.r5c5%</td>
<td>%v.r5c6%</td>
<td>%v.r5c7%</td>
</tr>
<tr>
<td class="align-left">PADD 5</td>
<td>%v.r6c1%</td>
<td>%v.r6c2%</td>
<td>%v.r6c3%</td>
<td>%v.r6c4%</td>
<td class="no-border" style="width:1px"> </td>
<td>%v.r6c5%</td>
<td>%v.r6c6%</td>
<td>%v.r6c7%</td>
</tr>
<tr>
<th colspan="9"></strong>Prime supplier sales volumes of propane by state </strong><span style="font-weight:normal">thousand gallons </span></th>
</tr>
<tr>
<td class="no-border">&nbsp;</td>
<td class="no-border">&nbsp;</td>
<td class="no-border">&nbsp;</td>
<td colspan="2" class="align-center"><strong>YTD</strong></td>
<td class="no-border" style="width:1px"> </td>
<td colspan="3" class="align-center"><strong>% change</strong><sup>1</sup></td>
</tr>
<tr>
<td><strong>State</strong></td>
<td><strong>%v.date1% %v.date2%</strong></td>
<td><strong>%v.date3% %v.date4%</strong></td>
<td><strong>%v.date5%</strong></td>
<td><strong>%v.date6%</strong></td>
<td style="width:1px"> </td>
<td class="no-wrap"><strong>month</strong> ago</strong></td>
<td class="no-wrap"><strong>year</strong> ago</strong></td>
<td class="no-wrap"><strong>YTD</strong></td>
</tr>
<tr>
<td class="align-left">Alaska</td>
<td>%v.r49c1%</td>
<td>%v.r49c2%</td>
<td>%v.r49c3%</td>
<td>%v.r49c4%</td>
<td style="width:1px"> </td>
<td>%v.r49c5%</td>
<td>%v.r49c6%</td>
<td>%v.r49c7%</td>
</tr>
<tr>
<td class="align-left">Alabama</td>
<td>%v.r38c1%</td>
<td>%v.r38c2%</td>
<td>%v.r38c3%</td>
<td>%v.r38c4%</td>
<td style="width:1px"> </td>
<td>%v.r38c5%</td>
<td>%v.r38c6%</td>
<td>%v.r38c7%</td>
</tr>
<tr>
<td class="align-left">Arkansas</td>
<td>%v.r39c1%</td>
<td>%v.r39c2%</td>
<td>%v.r39c3%</td>
<td>%v.r39c4%</td>
<td style="width:1px"> </td>
<td>%v.r39c5%</td>
<td>%v.r39c6%</td>
<td>%v.r39c7%</td>
</tr>
<tr>
<td class="align-left">Arizona</td>
<td>%v.r50c1%</td>
<td>%v.r50c2%</td>
<td>%v.r50c3%</td>
<td>%v.r50c4%</td>
<td style="width:1px"> </td>
<td>%v.r50c5%</td>
<td>%v.r50c6%</td>
<td>%v.r50c7%</td>
</tr>
<tr>
<td class="align-left">California</td>
<td>%v.r51c1%</td>
<td>%v.r51c2%</td>
<td>%v.r51c3%</td>
<td>%v.r51c4%</td>
<td style="width:1px"> </td>
<td>%v.r51c5%</td>
<td>%v.r51c6%</td>
<td>%v.r51c7%</td>
</tr>
<tr>
<td class="align-left">Colorado</td>
<td>%v.r44c1%</td>
<td>%v.r44c2%</td>
<td>%v.r44c3%</td>
<td>%v.r44c4%</td>
<td style="width:1px"> </td>
<td>%v.r44c5%</td>
<td>%v.r44c6%</td>
<td>%v.r44c7%</td>
</tr>
<tr>
<td class="align-left">Connecticut</td>
<td>%v.r7c1%</td>
<td>%v.r7c2%</td>
<td>%v.r7c3%</td>
<td>%v.r7c4%</td>
<td style="width:1px"> </td>
<td>%v.r7c5%</td>
<td>%v.r7c6%</td>
<td>%v.r7c7%</td>
</tr>
<tr>
<td class="align-left">D.C.</td>
<td>%v.r14c1%</td>
<td>%v.r14c2%</td>
<td>%v.r14c3%</td>
<td>%v.r14c4%</td>
<td style="width:1px"> </td>
<td>%v.r14c5%</td>
<td>%v.r14c6%</td>
<td>%v.r14c7%</td>
</tr>
<tr>
<td class="align-left">Delaware</td>
<td>%v.r13c1%</td>
<td>%v.r13c2%</td>
<td>%v.r13c3%</td>
<td>%v.r13c4%</td>
<td style="width:1px"> </td>
<td>%v.r13c5%</td>
<td>%v.r13c6%</td>
<td>%v.r13c7%</td>
</tr>
<tr>
<td class="align-left">Florida</td>
<td>%v.r19c1%</td>
<td>%v.r19c2%</td>
<td>%v.r19c3%</td>
<td>%v.r19c4%</td>
<td style="width:1px"> </td>
<td>%v.r19c5%</td>
<td>%v.r19c6%</td>
<td>%v.r19c7%</td>
</tr>
<tr>
<td class="align-left">Georgia</td>
<td>%v.r20c1%</td>
<td>%v.r20c2%</td>
<td>%v.r20c3%</td>
<td>%v.r20c4%</td>
<td style="width:1px"> </td>
<td>%v.r20c5%</td>
<td>%v.r20c6%</td>
<td>%v.r20c7%</td>
</tr>
<tr>
<td class="align-left">Hawaii</td>
<td>%v.r52c1%</td>
<td>%v.r52c2%</td>
<td>%v.r52c3%</td>
<td>%v.r52c4%</td>
<td style="width:1px"> </td>
<td>%v.r52c5%</td>
<td>%v.r52c6%</td>
<td>%v.r52c7%</td>
</tr>
<tr>
<td class="align-left">Iowa</td>
<td>%v.r25c1%</td>
<td>%v.r25c2%</td>
<td>%v.r25c3%</td>
<td>%v.r25c4%</td>
<td style="width:1px"> </td>
<td>%v.r25c5%</td>
<td>%v.r25c6%</td>
<td>%v.r25c7%</td>
</tr>
<tr>
<td class="align-left">Idaho</td>
<td>%v.r45c1%</td>
<td>%v.r45c2%</td>
<td>%v.r45c3%</td>
<td>%v.r45c4%</td>
<td style="width:1px"> </td>
<td>%v.r45c5%</td>
<td>%v.r45c6%</td>
<td>%v.r45c7%</td>
</tr>
<tr>
<td class="align-left">Illinois</td>
<td>%v.r57c1%</td>
<td>%v.r57c2%</td>
<td>%v.r57c3%</td>
<td>%v.r57c4%</td>
<td style="width:1px"> </td>
<td>%v.r57c5%</td>
<td>%v.r57c6%</td>
<td>%v.r57c7%</td>
</tr>
<tr>
<td class="align-left">Indiana</td>
<td>%v.r24c1%</td>
<td>%v.r24c2%</td>
<td>%v.r24c3%</td>
<td>%v.r24c4%</td>
<td style="width:1px"> </td>
<td>%v.r24c5%</td>
<td>%v.r24c6%</td>
<td>%v.r24c7%</td>
</tr>
<tr>
<td class="align-left">Kansas</td>
<td>%v.r26c1%</td>
<td>%v.r26c2%</td>
<td>%v.r26c3%</td>
<td>%v.r26c4%</td>
<td style="width:1px"> </td>
<td>%v.r26c5%</td>
<td>%v.r26c6%</td>
<td>%v.r26c7%</td>
</tr>
<tr>
<td class="align-left">Kentucky</td>
<td>%v.r27c1%</td>
<td>%v.r27c2%</td>
<td>%v.r27c3%</td>
<td>%v.r27c4%</td>
<td style="width:1px"> </td>
<td>%v.r27c5%</td>
<td>%v.r27c6%</td>
<td>%v.r27c7%</td>
</tr>
<tr>
<td class="align-left">Louisiana</td>
<td>%v.r40c1%</td>
<td>%v.r40c2%</td>
<td>%v.r40c3%</td>
<td>%v.r40c4%</td>
<td style="width:1px"> </td>
<td>%v.r40c5%</td>
<td>%v.r40c6%</td>
<td>%v.r40c7%</td>
</tr>
<tr>
<td class="align-left">Massachusetts</td>
<td>%v.r9c1%</td>
<td>%v.r9c2%</td>
<td>%v.r9c3%</td>
<td>%v.r9c4%</td>
<td style="width:1px"> </td>
<td>%v.r9c5%</td>
<td>%v.r9c6%</td>
<td>%v.r9c7%</td>
</tr>
<tr>
<td class="align-left">Maryland</td>
<td>%v.r15c1%</td>
<td>%v.r15c2%</td>
<td>%v.r15c3%</td>
<td>%v.r15c4%</td>
<td style="width:1px"> </td>
<td>%v.r15c5%</td>
<td>%v.r15c6%</td>
<td>%v.r15c7%</td>
</tr>
<tr>
<td class="align-left">Maine</td>
<td>%v.r8c1%</td>
<td>%v.r8c2%</td>
<td>%v.r8c3%</td>
<td>%v.r8c4%</td>
<td style="width:1px"> </td>
<td>%v.r8c5%</td>
<td>%v.r8c6%</td>
<td>%v.r8c7%</td>
</tr>
<tr>
<td class="align-left">Michigan</td>
<td>%v.r28c1%</td>
<td>%v.r28c2%</td>
<td>%v.r28c3%</td>
<td>%v.r28c4%</td>
<td style="width:1px"> </td>
<td>%v.r28c5%</td>
<td>%v.r28c6%</td>
<td>%v.r28c7%</td>
</tr>
<tr>
<td class="align-left">Minnesota</td>
<td>%v.r29c1%</td>
<td>%v.r29c2%</td>
<td>%v.r29c3%</td>
<td>%v.r29c4%</td>
<td style="width:1px"> </td>
<td>%v.r29c5%</td>
<td>%v.r29c6%</td>
<td>%v.r29c7%</td>
</tr>
<tr>
<td class="align-left">Missouri</td>
<td>%v.r30c1%</td>
<td>%v.r30c2%</td>
<td>%v.r30c3%</td>
<td>%v.r30c4%</td>
<td style="width:1px"> </td>
<td>%v.r30c5%</td>
<td>%v.r30c6%</td>
<td>%v.r30c7%</td>
</tr>
<tr>
<td class="align-left">Mississippi</td>
<td>%v.r41c1%</td>
<td>%v.r41c2%</td>
<td>%v.r41c3%</td>
<td>%v.r41c4%</td>
<td style="width:1px"> </td>
<td>%v.r41c5%</td>
<td>%v.r41c6%</td>
<td>%v.r41c7%</td>
</tr>
<tr>
<td class="align-left">Montana</td>
<td>%v.r46c1%</td>
<td>%v.r46c2%</td>
<td>%v.r46c3%</td>
<td>%v.r46c4%</td>
<td style="width:1px"> </td>
<td>%v.r46c5%</td>
<td>%v.r46c6%</td>
<td>%v.r46c7%</td>
</tr>
<tr>
<td class="align-left">North Carolina</td>
<td>%v.r21c1%</td>
<td>%v.r21c2%</td>
<td>%v.r21c3%</td>
<td>%v.r21c4%</td>
<td style="width:1px"> </td>
<td>%v.r21c5%</td>
<td>%v.r21c6%</td>
<td>%v.r21c7%</td>
</tr>
<tr>
<td class="align-left">North Dakota</td>
<td>%v.r32c1%</td>
<td>%v.r32c2%</td>
<td>%v.r32c3%</td>
<td>%v.r32c4%</td>
<td style="width:1px"> </td>
<td>%v.r32c5%</td>
<td>%v.r32c6%</td>
<td>%v.r32c7%</td>
</tr>
<tr>
<td class="align-left">Nebraska</td>
<td>%v.r31c1%</td>
<td>%v.r31c2%</td>
<td>%v.r31c3%</td>
<td>%v.r31c4%</td>
<td style="width:1px"> </td>
<td>%v.r31c5%</td>
<td>%v.r31c6%</td>
<td>%v.r31c7%</td>
</tr>
<tr>
<td class="align-left">New Hampshire</td>
<td>%v.r10c1%</td>
<td>%v.r10c2%</td>
<td>%v.r10c3%</td>
<td>%v.r10c4%</td>
<td style="width:1px"> </td>
<td>%v.r10c5%</td>
<td>%v.r10c6%</td>
<td>%v.r10c7%</td>
</tr>
<tr>
<td class="align-left">New Jersey</td>
<td>%v.r16c1%</td>
<td>%v.r16c2%</td>
<td>%v.r16c3%</td>
<td>%v.r16c4%</td>
<td style="width:1px"> </td>
<td>%v.r16c5%</td>
<td>%v.r16c6%</td>
<td>%v.r16c7%</td>
</tr>
<tr>
<td class="align-left">New Mexico</td>
<td>%v.r42c1%</td>
<td>%v.r42c2%</td>
<td>%v.r42c3%</td>
<td>%v.r42c4%</td>
<td style="width:1px"> </td>
<td>%v.r42c5%</td>
<td>%v.r42c6%</td>
<td>%v.r42c7%</td>
</tr>
<tr>
<td class="align-left">Nevada</td>
<td>%v.r53c1%</td>
<td>%v.r53c2%</td>
<td>%v.r53c3%</td>
<td>%v.r53c4%</td>
<td style="width:1px"> </td>
<td>%v.r53c5%</td>
<td>%v.r53c6%</td>
<td>%v.r53c7%</td>
</tr>
<tr>
<td class="align-left">New York</td>
<td>%v.r17c1%</td>
<td>%v.r17c2%</td>
<td>%v.r17c3%</td>
<td>%v.r17c4%</td>
<td style="width:1px"> </td>
<td>%v.r17c5%</td>
<td>%v.r17c6%</td>
<td>%v.r17c7%</td>
</tr>
<tr>
<td class="align-left">Ohio</td>
<td>%v.r33c1%</td>
<td>%v.r33c2%</td>
<td>%v.r33c3%</td>
<td>%v.r33c4%</td>
<td style="width:1px"> </td>
<td>%v.r33c5%</td>
<td>%v.r33c6%</td>
<td>%v.r33c7%</td>
</tr>
<tr>
<td class="align-left">Oklahoma</td>
<td>%v.r34c1%</td>
<td>%v.r34c2%</td>
<td>%v.r34c3%</td>
<td>%v.r34c4%</td>
<td style="width:1px"> </td>
<td>%v.r34c5%</td>
<td>%v.r34c6%</td>
<td>%v.r34c7%</td>
</tr>
<tr>
<td class="align-left">Oregon</td>
<td>%v.r54c1%</td>
<td>%v.r54c2%</td>
<td>%v.r54c3%</td>
<td>%v.r54c4%</td>
<td style="width:1px"> </td>
<td>%v.r54c5%</td>
<td>%v.r54c6%</td>
<td>%v.r54c7%</td>
</tr>
<tr>
<td class="align-left">Pennsylvania</td>
<td>%v.r18c1%</td>
<td>%v.r18c2%</td>
<td>%v.r18c3%</td>
<td>%v.r18c4%</td>
<td style="width:1px"> </td>
<td>%v.r18c5%</td>
<td>%v.r18c6%</td>
<td>%v.r18c7%</td>
</tr>
<tr>
<td class="align-left">Rhode Island</td>
<td>%v.r11c1%</td>
<td>%v.r11c2%</td>
<td>%v.r11c3%</td>
<td>%v.r11c4%</td>
<td style="width:1px"> </td>
<td>%v.r11c5%</td>
<td>%v.r11c6%</td>
<td>%v.r11c7%</td>
</tr>
<tr>
<td class="align-left">South Carolina</td>
<td>%v.r22c1%</td>
<td>%v.r22c2%</td>
<td>%v.r22c3%</td>
<td>%v.r22c4%</td>
<td style="width:1px"> </td>
<td>%v.r22c5%</td>
<td>%v.r22c6%</td>
<td>%v.r22c7%</td>
</tr>
<tr>
<td class="align-left">South Dakota</td>
<td>%v.r35c1%</td>
<td>%v.r35c2%</td>
<td>%v.r35c3%</td>
<td>%v.r35c4%</td>
<td style="width:1px"> </td>
<td>%v.r35c5%</td>
<td>%v.r35c6%</td>
<td>%v.r35c7%</td>
</tr>
<tr>
<td class="align-left">Tennessee</td>
<td>%v.r36c1%</td>
<td>%v.r36c2%</td>
<td>%v.r36c3%</td>
<td>%v.r36c4%</td>
<td style="width:1px"> </td>
<td>%v.r36c5%</td>
<td>%v.r36c6%</td>
<td>%v.r36c7%</td>
</tr>
<tr>
<td class="align-left">Texas</td>
<td>%v.r43c1%</td>
<td>%v.r43c2%</td>
<td>%v.r43c3%</td>
<td>%v.r43c4%</td>
<td style="width:1px"> </td>
<td>%v.r43c5%</td>
<td>%v.r43c6%</td>
<td>%v.r43c7%</td>
</tr>
<tr>
<td class="align-left">Utah</td>
<td>%v.r47c1%</td>
<td>%v.r47c2%</td>
<td>%v.r47c3%</td>
<td>%v.r47c4%</td>
<td style="width:1px"> </td>
<td>%v.r47c5%</td>
<td>%v.r47c6%</td>
<td>%v.r47c7%</td>
</tr>
<tr>
<td class="align-left">Virginia</td>
<td>%v.r23c1%</td>
<td>%v.r23c2%</td>
<td>%v.r23c3%</td>
<td>%v.r23c4%</td>
<td style="width:1px"> </td>
<td>%v.r23c5%</td>
<td>%v.r23c6%</td>
<td>%v.r23c7%</td>
</tr>
<tr>
<td class="align-left">Vermont</td>
<td>%v.r12c1%</td>
<td>%v.r12c2%</td>
<td>%v.r12c3%</td>
<td>%v.r12c4%</td>
<td style="width:1px"> </td>
<td>%v.r12c5%</td>
<td>%v.r12c6%</td>
<td>%v.r12c7%</td>
</tr>
<tr>
<td class="align-left">Washington</td>
<td>%v.r55c1%</td>
<td>%v.r55c2%</td>
<td>%v.r55c3%</td>
<td>%v.r55c4%</td>
<td style="width:1px"> </td>
<td>%v.r55c5%</td>
<td>%v.r55c6%</td>
<td>%v.r55c7%</td>
</tr>
<tr>
<td class="align-left">Wisconsin</td>
<td>%v.r37c1%</td>
<td>%v.r37c2%</td>
<td>%v.r37c3%</td>
<td>%v.r37c4%</td>
<td style="width:1px"> </td>
<td>%v.r37c5%</td>
<td>%v.r37c6%</td>
<td>%v.r37c7%</td>
</tr>
<tr>
<td class="align-left">West Virginia</td>
<td>%v.r56c1%</td>
<td>%v.r56c2%</td>
<td>%v.r56c3%</td>
<td>%v.r56c4%</td>
<td style="width:1px"> </td>
<td>%v.r56c5%</td>
<td>%v.r56c6%</td>
<td>%v.r56c7%</td>
</tr>
<tr>
<td class="align-left">Wyoming</td>
<td>%v.r48c1%</td>
<td>%v.r48c2%</td>
<td>%v.r48c3%</td>
<td>%v.r48c4%</td>
<td style="width:1px"> </td>
<td>%v.r48c5%</td>
<td>%v.r48c6%</td>
<td>%v.r48c7%</td>
</tr>
