<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2016-06/fig_HL1coppwp2.png" class="lightbox"><img src="images/2016-06/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude Oil</h2>
            <ul>
                <li>Monthly average crude oil prices increased in all sales categories during March. The average domestic crude oil first purchase price rose $6.36 (24.9%), to $31.87 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil climbed $5.09 (20.7%) to $29.73 per barrel. The average landed cost of foreign crude oil increased $4.66 (17.6%), to $31.16 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil rose $4.98 (16.4%), to $35.28 per barrel. The average cost of imported crude oil climbed $5.64 (21.2%), to $32.25 per barrel. The composite refiner acquisition cost for crude oil increased $5.29 (18.5%), to $33.82 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>March monthly average prices for sales of motor gasoline by refiners rose in all sales categories. The average retail price increased 22.1 cents to $1.553 per gallon, while the average wholesale price climbed 28.9 cents to $1.335 per gallon.</li>
                <li>Refiner sales of finished motor gasoline increased in March. Total sales rose 9.0 million gallons per day (2.8%) to an average of 329.2 million gallons per day. Retail sales fell 200,000 gallons per day (0.8%), while wholesales rose 9.2 million gallons per day (3.1%). DTW sales accounted for 7.7% of wholesales, while rack and bulk sales made up 83.9% and 8.4%, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>Monthly average prices for refiner sales of No. 2 distillates increased in March. The average price for No. 2 diesel fuel sold to end users rose 13.1 cents to $1.316 per gallon, while the average wholesale price climbed 14.6 cents to $1.189 per gallon. The average retail price for No. 2 fuel oil rose 14.8 cents to $1.555 per gallon, while the average wholesale price increased 12.2 cents to $1.070 per gallon.</li>
                <li>Refiner sales of No. 2 ultra-low sulfur diesel fuel were mixed in March. Retail sales fell 300,000 gallons per day (2.5%), while wholesales rose 3.5 million gallons per day (2.7%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Monthly average prices for residual fuel oil sales by refiners increased during March. The wholesale price for low-sulfur residual fuel oil climbed 10.7 cents to 58.2 cents per gallon. Prices for high-sulfur residual fuel oil rose 6.6 cents to 67.2 cents per gallon at retail, while the wholesale price increased 3.7 cents to 54.5 cents per gallon.</li>
                <li>Sales of residual fuel oil by refiners were flat in March. Retail sales rose 200,000 gallons per day (5.1%), while wholesales fell 200,000 gallons per day (2.2%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>Prices for refiner sales of the remaining surveyed products increased during March. Retail and wholesale prices for propane and kerosene-type jet fuel rose at both levels. Prices for aviation gasoline, kerosene, and No. 1 distillate increased at the wholesale level.</li>
                <li>Refiner sales of these products show mixed trends in March. Propane sales fell at both the retail and wholesale levels, while sales of kerosene-type jet fuel sales rose at retail but fell at wholesale. Sales of aviation gasoline, kerosene, and No. 1 distillate decreased at the wholesale level.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div> */ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/petroleum/marketing/annual/archive/" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a></li>
    </ul>
</div>