<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2016-03/fig_HL1coppwp2.png" class="lightbox"><img src="images/2016-03/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude Oil</h2>
            <ul>
                <li>Monthly average crude oil prices declined in all sales categories in December. The average domestic crude oil first purchase price decreased $5.93 (15.5%), to $32.26 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil fell $4.36 (13.0%) to $29.28 per barrel. The average landed cost of foreign crude oil decreased $5.19 (13.9%), to $32.20 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil dropped $5.51 (12.7%), to $37.79 per barrel. The average cost of imported crude oil declined $5.93 (15.2%), to $33.13 per barrel. The composite refiner acquisition cost for crude oil fell $5.79 (14.0%), to $35.64 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>Monthly average prices for sales of motor gasoline by refiners continued on a downward path in December. The average retail price fell 10.9 cents to $1.603 per gallon, while the average wholesale price decreased 7.0 cents to $1.356 per gallon.</li>
                <li>Refiner sales of finished motor gasoline increased in December. Total sales rose 1.8 million gallons per day (0.6%) to an average of 325.2 million gallons per day. Retail sales increased 100,000 gallons per day (0.4%), while wholesales climbed 1.7 million gallons per day (0.6%). DTW sales accounted for 7.6% of wholesales, while rack and bulk sales made up 84.2% and 8.1%, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>Monthly average prices for refiner sales of No. 2 distillates decreased in December. The average price for No. 2 diesel fuel sold to end users fell 24.3 cents to $1.360 per gallon, while the average wholesale price declined 28.0 cents to $1.176 per gallon. The average wholesale price for No. 2 fuel oil decreased 23.0 cents to $1.126 per gallon.</li>
                <li>Refiner sales of No. 2 ultra-low sulfur diesel fuel rose in December. Retail sales fell 500,000 gallons per day (4.2%), while wholesales increased 900,000 gallons per day (0.7%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Monthly average prices for residual fuel oil sales by refiners declined in December. The wholesale price for low-sulfur residual fuel oil decreased 21.4 cents to 55.2 cents per gallon. Prices for high-sulfur residual fuel oil dropped 14.0 cents to 86.1 cents per gallon at retail, while the wholesale price fell 15.8 cents to 63.3 cents per gallon.</li>
                <li>Sales of residual fuel oil by refiners increased in December. Retail sales declined 400,000 gallons per day (9.1%), while wholesales climbed 700,000 gallons per day (8.7%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>Refiner prices for the remaining surveyed products were on the decline during December. Prices for propane and kerosene-type jet fuel fell at both the retail and wholesale levels, while prices for kerosene, aviation gasoline, and No. 1 distillate also decreased at the wholesale.</li>
                <li>Refiner sales of other products generally rose in December. Propane fell at retail but rose at wholesale. Kerosene-type jet fuel sales rose at both levels, while aviation gasoline, kerosene, and No. 1 distillate sales increased in the wholesale category.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div> */ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/petroleum/marketing/annual/archive/" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a></li>
    </ul>
</div>