<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong> Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2014-05/fig_HL1coppwp.jpg" class="lightbox"><img src="images/2014-05/fig_HL1_coppwp_sm.jpg" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
        <li class="header"><h2>Crude Oil</h2>
            <ul>
                <li>Monthly average crude oil prices show mixed trends in January.  The average domestic crude oil first purchase price fell $2.26 (2.5 percent), to $89.59 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil increased 83 cents (0.9 percent), to $90.81 per barrel.  The average landed cost of foreign crude oil fell 8 cents (0.1 percent), to $89.32 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil declined $2.09 (2.1 percent), to $95.78 per barrel.  The average cost of imported crude oil fell 86 cents (0.9 percent), to $89.71 per barrel.  The composite refiner acquisition cost for crude oil decreased $1.50 (1.6 percent), to $92.82 per barrel.</li>
            </ul>
        </li>
        <li class="header"><h2>Petroleum Products</h2></li>
                <li><h4>Motor Gasoline</h4>
            <ul>
                <li>Monthly average crude oil prices increased in all sales categories in February.  The average domestic crude oil first purchase price climbed $7.18 (8.0 percent), to $96.77 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil rose $2.36 (2.6 percent), to $93.36 per barrel.  The average landed cost of foreign crude oil increased $4.33 (4.8 percent), to $94.58 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil increased $5.18 (5.3 percent), to $102.35 per barrel.  The average cost of imported crude oil rose $6.41 (7.2 percent), to $96.04 per barrel.  The composite refiner acquisition cost for crude oil increased $5.81 (6.2 percent), to $99.33 per barrel.</li>
            </ul>
        </li>
        <li class="header"><h2>Petroleum Products</h2></li>
                <li><h4>Motor Gasoline</h4>
            <ul>
                <li>Monthly average prices sales of motor gasoline made by refiners continued to rise in February.  The average retail price increased 9.7 cents to $2.913 per gallon, while the average wholesale price rose 9.5 cents to $2.699 per gallon.</li>
                <li>Sales of finished motor gasoline by refiners increased in February.  Total sales climbed 14.8 million gallons per day (5.1 percent) to an average of 304.0 million gallons per day.  Retail sales rose 600,000 gallons per day (3.4 percent), while wholesales increased 14.2 million gallons per day (5.2 percent).  DTW sales accounted for 9.0 percent of wholesales, while rack and bulk sales made up 82.0 percent and 8.9 percent, respectively.</li>
                    </ul>
        </li>
                <li><h4>No. 2 Distillate</h4>
            <ul>
                <li>Monthly average refiner prices for No. 2 distillates were largely on the increase during February.  The average sales price for No. 2 diesel fuel to end users rose 11.8 cents to $3.142 per gallon, while the average wholesale price climbed 11.1 cents to $3.092 per gallon.  The average price for No. 2 fuel oil sales to end users increased 9.6 cents to $3.687 per gallon, while the average wholesale price for No. 2 fuel oil declined 0.8 cent to $3.051 per gallon.</li>
                <li>Refiner sales of No. 2 ultra-low sulfur diesel fuel decreased 4.1 million gallons per day (2.8 percent) to an average of 142.3 million gallons per day in February.  No. 2 fuel oil sales increased 2.1 million gallons per day (22.9 percent) to an average of 11.3 million gallons per day.</li>
                    </ul>
        </li>
                <li><h4>Residual Fuel Oil</h4>
            <ul>
                <li>Monthly average prices for residual fuel oil sales by refiners increased in February.  The price for low-sulfur residual fuel oil rose 12.2 cents to $2.459 per gallon at the wholesale level.  Prices for high-sulfur residual fuel oil increased 1.6 cents to $2.416 per gallon at retail, and 2.2 cents to $2.139 per gallon at wholesale.</li>
                <li>Sales of residual fuel oil by refiners declined modestly in February, with total sales falling 100,000 gallons per day (0.8 percent) to an average of 13.1 million gallons per day</li>
                    </ul>
        </li>
                <li><h4>Other Products</h4>
            <ul>
                <li>Prices for other surveyed products increased during February.  Propane, kerosene-type jet fuel, and No. 1 distillate prices rose at both the retail and wholesale levels, while aviation gasoline and kerosene prices registered increases at wholesale.</li>
                <li>Refiner sales of propane and No. 1 distillate declined at both the retail and wholesale levels in February.  Kerosene-type jet fuel sales increased at retail, but fell at wholesale.  Aviation gasoline sales declined at wholesale, while sales of kerosene rose at the same level.</li>
            </ul>
        </li>
    </ul>
</div>

<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>