<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong> Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2012-03/fig_HL1coppwp.jpg" class="lightbox"><img src="images/2012-03/fig_HL1_coppwp_sm.jpg" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li><h3>Highlights</h3></li>
                <li><p>International crude oil prices were in a more settled state
in December, in contrast to the volatility that has
characterized them during much of 2011. Though prices
generally saw comparatively modest changes, ongoing
sovereign debt matters in the euro-zone nations,
inventory levels, and political issues continued to assert
their influence at various points in the month. At the start
of December, supportive economic news from the United
States and simmering political tensions over Iran's
nuclear fuels program underpinned prices while
troubling developments in the euro-zone debt crisis and
other international economic news acted as cap on them.
At mid-month, the Organization of Oil Exporting
Countries (OPEC) voted to officially raise its production
ceiling to 30 million barrels
per day; in doing so, the
group incorporated
existent production
overages from some of its
members. The decision,
coupled with fresh news
of troubling
developments in the
euro-zone debt crisis, led
prices firmly down to
their lowest point for the
month. Prices rebounded
quickly though, first on
supportive economic and
petroleum products
inventory data from the
United States, then on
political affairs in Iraq
following the exit of U.S.
troops and naval war
games conducted by Iran
in the Strait of Hormuz.
Iran also threatened to
block all crude oil
shipments through the
Strait if the West placed
sanctions on its crude oil
exports. Almost 20
percent of the world's oil
supply travels through
the waterway. Crude oil prices remained supported
by these political events as the month drew to a close...</p></li>
                <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>
    </ul>
</div>
