<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2017-07/fig_HL1coppwp2.png" class="lightbox"><img src="images/2017-07/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude oil</h2>
            <ul>Monthly average crude oil prices show mixed trends in April. The average domestic crude oil first purchase price rose 84 cents (1.8%), to $47.23 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil decreased 29 cents (0.7%) to $43.77 per barrel. The average landed cost of foreign crude oil fell 39 cents (0.8%), to $45.67 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil increased 74 cents (1.5%), to $51.34 per barrel. The average cost of imported crude oil rose 94 cents (2.0%), to $47.47 per barrel. The composite refiner acquisition cost for crude oil increased 82 cents (1.7%), to $49.47 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>Refiner monthly average prices for motor gasoline continued to rise in April. The average retail price rose 9.3 cents to $1.997 per gallon, while the average wholesale price climbed 8.9 cents to $1.723 per gallon.</li>
                <li>Refiner sales of finished motor gasoline increased in April. Total sales rose 5.3 million gallons per day (1.6%) to an average of 327.0 million gallons per day. Retail sales fell 200,000 gallons per day (0.8%), while wholesales increased 5.5 million gallons per day (1.9%). DTW sales made up 7.5% of wholesales, while rack and bulk sales accounted for 85.8% and 6.8%, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>Monthly average prices for refiner sales of No. 2 distillates rose in April. The average price for No. 2 diesel fuel sold to end users climbed 4.6 cents to $1.745 per gallon, while the average wholesale price also increased 4.6 cents, rising to $1.627 per gallon. The average retail price for No. fuel oil rose 17.2 cents to $2.081, while the average wholesale price for No. 2 fuel oil rose 0.4 cent to $1.499 per gallon.</li>
                <li>Refiner sales of No. 2 ultra-low sulfur diesel fuel increased 1.5 million gallons per day (1.0%) to 148.3 million gallons per day in April. Retail sales declined 600,000 gallons per day (4.8%), while wholesales increased 2.1 million gallons per day (1.6%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Refiner monthly average residual fuel oil prices fell in April. The wholesale price for low-sulfur residual fuel oil declined 6.5 cents to $1.038 per gallon. The price for high-sulfur residual fuel oil fell 3.9 cents to $1.147 per gallon at retail, while the wholesale price decreased 3.6 cents to $1.039 per gallon.</li>
                <li>Sales of residual fuel oil by refiners dropped 500,000 gallons per day (4.8%) to 10.0 million gallons per day in April. Retail sales fell 800,000 gallons per day (17.4%), while wholesales increased 300,000 gallons per day (5.1%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>The direction of refiner prices for the remaining surveyed products were mixed in April. Propane prices fell at both the retail and wholesale levels, while prices for kerosene-type jet fuel increased in both categories. Prices for aviation gasoline and No. 1 distillate also rose at wholesale, while the price for kerosene declined in the same category.</li>
                <li>In April, refiner sales of propane rose at the retail level, but declined at wholesale, while data for kerosene-type jet fuel sales show the opposite trend. Sales of aviation gasoline increased at the wholesale level, while kerosene and No. 1 distillate sales fell in the same category.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>*/ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/petroleum/marketing/annual/archive/" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a></li>
    </ul>
</div>