<?php $L2Title = "Petroleum & Other Liquids"; ?><div class="l-row header">
<div class="l-full-width-column">
<div class="title-banner bg-petroleum"><?php /* Page/Section Title */ ?><h1><?php echo "$L2Title"?></h1></div>
<div class="subnav">
<div class="right">
<span class="align-right"><a href="<?php echo "$glossary_path"?>?id=petroleum">Glossary</a> <a href="<?php echo "$faqs_path"?>#crudeoil">FAQS</a></span></div>
<div class="left">
<ul class="left-nav"><li <?php if ( $locale == 'overview') {?>class="active"<?php  } // end if ?>><a href="/petroleum/">Overview</a></li><li  <?php if ( $locale == 'data') {?>class="active"<?php  } // end if ?>><a href="/petroleum/data.cfm">Data</a></li><li <?php if ( $locale == 'ap') {?>class="active"<?php  } // end if ?>><a href="/petroleum/reports.cfm">Analysis &amp; Projections</a></li>    </ul>
</div>
</div>
</div>
</div>