<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2014-11/fig_HL1coppwp2.png" class="lightbox"><img src="images/2014-11/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude Oil</h2>
            <ul>
                <li>Monthly average crude oil prices continued to decline in all categories of sale during August.  The average domestic crude oil first purchase price fell $6.01 (6.2 percent), to $90.66 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil dropped $2.93 (3.1 percent), to $90.90 per barrel.  The average landed cost of foreign crude oil fell $4.65 (4.8 percent), to $92.06 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil declined $5.45 (5.3 percent), to $97.75 per barrel.  The average cost of imported crude oil decreased $5.42 (5.5 percent), to $93.24 per barrel.  The composite refiner acquisition cost for crude oil dropped $5.48 (5.4 percent), to $95.70 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>Monthly average prices for refiner sales of motor gasoline also registered decreases in August.  The average retail price fell 11.5 cents to $3.013 per gallon, while the average wholesale price declined 9.6 cents to $2.759 per gallon.</li>
                <li>Sales of finished motor gasoline by refiners rose in August, with total sales increasing 1.1 million gallons per day (0.3 percent) to an average of 316.1 million gallons per day.  Retail sales rose 200,000 gallons per day (1.0 percent), while wholesales climbed 900,000 gallons per day (0.3 percent).  DTW sales accounted for 7.9 percent of wholesales, while rack and bulk sales made up 85.2 percent and 6.8 percent, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>Monthly average prices for sales of No. 2 distillates by refiners fell in August.  The average sales price for No. 2 diesel fuel to end users declined 1.8 cents to $3.012 per gallon, while the average wholesale price decreased 2.2 cents to $2.899 per gallon.  The average price for No. 2 fuel oil sales to end users fell 2.0 cents to $3.408 per gallon, while the average wholesale price dropped 4.1 cents to $2.784 per gallon.</li>
                <li>Refiner sales of No. 2 ultra-low sulfur diesel fuel decreased 700,000 gallons per day (0.5 percent) to an average of 153.5 million gallons per day in August.  Total No. 2 fuel oil sales increased 200,000 gallons per day (4.8 percent) to an average of 4.5 million gallons per day.</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>The direction of monthly average prices for refiner sales of residual fuel oil varied in August.  The wholesale price for low-sulfur residual fuel oil fell 13.6 cents to $2.151 per gallon.  Prices for high-sulfur residual fuel oil increased 2.6 cents to $2.350 per gallon at retail, but decreased 5.6 cents to $2.130 per gallon at wholesale.</li>
                <li>Refiner sales of residual fuel oil fell in August.  Total sales of residual fuel declined 900,000 gallons per day (7.3 percent) to an average of 11.5 million gallons per day.</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>Prices for the remaining surveyed products show mixed trends in August.  Kerosene-type jet fuel prices increased modestly at retail, but remained flat at wholesale.  The wholesale price for No. 1 distillate increased, while prices for aviation gasoline and No. 4 distillate decreased at the same level. Kerosene prices fell at retail, but rose at the wholesale, while propane prices declined at both levels.</li>
                <li>Refiner sales of propane rose at both retail and wholesale during August.  Kerosene-type jet fuel and kerosene sales were flat at retail, but declined at wholesale.  Sales of aviation gasoline fell at the wholesale level, while of No. 1 and No. 4 distillates increased at the same level.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>*/ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/oil_gas/petroleum/data_publications/petroleum_marketing_annual/pma_historical.html" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a>