<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Receive Email Updates</h2></li>
                <li>Sign up to receive Drilling Productivity Report updates via email</li>
                <li>
<fieldset>
<form action="http://www.eia.gov/nl/subscribe.cfm" method="POST" name="signup" class="report_summary">
<input type="text" name="email" value="" /><br/>
<input name="subscribe" type="submit" title="subscribe" value="Subscribe" alt="subscribe" />
<input type="hidden" name="list" value="drilling" />
<input type="hidden" name="confirm" value="two" />
<input type="hidden" name="showconfirm" value="T" />
</form>
</fieldset>
</li>
                <li><i class="ico email"></i><a href="/tools/emailupdates/">Sign up for more email updates</a></li>
    </ul>
</div>
