<!--dpr_text_box-->
<div class="content-container standard-container">
    <ul>
        <li class="header"><h2>Contents</h2></li>
                <li><i class="ico pdf">PDF</i><a href="pdf/anadarko.pdf">Anadarko</a></li>
                <li><i class="ico pdf">PDF</i><a href="pdf/appalachia.pdf">Appalachia</a></li>
                <li><i class="ico pdf">PDF</i><a href="pdf/bakken.pdf">Bakken</a></li>
                <li><i class="ico pdf">PDF</i><a href="pdf/eagleford.pdf">Eagle Ford</a></li>
                <li><i class="ico pdf">PDF</i><a href="pdf/haynesville.pdf">Haynesville</a></li>
                <li><i class="ico pdf">PDF</i><a href="pdf/niobrara.pdf">Niobrara</a></li>
                <li><i class="ico pdf">PDF</i><a href="pdf/permian.pdf">Permian</a></li>
                <li><i class="ico pdf">PDF</i><a href="pdf/dpr-full.pdf">Full report</a></li>
                <li><i class="ico pdf">PDF</i><a href="pdf/summary.pdf">Year-over-year summary</a></li>
                <li></li>
                <li><i class="ico xls">XLS</i><a href="xls/dpr-data.xlsx">Report data</a> (aggregated by region)</li>
                <li><i class="ico xls">XLS</i><a href="xls/duc-data.xlsx">DUC data</a> (aggregated by region)</li>
                <li></li>
                <li><i class="ico pdf">PDF</i><a href="pdf/duc_supplement.pdf">DUC supplement</a></li>
                <li><i class="ico pdf">PDF</i><a href="pdf/dpr_methodology.pdf"> Documentation</a></li>
                <li><i class="ico pdf">PDF</i><a href="pdf/notes-sources.pdf">Explanatory notes and sources</a></li>
                <li><i class="ico pdf">PDF</i><a href="faqs.php">Frequently Asked Questions</a></li>
    </ul>
</div>
<div class="content-container standard-list-container">
    <ul>
        <li class="header"><h2>Related Today in Energy articles</h2></li>
                <li><a href="http://www.eia.gov/todayinenergy/detail.php?id=27932">EIA now provides estimates of drilled but uncompleted wells in major production regions</a></li>
                <li><a href="/todayinenergy/detail.cfm?id=24932">Initial production rates in tight oil formations continue to rise</a></li>
                <li><a href="/todayinenergy/detail.cfm?id=22672">EIA expects near-term decline in natural gas production in major shale regions</a></li>
                <li><a href="/todayinenergy/detail.cfm?id=20392">Falling rig counts drive projected near-term oil production decline in 3 key U.S. regions</a></li>
                <li><a href="/todayinenergy/detail.cfm?id=22292">EIA reports show different aspects of U.S. oil production statistics and trends</a></li>
                <li><a href="/todayinenergy/detail.cfm?id=17511">Ohio's Utica Region now included in EIA's monthly Drilling Productivity Report</a></li>
                <li><a href="/todayinenergy/detail.cfm?id=14091">Marcellus region to provide 18% of total U.S. natural gas production this month</a></li>
                <li><a href="/todayinenergy/detail.cfm?id=13811">Bakken oil production forecast to top 1 million barrels per day next month</a></li>
                <li><a href="/todayinenergy/detail.cfm?id=13671">Production, depletion trends are keys to predicting natural gas and oil production</a></li>
                <li><a href="/todayinenergy/detail.cfm?id=13651">Drilling efficiency is a key driver of oil and natural gas production</a></li>
                <li><a href="/todayinenergy/detail.cfm?id=13571">Drilling often results in both oil and natural gas production</a></li>
                <li><a href="/todayinenergy/detail.cfm?id=13551">Rethinking rig count as a predictor of natural gas production</a></li>
                <li><a href="/todayinenergy/detail.cfm?id=13451">EIA to release new Drilling Productivity Report</a></li>
                <li><a href="/todayinenergy/detail.cfm?id=13471">Highlights of new Drilling Productivity Report</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Give Us Your Feedback</h2></li>
    </ul>
<?php include ('feedback.inc') ; ?>
</div>
<?php include ('email_updates.inc') ; ?>
