<table class="data">
<caption></caption>
<thead>
<tr class="double-header">
<th class="no-border"></th>
<th colspan="3">New-well oil production per rig <strong>barrels/day</strong></th>
<th class="no-border"></th>
<th colspan="3">New-well gas production per rig <strong>thousand cubic feet/day</strong></th>
</tr>
<tr>
<th>Region</td>
<th>August 2017</th>
<th>September 2017</th>
<th>change</th>
<th>&nbsp;</th>
<th>August 2017</th>
<th>September 2017</th>
<th>change</th>
</tr>
</thead>
<tbody>
<tr>
<td>Anadarko</td>
<td>370</td>
<td>372</td>
<td>2</td>
<td class="indented"></td>
<td>2,507</td>
<td>2,512</td>
<td>5</td>
</tr>
<tr>
<td>Appalachia</td>
<td>127</td>
<td>128</td>
<td>1</td>
<td class="indented"></td>
<td>14,210</td>
<td>14,108</td>
<td>(102)</td>
</tr>
<tr>
<td>Bakken</td>
<td>1,177</td>
<td>1,190</td>
<td>13</td>
<td class="indented"></td>
<td>1,554</td>
<td>1,557</td>
<td>3</td>
</tr>
<tr>
<td>Eagle Ford</td>
<td>1,410</td>
<td>1,379</td>
<td>(31)</td>
<td class="indented"></td>
<td>4,620</td>
<td>4,642</td>
<td>22</td>
</tr>
<tr>
<td>Haynesville</td>
<td>33</td>
<td>34</td>
<td>1</td>
<td class="indented"></td>
<td>7,540</td>
<td>7,578</td>
<td>38</td>
</tr>
<tr>
<td>Niobrara</td>
<td>1,284</td>
<td>1,285</td>
<td>1</td>
<td class="indented"></td>
<td>4,523</td>
<td>4,552</td>
<td>29</td>
</tr>
<tr>
<td>Permian</td>
<td>599</td>
<td>595</td>
<td>(4)</td>
<td class="indented"></td>
<td>1,005</td>
<td>999</td>
<td>(6)</td>
</tr>
<tr>
<td>Total</td>
<td>655</td>
<td>645</td>
<td>(10)</td>
<td class="indented"></td>
<td>3,483</td>
<td>3,460</td>
<td>(23)</td>
</tr>
</tbody>
<tfoot>
</tfoot>
</table>
