<table class="data"><caption></caption>
<thead>
<tr>
<th colspan="3"><strong>U.S. Natural Gas Supply - <?php echo "$gas_week_supply"?></strong></th>
</tr>
<tr>
<td class="no-border"><strong></strong></td>
<td colspan="2"><div align="center">Percent change for week compared with:</td>
</tr>
<tr>
<td width="120" class="no-border">&nbsp;</td>
<td><strong>last year</strong></td>
<td><strong>last week</strong></td>
</tr>
<tr>
<td>Gross Production</td>
<td><?php echo "$gp_thisweek_lastyear"?></td>
<td><?php echo "$gp_thisweek_lastweek"?></td>
</tr>
<tr>
<td>Dry Production</td>
<td><?php echo "$dp_thisweek_lastyear"?></td>
<td><?php echo "$dp_thisweek_lastweek"?></td>
</tr>
<tr>
<td>Canadian Imports</td>
<td><?php echo "$ci_thisweek_lastyear"?></td>
<td><?php echo "$ci_thisweek_lastweek"?></td>
</tr>
<tr>
<td class="indented">West (Net)</td>
<td><?php echo "$ci_w_thisweek_lastyear"?></td>
<td><?php echo "$ci_w_thisweek_lastweek"?></td>
</tr>
<tr>
<td class="indented">MidWest (Net)</td>
<td><?php echo "$ci_mw_thisweek_lastyear"?></td>
<td><?php echo "$ci_mw_thisweek_lastweek"?></td>
</tr>
<tr>
<td class="indented">Northeast (Net)</td>
<td><?php echo "$ci_ne_thisweek_lastyear"?></td>
<td><?php echo "$ci_ne_thisweek_lastweek"?></td>
</tr>
<tr>
<td>LNG Imports</td>
<td><?php echo "$lng_imports_thisweek_lastyear"?></td>
<td><?php echo "$lng_imports_thisweek_lastweek"?></td>
</tr>
<tr>
<td>Total Supply</td>
<td><?php echo "$ts_thisweek_lastyear"?></td>
<td><?php echo "$ts_thisweek_lastweek"?></td>
</tr>
<tr>            <td colspan="3" class="no-border">
<span class="source">Source: BENTEK Energy LLC</span></td>        </tr>
</table>
