<table class="data">
<caption></caption>
<thead>
<tr class="double-header">
<th class="no-border"></th>
<th colspan="3">Oil production <strong>thousand barrels/day</strong></th>
<th class="no-border"></th>
<th colspan="3">Gas production <strong>million cubic feet/day</strong></th>
</tr>
<tr>
<th>Region</td>
<th>August 2017</th>
<th>September 2017</th>
<th>change</th>
<th>&nbsp;</th>
<th>August 2017</th>
<th>September 2017</th>
<th>change</th>
</tr>
</thead>
<tbody>
<tr>
<td>Anadarko</td>
<td>447</td>
<td>459</td>
<td>12</td>
<td class="indented"></td>
<td>5,979</td>
<td>6,057</td>
<td>78</td>
</tr>
<tr>
<td>Appalachia</td>
<td>96</td>
<td>98</td>
<td>2</td>
<td class="indented"></td>
<td>24,299</td>
<td>24,649</td>
<td>350</td>
</tr>
<tr>
<td>Bakken</td>
<td>1,044</td>
<td>1,054</td>
<td>10</td>
<td class="indented"></td>
<td>1,924</td>
<td>1,950</td>
<td>26</td>
</tr>
<tr>
<td>Eagle Ford</td>
<td>1,379</td>
<td>1,393</td>
<td>14</td>
<td class="indented"></td>
<td>6,254</td>
<td>6,317</td>
<td>63</td>
</tr>
<tr>
<td>Haynesville</td>
<td>46</td>
<td>46</td>
<td>-</td>
<td class="indented"></td>
<td>6,725</td>
<td>6,877</td>
<td>152</td>
</tr>
<tr>
<td>Niobrara</td>
<td>483</td>
<td>498</td>
<td>15</td>
<td class="indented"></td>
<td>4,805</td>
<td>4,905</td>
<td>100</td>
</tr>
<tr>
<td>Permian</td>
<td>2,537</td>
<td>2,601</td>
<td>64</td>
<td class="indented"></td>
<td>8,511</td>
<td>8,671</td>
<td>160</td>
</tr>
<tr>
<td>Total</td>
<td>6,032</td>
<td>6,149</td>
<td>117</td>
<td class="indented"></td>
<td>58,497</td>
<td>59,426</td>
<td>929</td>
</tr>
</tbody>
<tfoot>
</tfoot>
</table>
