<table class="data"><caption></caption>
<thead>
<tr>
<th colspan="3"><strong>U.S. Consumption - <?php echo "$gas_week_demand"?></strong></th>
</tr>
<tr>
<td class="no-border"></td>
<td colspan="2"><div align="center">Percent change for week compared with:</td>
</tr>
<tr>
<td width="120" class="no-border">&nbsp;</td>
<td class="align-center"><strong>last year</strong></td>
<td class="align-center"><strong>last week</strong></td>
</tr>
<tr>
<td>U.S. Consumption</td>
<td class="align-center"><?php echo "$us_demand_thisweek_lastyear"?></td>
<td class="align-center"><?php echo "$us_demand_thisweek_lastweek"?></td>
</tr>
<tr>
<td>Power</td>
<td class="align-center"><?php echo "$power_thisweek_lastyear"?></td>
<td class="align-center"><?php echo "$power_thisweek_lastweek"?></td>
</tr>
<tr>
<td>Industrial</td>
<td class="align-center"><?php echo "$industrial_thisweek_lastyear"?></td>
<td class="align-center"><?php echo "$industrial_thisweek_lastweek"?></td>
</tr>
<tr>
<td>Residential/Commercial</td>
<td class="align-center"><?php echo "$rescom_thisweek_lastyear"?></td>
<td class="align-center"><?php echo "$rescom_thisweek_lastweek"?></td>
</tr>
<tr>
<td>Total Demand</td>
<td class="align-center"><?php echo "$td_thisweek_lastyear"?></td>
<td class="align-center"><?php echo "$td_thisweek_lastweek"?></td>
</tr>
<tr>            <td colspan="3" class="no-border">
<span class="source">Source: BENTEK Energy LLC</span></td>        </tr>
</table>
