<table class="data"><caption></caption>
<thead>
<tr class="double-header">
<th class="no-border"></th>
<th colspan="3">Drilled but uncompleted wells (DUC) <span style="font-weight:normal">wells</span></th>
</tr>
<tr>
<th>Region</td>
<th>June 2017</th>
<th>July 2017</th>
<th>change</th>
<th>&nbsp;</th>
</tr>
</thead>
<tbody>
<tr>
<td>Anadarko</td>
<td>906</td>
<td>948</td>
<td>42</td>
<td class="indented"></td>
</tr>
<tr>
<td>Appalachia</td>
<td>724</td>
<td>711</td>
<td>(13)</td>
<td class="indented"></td>
</tr>
<tr>
<td>Bakken</td>
<td>784</td>
<td>782</td>
<td>(2)</td>
<td class="indented"></td>
</tr>
<tr>
<td>Eagle Ford</td>
<td>1,385</td>
<td>1,420</td>
<td>35</td>
<td class="indented"></td>
</tr>
<tr>
<td>Haynesville</td>
<td>189</td>
<td>194</td>
<td>5</td>
<td class="indented"></td>
</tr>
<tr>
<td>Niobrara</td>
<td>668</td>
<td>674</td>
<td>6</td>
<td class="indented"></td>
</tr>
<tr>
<td>Permian</td>
<td>2,195</td>
<td>2,330</td>
<td>135</td>
<td class="indented"></td>
</tr>
<tr class="section">
<td>Total</td>
<td>6,851</td>
<td>7,059</td>
<td>208</td>
<td class="indented"></td>
</tr>
</tbody>
<tfoot>
</tfoot>
</table>
