<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2015-04/fig_HL1coppwp2.png" class="lightbox"><img src="images/2015-04/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude Oil</h2>
            <ul>
                <li>Monthly average crude oil prices continued to fall in January.  The average domestic crude oil first purchase price declined $11.76 (21.4 percent), to $43.10 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil dropped $9.77 (19.5 percent), to $40.29 per barrel.  The average landed cost of foreign crude oil fell $11.26 (20.5 percent), to $43.75 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil declined $14.25 (22.5 percent), to $48.97 per barrel.  The average cost of imported crude oil decreased $12.52 (21.9 percent), to $44.74 per barrel.  The composite refiner acquisition cost for crude oil fell $13.61 (22.4 percent), to $47.03 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>Monthly average prices for sales of motor gasoline by refiners remained on a downward path during January.  The average retail price declined 33.5 cents to $1.678 per gallon, while the average wholesale price fell 26.9 cents to $1.365 per gallon.</li>
                <li>Sales of finished motor gasoline by refiners declined in January.  Total sales fell 17.6 million gallons per day (5.4 percent) to an average of 305.7 million gallons per day.  Retail sales dropped 2.6 million gallons per day (9.7 percent), while wholesales decreased 15.0 million gallons per day (5.1 percent).  DTW sales accounted for 7.8 percent of wholesales, while rack and bulk sales made up 84.5 percent and 7.7 percent, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>January monthly average prices for sales of No. 2 distillates by refiners registered considerable declines.  The average sales price for No. 2 diesel fuel to end users fell 36.8 cents to $1.825 per gallon, while the average wholesale price decreased 36.4 cents to $1.616 per gallon.  The average wholesale price for No. 2 fuel oil fell 37.1 cents to $2.050 per gallon.</li>
                <li>Sales of No. 2 ultra-low sulfur diesel fuel by refiners declined in January.  Retail sales remained flat at 12.4 million gallons per day, while sales fell 11.8 million gallons per day (7.2 percent) at the wholesale level.</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Monthly average prices for sales of residual fuel oil by refiners continued to fall in January.  The wholesale price for low-sulfur residual fuel oil declined 29.8 cents to 93.9 cents per gallon.  Prices for high-sulfur residual fuel oil decreased 41.2 cents to $1.199 per gallon at retail, while the wholesale price fell 28.6 cents to $1.024 per gallon.</li>
                <li>Refiner sales of residual fuel oil declined in January.  Total sales fell 2.1 million gallons per day (15.7 percent) to an average of 11.3 million gallons per day.</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>Prices for the remaining surveyed products continued to fall in January.  Propane, kerosene-type jet fuel, and No. 1 distillate prices decreased at both the retail and wholesale levels, while prices for aviation gasoline, kerosene, and No. 4 distillate declined at wholesale.</li>
                <li>Refiner sales of propane increased at both retail and wholesale during January, while kerosene-type jet fuel sales fell at both levels.  No. 1 distillate sales rose at the retail level, while wholesales remained flat.  Sales of aviation gasoline fell at wholesale, while kerosene and No. 4 distillate sales increased at the same level.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>*/ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/oil_gas/petroleum/data_publications/petroleum_marketing_annual/pma_historical.html" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a>