<?php/**
* First we need to log the error
*/
require_once 'vendor/autoload.php';
use Monolog\Logger;
use Monolog\Handler\StreamHandler;
// create a log channel
$log = new Logger($_SERVER["COMPUTERNAME"] . '_error_log');
// Each web server logs are stored on the servers in D:\php_errorlogs\{server_name}\phpError.log
// E.g. D:\php_errorlogs\www1\phpError.log
if ($_SERVER["COMPUTERNAME"] === "WWWDEV"){
$errorLogPath =  "D:/website/global/error/" . strtolower($_SERVER["COMPUTERNAME"]) . "/phpError.log";
} elseif (strpos($_SERVER["COMPUTERNAME"], 'VRA-OC') !== false){
$errorLogPath =  "C:/inetpub/wwwroot/global/error/" . strtolower($_SERVER["COMPUTERNAME"]) . "/phpError.log";
} else {
$errorLogPath =  "D:/php_errorlogs/" . strtolower($_SERVER["COMPUTERNAME"]) . "/phpError.log";
}
$stream = new StreamHandler($errorLogPath, Logger::DEBUG);
$stream->setFormatter( new \Monolog\Formatter\JsonFormatter());
$log->pushHandler($stream);
/**
* This array stores how we want to log the errors in monolog based on the php error type
* @var array
*/
$phpLogVals = [
// http://php.net/manual/en/errorfunc.constants.php
1 => "critical",       // Fatal run-time errors. These indicate errors that can not be recovered from, such as a memory allocation problem. Execution of the script is halted.
2 => "warn",           // Run-time warnings (non-fatal errors). Execution of the script is not halted.
4 => "critical",       // Compile-time parse errors. Parse errors should only be generated by the parser.
8 => "notice",         // Run-time notices. Indicate that the script encountered something that could indicate an error, but could also happen in the normal course of running a script.
16 => "error",
32 => "warn",
64 => "critical",
128 => "warn",
256 => "error",
512 => "warn",
1024 => "notice",
2048 => "debug",
4096 => "error",
8192 => "notice",
16384 => "notice",
32767 => "info",
];
/**
* For certain errors, rather than stop the script at the error, the script won't execute at all.
* In these cases, we need to add the EIA header and footer
* @var array
*/
$showHeader = [
4
];
// This will tell us if users are going to individual web servers when getting an error
$webServerName  = $_SERVER['SERVER_NAME'] ?? "No SERVER_NAME set";
$urlDuringError = $_SERVER['REQUEST_URI'] ?? "No REQUEST_URI";
$urlQueryParams = $_SERVER['QUERY_STRING'] ?? "No QUERY_STRING";
$urlHttpReferrer = $_SERVER['HTTP_REFERER'] ?? "No HTTP_REFERER";
$webServerName  = htmlspecialchars($webServerName, ENT_QUOTES);
$urlDuringError = htmlspecialchars($urlDuringError, ENT_QUOTES);
$urlQueryParams = htmlspecialchars($urlQueryParams, ENT_QUOTES);
$urlHttpReferrer = htmlspecialchars($urlHttpReferrer, ENT_QUOTES);
$logContext = [
'file' => $last_error['file'],
'line' => $last_error['line'],
'phpErrorLevel' => $last_error['type'],
'requestUri' => $urlDuringError,
'urlQueryParams' => $urlQueryParams,
'urlHttpReferrer' => $urlHttpReferrer,
];
$log->{$phpLogVals[$last_error['type']]}($last_error['message'], $logContext);
// if a showstopper, show the canned error page to the user and email
if ($showStopper === true) {
header("HTTP/1.0 200 Ok");
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>EIA - Sorry!  Unexpected Error</title>
<!-- ****************************************** Begin META TAGS ********************************************* -->
<meta name="agency" content="EIA">
<meta name="description" content="Sorry! PHP Error Encountered">
<!-- ****************************************** End META TAGS *********************************************** -->
<link rel="stylesheet" href="/styles/eia_sitewideF.css" type="text/css">
<?php
// for some errors, the entire page won't parse, so we must render headers and footers
if(in_array( $logContext['phpErrorLevel'], $showHeader)) { ?>
<script language="JavaScript" src="/styles/eia_header.js" type="text/javascript"></script>
<?php }?>
<?php /* If the script ends abruptly, we don't need the header, but we will need the footer */ ?>
<script language="JavaScript" src="/styles/eia_footer.js" type="text/javascript"></script>
</head>
<body bgColor="#ffffff" leftMargin="0" topMargin="0" marginwidth="0" marginheight="0">
<!-- ****************************************** Begin HEADER ************************************************ -->
<div align="center">
<center>
<!-- BEGIN BANNER, FOLLOWED BY TOP NAV-->
<?php
// for some errors, the entire page won't parse, so we must render headers and footers
if(in_array( $logContext['phpErrorLevel'], $showHeader)) { ?>
<script language="JavaScript">InsertEIAHeaderCode();</script>
<?php }?>
<!-- END OF TOP NAV & BANNER -->
<!-- ****************************************** End HEADER ************************************************** -->
<!-- THIS BEGIN THE MAIN CONTENT TABLE-->
<!-- INSERT CONTENT HERE-->
<table border="0" width="95%" cellpadding="2" cellspacing="0">
<tr>
<td height="8" colspan="3" valign="TOP"><span class="breadcrumbs"><a href="/">Home</a>
></span> <span class="breadcrumbshd">Error</span></td>
</tr>
<th height="5" colspan="3" valign="TOP" class="SectionHead">
<div align="left" class="Pagetitle">Unexpected Error &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; </div>
</th>
</tr>
<tr>
<td>
<span style="font-family: arial;">
<br />
<h3>Sorry!  An error was encountered.</h3>
This error could be due to scheduled maintenance.
<br />
<br />
Information about the error has been routed to the appropriate person.
<h4>Please try again later</h4>
<BR><i style="font-size: 7pt">Site-wide Error Handler</i>
</span>
<?php
try {
// Define the global SMTP mailer
include_once 'global/includes/utils/Mailer.inc';
$mailer = new Mailer();
// Make work even when on individual web servers
$mailer->Host = "tontorelay.eia.gov";
$srvr = $_SERVER['SERVER_NAME'] ?? "";
$filePath = realpath($last_error['file']);
$sbj = $srvr . ": PHP Error: In file " . $filePath;
$mailer->addAddress('Scott.Gearhart@eia.gov', 'Scott Gearhart');
$mailer->addAddress('Robert.Ciconte@eia.gov', 'Robert Ciconte');
$mailer->addAddress('Steve.Luminati@eia.gov', 'Steve Luminati');
$bdy = "<h2>Uncaught Error trapped by the " . $srvr . " Sitewide Error Handler</h2>";
$bdy .= "<p>Date/Time: " . date("Y-m-d H:i:s") . "</p>";
$bdy .= "<p>Type: " . $last_error['type'] . "</p>";
$bdy .= "<p>Message: " . $last_error['message'] . "</p>";
$bdy .= "<p>File: " . $last_error['file'] . "</p>";
$bdy .= "<p>Line:" .$last_error['type'] . "</p>";
$bdy .= "<p>The contents of the debug backtrace are:</p>";
$e = new \Exception;
$bdy .= $e->getTraceAsString();
$mailer->FromName = "PHP Site-Err";
$mailer->Subject = $sbj;
$mailer->Body = $bdy;
// If sending fails, throw a PHP error
if (!$mailer->send()) {
throw new Exception($mailer->ErrorInfo);
} else {
$json = [
'status' => 'ok',
'msg'    => 'Error message sent'
];
}
}
catch (Exception $e){
echo "<br><br> ...and there was an error in the error page!";
}
?>
</td>
</tr>
</table>
<!-- END BODY TEXT -->
<!-- THIS END THE MAIN CONTENT TABLE-->
<!-- ****************************************** Begin FOOTER ************************************************ -->
<!-- START FOOTER HERE -->
<script language="JavaScript">InsertEIAFooterCode();</script>
<!-- ****************************************** End FOOTER ************************************************** -->
</CENTER>
</div>
</body>
</html>
<?php } // end checking for $showStopper variable?>
