<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong> Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2013-09/fig_HL1coppwp.jpg" class="lightbox"><img src="images/2013-09/fig_HL1_coppwp_sm.jpg" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3>Highlights</h3></li>
        <li class="header"><h2>Crude Oil</h2>
            <ul>
                <li>Monthly average prices for crude oil declined in allsales categories during June. The average domesticcrude oil first purchase price fell 95 cents (1.0 percent),to $94.05 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of importedcrude oil decreased 64 cents (0.7 percent), to $95.50 perbarrel. The average landed cost of foreign crude oildeclined $2.09 (2.2 percent), to $95.02 per barrel.</li>
                <li>The average refiner acquisition cost for domesticcrude oil dropped $1.72 (1.7 percent), to $100.26 perbarrel. The average cost of imported crude decreased$1.33 (1.4 percent), to $97.17 per barrel. The compositerefiner acquisition cost for crude oil fell $1.50 (1.5percent), to $98.67 per barrel.</li>
            </ul>
        </li>
        <li class="header"><h2>Petroleum Products</h2></li>
                <li><h4>Motor Gasoline</h4>
            <ul>
                <li>Monthly average prices for sales of finished gasolineby refiners decreased in June. The average retail salesprice for motor gasoline fell 0.2 cent to $3.186 pergallon, while the average wholesale price declined 6.9cents to $2.882 per gallon.</li>
                <li>Refiner sales of finished motor gasoline were on therise in June. Total sales increased 700,000 gallons perday (0.2 percent) to an average of 322.4 million gallonsper day. Retail sales decreased 100,000 gallons per day(0.4 percent), while wholesales increased 800,000gallons per day (0.3 percent). DTW salesaccounted for 10.1 percent of wholesales, whilerack and bulk sales made up 81.8 percent and 8.1percent, respectively.</li>
                    </ul>
        </li>
                <li><h4>No. 2 Distillate</h4>
            <ul>
                <li>Refiner monthly average prices for No. 2 distillateslargely decreased during June. The average salesprice for No. 2 diesel fuel to end users fell 2.8 centsto $3.030 per gallon, while the average wholesaleprice decreased 3.6 cents to $2.922 per gallon. Theaverage price for No. 2 fuel oil sales to end usersdropped 5.0 cents to $3.172 per gallon, while theaverage wholesale price rose 3.3 cents to $2.741 pergallon.</li>
                <li>Overall, refiner sales of No. 2 distillates increasedduring June, rising 1.9 million gallons per day.No. 2 fuel oil sales fell 1.5 million gallons per day(26.8 percent), while sales of No. 2 diesel fuel rose3.5 million gallons per day (2.2 percent).</li>
                    </ul>
        </li>
                <li><h4>Residual Fuel Oil</h4>
            <ul>
                <li>Monthly average prices for refiner residual fueloilJune monthly average prices for refiner residualfuel oil sales decreased in all sales categories.Prices for low-sulfur residual fuel oil fell 5.4 centsto $2.785 per gallon at retail, and 3.1 cents to $2.285per gallon at wholesale. Prices for high-sulfurresidual fuel oil declined 3.8 cents to $2.383 pergallon at retail, and 0.4 cent to $2.209 per gallon atwholesale.</li>
                <li>Sales of residual fuel oil by refiners rose in June. Totalsales increased 500,000 gallons to 15.3 million gallonsper day. Low-sulfur residual fuel oil sales remainedflat, while high-sulfur residual fuel oil sales rose600,000 gallons per day (5.4 percent).</li>
                    </ul>
        </li>
                <li><h4>Other Products</h4>
            <ul>
                <li>During June, prices for propane and No. 1 distillatedeclined at both the retail and wholesale levels, whileprices for kerosene-type jet fuel did just the opposite.Kerosene prices decreased at retail, but rose atwholesale. Aviation gasoline and No. 4 fuel oilprices fell at the wholesale level.</li>
                <li>Refiner sales of these products varied in June.Sales of propane, kerosene, and No. 1 distillatedecreased at retail and wholesale. Kerosene-typejet fuel sales fell at the retail level, but increased atwholesale. Aviation gasoline sales increased atthe wholesale level, while sales of No. 4 distillatedeclined at wholesale.</li>
        </ul></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>