<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2015-12/fig_HL1coppwp2.png" class="lightbox"><img src="images/2015-12/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude Oil</h2>
            <ul>
                <li>Monthly average crude oil prices show mixed trends in September. The average domestic crude oil first purchase price increased $1.62 (4.1%), to $41.60 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil moved 15 cents higher (0.4%) to $37.08 per barrel. The average landed cost of foreign crude oil fell $1.63 (4.0%), to $39.57 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil rose 48 cents (1.0%), to $46.78 per barrel. The average cost of imported crude oil decreased $2.13 (4.9%), to $41.10 per barrel. The composite refiner acquisition cost for crude oil dropped 53 cents (1.2%), to $44.44 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>Refiner monthly average prices for sales of motor gasoline continued to fall in September. The average retail price decreased 29.8 cents to $1.920 per gallon, while the average wholesale price fell 22.9 cents to $1.609 per gallon.</li>
                <li>Sales of finished motor gasoline by refiners declined in September. Total sales fell 400,000 gallons per day (0.1%) to an average of 329.7 million gallons per day. Retail sales declined 300,000 gallons per day (1.2%), while wholesales decreased 100,000 gallons per day (0.0%). DTW sales accounted for 7.6% of wholesales, while rack and bulk sales made up 84.4% and 8.0%, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>Monthly average prices for refiner sales of No. 2 distillates decreased in September.  The average sales price for No. 2 diesel fuel to end users declined 4.4 cents to $1.693 per gallon, while the average wholesale price fell 1.1 cents to $1.551 per gallon. The average sales price for No. 2 fuel oil to end users dropped 9.7 cents to $1.949 per gallon, while the average wholesale price for No. 2 fuel oil decreased 2.3 cents to $1.438 per gallon.</li>
                <li>Refiner sales of No. 2 ultra-low sulfur diesel fuel increased in September. Retail sales rose 300,000 gallons per day (2.4%), while wholesales climbed 5.9 million gallons per day (4.1%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>The direction of refiner monthly average prices for residual fuel oil varied in September. The wholesale price for low-sulfur residual fuel oil increased 2.1 cents to 81.8 cents per gallon. Prices for high-sulfur residual fuel oil decreased 8.7 cents to $1.063 per gallon at retail, while the wholesale price fell 7.5 cents to 85.3 cents per gallon.</li>
                <li>Overall, sales of residual fuel oil by refiners declined in September. Retail sales increased 200,000 gallons per day (4.7%), while wholesales declined 800,000 gallons per day (8.8%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>Refiner monthly average prices for sales of the remaining surveyed products show mixed movements in September. Prices for propane increased at both the retail and wholesale levels, while prices for kerosene-type jet fuel fell at both levels.  The wholesale price for kerosene rose, while wholesale prices for aviation gasoline, No. 1 distillate, and No. 4 distillate registered decreases.</li>
                <li>Refiner sales of products included in this section were varied during September. Sales of propane and kerosene-type jet fuel fell at retail, but increased at wholesale. Aviation gasoline and No. 1 distillate sales rose at the wholesale level, while sales of kerosene and No. 4 declined in the same category.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>*/ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/petroleum/marketing/annual/archive/" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a></li>
    </ul>
</div>