<!-- diff -->
<table class="data-table-two fullwidth" id="rh">
<caption>        <li><a href="/dnav/pet/pet_pri_wfr_a_EPD2F_PRS_dpgal_w.htm">Residential Heating Oil <span class="date">(dollars per gallon)</span><span>more price data &rsaquo;</span></a></caption>
<thead class="double-header">
<tr>
<th>&nbsp;</th>
<th>&nbsp;</th>
<th colspan="2">change from</th>
</tr>
<tr>
<th>&nbsp;</th>
<th>RHWDate</th>
<th>week ago</th>
<th>year ago</th>
</tr>
</thead>
<tbody>
<tr class="selected" id="rh_us">
<td><i class="ico linechart" title="Click to chart this series"></i>U.S. Average</td>
<td>RHW1Avg</td>
<td>RHW2Avg<span class="%g.r1c2%"></span></td>
<td>RHW3Avg<span class="%g.r1c3%"></span></td>
</tr>
<tr id="rh_padd1">
<td><i class="ico linechart" title="Click to chart this series"></i>East Coast (PADD 1)</td>
<td>RHW1EastCst</td>
<td>RHW2EastCst<span class="%g.r2c2%"></span></td>
<td>RHW3EastCst<span class="%g.r2c3%"></span></td>
</tr>
<tr class="ne">
<td><i class="ico toggle">Toggle</i>New England (PADD 1A)</td>
<td>RHW1NewEng</td>
<td>RHW2NewEng<span class="%g.r3c2%"></span></td>
<td>RHW3NewEng<span class="%g.r3c3%"></span></td>
</tr>
<tr class="padd1a">
<td>Connecticut</td>
<td>RHW1CT</td>
<td>RHW2CT<span class="%g.r4c2%"></span></td>
<td>RHW3CT<span class="%g.r4c3%"></span></td>
</tr>
<tr class="padd1a">
<td>Maine</td>
<td>RHW1ME</td>
<td>RHW2ME<span class="%g.r5c2%"></span></td>
<td>RHW3ME<span class="%g.r5c3%"></span></td>
</tr>
<tr class="padd1a">
<td>Massachusetts</td>
<td>RHW1MA</td>
<td>RHW2MA<span class="%g.r6c2%"></span></td>
<td>RHW3MA<span class="%g.r6c3%"></span></td>
</tr>
<tr class="padd1a">
<td>New Hampshire</td>
<td>RHW1NH</td>
<td>RHW2NH<span class="%g.r7c2%"></span></td>
<td>RHW3NH<span class="%g.r7c3%"></span></td>
</tr>
<tr class="padd1a">
<td>Rhode Island</td>
<td>RHW1RI</td>
<td>RHW2RI<span class="%g.r8c2%"></span></td>
<td>RHW3RI<span class="%g.r8c3%"></span></td>
</tr>
<tr class="padd1a">
<td>Vermont</td>
<td>RHW1VT</td>
<td>RHW2VT<span class="%g.r9c2%"></span></td>
<td>RHW3VT<span class="%g.r9c3%"></span></td>
</tr>
<tr class="ca">
<td><i class="ico toggle">Toggle</i>Central Atlantic (PADD 1B)</td>
<td>RHW1CentAtl</td>
<td>RHW2CentAtl<span class="%g.r10c2%"></span></td>
<td>RHW3CentAtl<span class="%g.r10c3%"></span></td>
</tr>
<tr class="padd1b">
<td>Delaware</td>
<td>RHW1DE</td>
<td>RHW2DE<span class="%g.r11c2%"></span></td>
<td>RHW3DE<span class="%g.r11c3%"></span></td>
</tr>
<tr class="padd1b">
<td>Dist Columbia</td>
<td>RHW1DC</td>
<td>RHW2DC<span class="%g.r12c2%"></span></td>
<td>RHW3DC<span class="%g.r12c3%"></span></td>
</tr>
<tr class="padd1b">
<td>Maryland</td>
<td>RHW1MD</td>
<td>RHW2MD<span class="%g.r13c2%"></span></td>
<td>RHW3MD<span class="%g.r13c3%"></span></td>
</tr>
<tr class="padd1b">
<td>New Jersey</td>
<td>RHW1NJ</td>
<td>RHW2NJ<span class="%g.r14c2%"></span></td>
<td>RHW3NJ<span class="%g.r14c3%"></span></td>
</tr>
<tr class="padd1b">
<td>New York</td>
<td>RHW1NY</td>
<td>RHW2NY<span class="%g.r15c2%"></span></td>
<td>RHW3NY<span class="%g.r15c3%"></span></td>
</tr>
<tr class="padd1b">
<td>Pennsylvania</td>
<td>RHW1PA</td>
<td>RHW2PA<span class="%g.r16c2%"></span></td>
<td>RHW3PA<span class="%g.r16c3%"></span></td>
</tr>
<tr class="la">
<td><i class="ico toggle">Toggle</i>Lower Atlantic (PADD 1C)</td>
<td>RHW1LowerAtl</td>
<td>RHW2LowerAtl<span class="%g.r17c2%"></span></td>
<td>RHW3LowerAtl<span class="%g.r17c3%"></span></td>
</tr>
<tr class="padd1c">
<td>North Carolina</td>
<td>RHW1NC</td>
<td>RHW2NC<span class="%g.r18c2%"></span></td>
<td>RHW3NC<span class="%g.r18c3%"></span></td>
</tr>
<tr class="padd1c">
<td>Virginia</td>
<td>RHW1VA</td>
<td>RHW2VA<span class="%g.r19c2%"></span></td>
<td>RHW3VA<span class="%g.r19c3%"></span></td>
</tr>
<tr id="rh_padd2">
<td><i class="ico linechart" title="Click to chart this series"></i><i class="ico toggle">Toggle</i>Midwest (PADD 2)</td>
<td>RHW1Midwest</td>
<td>RHW2Midwest<span class="%g.r20c2%"></span></td>
<td>RHW3Midwest<span class="%g.r20c3%"></span></td>
</tr>
<tr class="padd2">
<td>Indiana</td>
<td>RHW1IN</td>
<td>RHW2IN<span class="%g.r21c2%"></span></td>
<td>RHW3IN<span class="%g.r21c3%"></span></td>
</tr>
<tr class="padd2">
<td>Iowa</td>
<td>RHW1IA</td>
<td>RHW2IA<span class="%g.r22c2%"></span></td>
<td>RHW3IA<span class="%g.r22c3%"></span></td>
</tr>
<tr class="padd2">
<td>Kentucky</td>
<td>RHW1KY</td>
<td>RHW2KY<span class="%g.r23c2%"></span></td>
<td>RHW3KY<span class="%g.r23c3%"></span></td>
</tr>
<tr class="padd2">
<td>Michigan</td>
<td>RHW1MI</td>
<td>RHW2MI<span class="%g.r24c2%"></span></td>
<td>RHW3MI<span class="%g.r24c3%"></span></td>
</tr>
<tr class="padd2">
<td>Minnesota</td>
<td>RHW1MN</td>
<td>RHW2MN<span class="%g.r25c2%"></span></td>
<td>RHW3MN<span class="%g.r25c3%"></span></td>
</tr>
<tr class="padd2">
<td>Nebraska</td>
<td>RHW1NE</td>
<td>RHW2NE<span class="%g.r26c2%"></span></td>
<td>RHW3NE<span class="%g.r26c3%"></span></td>
</tr>
<tr class="padd2">
<td>Ohio</td>
<td>RHW1OH</td>
<td>RHW2OH<span class="%g.r27c2%"></span></td>
<td>RHW3OH<span class="%g.r27c3%"></span></td>
</tr>
<tr class="padd2">
<td>Wisconsin</td>
<td>RHW1WI</td>
<td>RHW2WI<span class="%g.r28c2%"></span></td>
<td>RHW3WI<span class="%g.r28c3%"></span></td>
</tr>
</tbody>
<tfoot>
<tr>
<td colspan="4"></td>        </tr>
</tfoot>
</table>
<!--  Wholesale heating oil -->
<div id="wholesale_heating"><img name="wholesale_heating" src="images/howhsus.gif" alt="Wholesale heating oil graphs"></div>
<table class="data-table-two fullwidth" id="wh">
<caption>        <li><a href="/dnav/pet/pet_pri_wfr_a_EPD2F_PWR_dpgal_w.htm">Wholesale Heating Oil <span class="date">(dollars per gallon)</span><span>more price data &rsaquo;</span></a></caption>
<thead class="double-header">
<tr>
<th>&nbsp;</th>
<th>&nbsp;</th>
<th colspan="2">change from</th>
</tr>
<tr>
<th>&nbsp;</th>
<th>WHWDate</th>
<th>week ago</th>
<th>year ago</th>
</tr>
</thead>
<tbody>
<tr class="selected" id="wh_us">
<td><i class="ico linechart" title="Click to chart this series"></i>U.S. Average</td>
<td>WHW1Avg</td>
<td>WHW2Avg<span class="%g.r29c2%"></span></td>
<td>WHW3Avg<span class="%g.r29c3%"></span></td>
</tr>
<tr id="wh_padd1">
<td><i class="ico linechart" title="Click to chart this series"></i>East Coast (PADD 1)</td>
<td>WHW1EastCst</td>
<td>WHW2EastCst<span class="%g.r30c2%"></span></td>
<td>WHW3EastCst<span class="%g.r30c3%"></span></td>
</tr>
<tr class="ne">
<td><i class="ico toggle">Toggle</i>New England (PADD 1A)</td>
<td>WHW1NewEng</td>
<td>WHW2NewEng<span class="%g.r31c2%"></span></td>
<td>WHW3NewEng<span class="%g.r31c3%"></span></td>
</tr>
<tr class="padd1a">
<td>Connecticut</td>
<td>WHW1CT</td>
<td>WHW2CT<span class="%g.r32c2%"></span></td>
<td>WHW3CT<span class="%g.r32c3%"></span></td>
</tr>
<tr class="padd1a">
<td>Maine</td>
<td>WHW1ME</td>
<td>WHW2ME<span class="%g.r33c2%"></span></td>
<td>WHW3ME<span class="%g.r33c3%"></span></td>
</tr>
<tr class="padd1a">
<td>Massachusetts</td>
<td>WHW1MA</td>
<td>WHW2MA<span class="%g.r34c2%"></span></td>
<td>WHW3MA<span class="%g.r34c3%"></span></td>
</tr>
<tr class="padd1a">
<td>New Hampshire</td>
<td>WHW1NH</td>
<td>WHW2NH<span class="%g.r35c2%"></span></td>
<td>WHW3NH<span class="%g.r35c3%"></span></td>
</tr>
<tr class="padd1a">
<td>Rhode Island</td>
<td>WHW1RI</td>
<td>WHW2RI<span class="%g.r36c2%"></span></td>
<td>WHW3RI<span class="%g.r36c3%"></span></td>
</tr>
<tr class="padd1a">
<td>Vermont</td>
<td>WHW1VT</td>
<td>WHW2VT<span class="%g.r37c2%"></span></td>
<td>WHW3VT<span class="%g.r37c3%"></span></td>
</tr>
<tr class="ca">
<td><i class="ico toggle">Toggle</i>Central Atlantic (PADD 1B)</td>
<td>WHW1CentAtl</td>
<td>WHW2CentAtl<span class="%g.r38c2%"></span></td>
<td>WHW3CentAtl<span class="%g.r38c3%"></span></td>
</tr>
<tr class="padd1b">
<td>Delaware</td>
<td>WHW1DE</td>
<td>WHW2DE<span class="%g.r39c2%"></span></td>
<td>WHW3DE<span class="%g.r39c3%"></span></td>
</tr>
<tr class="padd1b">
<td>Maryland</td>
<td>WHW1MD</td>
<td>WHW2MD<span class="%g.r41c2%"></span></td>
<td>WHW3MD<span class="%g.r41c3%"></span></td>
</tr>
<tr class="padd1b">
<td>New Jersey</td>
<td>WHW1NJ</td>
<td>WHW2NJ<span class="%g.r42c2%"></span></td>
<td>WHW3NJ<span class="%g.r42c3%"></span></td>
</tr>
<tr class="padd1b">
<td>New York</td>
<td>WHW1NY</td>
<td>WHW2NY<span class="%g.r43c2%"></span></td>
<td>WHW3NY<span class="%g.r43c3%"></span></td>
</tr>
<tr class="padd1b">
<td>Pennsylvania</td>
<td>WHW1PA</td>
<td>WHW2PA<span class="%g.r44c2%"></span></td>
<td>WHW3PA<span class="%g.r44c3%"></span></td>
</tr>
<tr class="la">
<td><i class="ico toggle">Toggle</i>Lower Atlantic (PADD 1C)</td>
<td>WHW1LowerAtl</td>
<td>WHW2LowerAtl<span class="%g.r45c2%"></span></td>
<td>WHW3LowerAtl<span class="%g.r45c3%"></span></td>
</tr>
<tr class="padd1c">
<td>North Carolina</td>
<td>WHW1NC</td>
<td>WHW2NC<span class="%g.r46c2%"></span></td>
<td>WHW3NC<span class="%g.r46c3%"></span></td>
</tr>
<tr class="padd1c">
<td>Virginia</td>
<td>WHW1VA</td>
<td>WHW2VA<span class="%g.r47c2%"></span></td>
<td>WHW3VA<span class="%g.r47c3%"></span></td>
</tr>
<tr id="wh_padd2">
<td><i class="ico linechart" title="Click to chart this series"></i><i class="ico toggle">Toggle</i>Midwest (PADD 2)</td>
<td>WHW1Midwest</td>
<td>WHW2Midwest<span class="%g.r48c2%"></span></td>
<td>WHW3Midwest<span class="%g.r48c3%"></span></td>
</tr>
<tr class="padd2">
<td>Illinois</td>
<td>WHW1IL</td>
<td>WHW2IL<span class="%g.r49c2%"></span></td>
<td>WHW3IL<span class="%g.r49c3%"></span></td>
</tr>
<tr class="padd2">
<td>Indiana</td>
<td>WHW1IN</td>
<td>WHW2IN<span class="%g.r50c2%"></span></td>
<td>WHW3IN<span class="%g.r50c3%"></span></td>
</tr>
<tr class="padd2">
<td>Iowa</td>
<td>WHW1IA</td>
<td>WHW2IA<span class="%g.r51c2%"></span></td>
<td>WHW3IA<span class="%g.r51c3%"></span></td>
</tr>
<tr class="padd2">
<td>Kansas</td>
<td>WHW1KS</td>
<td>WHW2KS<span class="%g.r52c2%"></span></td>
<td>WHW3KS<span class="%g.r52c3%"></span></td>
</tr>
<tr class="padd2">
<td>Kentucky</td>
<td>WHW1KY</td>
<td>WHW2KY<span class="%g.r53c2%"></span></td>
<td>WHW3KY<span class="%g.r53c3%"></span></td>
</tr>
<tr class="padd2">
<td>Michigan</td>
<td>WHW1MI</td>
<td>WHW2MI<span class="%g.r54c2%"></span></td>
<td>WHW3MI<span class="%g.r54c3%"></span></td>
</tr>
<tr class="padd2">
<td>Minnesota</td>
<td>WHW1MN</td>
<td>WHW2MN<span class="%g.r55c2%"></span></td>
<td>WHW3MN<span class="%g.r55c3%"></span></td>
</tr>
<tr class="padd2">
<td>Missouri</td>
<td>WHW1MO</td>
<td>WHW2MO<span class="%g.r56c2%"></span></td>
<td>WHW3MO<span class="%g.r56c3%"></span></td>
</tr>
<tr class="padd2">
<td>Nebraska</td>
<td>WHW1NE</td>
<td>WHW2NE<span class="%g.r57c2%"></span></td>
<td>WHW3NE<span class="%g.r57c3%"></span></td>
</tr>
<tr class="padd2">
<td>North Dakota</td>
<td>WHW1ND</td>
<td>WHW2ND<span class="%g.r58c2%"></span></td>
<td>WHW3ND<span class="%g.r58c3%"></span></td>
</tr>
<tr class="padd2">
<td>Ohio</td>
<td>WHW1OH</td>
<td>WHW2OH<span class="%g.r59c2%"></span></td>
<td>WHW3OH<span class="%g.r59c3%"></span></td>
</tr>
<tr class="padd2">
<td>South Dakota</td>
<td>WHW1SD</td>
<td>WHW2SD<span class="%g.r60c2%"></span></td>
<td>WHW3SD<span class="%g.r60c3%"></span></td>
</tr>
<tr class="padd2">
<td>Wisconsin</td>
<td>WHW1WI</td>
<td>WHW2WI<span class="%g.r61c2%"></span></td>
<td>WHW3WI<span class="%g.r61c3%"></span></td>
</tr>
</tbody>
<tfoot>
<tr>
<td colspan="4"><strong>Note:</strong> Price in dollars per gallon, excluding taxes. Values shown on the graph and corresponding data pages for the previous week may be revised to account for late submissions and corrections.</td>        </tr>
</tfoot>
</table>
<!--  Distillate supply -->
<div id="distillate_supply"><img name="distillate_supply" src="images/disstkus.gif" alt="Distillate supply graphs"></div>
<table class="data-table-two fullwidth" id="ds">
<caption>
        <li><a href="/dnav/pet/pet_sum_sndw_dcus_nus_w.htm">U.S. Distillate Supply <span>more supply data &rsaquo;</span></a>
</caption>
<thead class="double-header">
<tr>
<th>&nbsp;</th>
<th>&nbsp;</th>
<th colspan="2">change from</th>
</tr>
<tr>
<th>&nbsp;</th>
<th>SupplyDate</th>
<th>week ago</th>
<th>year ago</th>
</tr>
</thead>
<tbody>
<tr class="selected" id="ds_stock">
<td><i class="ico linechart" title="Click to chart this series"></i>Stocks</td>
<td>DS_W1</td>
<td>DS_W2<span class="%g.r127c2%"></span></td>
<td>DS_W3<span class="%g.r127c3%"></span></td>
</tr>
<tr id="ds_prod">
<td><i class="ico linechart" title="Click to chart this series"></i>Production</td>
<td>DP_W1</td>
<td>DP_W2<span class="%g.r128c2%"></span></td>
<td>DP_W3<span class="%g.r128c3%"></span></td>
</tr>
<tr id="ds_demand">
<td><i class="ico linechart" title="Click to chart this series"></i>Demand</td>
<td>DD_W1</td>
<td>DD_W2<span class="%g.r129c2%"></span></td>
<td>DD_W3<span class="%g.r129c3%"></span></td>
</tr>
</tbody>
<tfoot>
<tr>
<td colspan="4"><strong>Note:</strong> Stocks in millions of barrels. Production and Demand in millions of barrels per day.</li>
<li class="sub-header">*Demand</strong> = Product Supplied; approximately represents consumption of petroleum products because it measures the disappearance of these products from primary sources.</td>
</tr>
</tfoot>
</table>
