<!-- diff -->

<div id="residential_heating" class="image-container">
<img name="residential_heating" src="https://www.eia.gov/petroleum/heatingoilpropane/images/prresus.gif" alt="Residential heating oil graphs" class="responsive">
</div>
<table class="data-table-three" id="rh">
<caption>
<a href="/dnav/pet/pet_pri_wfr_a_EPD2F_PRS_dpgal_w.htm">Residential Heating Oil <em>(dollars per gallon)</em>
<div class="right">more price data &rsaquo;</div>
</a>
</caption>
<thead class="double-header">
<tr>
<th>&nbsp;</th>
<th>&nbsp;</th>
<th colspan="2">change from</th>
</tr>
<tr>
<th>&nbsp;</th>
<th>03/27/17</th>
<th>week ago</th>
<th>year ago</th>
</tr>
</thead>
<tbody>
<tr class="selected" id="rh_us">
<td><i class="ico linechart" title="Click to chart this series"></i>U.S. Average</td>
<td>2.586</td>
<td>-0.014<i class="ico value down">down</i></td>
<td>0.455<i class="ico value up">up</i></td>
</tr>
<tr id="rh_padd1">
<td><i class="ico linechart" title="Click to chart this series"></i>East Coast (PADD 1)</td>
<td>2.594</td>
<td>-0.014<i class="ico value down">down</i></td>
<td>0.458<i class="ico value up">up</i></td>
</tr>
<tr class="ne">
<td><i class="ico toggle">Toggle</i>New England (PADD 1A)</td>
<td>2.556</td>
<td>-0.014<i class="ico value down">down</i></td>
<td>0.488<i class="ico value up">up</i></td>
</tr>
<tr class="padd1a">
<td>Connecticut</td>
<td>2.724</td>
<td>-0.036<i class="ico value down">down</i></td>
<td>0.491<i class="ico value up">up</i></td>
</tr>
<tr class="padd1a">
<td>Maine</td>
<td>2.284</td>
<td>-0.023<i class="ico value down">down</i></td>
<td>0.492<i class="ico value up">up</i></td>
</tr>
<tr class="padd1a">
<td>Massachusetts</td>
<td>2.659</td>
<td>0.006<i class="ico value up">up</i></td>
<td>0.504<i class="ico value up">up</i></td>
</tr>
<tr class="padd1a">
<td>New Hampshire</td>
<td>2.451</td>
<td>-0.004<i class="ico value down">down</i></td>
<td>0.458<i class="ico value up">up</i></td>
</tr>
<tr class="padd1a">
<td>Rhode Island</td>
<td>2.679</td>
<td>-0.002<i class="ico value down">down</i></td>
<td>0.510<i class="ico value up">up</i></td>
</tr>
<tr class="padd1a">
<td>Vermont</td>
<td>2.291</td>
<td>-0.037<i class="ico value down">down</i></td>
<td>0.442<i class="ico value up">up</i></td>
</tr>
<tr class="ca">
<td><i class="ico toggle">Toggle</i>Central Atlantic (PADD 1B)</td>
<td>2.633</td>
<td>-0.013<i class="ico value down">down</i></td>
<td>0.427<i class="ico value up">up</i></td>
</tr>
<tr class="padd1b">
<td>Delaware</td>
<td>2.601</td>
<td>-0.023<i class="ico value down">down</i></td>
<td>0.296<i class="ico value up">up</i></td>
</tr>
<tr class="padd1b">
<td>Dist Columbia</td>
<td>3.128</td>
<td>-0.123<i class="ico value down">down</i></td>
<td>0.294<i class="ico value up">up</i></td>
</tr>
<tr class="padd1b">
<td>Maryland</td>
<td>2.643</td>
<td>-0.008<i class="ico value down">down</i></td>
<td>0.394<i class="ico value up">up</i></td>
</tr>
<tr class="padd1b">
<td>New Jersey</td>
<td>2.661</td>
<td>-0.051<i class="ico value down">down</i></td>
<td>0.367<i class="ico value up">up</i></td>
</tr>
<tr class="padd1b">
<td>New York</td>
<td>2.863</td>
<td>0.000<span class="no_change"></span></td>
<td>0.456<i class="ico value up">up</i></td>
</tr>
<tr class="padd1b">
<td>Pennsylvania</td>
<td>2.296</td>
<td>-0.011<i class="ico value down">down</i></td>
<td>0.423<i class="ico value up">up</i></td>
</tr>
<tr class="la">
<td><i class="ico toggle">Toggle</i>Lower Atlantic (PADD 1C)</td>
<td>2.416</td>
<td>-0.001<i class="ico value down">down</i></td>
<td>0.370<i class="ico value up">up</i></td>
</tr>
<tr class="padd1c">
<td>North Carolina</td>
<td>2.368</td>
<td>0.000<span class="no_change"></span></td>
<td>0.329<i class="ico value up">up</i></td>
</tr>
<tr class="padd1c">
<td>Virginia</td>
<td>2.426</td>
<td>-0.001<i class="ico value down">down</i></td>
<td>0.380<i class="ico value up">up</i></td>
</tr>
<tr id="rh_padd2">
<td><i class="ico linechart" title="Click to chart this series"></i><i class="ico toggle">Toggle</i>Midwest (PADD 2)</td>
<td>2.176</td>
<td>-0.014<i class="ico value down">down</i></td>
<td>0.327<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Indiana</td>
<td>2.238</td>
<td>-0.028<i class="ico value down">down</i></td>
<td>0.357<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Iowa</td>
<td>1.931</td>
<td>-0.027<i class="ico value down">down</i></td>
<td>0.276<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Kentucky</td>
<td>2.099</td>
<td>0.002<i class="ico value up">up</i></td>
<td>0.231<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Michigan</td>
<td>2.192</td>
<td>-0.002<i class="ico value down">down</i></td>
<td>0.316<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Minnesota</td>
<td>2.098</td>
<td>-0.019<i class="ico value down">down</i></td>
<td>0.349<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Nebraska</td>
<td>1.935</td>
<td>-0.035<i class="ico value down">down</i></td>
<td>0.266<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Ohio</td>
<td>2.172</td>
<td>-0.007<i class="ico value down">down</i></td>
<td>0.336<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Wisconsin</td>
<td>2.134</td>
<td>-0.024<i class="ico value down">down</i></td>
<td>0.271<i class="ico value up">up</i></td>
</tr>
</tbody>
<tfoot>
<tr>
<td colspan="4"></td>        </tr>
</tfoot>
</table>
<div id="wholesale_heating" class="image-container">
<img name="wholesale_heating" src="https://www.eia.gov/petroleum/heatingoilpropane/images/howhsus.gif" alt="Wholesale heating oil graphs" class="responsive"></div>
<table class="data-table-three" id="wh">
<caption><a href="/dnav/pet/pet_pri_wfr_a_EPD2F_PWR_dpgal_w.htm">Wholesale Heating Oil <em>(dollars per gallon)</em><div class="responsive">more price data &rsaquo;</div></a></caption>
<thead class="double-header">
<tr>
<th>&nbsp;</th>
<th>&nbsp;</th>
<th colspan="2">change from</th>
</tr>
<tr>
<th>&nbsp;</th>
<th>03/27/17</th>
<th>week ago</th>
<th>year ago</th>
</tr>
</thead>
<tbody>
<tr class="selected" id="wh_us">
<td><i class="ico linechart" title="Click to chart this series"></i>U.S. Average</td>
<td>1.595</td>
<td>-0.005<i class="ico value down">down</i></td>
<td>0.332<i class="ico value up">up</i></td>
</tr>
<tr id="wh_padd1">
<td><i class="ico linechart" title="Click to chart this series"></i>East Coast (PADD 1)</td>
<td>1.595</td>
<td>-0.005<i class="ico value down">down</i></td>
<td>0.340<i class="ico value up">up</i></td>
</tr>
<tr class="ne">
<td><i class="ico toggle">Toggle</i>New England (PADD 1A)</td>
<td>1.614</td>
<td>-0.006<i class="ico value down">down</i></td>
<td>0.292<i class="ico value up">up</i></td>
</tr>
<tr class="padd1a">
<td>Connecticut</td>
<td>1.598</td>
<td>-0.002<i class="ico value down">down</i></td>
<td>0.295<i class="ico value up">up</i></td>
</tr>
<tr class="padd1a">
<td>Maine</td>
<td>1.631</td>
<td>-0.008<i class="ico value down">down</i></td>
<td>0.329<i class="ico value up">up</i></td>
</tr>
<tr class="padd1a">
<td>Massachusetts</td>
<td>1.628</td>
<td>-0.001<i class="ico value down">down</i></td>
<td>0.264<i class="ico value up">up</i></td>
</tr>
<tr class="padd1a">
<td>New Hampshire</td>
<td>1.546</td>
<td>-0.014<i class="ico value down">down</i></td>
<td>0.321<i class="ico value up">up</i></td>
</tr>
<tr class="padd1a">
<td>Rhode Island</td>
<td>1.597</td>
<td>-0.005<i class="ico value down">down</i></td>
<td>0.312<i class="ico value up">up</i></td>
</tr>
<tr class="padd1a">
<td>Vermont</td>
<td>1.725</td>
<td>-0.021<i class="ico value down">down</i></td>
<td>0.292<i class="ico value up">up</i></td>
</tr>
<tr class="ca">
<td><i class="ico toggle">Toggle</i>Central Atlantic (PADD 1B)</td>
<td>1.578</td>
<td>-0.004<i class="ico value down">down</i></td>
<td>0.354<i class="ico value up">up</i></td>
</tr>
<tr class="padd1b">
<td>Delaware</td>
<td>1.567</td>
<td>-0.005<i class="ico value down">down</i></td>
<td>0.324<i class="ico value up">up</i></td>
</tr>
<tr class="padd1b">
<td>Maryland</td>
<td>1.534</td>
<td>-0.017<i class="ico value down">down</i></td>
<td>0.399<i class="ico value up">up</i></td>
</tr>
<tr class="padd1b">
<td>New Jersey</td>
<td>1.546</td>
<td>-0.006<i class="ico value down">down</i></td>
<td>0.355<i class="ico value up">up</i></td>
</tr>
<tr class="padd1b">
<td>New York</td>
<td>1.607</td>
<td>-0.002<i class="ico value down">down</i></td>
<td>0.312<i class="ico value up">up</i></td>
</tr>
<tr class="padd1b">
<td>Pennsylvania</td>
<td>1.566</td>
<td>-0.004<i class="ico value down">down</i></td>
<td>0.368<i class="ico value up">up</i></td>
</tr>
<tr class="la">
<td><i class="ico toggle">Toggle</i>Lower Atlantic (PADD 1C)</td>
<td>1.505</td>
<td>-0.012<i class="ico value down">down</i></td>
<td>0.323<i class="ico value up">up</i></td>
</tr>
<tr class="padd1c">
<td>North Carolina</td>
<td>1.498</td>
<td>-0.008<i class="ico value down">down</i></td>
<td>0.311<i class="ico value up">up</i></td>
</tr>
<tr class="padd1c">
<td>Virginia</td>
<td>1.506</td>
<td>-0.013<i class="ico value down">down</i></td>
<td>0.327<i class="ico value up">up</i></td>
</tr>
<tr id="wh_padd2">
<td><i class="ico linechart" title="Click to chart this series"></i><i class="ico toggle">Toggle</i>Midwest (PADD 2)</td>
<td>1.601</td>
<td>-0.015<i class="ico value down">down</i></td>
<td>0.302<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Illinois</td>
<td>1.568</td>
<td>-0.018<i class="ico value down">down</i></td>
<td>0.288<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Indiana</td>
<td>1.598</td>
<td>-0.008<i class="ico value down">down</i></td>
<td>0.298<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Iowa</td>
<td>1.602</td>
<td>0.001<i class="ico value up">up</i></td>
<td>0.340<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Kansas</td>
<td>1.573</td>
<td>-0.002<i class="ico value down">down</i></td>
<td>0.346<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Kentucky</td>
<td>1.633</td>
<td>0.013<i class="ico value up">up</i></td>
<td>0.312<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Michigan</td>
<td>1.585</td>
<td>-0.007<i class="ico value down">down</i></td>
<td>0.286<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Minnesota</td>
<td>1.614</td>
<td>0.009<i class="ico value up">up</i></td>
<td>0.336<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Missouri</td>
<td>1.602</td>
<td>-0.007<i class="ico value down">down</i></td>
<td>0.340<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Nebraska</td>
<td>1.600</td>
<td>-0.001<i class="ico value down">down</i></td>
<td>0.344<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>North Dakota</td>
<td>1.640</td>
<td>0.007<i class="ico value up">up</i></td>
<td>0.493<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Ohio</td>
<td>1.581</td>
<td>-0.027<i class="ico value down">down</i></td>
<td>0.268<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>South Dakota</td>
<td>1.687</td>
<td>-0.001<i class="ico value down">down</i></td>
<td>0.413<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Wisconsin</td>
<td>1.594</td>
<td>-0.012<i class="ico value down">down</i></td>
<td>0.282<i class="ico value up">up</i></td>
</tr>
</tbody>
<tfoot>
<tr>
<td colspan="4"><strong>Note:</strong> Price in dollars per gallon, excluding taxes. Values shown on the graph and corresponding data pages for the previous week may be revised to account for late submissions and corrections.</td>        </tr>
</tfoot>
</table>
<table class="data-table-three" id="ds">
<caption>
<a href="/dnav/pet/pet_sum_sndw_dcus_nus_w.htm">U.S. Distillate Supply <div class="right">more supply data &rsaquo;</right></a>
</caption>
</tbody>
<tfoot>
<tr>
<td colspan="4">
<strong>Note:</strong> Stocks in millions of barrels. Production and Demand in millions of barrels per day.<br />
<strong>*Demand</strong> = Product Supplied; approximately represents consumption of petroleum products because it measures the disappearance of these products from primary sources.</td>
</tr>
</tfoot>
</table>
