<div class="content-container">
    <ul class="resources">
        <li><i class="ico calendar"></i><a href="schedule.cfm">Release schedule</a></li>
        <li><i class="ico email"></i><a href="/tools/emailupdates/">Sign up for email updates</a></li>
        <li><i class="ico rss"></i><a href="/petroleum/heatingoilpropane/includes/hopu_rss.xml">Get the RSS feed</a></li>
        <li><i class="ico radio"></i><a href="/radio/">Radio spots</a></li>
    </ul>
</div>





<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Survey & Report Information</h2></li>
        <li>
            <ul>
                <li><a href="/petroleum/heatingoilpropane/pdf/explanatorynotes.pdf"><i class="ico pdf">pdf</i>Explanatory notes</a></li>
                <li><a href="state-coverage.xls" class="ico_xls_right">State coverage</a></li>
                <li><a href="padd-state_maps.cfm">Survey maps</a></li>
                <li><a href="revision_report.cfm" style="white-space:nowrap;">Revision reports</a></li>
            </ul>
        </li>
        <li class="header"><h2>More Price Data</h2></li>
        <li>
            <ul>
                <li><a href="/dnav/pet/pet_pri_spt_s1_d.htm">Spot prices</a></li>
                <li><a href="/dnav/pet/pet_pri_fut_s1_d.htm">NYMEX futures prices</a></li>
            </ul>
        </li>
    </ul>
</div>





<div class="content-container faq">
    <ul>
        <li class="header"><h2><a href="faq_datausers.cfm">Why are data not collected over the summer?</a></h2></li>
        <li class="sub-header"><a href="faq_datausers.cfm">FAQs for Data User›</a></li>
        <li class="sub-header"><a href="faq_respondents.cfm">FAQs for Respondents</a></li>
        <li class="sub-header"><a href="faq_stateofficials.cfm">FAQs for State Energy Offices</a></li>
    </ul>
</div>





<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related Information</h2></li>
        <li>
            <ul>
                <li><a href="/petroleum/heatingoilpropane/pdf/winterfuels2016.pdf"><i class="ico pdf">pdf</i>Winter Fuels Outlook</a></li>
                <li><a href="/special/heatingfuels/">Winter Heating Fuels</a></li>
                <li><a href="/special/heatingfuels/resources/Propane_Briefing.pdf"><i class="ico pdf">pdf</i>Propane Situation Update</a></li>
                <li><a href="/outlooks/steo/">Short-Term Energy Outlook</a></li>
                <li><a href="/energyexplained/index.cfm?page=heating_oil_home">Heating Oil Explained</a></li>
                <li><a href="/energyexplained/index.cfm?page=hgls_prices#tab2">Propane Explained</a></li>
                <li><a href="/petroleum/weekly/">This Week In Petroleum</a></li>
                <li><a href="/petroleum/supply/weekly/">Weekly Petroleum Status Report</a></li>
                <li><a href="/petroleum/supply/weekly/nehor.cfm">Northeast Heating Oil Reserve</a></li>
            </ul>
        </li>
    </ul>
</div>





<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>For State Energy Officials</h2></li>
        <li><a href="forstateofficials.cfm">Financial Forms</a></li>
        <li><a href="faq_stateofficials.cfm">FAQs for State Energy Offices</a></li>
        <li><a href="/petroleum/heatingoilpropane/workshop/">2016 SHOPP Workshop</a></li>
        <li><a href="/petroleum/heatingoilpropane/workshop/2014/">2014 SHOPP Workshop</a></li>
        <li><a href="/petroleum/heatingoilpropane/webinar/">2014 SHOPP Webinar</a></li>
        <li><a href="/petroleum/heatingoilpropane/webinar/archive/2012">2012 SHOPP Webinar</a></li>
        <li><a href="/petroleum/heatingoilpropane/training/video/datacollection.mp4">SHOPP Data Collection Training</a></li>
    </ul>
</div>
