<div id="residential_propane" class="image-container"><img name="residential_propane" src="https://www.eia.gov/petroleum/heatingoilpropane/images/prresus.gif" alt="Residential propane graphs" class="responsive">
</div>
<table class="data-table-three" id="rp">
<caption>
<a href="/dnav/pet/pet_pri_wfr_a_EPLLPA_PRS_dpgal_w.htm">Residential Propane <em>(dollars per gallon)</em>
<div class="right">more price data &rsaquo;</div>
</a>
</caption>
<thead class="double-header">
<tr>
<th>&nbsp;</th>
<th>&nbsp;</th>
<th colspan="2">change from</th>
</tr>
<tr>
<th>&nbsp;</th>
<th>03/27/17</th>
<th>week ago</th>
<th>year ago</th>
</tr>
</thead>
<tbody>
<tr class="selected" id="rp_us">
<td><i class="ico linechart" title="Click to chart this series"></i>U.S. Average</td>
<td>2.390</td>
<td>-0.015<i class="ico value down">down</i></td>
<td>0.382<i class="ico value up">up</i></td>
</tr>
<tr id="rp_padd1">
<td><i class="ico linechart" title="Click to chart this series"></i>East Coast (PADD 1)</td>
<td>3.177</td>
<td>-0.019<i class="ico value down">down</i></td>
<td>0.429<i class="ico value up">up</i></td>
</tr>
<tr class="ne">
<td><i class="ico toggle">Toggle</i>New England (PADD 1A)</td>
<td>3.209</td>
<td>-0.019<i class="ico value down">down</i></td>
<td>0.407<i class="ico value up">up</i></td>
</tr>
<tr class="padd1a">
<td>Connecticut</td>
<td>2.969</td>
<td>-0.019<i class="ico value down">down</i></td>
<td>0.457<i class="ico value up">up</i></td>
</tr>
<tr class="padd1a">
<td>Maine</td>
<td>2.596</td>
<td>-0.011<i class="ico value down">down</i></td>
<td>0.335<i class="ico value up">up</i></td>
</tr>
<tr class="padd1a">
<td>Massachusetts</td>
<td>3.120</td>
<td>-0.011<i class="ico value down">down</i></td>
<td>0.208<i class="ico value up">up</i></td>
</tr>
<tr class="padd1a">
<td>New Hampshire</td>
<td>3.579</td>
<td>-0.003<i class="ico value down">down</i></td>
<td>0.598<i class="ico value up">up</i></td>
</tr>
<tr class="padd1a">
<td>Rhode Island</td>
<td>3.654</td>
<td>-0.049<i class="ico value down">down</i></td>
<td>0.138<i class="ico value up">up</i></td>
</tr>
<tr class="padd1a">
<td>Vermont</td>
<td>3.673</td>
<td>-0.060<i class="ico value down">down</i></td>
<td>0.522<i class="ico value up">up</i></td>
</tr>
<tr class="ca">
<td><i class="ico toggle">Toggle</i>Central Atlantic (PADD 1B)</td>
<td>3.181</td>
<td>-0.021<i class="ico value down">down</i></td>
<td>0.486<i class="ico value up">up</i></td>
</tr>
<tr class="padd1b">
<td>Delaware</td>
<td>3.080</td>
<td>0.004<i class="ico value up">up</i></td>
<td>0.317<i class="ico value up">up</i></td>
</tr>
<tr class="padd1b">
<td>Maryland</td>
<td>3.145</td>
<td>0.010<i class="ico value up">up</i></td>
<td>0.451<i class="ico value up">up</i></td>
</tr>
<tr class="padd1b">
<td>New Jersey</td>
<td>3.757</td>
<td>-0.012<i class="ico value down">down</i></td>
<td>0.456<i class="ico value up">up</i></td>
</tr>
<tr class="padd1b">
<td>New York</td>
<td>3.174</td>
<td>-0.040<i class="ico value down">down</i></td>
<td>0.657<i class="ico value up">up</i></td>
</tr>
<tr class="padd1b">
<td>Pennsylvania</td>
<td>3.083</td>
<td>-0.017<i class="ico value down">down</i></td>
<td>0.356<i class="ico value up">up</i></td>
</tr>
<tr class="la">
<td><i class="ico toggle">Toggle</i>Lower Atlantic (PADD 1C)</td>
<td>3.152</td>
<td>-0.015<i class="ico value down">down</i></td>
<td>0.374<i class="ico value up">up</i></td>
</tr>
<tr class="padd1c">
<td>Florida</td>
<td>5.089</td>
<td>-0.020<i class="ico value down">down</i></td>
<td>0.373<i class="ico value up">up</i></td>
</tr>
<tr class="padd1c">
<td>Georgia</td>
<td>2.369</td>
<td>-0.004<i class="ico value down">down</i></td>
<td>0.310<i class="ico value up">up</i></td>
</tr>
<tr class="padd1c">
<td>North Carolina</td>
<td>2.707</td>
<td>-0.014<i class="ico value down">down</i></td>
<td>0.377<i class="ico value up">up</i></td>
</tr>
<tr class="padd1c">
<td>Virginia</td>
<td>2.850</td>
<td>-0.025<i class="ico value down">down</i></td>
<td>0.404<i class="ico value up">up</i></td>
</tr>
<tr id="rp_padd2">
<td><i class="ico linechart" title="Click to chart this series"></i><i class="ico toggle">Toggle</i>Midwest (PADD 2)</td>
<td>1.791</td>
<td>-0.014<i class="ico value down">down</i></td>
<td>0.346<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Illinois</td>
<td>1.673</td>
<td>-0.023<i class="ico value down">down</i></td>
<td>0.338<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Indiana</td>
<td>2.147</td>
<td>-0.054<i class="ico value down">down</i></td>
<td>0.426<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Iowa</td>
<td>1.191</td>
<td>-0.014<i class="ico value down">down</i></td>
<td>0.177<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Kansas</td>
<td>1.427</td>
<td>-0.016<i class="ico value down">down</i></td>
<td>0.271<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Kentucky</td>
<td>2.090</td>
<td>-0.013<i class="ico value down">down</i></td>
<td>0.309<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Michigan</td>
<td>2.005</td>
<td>-0.001<i class="ico value down">down</i></td>
<td>0.306<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Minnesota</td>
<td>1.585</td>
<td>0.001<i class="ico value up">up</i></td>
<td>0.344<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Missouri</td>
<td>1.701</td>
<td>-0.021<i class="ico value down">down</i></td>
<td>0.343<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Nebraska</td>
<td>1.218</td>
<td>-0.020<i class="ico value down">down</i></td>
<td>0.216<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>North Dakota</td>
<td>1.316</td>
<td>-0.024<i class="ico value down">down</i></td>
<td>0.319<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Ohio</td>
<td>2.697</td>
<td>-0.013<i class="ico value down">down</i></td>
<td>0.525<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Oklahoma</td>
<td>1.864</td>
<td>-0.007<i class="ico value down">down</i></td>
<td>0.337<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>South Dakota</td>
<td>1.356</td>
<td>-0.012<i class="ico value down">down</i></td>
<td>0.309<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Tennessee</td>
<td>3.700</td>
<td>-0.010<i class="ico value down">down</i></td>
<td>0.620<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Wisconsin</td>
<td>1.561</td>
<td>-0.004<i class="ico value down">down</i></td>
<td>0.413<i class="ico value up">up</i></td>
</tr>
<tr id="rp_padd3">
<td><i class="ico linechart" title="Click to chart this series"></i><i class="ico toggle">Toggle</i>Gulf Coast (PADD 3)</td>
<td>2.401</td>
<td>-0.002<i class="ico value down">down</i></td>
<td>0.180<i class="ico value up">up</i></td>
</tr>
<tr class="padd3">
<td>Alabama</td>
<td>2.642</td>
<td>0.000<span class="no_change"></span></td>
<td>-0.054<i class="ico value down">down</i></td>
</tr>
<tr class="padd3">
<td>Arkansas</td>
<td>2.231</td>
<td>-0.015<i class="ico value down">down</i></td>
<td>0.226<i class="ico value up">up</i></td>
</tr>
<tr class="padd3">
<td>Mississippi</td>
<td>2.270</td>
<td>0.013<i class="ico value up">up</i></td>
<td>0.223<i class="ico value up">up</i></td>
</tr>
<tr class="padd3">
<td>Texas</td>
<td>2.418</td>
<td>-0.008<i class="ico value down">down</i></td>
<td>0.292<i class="ico value up">up</i></td>
</tr>
<tr id="rp_padd4">
<td><i class="ico linechart" title="Click to chart this series"></i><i class="ico toggle">Toggle</i>Rocky Mountain (PADD 4)</td>
<td>2.483</td>
<td>-0.005<i class="ico value down">down</i></td>
<td>0.652<i class="ico value up">up</i></td>
</tr>
<tr class="padd4">
<td>Colorado</td>
<td>2.337</td>
<td>-0.002<i class="ico value down">down</i></td>
<td>0.572<i class="ico value up">up</i></td>
</tr>
<tr class="padd4">
<td>Idaho</td>
<td>2.970</td>
<td>0.004<i class="ico value up">up</i></td>
<td>0.792<i class="ico value up">up</i></td>
</tr>
<tr class="padd4">
<td>Montana</td>
<td>2.253</td>
<td>-0.007<i class="ico value down">down</i></td>
<td>0.669<i class="ico value up">up</i></td>
</tr>
<tr class="padd4">
<td>Utah</td>
<td>2.997</td>
<td>-0.019<i class="ico value down">down</i></td>
<td>0.685<i class="ico value up">up</i></td>
</tr>
</tbody>
<tfoot>
<tr>
<td colspan="4"></td>
</tr>
</tfoot>
</table>
<div id="wholesale_propane" class="image-container">
<img name="wholesale_propane" src="https://www.eia.gov/petroleum/heatingoilpropane/images/prwhsus.gif" alt="Wholesale propane graphs" class="responsive">
</div>
<table class="data-table-three" id="wp">
<caption><a href="/dnav/pet/pet_pri_wfr_a_EPLLPA_PWR_dpgal_w.htm">Wholesale Propane <em>(dollars per gallon)</em><div class="right">more price data &rsaquo;</div></a></caption>
<thead class="double-header">
<tr>
<th>&nbsp;</th>
<th>&nbsp;</th>
<th colspan="2">change from</th>
</tr>
<tr>
<th>&nbsp;</th>
<th>03/27/17</th>
<th>week ago</th>
<th>year ago</th>
</tr>
</thead>
<tbody>
<tr class="selected" id="wp_us">
<td><i class="ico linechart" title="Click to chart this series"></i>U.S. Average</td>
<td>0.672</td>
<td>-0.021<i class="ico value down">down</i></td>
<td>0.159<i class="ico value up">up</i></td>
</tr>
<tr id="wp_padd1">
<td><i class="ico linechart" title="Click to chart this series"></i>East Coast (PADD 1)</td>
<td>0.733</td>
<td>-0.030<i class="ico value down">down</i></td>
<td>0.138<i class="ico value up">up</i></td>
</tr>
<?php ?>
<tr class="ca">
<td><i class="ico toggle">Toggle</i>Central Atlantic (PADD 1B)</td>
<td>0.783</td>
<td>-0.028<i class="ico value down">down</i></td>
<td>0.149<i class="ico value up">up</i></td>
</tr>
<?php ?>
<tr class="padd1b">            <td>Maryland</td>
<td>0.785</td>
<td>-0.070<i class="ico value down">down</i></td>
<td> <span class="no_change"></span></td>
</tr>
<tr class="padd1b">
<td>New Jersey</td>
<td>0.821</td>
<td>-0.025<i class="ico value down">down</i></td>
<td>0.160<i class="ico value up">up</i></td>
</tr>
<tr class="padd1b">
<td>New York</td>
<td>0.796</td>
<td>-0.023<i class="ico value down">down</i></td>
<td>0.162<i class="ico value up">up</i></td>
</tr>
<tr class="padd1b">
<td>Pennsylvania</td>
<td>0.759</td>
<td>-0.022<i class="ico value down">down</i></td>
<td>0.140<i class="ico value up">up</i></td>
</tr>
<tr class="la">
<td><i class="ico toggle">Toggle</i>Lower Atlantic (PADD 1C)</td>
<td>0.663</td>
<td>-0.034<i class="ico value down">down</i></td>
<td>0.125<i class="ico value up">up</i></td>
</tr>
<tr class="padd1c">
<td>Georgia</td>
<td>0.609</td>
<td>-0.025<i class="ico value down">down</i></td>
<td> <span class="no_change"></span></td>
</tr>
<tr class="padd1c">
<td>North Carolina</td>
<td>0.636</td>
<td>-0.023<i class="ico value down">down</i></td>
<td>0.148<i class="ico value up">up</i></td>
</tr>
<tr class="padd1c">
<td>Virginia</td>
<td>0.785</td>
<td>-0.070<i class="ico value down">down</i></td>
<td>0.120<i class="ico value up">up</i></td>
</tr>
<tr id="wp_padd2">
<td><i class="ico linechart" title="Click to chart this series"></i><i class="ico toggle">Toggle</i>Midwest (PADD 2)</td>
<td>0.645</td>
<td>-0.016<i class="ico value down">down</i></td>
<td>0.164<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Illinois</td>
<td>0.630</td>
<td>-0.024<i class="ico value down">down</i></td>
<td>0.174<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Indiana</td>
<td>0.743</td>
<td>-0.023<i class="ico value down">down</i></td>
<td>0.216<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Iowa</td>
<td>0.626</td>
<td>-0.010<i class="ico value down">down</i></td>
<td>0.129<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Kansas</td>
<td>0.595</td>
<td>-0.008<i class="ico value down">down</i></td>
<td>0.138<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">            <td>Kentucky</td>
<td>0.737</td>
<td>-0.018<i class="ico value down">down</i></td>
<td> <span class="no_change"></span></td>
</tr>
<tr class="padd2">            <td>Michigan</td>
<td>0.661</td>
<td>-0.022<i class="ico value down">down</i></td>
<td> <span class="no_change"></span></td>
</tr>
<tr class="padd2">
<td>Minnesota</td>
<td>0.623</td>
<td>-0.016<i class="ico value down">down</i></td>
<td>0.148<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Missouri</td>
<td>0.637</td>
<td>-0.004<i class="ico value down">down</i></td>
<td>0.121<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Nebraska</td>
<td>0.609</td>
<td>-0.007<i class="ico value down">down</i></td>
<td>0.138<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>North Dakota</td>
<td>0.527</td>
<td>-0.023<i class="ico value down">down</i></td>
<td>0.225<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Ohio</td>
<td>0.704</td>
<td>-0.025<i class="ico value down">down</i></td>
<td>0.193<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">            <td>Oklahoma</td>
<td>0.603</td>
<td>-0.014<i class="ico value down">down</i></td>
<td> <span class="no_change"></span></td>
</tr>
<tr class="padd2">
<td>South Dakota</td>
<td>0.625</td>
<td>-0.007<i class="ico value down">down</i></td>
<td>0.136<i class="ico value up">up</i></td>
</tr>
<tr class="padd2">
<td>Wisconsin</td>
<td>0.648</td>
<td>-0.008<i class="ico value down">down</i></td>
<td>0.133<i class="ico value up">up</i></td>
</tr>
<tr id="wp_padd3">
<td><i class="ico linechart" title="Click to chart this series"></i><i class="ico toggle">Toggle</i>Gulf Coast (PADD 3)</td>
<td>0.641</td>
<td>-0.026<i class="ico value down">down</i></td>
<td> <span class="no_change"></span></td>
</tr>
<tr class="padd3">            <td>Alabama</td>
<td>0.597</td>
<td>-0.024<i class="ico value down">down</i></td>
<td> <span class="no_change"></span></td>
</tr>
<tr class="padd3">            <td>Arkansas</td>
<td>0.720</td>
<td>-0.035<i class="ico value down">down</i></td>
<td> <span class="no_change"></span></td>
</tr>
<tr class="padd3">            <td>Mississippi</td>
<td>0.583</td>
<td>-0.021<i class="ico value down">down</i></td>
<td> <span class="no_change"></span></td>
</tr>
<tr class="padd3">            <td>Texas</td>
<td>0.678</td>
<td>-0.026<i class="ico value down">down</i></td>
<td> <span class="no_change"></span></td>
</tr>
<tr id="wp_padd4">
<td><i class="ico linechart" title="Click to chart this series"></i><i class="ico toggle">Toggle</i>Rocky Mountain (PADD 4)</td>
<td>0.670</td>
<td>-0.009<i class="ico value down">down</i></td>
<td> <span class="no_change"></span></td>
</tr>
<tr class="padd4">            <td>Colorado</td>
<td>0.670</td>
<td>-0.009<i class="ico value down">down</i></td>
<td> <span class="no_change"></span></td>
</tr>
</tbody>
<tfoot>
<tr>
<td colspan="4"><strong>Note:</strong> 10 new states were added to the wholesale propane price survey in 2016. This should be taken into consideration when comparing the average prices for last year (2015-2016 season) for the U.S., PADD 1, PADD 1B, PADD 1C, and PADD 2 averages.<br />
Price in dollars per gallon, excluding taxes. Values shown on the graph and corresponding data pages for the previous week may be revised to account for late submissions and corrections.</td>
</tr>
</tfoot>
</table>
<table class="data-table-three" id="ps">
<caption>
<a href="/dnav/pet/pet_sum_sndw_dcus_nus_w.htm">U.S. Propane Supply <class="right">more supply data &rsaquo;</div></a>
</caption>
<tbody>
</tbody>
<tfoot>
<tr>
<td><strong>Note:</strong> Stocks in millions of barrels. Production and Demand in millions of barrels per day.<br />
<strong>*Demand</strong> = Product Supplied; approximately represents consumption of petroleum products because it measures the disappearance of these products from primary sources.</td>
</tr>
</tfoot>
</table>
