<table class="data-table-three" id="rp">
<caption>        <li><a href="/dnav/pet/pet_pri_wfr_a_EPLLPA_PRS_dpgal_w.htm">Residential Propane <span class="date">(dollars per gallon)</span><span>more price data &rsaquo;</span></a></caption>
<thead class="double-header">
<tr>
<th>&nbsp;</th>
<th>&nbsp;</th>
<th colspan="2">change from</th>
</tr>
<tr>
<th>&nbsp;</th>
<th>RPWDate</th>
<th>week ago</th>
<th>year ago</th>
</tr>
</thead>
<tbody>
<tr class="selected" id="rp_us">
<td><i class="ico linechart" title="Click to chart this series"></i>U.S. Average</td>
<td>RPW1Avg</td>
<td>RPW2Avg<span class="%g.r62c2%"></span></td>
<td>RPW3Avg<span class="%g.r62c3%"></span></td>
</tr>
<tr id="rp_padd1">
<td><i class="ico linechart" title="Click to chart this series"></i>East Coast (PADD 1)</td>
<td>RPW1EastCst</td>
<td>RPW2EastCst<span class="%g.r63c2%"></span></td>
<td>RPW3EastCst<span class="%g.r63c3%"></span></td>
</tr>
<tr class="ne">
<td><i class="ico toggle">Toggle</i>New England (PADD 1A)</td>
<td>RPW1NewEng</td>
<td>RPW2NewEng<span class="%g.r64c2%"></span></td>
<td>RPW3NewEng<span class="%g.r64c3%"></span></td>
</tr>
<tr class="padd1a">
<td>Connecticut</td>
<td>RPW1CT</td>
<td>RPW2CT<span class="%g.r65c2%"></span></td>
<td>RPW3CT<span class="%g.r65c3%"></span></td>
</tr>
<tr class="padd1a">
<td>Maine</td>
<td>RPW1ME</td>
<td>RPW2ME<span class="%g.r66c2%"></span></td>
<td>RPW3ME<span class="%g.r66c3%"></span></td>
</tr>
<tr class="padd1a">
<td>Massachusetts</td>
<td>RPW1MA</td>
<td>RPW2MA<span class="%g.r67c2%"></span></td>
<td>RPW3MA<span class="%g.r67c3%"></span></td>
</tr>
<tr class="padd1a">
<td>New Hampshire</td>
<td>RPW1NH</td>
<td>RPW2NH<span class="%g.r68c2%"></span></td>
<td>RPW3NH<span class="%g.r68c3%"></span></td>
</tr>
<tr class="padd1a">
<td>Rhode Island</td>
<td>RPW1RI</td>
<td>RPW2RI<span class="%g.r69c2%"></span></td>
<td>RPW3RI<span class="%g.r69c3%"></span></td>
</tr>
<tr class="padd1a">
<td>Vermont</td>
<td>RPW1VT</td>
<td>RPW2VT<span class="%g.r70c2%"></span></td>
<td>RPW3VT<span class="%g.r70c3%"></span></td>
</tr>
<tr class="ca">
<td><i class="ico toggle">Toggle</i>Central Atlantic (PADD 1B)</td>
<td>RPW1CentAtl</td>
<td>RPW2CentAtl<span class="%g.r71c2%"></span></td>
<td>RPW3CentAtl<span class="%g.r71c3%"></span></td>
</tr>
<tr class="padd1b">
<td>Delaware</td>
<td>RPW1DE</td>
<td>RPW2DE<span class="%g.r72c2%"></span></td>
<td>RPW3DE<span class="%g.r72c3%"></span></td>
</tr>
<tr class="padd1b">
<td>Maryland</td>
<td>RPW1MD</td>
<td>RPW2MD<span class="%g.r74c2%"></span></td>
<td>RPW3MD<span class="%g.r74c3%"></span></td>
</tr>
<tr class="padd1b">
<td>New Jersey</td>
<td>RPW1NJ</td>
<td>RPW2NJ<span class="%g.r75c2%"></span></td>
<td>RPW3NJ<span class="%g.r75c3%"></span></td>
</tr>
<tr class="padd1b">
<td>New York</td>
<td>RPW1NY</td>
<td>RPW2NY<span class="%g.r76c2%"></span></td>
<td>RPW3NY<span class="%g.r76c3%"></span></td>
</tr>
<tr class="padd1b">
<td>Pennsylvania</td>
<td>RPW1PA</td>
<td>RPW2PA<span class="%g.r77c2%"></span></td>
<td>RPW3PA<span class="%g.r77c3%"></span></td>
</tr>
<tr class="la">
<td><i class="ico toggle">Toggle</i>Lower Atlantic (PADD 1C)</td>
<td>RPW1LowerAtl</td>
<td>RPW2LowerAtl<span class="%g.r78c2%"></span></td>
<td>RPW3LowerAtl<span class="%g.r78c3%"></span></td>
</tr>
<tr class="padd1c">
<td>Florida</td>
<td>RPW1FL</td>
<td>RPW2FL<span class="%g.r113c2%"></span></td>
<td>RPW3FL<span class="%g.r113c3%"></span></td>
</tr>
<tr class="padd1c">
<td>Georgia</td>
<td>RPW1GA</td>
<td>RPW2GA<span class="%g.r114c2%"></span></td>
<td>RPW3GA<span class="%g.r114c3%"></span></td>
</tr>
<tr class="padd1c">
<td>North Carolina</td>
<td>RPW1NC</td>
<td>RPW2NC<span class="%g.r79c2%"></span></td>
<td>RPW3NC<span class="%g.r79c3%"></span></td>
</tr>
<tr class="padd1c">
<td>Virginia</td>
<td>RPW1VA</td>
<td>RPW2VA<span class="%g.r80c2%"></span></td>
<td>RPW3VA<span class="%g.r80c3%"></span></td>
</tr>
<tr id="rp_padd2">
<td><i class="ico linechart" title="Click to chart this series"></i><i class="ico toggle">Toggle</i>Midwest (PADD 2)</td>
<td>RPW1Midwest</td>
<td>RPW2Midwest<span class="%g.r81c2%"></span></td>
<td>RPW3Midwest<span class="%g.r81c3%"></span></td>
</tr>
<tr class="padd2">
<td>Illinois</td>
<td>RPW1IL</td>
<td>RPW2IL<span class="%g.r135c2%"></span></td>
<td>RPW3IL<span class="%g.r135c3%"></span></td>
</tr>
<tr class="padd2">
<td>Indiana</td>
<td>RPW1IN</td>
<td>RPW2IN<span class="%g.r82c2%"></span></td>
<td>RPW3IN<span class="%g.r82c3%"></span></td>
</tr>
<tr class="padd2">
<td>Iowa</td>
<td>RPW1IA</td>
<td>RPW2IA<span class="%g.r83c2%"></span></td>
<td>RPW3IA<span class="%g.r83c3%"></span></td>
</tr>
<tr class="padd2">
<td>Kansas</td>
<td>RPW1KS</td>
<td>RPW2KS<span class="%g.r136c2%"></span></td>
<td>RPW3KS<span class="%g.r136c3%"></span></td>
</tr>
<tr class="padd2">
<td>Kentucky</td>
<td>RPW1KY</td>
<td>RPW2KY<span class="%g.r84c2%"></span></td>
<td>RPW3KY<span class="%g.r84c3%"></span></td>
</tr>
<tr class="padd2">
<td>Michigan</td>
<td>RPW1MI</td>
<td>RPW2MI<span class="%g.r85c2%"></span></td>
<td>RPW3MI<span class="%g.r85c3%"></span></td>
</tr>
<tr class="padd2">
<td>Minnesota</td>
<td>RPW1MN</td>
<td>RPW2MN<span class="%g.r86c2%"></span></td>
<td>RPW3MN<span class="%g.r86c3%"></span></td>
</tr>
<tr class="padd2">
<td>Missouri</td>
<td>RPW1MO</td>
<td>RPW2MO<span class="%g.r133c2%"></span></td>
<td>RPW3MO<span class="%g.r133c3%"></span></td>
</tr>
<tr class="padd2">
<td>Nebraska</td>
<td>RPW1NE</td>
<td>RPW2NE<span class="%g.r87c2%"></span></td>
<td>RPW3NE<span class="%g.r87c3%"></span></td>
</tr>
<tr class="padd2">
<td>North Dakota</td>
<td>RPW1ND</td>
<td>RPW2ND<span class="%g.r134c2%"></span></td>
<td>RPW3ND<span class="%g.r134c3%"></span></td>
</tr>
<tr class="padd2">
<td>Ohio</td>
<td>RPW1OH</td>
<td>RPW2OH<span class="%g.r88c2%"></span></td>
<td>RPW3OH<span class="%g.r88c3%"></span></td>
</tr>
<tr class="padd2">
<td>Oklahoma</td>
<td>RPW1OK</td>
<td>RPW2OK<span class="%g.r115c2%"></span></td>
<td>RPW3OK<span class="%g.r115c3%"></span></td>
</tr>
<tr class="padd2">
<td>South Dakota</td>
<td>RPW1SD</td>
<td>RPW2SD<span class="%g.r89c2%"></span></td>
<td>RPW3SD<span class="%g.r89c3%"></span></td>
</tr>
<tr class="padd2">
<td>Tennessee</td>
<td>RPW1TN</td>
<td>RPW2TN<span class="%g.r116c2%"></span></td>
<td>RPW3TN<span class="%g.r116c3%"></span></td>
</tr>
<tr class="padd2">
<td>Wisconsin</td>
<td>RPW1WI</td>
<td>RPW2WI<span class="%g.r90c2%"></span></td>
<td>RPW3WI<span class="%g.r90c3%"></span></td>
</tr>
<tr id="rp_padd3">
<td><i class="ico linechart" title="Click to chart this series"></i><i class="ico toggle">Toggle</i>Gulf Coast (PADD 3)</td>
<td>RPW1GulfCst</td>
<td>RPW2GulfCst<span class="%g.r117c2%"></span></td>
<td>RPW3GulfCst<span class="%g.r117c3%"></span></td>
</tr>
<tr class="padd3">
<td>Alabama</td>
<td>RPW1AL</td>
<td>RPW2AL<span class="%g.r118c2%"></span></td>
<td>RPW3AL<span class="%g.r118c3%"></span></td>
</tr>
<tr class="padd3">
<td>Arkansas</td>
<td>RPW1AR</td>
<td>RPW2AR<span class="%g.r119c2%"></span></td>
<td>RPW3AR<span class="%g.r119c3%"></span></td>
</tr>
<tr class="padd3">
<td>Mississippi</td>
<td>RPW1MS</td>
<td>RPW2MS<span class="%g.r120c2%"></span></td>
<td>RPW3MS<span class="%g.r120c3%"></span></td>
</tr>
<tr class="padd3">
<td>Texas</td>
<td>RPW1TX</td>
<td>RPW2TX<span class="%g.r121c2%"></span></td>
<td>RPW3TX<span class="%g.r121c3%"></span></td>
</tr>
<tr id="rp_padd4">
<td><i class="ico linechart" title="Click to chart this series"></i><i class="ico toggle">Toggle</i>Rocky Mountain (PADD 4)</td>
<td>RPW1RkyMtn</td>
<td>RPW2RkyMtn<span class="%g.r122c2%"></span></td>
<td>RPW3RkyMtn<span class="%g.r122c3%"></span></td>
</tr>
<tr class="padd4">
<td>Colorado</td>
<td>RPW1CO</td>
<td>RPW2CO<span class="%g.r123c2%"></span></td>
<td>RPW3CO<span class="%g.r123c3%"></span></td>
</tr>
<tr class="padd4">
<td>Idaho</td>
<td>RPW1ID</td>
<td>RPW2ID<span class="%g.r124c2%"></span></td>
<td>RPW3ID<span class="%g.r124c3%"></span></td>
</tr>
<tr class="padd4">
<td>Montana</td>
<td>RPW1MT</td>
<td>RPW2MT<span class="%g.r125c2%"></span></td>
<td>RPW3MT<span class="%g.r125c3%"></span></td>
</tr>
<tr class="padd4">
<td>Utah</td>
<td>RPW1UT</td>
<td>RPW2UT<span class="%g.r126c2%"></span></td>
<td>RPW3UT<span class="%g.r126c3%"></span></td>
</tr>
</tbody>
<tfoot>
<tr>
<td colspan="4"></td>
</tr>
</tfoot>
</table>
<!--  Wholesale propane -->
<div id="wholesale_propane"><img name="wholesale_propane" src="images/prwhsus.gif" alt="Wholesale propane graphs"></div>
<table class="data-table-three" id="wp">
<caption>        <li><a href="/dnav/pet/pet_pri_wfr_a_EPLLPA_PWR_dpgal_w.htm">Wholesale Propane <span class="date">(dollars per gallon)</span><span>more price data &rsaquo;</span></a></caption>
<thead class="double-header">
<tr>
<th>&nbsp;</th>
<th>&nbsp;</th>
<th colspan="2">change from</th>
</tr>
<tr>
<th>&nbsp;</th>
<th>WPWDate</th>
<th>week ago</th>
<th>year ago</th>
</tr>
</thead>
<tbody>
<tr class="selected" id="wp_us">
<td><i class="ico linechart" title="Click to chart this series"></i>U.S. Average</td>
<td>WPW1Avg</td>
<td>WPW2Avg<span class="%g.r91c2%"></span></td>
<td>WPW3Avg<span class="%g.r91c3%"></span></td>
</tr>
<tr id="wp_padd1">
<td><i class="ico linechart" title="Click to chart this series"></i>East Coast (PADD 1)</td>
<td>WPW1EastCst</td>
<td>WPW2EastCst<span class="%g.r92c2%"></span></td>
<td>WPW3EastCst<span class="%g.r92c3%"></span></td>
</tr>
<!---        <tr class="neweng">
<td><i class="ico toggle">Toggle</i>New England (PADD 1A)</td>
<td>WPW1NwEng</td>
<td>WPW2NwEng<span class="%g.r137c2%"></span></td>
<td>WPW3NwEng<span class="%g.r137c3%"></span></td>
</tr>
--->
<tr class="ca">
<td><i class="ico toggle">Toggle</i>Central Atlantic (PADD 1B)</td>
<td>WPW1CentAtl</td>
<td>WPW2CentAtl<span class="%g.r93c2%"></span></td>
<td>WPW3CentAtl<span class="%g.r93c3%"></span></td>
</tr>
<!---        <tr class="padd1b">
<td>Delaware</td>
<td>WPW1DE</td>
<td>WPW2DE<span class="%g.r94c2%"></span></td>
<td>WPW3DE<span class="%g.r94c3%"></span></td>
</tr>--->
<tr class="padd1b">            <td>Maryland</td>
<td>WPW1MD</td>
<td>WPW2MD<span class="%g.r145c2%"></span></td>
<td>WPW3MD<span class="%g.r145c3%"></span></td>
</tr>
<tr class="padd1b">
<td>New Jersey</td>
<td>WPW1NJ</td>
<td>WPW2NJ<span class="%g.r95c2%"></span></td>
<td>WPW3NJ<span class="%g.r95c3%"></span></td>
</tr>
<tr class="padd1b">
<td>New York</td>
<td>WPW1NY</td>
<td>WPW2NY<span class="%g.r96c2%"></span></td>
<td>WPW3NY<span class="%g.r96c3%"></span></td>
</tr>
<tr class="padd1b">
<td>Pennsylvania</td>
<td>WPW1PA</td>
<td>WPW2PA<span class="%g.r97c2%"></span></td>
<td>WPW3PA<span class="%g.r97c3%"></span></td>
</tr>
<tr class="la">
<td><i class="ico toggle">Toggle</i>Lower Atlantic (PADD 1C)</td>
<td>WPW1LowerAtl</td>
<td>WPW2LowerAtl<span class="%g.r98c2%"></span></td>
<td>WPW3LowerAtl<span class="%g.r98c3%"></span></td>
</tr>
<tr class="padd1c">
<td>Georgia</td>
<td>WPW1GA</td>
<td>WPW2GA<span class="%g.r143c2%"></span></td>
<td>WPW3GA<span class="%g.r143c3%"></span></td>
</tr>
<tr class="padd1c">
<td>North Carolina</td>
<td>WPW1NC</td>
<td>WPW2NC<span class="%g.r99c2%"></span></td>
<td>WPW3NC<span class="%g.r99c3%"></span></td>
</tr>
<tr class="padd1c">
<td>Virginia</td>
<td>WPW1VA</td>
<td>WPW2VA<span class="%g.r100c2%"></span></td>
<td>WPW3VA<span class="%g.r100c3%"></span></td>
</tr>
<tr id="wp_padd2">
<td><i class="ico linechart" title="Click to chart this series"></i><i class="ico toggle">Toggle</i>Midwest (PADD 2)</td>
<td>WPW1Midwest</td>
<td>WPW2Midwest<span class="%g.r101c2%"></span></td>
<td>WPW3Midwest<span class="%g.r101c3%"></span></td>
</tr>
<tr class="padd2">
<td>Illinois</td>
<td>WPW1IL</td>
<td>WPW2IL<span class="%g.r102c2%"></span></td>
<td>WPW3IL<span class="%g.r102c3%"></span></td>
</tr>
<tr class="padd2">
<td>Indiana</td>
<td>WPW1IN</td>
<td>WPW2IN<span class="%g.r103c2%"></span></td>
<td>WPW3IN<span class="%g.r103c3%"></span></td>
</tr>
<tr class="padd2">
<td>Iowa</td>
<td>WPW1IA</td>
<td>WPW2IA<span class="%g.r104c2%"></span></td>
<td>WPW3IA<span class="%g.r104c3%"></span></td>
</tr>
<tr class="padd2">
<td>Kansas</td>
<td>WPW1KS</td>
<td>WPW2KS<span class="%g.r105c2%"></span></td>
<td>WPW3KS<span class="%g.r105c3%"></span></td>
</tr>
<tr class="padd2">            <td>Kentucky</td>
<td>WPW1KY</td>
<td>WPW2KY<span class="%g.r144c2%"></span></td>
<td>WPW3KY<span class="%g.r144c3%"></span></td>
</tr>
<tr class="padd2">            <td>Michigan</td>
<td>WPW1MI</td>
<td>WPW2MI<span class="%g.r146c2%"></span></td>
<td>WPW3MI<span class="%g.r146c3%"></span></td>
</tr>
<tr class="padd2">
<td>Minnesota</td>
<td>WPW1MN</td>
<td>WPW2MN<span class="%g.r106c2%"></span></td>
<td>WPW3MN<span class="%g.r106c3%"></span></td>
</tr>
<tr class="padd2">
<td>Missouri</td>
<td>WPW1MO</td>
<td>WPW2MO<span class="%g.r107c2%"></span></td>
<td>WPW3MO<span class="%g.r107c3%"></span></td>
</tr>
<tr class="padd2">
<td>Nebraska</td>
<td>WPW1NE</td>
<td>WPW2NE<span class="%g.r108c2%"></span></td>
<td>WPW3NE<span class="%g.r108c3%"></span></td>
</tr>
<tr class="padd2">
<td>North Dakota</td>
<td>WPW1ND</td>
<td>WPW2ND<span class="%g.r109c2%"></span></td>
<td>WPW3ND<span class="%g.r109c3%"></span></td>
</tr>
<tr class="padd2">
<td>Ohio</td>
<td>WPW1OH</td>
<td>WPW2OH<span class="%g.r110c2%"></span></td>
<td>WPW3OH<span class="%g.r110c3%"></span></td>
</tr>
<tr class="padd2">            <td>Oklahoma</td>
<td>WPW1OK</td>
<td>WPW2OK<span class="%g.r148c2%"></span></td>
<td>WPW3OK<span class="%g.r148c3%"></span></td>
</tr>
<tr class="padd2">
<td>South Dakota</td>
<td>WPW1SD</td>
<td>WPW2SD<span class="%g.r111c2%"></span></td>
<td>WPW3SD<span class="%g.r111c3%"></span></td>
</tr>
<tr class="padd2">
<td>Wisconsin</td>
<td>WPW1WI</td>
<td>WPW2WI<span class="%g.r112c2%"></span></td>
<td>WPW3WI<span class="%g.r112c3%"></span></td>
</tr>
<tr id="wp_padd3">
<td><i class="ico linechart" title="Click to chart this series"></i><i class="ico toggle">Toggle</i>Gulf Coast (PADD 3)</td>
<td>WPW1GulfCst</td>
<td>WPW2GulfCst<span class="%g.r138c2%"></span></td>
<td>WPW3GulfCst<span class="%g.r138c3%"></span></td>
</tr>
<tr class="padd3">            <td>Alabama</td>
<td>WPW1AL</td>
<td>WPW2AL<span class="%g.r140c2%"></span></td>
<td>WPW3AL<span class="%g.r140c3%"></span></td>
</tr>
<tr class="padd3">            <td>Arkansas</td>
<td>WPW1AR</td>
<td>WPW2AR<span class="%g.r141c2%"></span></td>
<td>WPW3AR<span class="%g.r141c3%"></span></td>
</tr>
<tr class="padd3">            <td>Mississippi</td>
<td>WPW1MS</td>
<td>WPW2MS<span class="%g.r147c2%"></span></td>
<td>WPW3MS<span class="%g.r147c3%"></span></td>
</tr>
<tr class="padd3">            <td>Texas</td>
<td>WPW1TX</td>
<td>WPW2TX<span class="%g.r149c2%"></span></td>
<td>WPW3TX<span class="%g.r149c3%"></span></td>
</tr>
<tr id="wp_padd4">
<td><i class="ico linechart" title="Click to chart this series"></i><i class="ico toggle">Toggle</i>Rocky Mountain (PADD 4)</td>
<td>WPW1RkyMtn</td>
<td>WPW2RkyMtn<span class="%g.r139c2%"></span></td>
<td>WPW3RkyMtn<span class="%g.r139c3%"></span></td>
</tr>
<tr class="padd4">            <td>Colorado</td>
<td>WPW1CO</td>
<td>WPW2CO<span class="%g.r142c2%"></span></td>
<td>WPW3CO<span class="%g.r142c3%"></span></td>
</tr>
</tbody>
<tfoot>
<tr>
<td colspan="4"><strong>Note:</strong>
10 new states were added to the wholesale propane price survey in 2016. This should be taken into consideration when comparing the average prices for last year (2015-2016 season) for the U.S., PADD 1, PADD 1B, PADD 1C, and PADD 2 averages.</br>
Price in dollars per gallon, excluding taxes. Values shown on the graph and corresponding data pages for the previous week may be revised to account for late submissions and corrections.</td>
</tr>
</tfoot>
</table>
<!--  Propane supply -->
<div id="propane_supply"><img name="propane_supply" src="images/prostkus.gif" alt="Propane supply graphs"></div>
<table class="data-table-three" id="ps">
<caption>
        <li><a href="/dnav/pet/pet_sum_sndw_dcus_nus_w.htm">U.S. Propane Supply <span>more supply data &rsaquo;</span></a>
</caption>
<thead class="double-header">
<tr>
<th>&nbsp;</th>
<th>&nbsp;</th>
<th colspan="2">change from</th>
</tr>
<tr>
<th>&nbsp;</th>
<th>SupplyDate</th>
<th>week ago</th>
<th>year ago</th>
</tr>
</thead>
<tbody>
<tr class="selected" id="ps_stock">
<td><i class="ico linechart" title="Click to chart this series"></i>Stocks</td>
<td>PS_W1</td>
<td>PS_W2<span class="%g.r130c2%"></span></td>
<td>PS_W3<span class="%g.r130c3%"></span></td>
</tr>
<tr id="ps_prod">
<td><i class="ico linechart" title="Click to chart this series"></i>Production</td>
<td>PP_W1</td>
<td>PP_W2<span class="%g.r131c2%"></span></td>
<td>PP_W3<span class="%g.r131c3%"></span></td>
</tr>
<tr id="ps_demand">
<td><i class="ico linechart" title="Click to chart this series"></i>Demand</td>
<td>PD_W1</td>
<td>PD_W2<span class="%g.r132c2%"></span></td>
<td>PD_W3<span class="%g.r132c3%"></span></td>
</tr>
</tbody>
<tfoot>
<tr>
<td colspan="4"><strong>Note:</strong> Stocks in millions of barrels. Production and Demand in millions of barrels per day.</li>
<li class="sub-header">*Demand</strong> = Product Supplied; approximately represents consumption of petroleum products because it measures the disappearance of these products from primary sources.</td>
</tr>
</tfoot>
</table>
