<h4>Resources</h4>
<p><strong>U.S. Energy Information Administration</strong></p>
<ul>
	<li><a href="/beta/realtime_grid">U.S. Electric System Operating Data</a></li>
	<li><a href="/todayinenergy/prices.php">Daily Wholesale Energy Prices</a></li>
	<li><a href="/petroleum/gasdiesel/">Gasoline and Diesel Fuel Update</a></li>
	<li><a href="/petroleum/supply/weekly/">Weekly Petroleum Status Report</a></li>
	<li><a href="/petroleum/weekly/">This Week in Petroleum</a></li>
	<li><a href="/naturalgas/weekly/">Natural Gas Weekly Update</a></li>
	<li><a href="/special/alert/east_coast/">Energy Market Alert</a></li>
	<li><a href="/special/disruptions/socal/winter/">Southern California Daily Energy Report</a></li>
</ul>	
<p><strong>EIA Regional Transportation Fuel Market Primers </strong></p>
<ul>
	<li><a href="/analysis/transportationfuels/padd1n3/">East Coast and Gulf Coast</a></li>
	<li><a href="/analysis/transportationfuels/padd2n4/">Midwest and Rocky Mountain</a></li>
	<li><a href="/analysis/transportationfuels/padd5/">West Coast</a></li>	
	<li><a href="/special/gulf_of_mexico/">Gulf of Mexico Fact Sheet</a></li>
</ul>
<p><strong>U.S. Department of Energy</strong></p>
<ul>
	<li><a href="https://energy.gov/oe/services/energy-assurance/response-and-restoration/emergency-situation-reports">Emergency Situation Reports</a></li>
</ul>

<p><strong>National Oceanic and Atmospheric Administration</strong></p>
<ul>
	<li><a href="http://www.weather.gov/">National Weather Service</a></li>
	<li><a href="http://www.nhc.noaa.gov/">National Hurricane Center</a></li>
</ul>
<p><strong>Bureau of Safety and Environmental Enforcement</strong></p>
<ul>
	<li><a href="https://www.bsee.gov/resources-tools/hurricane">Hurricane Information</a></li>
</ul>
<p><strong>U.S. Nuclear Regulatory Commission</strong></p>
<ul>
	<li><a href="https://www.nrc.gov/reading-rm/doc-collections/event-status/reactor-status/">Power Reactor Status Reports</a></li>

</ul>
