<div class="l-row header report-details">
        <div class="l-full-width-column">
<!--- Page/Section Title --->
<img src="/global/images/logos/eia_logo_only_print.png" class="print">
<h1>Petroleum &amp; Other Liquids</h1>
<!-- <p class="pub-date"> -->
<div class="release-dates">
                        <div class="date-container">
                                <div class="label">Release date:</div>
<div class="date" id="release_date">Jan 1, 2017</div>
</div>
<div class="label">Next release date:</div>
<div class="date" id="next_release_date">Feb 1, 2017</div>
</div>
</div>
</div>
