<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2016-02/fig_HL1coppwp2.png" class="lightbox"><img src="images/2016-02/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude Oil</h2>
            <ul>
                <li>Monthly average crude oil prices decreased in all sales categories in November. The average domestic crude oil first purchase price fell $4.14 (9.8%), to $38.19 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil declined $2.06 (5.5%) to $35.22 per barrel. The average landed cost of foreign crude oil decreased $2.61 (6.4%), to $38.04 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil fell $3.65 (7.8%), to $43.37 per barrel. The average cost of imported crude oil declined $2.97 (7.1%), to $39.06 per barrel. The composite refiner acquisition cost for crude oil decreased $3.31 (7.4%), to $41.47 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>Refiner monthly average prices for sales of motor gasoline continued to decline in November. The average retail price decreased 13.8 cents to $1.711 per gallon, while the average wholesale price fell 13.2 cents to $1.426 per gallon.</li>
                <li>Sales of finished motor gasoline by refiners decreased in November. Total sales fell 2.3 million gallons per day (0.7%) to an average of 323.4 million gallons per day. Retail sales declined 800,000 gallons per day (3.1%), while wholesales dropped 1.5 million gallons per day (0.5%). DTW sales accounted for 7.6% of wholesales, while rack and bulk sales made up 85.0% and 7.4%, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>Monthly average prices for refiner sales of No. 2 distillates fell in November.  The average price for No. 2 diesel fuel sold to end users declined 9.9 cents to $1.603 per gallon, while the average wholesale price decreased 11.6 cents to $1.456 per gallon. The average wholesale price for No. 2 fuel oil declined 5.5 cents to $1.356 per gallon.</li>
                <li>Refiner sales of No. 2 ultra-low sulfur diesel fuel decreased again in November. Retail sales dropped 200,000 gallons per day (1.7%), while wholesales declined 10.1 million gallons per day (6.9%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Refiner monthly average prices for residual fuel oil fell in November. The wholesale price for low-sulfur residual fuel oil decreased 3.6 cents to 77.6 cents per gallon. Prices for high-sulfur residual fuel oil dropped 4.7 cents to 99.4 cents per gallon at retail, while the wholesale price declined 4.9 cents to 79.1 cents per gallon.</li>
                <li>Overall, sales of residual fuel oil by refiners increased in November. While retail sales climbed 700,000 gallons per day (18.9%), wholesales fell 200,000 gallons per day (2.4%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>Refiner monthly average prices for propane and kerosene-type jet fuel fell at both the retail and wholesale levels in November. Prices for kerosene, aviation gasoline, and No. 1 distillate also declined at the wholesale level.</li>
                <li>Refiner sales of the products included in this section varied during November. Sales of propane increased at both the retail and wholesale levels, while kerosene-type jet fuel sales declined at retail, but rose at wholesale. Aviation gasoline and kerosene fell at the wholesale level, while sales of No. 1 distillate increased in the same category.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>*/ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/petroleum/marketing/annual/archive/" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a></li>
    </ul>
</div>