<i class="ico value down">down</i><caption>
Natural Gas <span class="date">(million cubic feet per day)</span>
</caption>
<thead>
<tr>
<th></th>
<th>State/area</th>
<th>Jan-16</th>
<th>Dec-15</th>
<th>Percent change</th>
<th>Jan-15</th>
<th>Percent change</th>
</tr>
</thead>
<tbody>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>U.S.</td>
<td>91,135</td>
<td>91,030</td>
<td>0.1<i class="ico value up">up</i></td>
<td>89,309</td>
<td>2.0<i class="ico value up">up</i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Alaska</td>
<td>9,639</td>
<td>9,808</td>
<td>-1.7<i class="ico value down"></i></td>
<td>9,412</td>
<td>2.4<i class="ico value up">up</i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Arkansas</td>
<td>2,510</td>
<td>2,596</td>
<td>-3.3<i class="ico value down"></i></td>
<td>2,958</td>
<td>-15.2<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>California</td>
<td>610</td>
<td>608</td>
<td>0.3<i class="ico value up">up</i></td>
<td>607</td>
<td>0.4<i class="ico value up">up</i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Colorado</td>
<td>4,621</td>
<td>4,580</td>
<td>0.9<i class="ico value up">up</i></td>
<td>4,526</td>
<td>2.1<i class="ico value up">up</i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Kansas</td>
<td>725</td>
<td>737</td>
<td>-1.6<i class="ico value down"></i></td>
<td>838</td>
<td>-13.5<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Louisiana</td>
<td>5,132</td>
<td>5,231</td>
<td>-1.9<i class="ico value down"></i></td>
<td>5,309</td>
<td>-3.3<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Montana</td>
<td>146</td>
<td>149</td>
<td>-2.0<i class="ico value down"></i></td>
<td>159</td>
<td>-8.3<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>New Mexico</td>
<td>3,217</td>
<td>3,293</td>
<td>-2.3<i class="ico value down"></i></td>
<td>3,333</td>
<td>-3.5<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>North Dakota</td>
<td>1,611</td>
<td>1,651</td>
<td>-2.4<i class="ico value down"></i></td>
<td>1,478</td>
<td>9.0<i class="ico value up">up</i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Ohio</td>
<td>3,615</td>
<td>3,643</td>
<td>-0.7<i class="ico value down"></i></td>
<td>2,066</td>
<td>75.0<i class="ico value up">up</i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Oklahoma</td>
<td>6,813</td>
<td>6,683</td>
<td>1.9<i class="ico value up">up</i></td>
<td>6,672</td>
<td>2.1<i class="ico value up">up</i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Pennsylvania</td>
<td>14,522</td>
<td>13,949</td>
<td>4.1<i class="ico value up">up</i></td>
<td>13,012</td>
<td>11.6<i class="ico value up">up</i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Texas</td>
<td>22,840</td>
<td>23,147</td>
<td>-1.3<i class="ico value down"></i></td>
<td>23,607</td>
<td>-3.3<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Utah</td>
<td>1,102</td>
<td>1,101</td>
<td>0.1<i class="ico value up">up</i></td>
<td>1,214</td>
<td>-9.2<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>West Virginia</td>
<td>3,685</td>
<td>3,400</td>
<td>8.4<i class="ico value up">up</i></td>
<td>3,559</td>
<td>3.5<i class="ico value up">up</i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Wyoming</td>
<td>5,200</td>
<td>5,260</td>
<td>-1.1<i class="ico value down"></i></td>
<td>5,368</td>
<td>-3.1<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Federal Offshore Gulf of Mexico</td>
<td>3,555</td>
<td>3,603</td>
<td>-1.3<i class="ico value down"></i></td>
<td>3,566</td>
<td>-0.3<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Other states</td>
<td>1,594</td>
<td>1,591</td>
<td>0.2<i class="ico value up">up</i></td>
<td>1,625</td>
<td>-1.9<i class="ico value down"></i></td>
</tr>
</tbody>
<tfoot>
<td colspan="10">        <li>Notes:  Natural gas production represents monthly natural gas gross withdrawals  estimated from data collected on the EIA-914 survey. Starting in 2015, 10  states (Arkansas, California, Colorado, Kansas, Montana, North Dakota, Ohio,  Pennsylvania, Utah, and West Virginia) were added to the EIA-914 data  collection and are reported individually. The remaining states/areas (Alabama,  Arizona, Federal Offshore Pacific, Florida, Illinois, Indiana, Kentucky,  Maryland, Michigan, Mississippi, Missouri, Nebraska, Nevada, New York, Oregon,  South Dakota, Tennessee, and Virginia) are grouped in the &quot;other  states&quot; category. Data for 2015 and 2016 are estimated. The sum of  individual states may not equal total U.S. volumes due to independent rounding.  Previous months' production volumes may have been revised for all states/areas.</li>
NA=Not Available.</li>
Sources: Form EIA-914,  Monthly Crude Oil, Lease Condensate, and Natural Gas Production Report and its  predecessor, Monthly Natural Gas Production Report; BSEE reports; PointLogic Energy;  Ventyx; BENTEK Energy; industry reports; and EIA computations.</li></td>    </tfoot>
</table>
