<i class="ico value down">down</i><caption>
Crude Oil <span class="date">(thousand barrels per day)</span>
</caption>
<thead>
<tr>
<th></th>
<th>State/area</th>
<th>Jan-16</th>
<th>Dec-15</th>
<th>Percent change</th>
<th>Jan-15</th>
<th>Percent change</th>
</tr>
</thead>
<tbody>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>U.S.</td>
<td>9,179</td>
<td>9,235</td>
<td>-0.6<i class="ico value down"></i></td>
<td>9,341</td>
<td>-1.7<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Alabama</td>
<td>22</td>
<td>23</td>
<td>-3.0<span class="no_change"></span></td>
<td>27</td>
<td>-18.8<i class="ico value up">up</i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Alaska</td>
<td>516</td>
<td>522</td>
<td>-1.3<i class="ico value down"></i></td>
<td>500</td>
<td>3.1<i class="ico value up">up</i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Arizona</td>
<td>0</td>
<td>0</td>
<td>-35.0<i class="ico value down"></i></td>
<td>0</td>
<td>-81.2<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Arkansas</td>
<td>15</td>
<td>16</td>
<td>-5.3<i class="ico value down"></i></td>
<td>21</td>
<td>-26.6<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>California</td>
<td>537</td>
<td>543</td>
<td>-1.2<i class="ico value down"></i>
<td>565</td>
<td>-5.0<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Colorado</td>
<td>323</td>
<td>324</td>
<td>-0.2<i class="ico value down"></i></td>
<td>310</td>
<td>4.3<i class="ico value up">up</i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Federal Offshore Gulf of Mexico</td>
<td>1,611</td>
<td>1,629</td>
<td>-1.1<i class="ico value down"></i></td>
<td>1,497</td>
<td>7.6<i class="ico value up">up</i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Federal Offshore Pacific</td>
<td>17</td>
<td>21</td>
<td>-21.7<i class="ico value down"></i></td>
<td>53</td>
<td>-68.2<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Florida</td>
<td>6</td>
<td>6</td>
<td>-5.1<i class="ico value down"></i></td>
<td>6</td>
<td>-8.2<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Illinois</td>
<td>22</td>
<td>27</td>
<td>-16.3<i class="ico value down"></i></td>
<td>26</td>
<td>-12.8<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Indiana</td>
<td>5</td>
<td>6</td>
<td>-19.4<i class="ico value down"></i></td>
<td>7</td>
<td>-32.8<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Kansas</td>
<td>107</td>
<td>107</td>
<td>0.4<i class="ico value up">up</i></td>
<td>137</td>
<td>-21.8<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Kentucky</td>
<td>7</td>
<td>12</td>
<td>-34.9<i class="ico value down"></i></td>
<td>9</td>
<td>-16.7<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Louisiana</td>
<td>156</td>
<td>163</td>
<td>-4.1<i class="ico value down"></i></td>
<td>186</td>
<td>-15.8<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Michigan</td>
<td>15</td>
<td>16</td>
<td>-5.2<i class="ico value down"></i></td>
<td>18</td>
<td>-16.7<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Mississippi</td>
<td>60</td>
<td>62</td>
<td>-2.8<i class="ico value down"></i></td>
<td>71</td>
<td>-14.6<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Missouri</td>
<td>0</td>
<td>0</td>
<td>-12.8<i class="ico value down"></i></td>
<td>0</td>
<td>-29.8<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Montana</td>
<td>69</td>
<td>72</td>
<td>-3.6<i class="ico value down"></i></td>
<td>84</td>
<td>-17.5<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Nebraska</td>
<td>7</td>
<td>7</td>
<td>-9.1<i class="ico value down"></i></td>
<td>8</td>
<td>-19.7<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Nevada</td>
<td>1</td>
<td>1</td>
<td>-19.5<i class="ico value down"></i></td>
<td>1</td>
<td>-16.0<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>New Mexico</td>
<td>382</td>
<td>361</td>
<td>6.0<i class="ico value up">up</i></td>
<td>370</td>
<td>3.3<i class="ico value up">up</i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>New York</td>
<td>1</td>
<td>1</td>
<td>0.0<span class="no_change"></span></td>
<td>1</td>
<td>0.0<span class="no_change"></span></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>North Dakota</td>
<td>1,108</td>
<td>1,140</td>
<td>-2.8<i class="ico value down"></i></td>
<td>1,167</td>
<td>-5.1<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Ohio</td>
<td>73</td>
<td>78</td>
<td>-7.6<i class="ico value down"></i></td>
<td>51</td>
<td>41.5<i class="ico value up">up</i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Oklahoma</td>
<td>405</td>
<td>396</td>
<td>2.2<i class="ico value up">up</i></td>
<td>448</td>
<td>-9.7<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Pennsylvania</td>
<td>17</td>
<td>18</td>
<td>-5.6<i class="ico value down"></i></td>
<td>19</td>
<td>-12.3<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>South Dakota</td>
<td>4</td>
<td>4</td>
<td>4.1<i class="ico value up">up</i></td>
<td>5</td>
<td>-13.7<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Tennessee</td>
<td>1</td>
<td>1</td>
<td>-4.7<i class="ico value down"></i></td>
<td>1</td>
<td>-36.5<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Texas</td>
<td>3,365</td>
<td>3,340</td>
<td>0.7<i class="ico value up">up</i></td>
<td>3,373</td>
<td>-0.2<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Utah</td>
<td>88</td>
<td>90</td>
<td>-3.2<i class="ico value down"></i></td>
<td>111</td>
<td>-21.0<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Virginia</td>
<td>0</td>
<td>0</td>
<td>0.0<span class="no_change"></span></td>
<td>0</td>
<td>53.8<i class="ico value up">up</i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>West Virginia</td>
<td>22</td>
<td>21</td>
<td>4.9<i class="ico value up">up</i></td>
<td>25</td>
<td>-15.2<i class="ico value down"></i></td>
</tr>
<tr class="addToVis">
<td class="icon"><i class="ico linechart" title="Click to chart this series"></i></td>
<td>Wyoming</td>
<td>217</td>
<td>228</td>
<td>-4.5<i class="ico value down"></i></td>
<td>241</td>
<td>-9.7<i class="ico value down"></i></td>
</tr>
</tbody>
<tfoot>
<td colspan="10">        <li>Notes: Crude oil includes lease condensate. The sum of  individual states may not equal total U.S. volumes due to independent rounding.  A zero may indicate volume of less than 0.5 thousand barrels per day. Previous  months' production volumes may have been revised for all states/areas.<br/>
Sources: Data for Arkansas, California, Colorado, Federal  Offshore Gulf of Mexico, Kansas, Louisiana, Montana, New Mexico, North Dakota,  Ohio, Oklahoma, Texas, Utah, West Virginia, and Wyoming are from the EIA-914  survey. Data for states/areas not individually surveyed on the EIA-914  (Alabama, Arizona, Federal Offshore Pacific, Florida, Illinois, Indiana,  Kentucky, Michigan, Mississippi, Missouri, Nebraska, Nevada, New York, South  Dakota, Tennessee, and Virginia) are from EIA estimates published in the  Petroleum Supply Annual and Petroleum Supply Monthly reports, based on crude  oil production data from state government agencies and the U.S. Department of  the Interior, Bureau of Safety and Environmental Enforcement (and predecessor  agencies), and first purchase data reported on Form EIA-182, <span class="date">Domestic Crude  Oil First Purchase Report</span>.</li>
</td>    </tfoot>
</table>
