<div class="l-row"><div class="l-two-third-column report-details">
        
                <a href="/petroleum/reports.cfm">&lsaquo; See all Petroleum &amp; Other Liquids Reports</a>
                <h2>Monthly Crude Oil and Natural Gas Production</h2>

                <div class="release-dates">
                        <div class="date-container">
                                <div class="label">Release date:</div>
                                <div class="date">August 31, 2017|Next release date:</div>
                                <div class="date">Date: September 29, 2017</a>
                        </div>
                </div>
        </div>
</div>
