<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>

<link media="screen, projection" type="text/css" href="/global/styles/screen.css" rel="stylesheet">
<link media="print" type="text/css" href="/global/styles/print.css" rel="stylesheet">
<link rel="stylesheet" href="/global/scripts/JQuery/datepicker/jquery-ui-dp.custom.css" type="text/css">
<link media="screen, projection" type="text/css" href="/global/styles/EIA_global.css" rel="stylesheet">
<link href="http://www.eia.gov/favicon.ico" rel="shortcut icon">
<link type="image/x-icon" href="http://www.eia.gov/favicon.ico" rel="icon">
<link href="http://www.eia.gov/favicon.ico" type="image/vnd.microsoft.icon" rel="shortcut icon">

<style>
	html,body {
		margin-bottom:0px;
		padding:0px;
		overflow-y:auto;
		background-color:#ffffff;
	}	
	.pagecontent, .map_container, .map_div {
		margin:0px;
	}
</style>

</head>
<body>
<div style="padding:16px;">
 <h3>Hurricane Irene as of August 29, 2011 (8:00 a.m. EDT)</h3>
   <p>The <a href="http://www.nhc.noaa.gov/index.shtml">National Hurricane Center</a> is posting routine updates on the status of <a href="http://www.nhc.noaa.gov/#IRENE">Hurricane Irene</a>.</p>
   <p>Also, the Department of Energy's <a href="http://energy.gov/oe/office-electricity-delivery-and-energy-reliability">Office of Electricity Delivery and Energy Reliability</a> is posting daily updates on the disposition of United States energy infrastructure in the <a href="http://www.oe.netl.doe.gov/ead.aspx">Energy Assurance Daily</a> report and posts information on <a href="http://www.oe.netl.doe.gov/emergency_sit_rpt.aspx">hurricane-related situation reports</a>.</p>
</div>
<?php include ('east_coast_map.php') ; ?>

</body>
</html>
