<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2016-07/fig_HL1coppwp2.png" class="lightbox"><img src="images/2016-07/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude Oil</h2>
            <ul>
                <li>Monthly average crude oil prices for April rose in all categories of sale. The average domestic crude oil first purchase price increased $3.72 (11.7%), to $35.59 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil rose $3.48 (11.7%) to $33.14 per barrel. The average landed cost of foreign crude oil increased $3.44 (10.9%), to $34.94 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil climbed $4.03 (11.4%), to $39.34 per barrel. The average cost of imported crude oil rose $3.69 (11.5%), to $35.90 per barrel. The composite refiner acquisition cost for crude oil increased $3.91 (11.6%), to $37.73 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>Monthly average prices for sales of motor gasoline by refiners increased again in all sales categories during April. The average retail price climbed 17.3 cents to $1.725 per gallon, while the average wholesale price rose 14.1 cents to $1.476 per gallon.</li>
                <li>Refiner sales of finished motor gasoline fell in April. Total sales dropped 600,000 gallons per day (0.2%) to an average of 328.4 million gallons per day. Retail sales rose 700,000 gallons per day (2.8%), while wholesales declined 1.3 million gallons per day (0.4%). DTW sales accounted for 7.8% of wholesales, while rack and bulk sales made up 85.9% and 6.3%, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>April monthly average prices for refiner sales of No. 2 distillates increased from March levels. The average price for No. 2 diesel fuel sold to end users rose 6.8 cents to $1.385 per gallon, while the average wholesale price increased 6.2 cents to $1.251 per gallon. The average retail price for No. 2 fuel oil climbed 6.9 cents to $1.624 per gallon, while the average wholesale price rose 4.2 cents to $1.112 per gallon.</li>
                <li>Refiner sales of No. 2 ultra-low sulfur diesel fuel were mixed again during April. Retail sales declined 100,000 gallons per day (0.8%), while wholesales increased 600,000 gallons per day (0.4%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Monthly average prices for residual fuel oil sales by refiners rose during April. The wholesale price for low-sulfur residual fuel oil increased 5.1 cents to 63.3 cents per gallon. Prices for high-sulfur residual fuel oil rose 2.9 cents to 70.1 cents per gallon at retail, while the wholesale price increased 5.9 cents to 61.4 cents per gallon.</li>
                <li>Sales of residual fuel oil by refiners fell in April. Retail sales dropped 100,000 gallons per day (2.4%), while wholesales declined 200,000 gallons per day (2.2%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>Prices for refiner sales of the remaining surveyed products show mixed trends during April. Retail and wholesale prices for propane declined, while prices for kerosene-type jet fuel rose at both levels. Prices for aviation gasoline, No. 1 distillate and No. 4 distillate increased at the wholesale level, while the price for kerosene fell in the same category.</li>
                <li>Refiner sales of these products varied in April. Propane, kerosene-type jet fuel, and No. 1 distillate sales fell at both the retail and wholesale levels. Sales of aviation gasoline and kerosene increased at wholesale, while No. 4 distillate sales fell at the wholesale level.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div> */ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/petroleum/marketing/annual/archive/" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a></li>
    </ul>
</div>