<h1>Recent Data</h1>
<table class="data" >
<caption>Wholesale spot petroleum prices, 3/27/2017 close</caption>
<thead>
<tr>
<th>Product</th>
<th>Area</th>
<th>Price</th>
<th>% change*</th>
</tr>
</thead>
<tbody>
<tr>
<td>Crude Oil <em>($/barrel)</em></td>
<td>WTI</td>
<td>47.02</td>
<td>-0.6</td>
</tr>
<tr>
<td class="indented"></td>
<td>Brent</td>
<td>50.12</td>
<td>0.3</td>
</tr>
<tr>
<td class="indented"></td>
<td>Louisiana Light</td>
<td>48.87</td>
<td>-0.6</td>
</tr>
<tr>
<td>Gasoline (RBOB) <em>($/gallon)</em></td>
<td>NY Harbor</td>
<td>1.46</td>
<td>0.5</td>
</tr>
<tr>
<td class="indented"></td>
<td>Gulf Coast</td>
<td>1.59</td>
<td>0.4</td>
</tr>
<tr>
<td class="indented"></td>
<td>Los Angeles</td>
<td>1.71</td>
<td>0.2</td>
</tr>
<tr>
<td>Heating Oil <em>($/gallon)</em></td>
<td>NY Harbor</td>
<td>1.46</td>
<td>-0.3</td>
</tr>
<tr>
<td class="indented"></td>
<td>Gulf Coast</td>
<td>1.33</td>
<td>-0.3</td>
</tr>
<td>        <li><a href="/todayinenergy/includes/CrackSpread_Explain.cfm">3:2:1 Crack Spread <em>($/barrel)</em></a></td>
<td>Gulf Coast (LLS)</td>
<td>16.18</td>
<td>2.6</td>
</tr>
<tr>
<td class="no-wrap">Low-Sulfur Diesel <em>($/gallon)</em></td>
<td>NY Harbor</td>
<td>1.50</td>
<td>-0.3</td>
</tr>
<tr>
<td class="indented"></td>
<td>Gulf Coast</td>
<td>1.47</td>
<td>-0.3</td>
</tr>
<tr>
<td class="indented"></td>
<td>Los Angeles</td>
<td>1.56</td>
<td>-0.3</td>
</tr>
<tr>
<td>Propane <em>($/gallon)</em></td>
<td class="no-wrap">Mont Belvieu, TX</td>
<td>0.56</td>
<td>-2.7</td>
</tr>
</tbody>
<tfoot>
<tr>
<td colspan="99">Source: <a href="/todayinenergy/prices.cfm">Daily Prices</a></td>
</tr>
</tfoot>
</table>
    <ul>
<li class="footer"><a href="/petroleum/data.cfm">See more data &rsaquo;</a></li>
    </ul>
