<div class="l-row"><div class="l-full-width-column">
<h1>Energy Education</h1>
<div class="l-row content-container energy-education">
<div class="l-one-third-column">
<i class="ico energy-education petroleum"></i>
    <ul>
        <li class="header"><h2><a href="/energyexplained/index.cfm?page=oil_home">Oil: Crude &amp; Petroleum Products Explained</a></h2></li>
<li class="sub-header"><a href="/energyexplained/index.cfm?page=gasoline_prices">Gasoline Prices and Outlook</a></li>
<li class="footer"><a href="/energyexplained/index.cfm?page=oil_home">See more petroleum topics</a></li>
    </ul>
</div>
<div class="l-one-third-column">
<div class="border">
<i class="ico energy-education faq"></i>
    <ul>
        <li class="header"><h2><a href="/tools/faqs/">FAQs</a></h2></li>
<li class="sub-header"><a href="/tools/faqs/faq.cfm?id=45&t=8">What are Mcf, Btu, and therms? How do I convert prices in Mcf to Btu's and therms?</a></li>
<li class="footer"><a href="/tools/faqs/">See all petroleum FAQs</a></li>
    </ul>
</div>
</div>
<div class="l-one-third-column">
<img src="/global/includes/issuestrends/images/icon_kids.png"/>
    <ul>
        <li class="header"><h2><a href="/kids">Energy Kids</a></h2></li>
<li class="sub-header"><a href="/kids/energy.cfm?page=oil_home-basics">How was oil formed?</a></li>
<li class="footer"><a href="/kids/energy.cfm?page=nonrenewable_home-basics"><span class="line-break">See nonrenewable sources</span> <span class="line-break">on Energy Kids</span></a></li>
    </ul>
</div>
</div>
</div>
