<span class="brt_blue_side">
<h4 class="eib_side">What is the electric power grid and what are some challenges it faces?</h2></li>
                <li><a href="#">Read the Energy in Brief Article &rsaquo;</a>    </ul>
</div>
<div class="content-container green-top-border-container grey-background">
    <ul>
        <li class="header"><h2>2007 State Electricity Profiles</h2></li>
<li class="sub-header">US Average Retail Price per</li>Kilowatthour is 9.13 Cents.</li>
    </ul>
</div><img src="/global/images/slush/state_map.png" />
<h4 class="legend_title"><li class="sub-header">Average Retail Price </li><em>(Cents per Kilowatthour)</span></h2></li>
<ul class="legend">
<li class="leg01">5.07 &ndash; 6.83</li>
<li class="leg04">8.54 &ndash; 12.88</li>
<li class="leg03">6.84 &ndash; 7.44</li>
<li class="leg05">13.01 &ndash; 21.29</li>
<li class="leg03">7.57 &ndash; 8.53</li>
    </ul>
</div>
<span class="promo_side blue_top">
<h4 class="updates_side">Updates have been made to Electricity Survey Forms <li class="sub-header">EIA-923</strong> and <li class="sub-header">EIA-860</strong></h2></li>
                <li><a href="#">Learn more about the updates &rsaquo;</a>    </ul>
</div>