<div class="content-container dark-top-border-container">
    <ul>
        <li class="header"><h2>Regular Weekly Releases*</h2></li>
<li class="sub-header">Monday</li>
                <li><a href="/oog/info/wohdp/diesel.asp">Weekly On-Highway Diesel Prices &rsaquo;</a></li>
<li class="date">4:00 - 5:00 p.m. EST</li>
                <li><a href="/oil_gas/petroleum/data_publications/wrgp/mogas_home_page.html">Weekly U.S. Retail Gasoline Prices &rsaquo;</a></li>
<li class="date">4:30 - 5:00 p.m. EST</li>
                <li><a href="/oog/info/gdu/gasdiesel.asp">Gasoline and Diesel Fuel Update &rsaquo;</a></li>
<li class="date">Normally updated Monday by 5pm</li>
<li class="sub-header">Tuesday</li>
<li class="date">No weekly releases</li>
<li class="sub-header">Wednesday</li>
                <li><a href="/oil_gas/petroleum/data_publications/weekly_petroleum_status_report/wpsr.html">Weekly Petroleum Status Report &rsaquo;</a></li>
<li class="date">After 10:30 a.m. EST</li>
                <li><a href="/oog/info/twip/twip.asp">This Week in Petroleum &rsaquo;</a></li>
<li class="date">1:00 p.m. EST</li>
                <li><a href="/oog/info/hopu/hopu.asp">Heating Oil and Propane Update &rsaquo;</a></li>
<li class="date">1:00 p.m. EST (Oct - March)</li>
<li class="sub-header">Thursday</li>
<li class="date">No weekly releases</li>
<li class="sub-header">Friday</li>
<li class="date">No weekly releases</li>
<li class="date">*Releases change on weeks with Federal holidays</li>
    </ul>
</div>