<div class="content-container light-top-border-container grey-background">    <ul>
        <li class="header"><h2>Most Requested Petroleum Data</h2></li>
<li class="sub-header">Summary
    <ul>
        <li><a href="/dnav/pet/pet_sum_sndw_dcus_nus_w.htm">Weekly Supply Estimates</a></li>
                <li><a href="/dnav/pet/pet_sum_crdsnd_k_m.htm"> U.S. Crude Oil Supply &amp; Disposition</a></li>
    </ul></li>
    </ul>
    <ul>
<li class="sub-header">Prices
    <ul>
        <li><a href="/dnav/pet/pet_pri_gnd_dcus_nus_w.htm">Weekly Retail Gasoline and Diesel Prices</a></li>
                <li><a href="/petroleum/gasdiesel/">Gasoline and Diesel Fuel Update</a></li>
                <li><a href="/dnav/pet/pet_pri_spt_s1_d.htm"> Spot Prices</a></li>
    </ul></li>
    </ul>
    <ul>
<li class="sub-header">Crude Reserves &amp; Production
    <ul>
        <li><a href="/dnav/pet/pet_crd_crpdn_adc_mbbl_m.htm"> Crude Oil Production</a></li>
                <li><a href="/dnav/pet/pet_crd_pres_dcu_NUS_a.htm">Reserves, Reserves Changes, and Production</a></li>
    </ul></li>
    </ul>
    <ul>
<li class="sub-header">Refining &amp; Processing
    <ul>
        <li><a href="/dnav/pet/pet_pnp_wiup_dcu_nus_w.htm">Weekly Inputs, Utilization &amp; Production</a></li>
                <li><a href="/dnav/pet/pet_pnp_pct_dc_nus_pct_m.htm">Refinery Yield</a></li>
    </ul></li>
    </ul>
    <ul>
<li class="sub-header">Imports/Exports &amp; Pipelines
    <ul>
        <li><a href="/dnav/pet/pet_move_wkly_dc_NUS-Z00_mbblpd_w.htm">Weekly Imports & Exports</a></li>
                <li><a href="/dnav/pet/pet_move_impcus_a2_nus_ep00_im0_mbbl_m.htm">U.S. Imports by Country of Origin</a></li>
                <li><a href="/petroleum/imports/browser/#/?vs=PET_IMPORTS.WORLD-US-ALL.A">Crude Import Tracking Tool</a></li>
    </ul></li>
    </ul>
    <ul>
<li class="sub-header">Stocks
    <ul>
        <li><a href="/dnav/pet/pet_stoc_wstk_dcu_nus_w.htm">Total Stocks (Weekly &amp; Monthly)</a></li>
                <li><a href="/dnav/pet/pet_stoc_typ_d_nus_SAE_mbbl_m.htm">Stocks by Type</a></li>
    </ul></li>
    </ul>
    <ul>
<li class="sub-header">Consumption/Sales
    <ul>
        <li><a href="/dnav/pet/pet_cons_psup_dc_nus_mbbl_m.htm">Product Supplied</a></li>
                <li><a href="/dnav/pet/pet_cons_prim_dcu_nus_m.htm">Prime Supplier Sales Volumes </a></li>
    </ul></li>
    </ul>
    <ul>
        <li class="header"><h2><h2>International Data</h2></li>
<li class="sub-header">Overview
    <ul>
        <li><a href="/cfapps/ipdbproject/IEDIndex3.cfm">International Energy Statistics</a></li>
    </ul></li>
    </ul>
