<div class="content-container standard-container">    <ul>
        <li class="header"><h2>Survey Forms, Changes & Announcements</h2></li>
                <li><a href="/survey/#petroleum">Petroleum surveys &rsaquo;</a></li>
                <li><a href="/survey/notice/marketing2017.cfm">Petroleum Marketing Survey Form Changes Proposed for 2017 &rsaquo;</a></li>
                <li><a href="/survey/notice/petngproduction2017.cfm">Proposed Changes to the EIA-914 Monthly Crude Oil, Lease Condensate, and Natural Gas Production Form</a></li>
    </ul>
</div>
