<div class="content-container standard-container">    <ul>
        <li class="header"><h2>Upcoming Releases</h2></li>
                <li><a href="/petroleum/gasdiesel/">Gasoline and Diesel Fuel Update</a>: <span class="date">5:00 p.m. ET, Monday</span></li>
                <li><a href="/petroleum/supply/weekly/">Weekly Petroleum Status Report</a>: <span class="date">10:30 a.m. ET, Wednesday</span></li>
                <li><a href="/petroleum/heatingoilpropane/">Heating Oil and Propane Update</a>: <span class="date">After 1:00 p.m. ET, Wednesday (Oct - March only)</span></li>
                <li><a href="/petroleum/weekly/">This Week in Petroleum </a>: <span class="date">After 1:00 p.m. ET, Wednesday</span></li>
<li class="footer"><a href="/reports/upcoming.cfm">See all upcoming</a></li>
    </ul>
</div>
