<div class="content-container standard-container">    <ul>
        <li class="header"><h2>Updated Data Series</h2></li>
                <li><span><!-- class="date" -->9/13/2017</span> <a href="/dnav/pet/pet_sum_sndw_dcus_nus_w.htm">Weekly supply estimates</a></li>
                <li><span><!-- class="date" -->9/13/2017</span> <a href="/dnav/pet/pet_pri_spt_s1_d.htm">Spot prices</a></li>
                <li><span><!-- class="date" -->9/13/2017</span> <a href="/dnav/pet/pet_pri_fut_s1_d.htm">Futures prices (NYMEX)</a></li>
                <li><span><!-- class="date" -->9/13/2017</span> <a href="/dnav/pet/pet_pnp_wiup_dcu_nus_w.htm">Weekly inputs &amp; utilization</a></li>
    </ul>
</div>
