<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong> Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2013-07/fig_HL1coppwp.jpg" class="lightbox"><img src="images/2013-07/fig_HL1_coppwp_sm.jpg" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3>Highlights</h3></li>
                <li><p>The daily spot price for West Texas Intermediate (WTI) crude oil at Cushing, Oklahoma was unsettled during April.  After opening at $97.24 per barrel, its highest point for the month, the price entered a period of decline, pressured by ample inventories.  Demand rates for both crude oil and refined products helped lead the price to the month's low of $86.65 per barrel on April 17.  The price rebounded during the latter half of the month, due in part to expectations of higher demand as refineries came back online after scheduled maintenance.  Closing at $93.22 per barrel, the price was $4.02 below its opening level for April.  Averaging $92.02 per barrel for the month overall, the price was 92 cents (1.0 percent) lower than March's average of $92.94 per barrel.  The April 2012 price of $103.32 per barrel was $11.30 (10.9 percent) higher than the current price.  ...</p></li>
                <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>