<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2016-10/fig_HL1coppwp2.png" class="lightbox"><img src="images/2016-10/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude Oil</h2>
            <ul>
                <li>Monthly average crude oil prices fell in July. The average domestic crude oil first purchase price declined $3.26 (7.4%), to $40.70 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil decreased $2.47 (5.9%) to $39.51 per barrel. The average landed cost of foreign crude oil fell $2.59 (5.9%), to $41.02 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil decreased $2.70 (5.7%), to $44.87 per barrel. The average cost of imported crude oil declined $2.55 (5.8%), to $41.58 per barrel. The composite refiner acquisition cost for crude oil fell $2.65 (5.8%), to $43.31 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>Monthly average prices for sales of motor gasoline by refiners declined during July. The average retail price fell 15.7 cents to $1.804 per gallon, while the average wholesale price decreased 15.4 cents to $1.489 per gallon.</li>
                <li>Refiner sales of finished motor gasoline rose in July. Total sales increased 400,000 gallons per day (0.1%) to an average of 342.0 million gallons per day. Retail sales fell 400,000 gallons per day (1.5%), while wholesales increased 800,000 gallons per day (0.3%). DTW sales accounted for 7.5% of wholesales, while rack and bulk sales made up 84.6% and 7.9%, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>Monthly average prices for refiner sales of No. 2 distillates decreased in July. The average price for No. 2 diesel fuel sold to end users dropped 8.5 cents to $1.576 per gallon, while the average wholesale price fell 10.5 cents to $1.426 per gallon. The average retail price for No. 2 fuel oil declined 4.7 cents to $1.814 per gallon, while the average wholesale price dropped 9.9 cents to $1.305 per gallon.</li>
                <li>Refiner sales of No. 2 ultra-low sulfur diesel fuel were mixed in July. Retail sales rose 100,000 gallons per day (0.8%), while wholesales fell 6.7 million gallons per day (4.9%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Monthly average prices for residual fuel oil sold by refiners continued to rise during July. The wholesale price for low-sulfur residual fuel oil rose 2.6 cents to 87.6 cents per gallon. Prices for high-sulfur residual fuel oil increased 4.7 cents to 95.8 cents per gallon at retail, while the wholesale price rose 1.1 cents to 83.4 cents per gallon.</li>
                <li>Overall, sales of residual fuel oil by refiners declined in July. Retail sales increased 300,000 gallons per day (7.9%), while wholesales fell 1.0 million gallons per day (11.2%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>July monthly average prices for refiner sales of the remaining surveyed products fell from June levels.  Propane, kerosene-type jet fuel, and No. 1 distillate prices fell at both retail and wholesale. Prices for aviation gasoline and kerosene also decreased at the wholesale level.</li>
                <li>Trends in refiner sales of products included in this section varied in July. Sales of propane declined at both the retail and wholesale levels, while sales of No. 1 distillate did just the opposite. Kerosene-type jet fuel sales fell at retail but increased at wholesale. Aviation gasoline sales declined at the wholesale, while sales of kerosene rose in the same category.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div> */ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/petroleum/marketing/annual/archive/" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a></li>
    </ul>
</div>