<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong> Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2013-04/fig_HL1coppwp.jpg" class="lightbox"><img src="images/2013-04/fig_HL1_coppwp_sm.jpg" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3>Highlights</h3></li>
                <li><p>After opening at $91.83 per barrel, its lowest point for themonth, the daily spot price for West Texas Intermediate(WTI) crude oil at Cushing, Oklahoma saw only modestchanges during the first half of January. At mid-month, areported decline in crude oil inventories along with newsof an attack on a gas plant in Algeria by militants helpedunderpin an increase in the price. Supportive economicnews contributed to the month's high of $97.98 per barrelon January 30. Closing at $97.65 per barrel, the price was$5.82 above its open level for January. Averaging $94.76per barrel for the month, the price was $6.90 (7.9 percent)higher than December's average of $87.86 per barrel.Compared to this time last year, the current price is $5.51(5.5 percent) lower than the January 2012 average of$100.27 per barrel.  ...</p></li>
                <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>