<?php /* Sections Promo  */ ?><div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2016-04/fig_HL1coppwp2.png" class="lightbox"><img src="images/2016-04/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude Oil</h2>
            <ul>
                <li>Monthly average crude oil prices continued to fall in all sales categories during January. The average domestic crude oil first purchase price declined $5.15 (16.0%), to $27.11 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil dropped $4.45 (15.8%) to $23.73 per barrel. The average landed cost of foreign crude oil decreased $4.86 (15.3%), to $26.84 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil fell $5.54 (14.7%), to $32.22 per barrel. The average cost of imported crude oil decreased $5.69 (17.2%), to $27.47 per barrel. The composite refiner acquisition cost for crude oil dropped $5.62 (15.8%), to $30.01 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>Monthly average prices for sales of motor gasoline by refiners registered across-the-board decreases again in January. The average retail price dropped 9.9 cents to $1.505 per gallon, while the average wholesale price decreased 16.8 cents to $1.188 per gallon.</li>
                <li>Refiner sales of finished motor gasoline declined in January. Total sales decreased 15.9 million gallons per day (4.9%) to an average of 309.3 million gallons per day. Retail sales fell 900,000 gallons per day (3.6%), while wholesales declined 15.0 million gallons per day (5.0%). DTW sales accounted for 7.8% of wholesales, while rack and bulk sales made up 85.1% and 7.1%, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>January average prices for refiner sales of No. 2 distillates also decreased in all categories of sales. The average price for No. 2 diesel fuel sold to end users dropped 16.7 cents to $1.198 per gallon, while the average wholesale price fell 16.1 cents to $1.015 per gallon. The average retail price for No. 2 fuel oil decreased 24.5 cents to $1.450 per gallon, while the average wholesale price fell 15.0 cents to 97.6 cents per gallon.</li>
                <li>Overall, refiner sales of No. 2 ultra-low sulfur diesel fuel declined in January. Retail sales increased 400,000 gallons per day (3.5%), while wholesales fell 9.1 million gallons per day (6.6%.</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Monthly average prices for residual fuel oil sales by refiners decreased in January. The wholesale price for low-sulfur residual fuel oil dropped 7.5 cents to 47.7 cents per gallon. Prices for high-sulfur residual fuel oil declined 22.0 cents to 64.1 cents per gallon at retail, while the wholesale price decreased 13.7 cents to 50.2 cents per gallon.</li>
                <li>Sales of residual fuel oil by refiners rose in January. Retail sales increased 100,000 gallons per day (2.5%), while wholesales climbed 400,000 gallons per day (4.5%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>Prices for refiner sales of the remaining surveyed products fell in January. Propane and kerosene-type jet fuel prices declined at both the retail and wholesale levels, while prices for kerosene, aviation gasoline, and No. 1 distillate decreased at the wholesale.</li>
                <li>Refiner sales of products included in this section were mixed in January. Propane sales rose at both retail and wholesale, while sales of kerosene-type jet fuel sales declined at both levels. While sales of aviation gasoline declined at the wholesale level, kerosene, No. 1 and No. 4 distillates sales increased in the same category.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div> */ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/petroleum/marketing/annual/archive/" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a></li>
    </ul>
</div>