<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2014-07/fig_HL1coppwp2.png" class="lightbox"><img src="images/2014-07/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude Oil</h2>
            <ul>
                <li>Monthly average crude oil prices show modest changes in most sales categories during April.  The average domestic crude oil first purchase price rose 29 cents (0.3 percent), to $96.47 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil climbed $2.10 (2.3 percent), to $95.22 per barrel.  The average landed cost of foreign crude oil rose 52 cents (0.5 percent), to $95.77 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil dropped 57 cents (0.6 percent), to $102.04 per barrel.  The average cost of imported crude oil increased 36 cents (0.4 percent), to $97.40 per barrel.  The composite refiner acquisition cost for crude oil declined 14 cents (0.1 percent), to $99.91 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>Monthly average prices for sales of motor gasoline made by refiners show considerable increases again in April.  The average retail price rose 11.0 cents to $3.214 per gallon, while the average wholesale price increased 12.6 cents to $2.981 per gallon.</li>
                <li>Sales of finished motor gasoline by refiners climbed in April.  Total sales rose 4.6 million gallons per day (1.5 percent) to an average of 309.1 million gallons per day.  Retail sales increased 700,000 gallons per day (3.6 percent), while wholesales rose 3.9 million gallons per day (1.4 percent).  DTW sales accounted for 7.9 percent of wholesales, while rack and bulk sales made up 84.9 percent and 7.1 percent, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>Monthly average refiner prices for No. 2 distillates continued to fall in April.  The average sales price for No. 2 diesel fuel to end users decreased 0.6 cent to $3.109 per gallon, while the average wholesale price dropped 0.5 cent to $3.026 per gallon.  The average price for No. 2 fuel oil sales to end users declined 4.9 cents to $3.572 per gallon, while the average wholesale price for No. 2 fuel oil fell 6.7 cents to $2.912 per gallon.</li>
                <li>Refiner sales of No. 2 ultra-low sulfur diesel fuel climbed 6.9 million gallons per day (4.8 percent) to an average of 151.2 million gallons per day in April.  No. 2 fuel oil sales fell 4.8 million gallons per day (52.6 percent) to an average of 4.3 million gallons per day.</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Monthly average prices for residual fuel oil sales by refiners fell in April.  The price for low-sulfur residual fuel oil decreased 6.9 cents to $2.401 per gallon at the wholesale level.  Prices for high-sulfur residual fuel oil dropped 6.0 cents to $2.316 per gallon at retail, and 2.3 cents to $2.152 per gallon at wholesale.</li>
                <li>Sales of residual fuel oil by refiners rose in April, with total sales increasing 800,000 gallons per day (5.9 percent) to an average of 14.4 million gallons per day.</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>Prices for other surveyed products show mixed trends in April.  Propane, kerosene-type jet fuel, and No. 1 distillate prices fell at both the retail and wholesale levels.  Prices for kerosene increased at retail, but fell at wholesale.  Aviation gasoline and No. 4 distillate prices rose at wholesale.</li>
                <li>Refiner sales of kerosene-type jet fuel increased at both retail and wholesale, while kerosene and No. 1 distillate sales fell at both levels.  Sales of propane rose at retail, but fell at wholesale.  Aviation gasoline sales increased at wholesale, while No. 4 distillate sales declined in the same category.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>*/ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a>