<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2016-01/fig_HL1coppwp2.png" class="lightbox"><img src="images/2016-01/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude Oil</h2>
            <ul>
                <li>October monthly average crude oil prices increased from September levels. The average domestic crude oil first purchase price rose 73 cents (1.8%), to $42.33 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil climbed $1.56 (4.2%) to $38.49 per barrel. The average landed cost of foreign crude oil rose 98 cents (2.5%), to $40.88 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil increased 24 cents (0.5%), to $46.92 per barrel. The average cost of imported crude oil rose 92 cents (2.2%), to $42.05 per barrel. The composite refiner acquisition cost for crude oil increased 34 cents (0.8%), to $44.72 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>Refiner monthly average prices for sales of motor gasoline remained on a downward path during October. The average retail price fell 7.0 cents to $1.850 per gallon, while the average wholesale price declined 5.1 cents to $1.558 per gallon.</li>
                <li>Overall, sales of finished motor gasoline by refiners fell in October. While total sales fell 3.6 million gallons per day (1.1%) to an average of 325.8 million gallons per day, retail sales increased 300,000 gallons per day (1.2%). Wholesales decreased 3.9 million gallons per day (1.3%). DTW sales accounted for 7.7% of wholesales, while rack and bulk sales explained 86.0% and 6.3%, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>The direction of monthly average prices for refiner sales of No. 2 distillates were mixed in October.  The average price for No. 2 diesel fuel sold to end users rose 0.9 cent to $1.702 per gallon, while the average wholesale price increased 2.2 cents to $1.573 per gallon. The average wholesale price for No. 2 fuel oil decreased 2.6 cents to $1.412 per gallon.</li>
                <li>Refiner sales of No. 2 ultra-low sulfur diesel fuel declined in October. Retail sales fell 500,000 gallons per day (4.0%), while wholesales decreased 3.4 million gallons per day (2.3%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Refiner monthly average prices for residual fuel oil varied in October. The wholesale price for low-sulfur residual fuel oil increased 2.5 cents to 84.4 cents per gallon. Prices for high-sulfur residual fuel oil declined 2.1 cents to $1.042 per gallon at retail, while the wholesale price decreased 1.5 cents to 84.1 cents per gallon.</li>
                <li>Sales of residual fuel oil by refiners fell in October. While retail sales declined 800,000 gallons per day (17.8%), wholesales increased 200,000 gallons per day (2.5%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>Refiner monthly average prices for sales of the remaining surveyed products show mixed changes in October. Propane and kerosene-type jet fuel prices rose at both the retail and wholesale levels.  The wholesale price for kerosene increased, while prices for aviation gasoline and No. 1 distillate fell at the same level.</li>
                <li>Refiner sales of products included in this section were varied during October. Sales of propane and kerosene-type jet fuel declined at both retail and wholesale. Aviation gasoline, kerosene, and No. 1 distillate sales increased at the wholesale level.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>*/ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/petroleum/marketing/annual/archive/" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a></li>
    </ul>
</div>