<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2015-06/fig_HL1coppwp2.png" class="lightbox"><img src="images/2015-06/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude Oil</h2>
            <ul>
                <li>Monthly average crude oil prices show mixed trends in March.  The average domestic crude oil first purchase price fell $1.69 (3.8%), to $42.66 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil remained flat at $43.91 per barrel.  The average landed cost of foreign crude oil decreased 49 cents (1.1%), to $45.96 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil declined $1.61 (3.2%), to $48.69 per barrel.  The average cost of imported crude oil increased 7 cents (0.1%), to $47.27 per barrel.  The composite refiner acquisition cost for crude oil fell 91 cents (1.9%), to $48.06 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>Refiner monthly average prices for sales of motor gasoline climbed in March.  The average retail price rose 19.4 cents to $2.052 per gallon, while the average wholesale price increased 12.8 cents to $1.765 per gallon.</li>
                <li>Sales of finished motor gasoline by refiners rose in March.  Total sales increased 2.0 million gallons per day (0.6%) to an average of 318.6 million gallons per day.  Retail sales increased 200,000 gallons per day (0.8%), while wholesales rose 1.8 million gallons per day (0.6%).  DTW sales made up 8.0% of wholesales, while rack and bulk sales accounted for 84.5% and 7.5%, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>Refiner monthly average prices for sales of No. 2 distillates declined in March.  The average sales price for No. 2 diesel fuel to end users fell 2.0 cents to $1.959 per gallon, while the average wholesale price decreased 4.5 cents to $1.816 per gallon.  The average sales price for No. 2 fuel oil to end users declined 6.3 cents to $2.141 per gallon, while the average wholesale price for No. 2 fuel oil fell 0.3 cent to $1.847 per gallon.</li>
                <li>Sales of No. 2 ultra-low sulfur diesel fuel by refiners increased modestly during March.  Retail sales remained flat, while wholesales rose 200,000 gallons per day (0.1%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Monthly average prices for sales of residual fuel oil by refiners show mixed changes in March.  The wholesale price for low-sulfur residual fuel oil fell 5.7 cents to $1.093 per gallon.  Prices for high-sulfur residual fuel oil rose 5.6 cents to $1.398 per gallon at retail, and 1.4 cents per gallon to $1.138 per gallon at wholesale.</li>
                <li>Refiner sales of residual fuel oil increased in March.  Total sales rose 900,000 gallons per day (7.9%) to an average of 12.3 million gallons per day.</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>Prices movements for the remaining surveyed products were mixed in March.  Propane prices fell at both retail and wholesale, while kerosene-type jet fuel prices rose at both levels.  Prices for aviation gasoline and No. 1 distillate increased at wholesale, while wholesale prices declined for kerosene and No. 4 distillate.</li>
                <li>Refiner sales propane sales declined at both the retail and wholesale levels in March.  Sales of kerosene-type jet fuel fell at retail, but rose at wholesale.  Aviation gasoline, kerosene, and No. 1 distillate sales fell at the wholesale level, while No. 4 distillate sales increased at the wholesale level.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>*/ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/petroleum/marketing/annual/archive/" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a>