<?php /* Side Column */ ?>

<span class="grey_side blue_top">
<h4>Additional Resources</h4>

<p class="no-border"><strong>Winter Weather</strong></p>
        <p><a href="http://www.oe.netl.doe.gov/ead.aspx">DOE Energy Assurance Daily Reports</a></p>
        <p><a href="http://www.oe.netl.doe.gov/emergency_sit_rpt.aspx">DOE Emergency Situation Reports</a></p>
        <p><a href="http://www.weather.gov/">National Weather Service</a></p>
<br />
<p class="no-border"><strong>Hurricane</strong></p>
<p><a href="/special/gulf_of_mexico/">Gulf of Mexico Fact Sheet &rsaquo;</a></p>
<p><a href="http://www.bsee.gov/Hurricane/ ">Bureau of Ocean Energy Management, Regulation and Enforcement (BOEMRE) Hurricane Information &rsaquo;</a></p>
<p><a href="http://www.oe.netl.doe.gov/emergency_sit_rpt.aspx">DOE Emergency   Situation Reports &rsaquo;</a></p>
<p><a href="/outlooks/steo/special/pdf/2013_sp_04.pdf">EIA Hurricane Outlook (pdf) &rsaquo;</a></p>
<?php /*p><a href="/special/disruptions/hurricane_gc/">Current Hurricane Information  &rsaquo;</a> </p*/ ?>
<p class="no-border"><a href="http://www.nhc.noaa.gov/">NOAA National Hurricane Center &rsaquo;</a></p>
</span>

<span class="grey_side blue_top">
<h4>Historical Reports</h4>
        <p><a href="/special/disruptions/hurricane/sandy/">Sandy</a> &mdash; Landfall October 29, 2012</p>
        <p><a href="/special/disruptions/hurricane/isaac/">Isaac</a> &mdash; Landfall August 29, 2012</p>
        <p><a href="http://www.eia.gov/todayinenergy/detail.cfm?id=2830">Irene</a> &mdash; Landfall August 27, 2011</p>
        <p><a href="/special/disruptions/hurricane/ike/">Ike</a> &mdash; Landfall September 13, 2008 </p>
        <p><a href="/special/disruptions/hurricane/gustav/">Gustav</a> &mdash; Landfall September 1,   2008 </p>
        <p><a href="/special/disruptions/hurricane/rita/">Rita</a> &mdash; Landfall September 23, 2005 </p>
        <p class="no-border"><a href="/special/disruptions/hurricane/katrina/">Katrina</a> &mdash; August 25, 2005 </p>

</span>