<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2014-12/fig_HL1coppwp2.png" class="lightbox"><img src="images/2014-12/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude Oil</h2>
            <ul>
                <li>Monthly average crude oil prices fell in all categories of sale for the third month in row during September.  The average domestic crude oil first purchase price dropped $3.38 (3.7 percent), to $87.34 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil declined $2.52 (2.8 percent), to $86.87 per barrel.  The average landed cost of foreign crude oil fell $3.62 (3.9 percent), to $88.08 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil fell $2.92 (3.0 percent), to $94.68 per barrel.  The average cost of imported crude oil decreased $3.84 (4.1 percent), to $89.39 per barrel.  The composite refiner acquisition cost for crude oil declined $3.34 (3.5 percent), to $92.27 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>September monthly average prices for refiner sales of motor gasoline fell across the board.  The average retail price declined 8.0 cents to $2.936 per gallon, while the average wholesale price decreased 9.0 cents to $2.669 per gallon.</li>
                <li>Sales of finished motor gasoline by refiners decreased in September, with total sales falling 9.8 million gallons per day (3.1 percent) to an average of 306.3 million gallons per day.  Retail sales dropped 100,000 gallons per day (0.5 percent), while wholesales fell 9.7 million gallons per day (3.3 percent).  DTW sales accounted for 8.0 percent of wholesales, while rack and bulk sales made up 85.6 percent and 6.4 percent, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>Monthly average prices for sales of No. 2 distillates by refiners decreased in September.  The average sales price for No. 2 diesel fuel to end users declined 8.7 cents to $2.925 per gallon, while the average wholesale price dropped 9.4 cents to $2.806 per gallon.  The average price for No. 2 fuel oil sales to end users fell 8.4 cents to $3.324 per gallon, while the average wholesale price declined 8.3 cents to $2.701per gallon.</li>
                <li>Refiner sales of No. 2 ultra-low sulfur diesel fuel increased 7.6 million gallons per day (4.9 percent) to an average of 161.2 million gallons per day in September.  Total No. 2 fuel oil sales increased 2.0 million gallons per day (2.0 percent) to an average of 6.6 million gallons per day.</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Monthly average prices for sales of residual fuel oil by refiners declined in September.  The wholesale price for low-sulfur residual fuel oil fell 4.8 cents to $2.100 per gallon.  Prices for high-sulfur residual fuel oil decreased 9.5 cents to $2.255 per gallon at retail, while the wholesale price fell 6.2 cents to $2.068 per gallon.</li>
                <li>Refiner sales of residual fuel oil decreased in September.  Total sales of residual fuel declined 200,000 gallons per day (1.7 percent) to an average of 11.3 million gallons per day.</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>The direction of prices for the remaining surveyed products varied in September.  Kerosene-type jet fuel prices fell at both retail and wholesale, while propane prices did just the opposite.  Kerosene and No. 1 distillate prices declined at the wholesale level, while prices for aviation gasoline and No. 4 distillate increased at the same level.</li>
                <li>Refiner sales of propane increased again at both the retail and wholesale levels during September.  Kerosene-type jet fuel sales declined at retail, but rose at wholesale.  Kerosene and No. 1 distillate wholesales increased, while sales of aviation gasoline and No. 4 distillates declined at the same level.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>*/ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/oil_gas/petroleum/data_publications/petroleum_marketing_annual/pma_historical.html" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a>