      <h1>Historical Gulf of Mexico Distruptions</h1>
      <p><strong>Historical Disruptions</strong><br />
        In previous   years, the U.S. Energy Information Administration has tracked and published the   following special reports of selected significant energy disruption events:      
      <ul>
        <li><a href="/special/disruptions/ike/">Ike</a> &mdash; Landfall September 13, 2008 </li>
        <li><a href="/special/disruptions/gustav/">Gustav</a> &mdash; Landfall September 1,   2008 </li>
        <li><a href="/special/disruptions/rita/">Rita</a> &mdash; Landfall September 23, 2005 </li>
        <li><a href="/special/disruptions/katrina/">Katrina</a> &mdash; August 25, 2005 </li>
      </ul>
      </p>