<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong> Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2013-06/fig_HL1coppwp.jpg" class="lightbox"><img src="images/2013-06/fig_HL1_coppwp_sm.jpg" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3>Highlights</h3></li>
                <li><p>The daily spot price at Cushing, Oklahoma for WestTexas Intermediate (WTI) crude oil was on the riseduring March. After opening at $92.03 per barrel, theprice dropped to the month's low of $90.13 per barrel onMarch 4, due to continuing economic concerns. The priceincreased modestly during the following weeks as crudeoil stocks at Cushing registered some decline amid risingrefinery utilization. By the end of the month,international economic issues and reported declines infinished product stocks lent some support to the price.Closing the month at its highest level, $97.24 per barrel,the price was $5.21 higher than its opening for March.For the month overall, however, the price averaged$92.94 per barrel, down $2.37 (2.5 percent) fromFebruary's average of $95.31 per barrel. The current priceis $13.22 (12.5 percent) below the March 2012 price of$106.16 per barrel.  ...</p></li>
                <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>