<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2015-11/fig_HL1coppwp2.png" class="lightbox"><img src="images/2015-11/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude Oil</h2>
            <ul>
                <li>Monthly average crude oil prices fell in all sales categories again in August. The average domestic crude oil first purchase price declined $7.72 (16.2%), to $39.98 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil decreased $7.54 (16.4%) to $38.32 per barrel. The average landed cost of foreign crude oil dropped $8.31 (16.6%), to $41.70 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil declined $7.82 (14.4%), to $46.33 per barrel. The average cost of imported crude oil dropped $9.17 (17.5%), to $43.25 per barrel. The composite refiner acquisition cost for crude oil fell $8.42 (15.8%), to $44.99 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>Refiner monthly average prices for sales of motor gasoline declined in August. The average retail price fell 11.5 cents to $2.223 per gallon, while the average wholesale price decreased 23.4 cents to $1.838 per gallon.</li>
                <li>Sales of finished motor gasoline by refiners decreased in August. Total sales fell 1.4 million gallons per day (0.4%) to an average of 330.0 million gallons per day. Retail sales declined 400,000 gallons per day (1.5%), while wholesales decreased 1.0 million gallons per day (0.3%). DTW sales accounted for 7.6% of wholesales, while rack and bulk sales made up 85.5% and 6.8%, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>Monthly average prices for refiner sales of No. 2 distillates continued to decline in August.  The average sales price for No. 2 diesel fuel to end users fell 17.5 cents to $1.738 per gallon, while the average wholesale price decreased 16.7 cents to $1.562 per gallon. The average sales price for No. 2 fuel oil to end users declined 16.1 cents to $2.046 per gallon, while the average wholesale price for No. 2 fuel oil dropped 19.3 cents to $1.461 per gallon.</li>
                <li>Overall, refiner sales of No. 2 ultra-low sulfur diesel fuel declined in August. Retail sales increased 100,000 gallons per day (0.8%), while wholesales fell 4.6 million gallons per day (3.1%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Refiner monthly average prices for residual fuel oil declined in August. The wholesale price for low-sulfur residual fuel oil fell 23.3 cents to 84.7 cents per gallon. Prices for high-sulfur residual fuel oil decreased 9.5 cents to $1.150 per gallon at retail, while the wholesale price dropped 20.2 cents to 92.8 cents per gallon.</li>
                <li>Total sales of residual fuel oil by refiners increased in August. Retail sales rose 700,000 gallons per day (19.4%), while wholesales climbed 900,000 gallons per day (10.8%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>Refiner monthly average prices for sales of the remaining surveyed products declined in August. Propane and kerosene-type jet fuel prices fell at both the retail and wholesale levels, while prices for aviation gasoline, kerosene, No. 1 distillate, and No. 4 distillate registered decreases at the wholesale level.</li>
                <li>Refiner sales of products included in this section were mixed during August. Sales of propane increased at both the retail and wholesale levels, while sales of kerosene-type jet fuel show the opposite trend. Aviation gasoline and No. 4 distillate sales fell at wholesale, while sales of kerosene and No. 1 distillate declined in the same category.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>*/ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/petroleum/marketing/annual/archive/" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a></li>
    </ul>
</div>