<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2017-01/fig_HL1coppwp2.png" class="lightbox"><img src="images/2017-01/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude oil</h2>
            <ul>
                <li>Monthly average crude oil prices increased in October. The average domestic crude oil first purchase price climbed $4.46 (11.0%), to $45.00 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil rose $4.29 (11.2%) to $42.58 per barrel. The average landed cost of foreign crude oil increased $3.34 (8.2%), to $43.86 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil rose $4.16 (9.4%), to $48.63 per barrel. The average cost of imported crude oil increased $3.90 (9.5%), to $44.76 per barrel. The composite refiner acquisition cost for crude oil rose $4.09 (9.6%), to $46.82 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>Monthly average prices for refiner sales of motor gasoline increased in October. The average retail price rose 3.1 cents to $1.819 per gallon, while the average wholesale price climbed 5.4 cents to $1.568 per gallon.</li>
                <li>Refiner sales of finished motor gasoline continued to fall in October. Total sales decreased 6.4 million gallons per day (1.9%) to an average of 327.8 million gallons per day. Retail sales fell 500,000 gallons per day (1.9%), while wholesales declined 5.9 million gallons per day (1.9%). DTW sales accounted for 7.6% of wholesales, while rack and bulk sales made up 86.3% and 6.1%, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>October monthly average prices for refiner sales of No. 2 distillates rose from September levels. The average price for No. 2 diesel fuel sold to end users increased 10.5 cents to $1.706 per gallon, while the average wholesale price climbed 12.1 cents to $1.592 per gallon. The average price for sales of No. 2 fuel oil sold to end users increased 13.6 cents to $1.941 per gallon, while the wholesale price for No. 2 fuel oil rose 10.2 cents to $1.443 per gallon.</li>
                <li>Overall, refiner sales of No. 2 ultra-low sulfur diesel fuel increased in October. Retail sales dropped 200,000 gallons per day (1.6%), while wholesales rose 2.8 million gallons per day (2.0%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Monthly average prices for residual fuel oil sold by refiners rose again in October. The wholesale price for low-sulfur residual fuel oil climbed 11.5 cents to 96.1 cents per gallon. Prices for high-sulfur residual fuel oil increased 3.2 cents to $1.091 per gallon at retail, while the wholesale price rose 8.0 cents to 93.5 cents per gallon.</li>
                <li>Sales of residual fuel oil by refiners dropped in October. Retail sales fell 300,000 gallons per day (6.4%), while wholesales decreased 800,000 gallons per day (10.1%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>Monthly average prices for refiner sales of the remaining surveyed products increased in October. Propane, kerosene-type jet fuel, and No. 1 distillate prices rose at both the retail and wholesale levels. Prices for aviation gasoline and kerosene also increased at wholesale.</li>
                <li>Refiner sales of products included in this section varied in October. Propane sales dropped at retail but increased at wholesale. Sales of kerosene-type jet fuel fell at both the retail and wholesale levels, while No. 1 distillate sales show the opposite trend. Aviation gasoline sales fell at the wholesale level, while sales of kerosene increased in the same sales category.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div> */ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/petroleum/marketing/annual/archive/" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a></li>
    </ul>
</div>