		<?php /* About EIA Menu */ ?>
          <span class="grey_side_nav blue_top side_nav">
            <h4><a href="/special/disruptions/">Hurricanes</a></h4>
              <ul>
                <li<?php if ( $locale == '2010') {?> class="active"<?php  } // end if ?>><span>2010 Season</span>
                  <ul>
                    <li><a href="/special/disruptions/hurricane/earl">Hurricane Earl</a></li>
                  </ul>
                </li>
                <li<?php if ( $locale == '2008') {?> class="active"<?php  } // end if ?>><span>2008 Season</span>
                  <ul>
                    <li><a href="/special/disruptions/hurricane/ike">Hurricane Ike</a></li>
                    <li><a href="/special/disruptions/hurricane/gustav">Hurricane Gustav</a></li>
                  </ul>
                </li>
                <li<?php if ( $locale == '2005') {?> class="active"<?php  } // end if ?>><span>2005 Season </span>
                  <ul>
                    <li><a href="/special/disruptions/hurricane/rita">Hurricane Rita</a></li>
                    <li><a href="/special/disruptions/hurricane/katrina">Hurricane Katrina</a></li>
                  </ul>
                <hr />
                <p ><a href="/special/gulf_of_mexico/">Gulf of Mexico Fact Sheet</a> </p>
                
          </span>
          <?php /* About EIA Menu */ ?>