<div class="secondary">
	<h2>Data tables and figures</h2>

	<div class="all-open">
		<h3>Summary</h3>
		<div class="accordion-content">
			<ul class="calculated-numbered">
				<li><span class="number">Table S1a.</span><a href="/uranium/marketing/summarytable1a.php?">Uranium purchased by owners and operators of U.S. civilian nuclear power reactors, 1994&ndash;2017 (Table S1a and Figure S1)</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartableS1afigureS1.pdf"><span class="ico pdf"><span>PDF</span></span></a> <a href="/uranium/marketing/xls/umartableS1afigureS1.xls"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
			<ul class="calculated-numbered">
				<li><span class="number">Table S1b.</span><a href="/uranium/marketing/summarytable1b.php">Weighted-average price of uranium purchased by owners and operators of U.S. civilian nuclear power reactors, 1994&ndash;2017 (Table S1b and Figure S2)</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartableS1bfigureS2.pdf"><span class="ico pdf"><span>PDF</span></span></a> <a href="/uranium/marketing/xls/umartableS1bfigureS2.xls"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
			<ul class="calculated-numbered">
				<li><span class="number">Table S2.</span><a href="/uranium/marketing/summarytable2.php">Uranium feed deliveries, enrichment services, and uranium loaded by owners and operators of U.S. civilian nuclear power reactors, 1994&ndash;2017 (Table S2 and Figures S3 and S4)</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartableS2figuresS3n4.pdf"><span class="ico pdf"><span>PDF</span></span></a> <a href="/uranium/marketing/xls/umartableS2figuresS3n4.xls"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
			<ul class="calculated-numbered">
				<li><span class="number">Table S3a.</span><a href="/uranium/marketing/summarytable3a.php">Foreign purchases, foreign sales, and uranium inventories owned by U.S. suppliers and owners and operators of U.S. civilian nuclear power reactors, 1994&ndash;2017 (Table S3a and Figure S5)</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartableS3afigureS5.pdf"><span class="ico pdf"><span>PDF</span></span></a> <a href="/uranium/marketing/xls/umartableS3afigureS5.xls"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
			<ul class="calculated-numbered">
				<li><span class="number">Table S3b.</span><a href="/uranium/marketing/summarytable3b.php">Weighted-average price of foreign purchases and foreign sales by U.S. suppliers and owners and operators of U.S. civilian nuclear power reactors, 1994&ndash;2017 (Table S3b and Figure S6)</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartableS3bfigureS6.pdf"><span class="ico pdf"><span>PDF</span></span></a> <a href="/uranium/marketing/xls/umartableS3bfigureS6.xls"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
		</div>

		<h3>Uranium purchased</h3>

		<div class="accordion-content">
			<ul class="calculated-numbered">
				<li><span class="number">Table 1.</span><a href="/uranium/marketing/table1.php">by supplier (Table 1 and Figures 1 and 2)</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartable1figures1n2.pdf" title="pdf format: by Supplier (Table 1.)"><span class="ico pdf"><span>PDF</span></span></a> <a href="/uranium/marketing/xls/umartable1figures1n2.xls" title="xls format: by Supplier (Table 1.)"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
			<ul class="calculated-numbered">
				<li><span class="number">Table 2.</span><a href="/uranium/marketing/table2.php">by origin (Table 2 and Figures 3 and 4)</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartable2figures3n4.pdf"><span class="ico pdf"><span>PDF</span></span></a> <a href="/uranium/marketing/xls/umartable2figures3n4.xls"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
			<ul class="calculated-numbered">
				<li><span class="number">Table 3.</span><a href="/uranium/marketing/table3.php">by origin country (Table 3 and Figure 5)</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartable3figure5.pdf"><span class="ico pdf"><span>PDF</span></span></a> <a href="/uranium/marketing/xls/umartable3figure5.xls"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
			<ul class="calculated-numbered">
				<li><span class="number">Table 4.</span><a href="/uranium/marketing/table4.php">by origin and material type (Table 4 and Figure 6)</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartable4figure6.pdf"><span class="ico pdf"><span>PDF</span></span></a> <a href="/uranium/marketing/xls/umartable4figure6.xls"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
		</div>

		<h3>Price mechanisms, distributions and contract types</h3>

		<div class="accordion-content">
			<ul class="calculated-numbered">
				<li><span class="number">Table 5.</span><a href="/uranium/marketing/table5.php">by pricing mechanisms (Table 5 and Figure 7)</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartable5figure7.pdf"><span class="ico pdf"><span>PDF</span></span></a> <a href="/uranium/marketing/xls/umartable5figure7.xls"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
			<ul class="calculated-numbered">
				<li><span class="number">Table 6a.</span><a href="/uranium/marketing/table6a.php">by price and distributed by quantity (Tables 6a)</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartable6a.pdf"><span class="ico pdf"><span>PDF</span></span></a> <a href="/uranium/marketing/xls/umartable6a.xls"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
			<ul class="calculated-numbered">
				<li><span class="number">Table 6b.</span><a href="/uranium/marketing/table6b.php">by price and distributed by purchaser (Tables 6b)</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartable6b.pdf"><span class="ico pdf"><span>PDF</span></span></a> <a href="/uranium/marketing/xls/umartable6b.xls"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
			<ul class="calculated-numbered">
				<li><span class="number">Table 7.</span><a href="/uranium/marketing/table7.php">by contract type (Table 7)</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartable7.pdf"><span class="ico pdf"><span>PDF</span></span></a> <a href="/uranium/marketing/xls/umartable7.xls"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
		</div>

		<h3>New purchases</h3>

		<div class="accordion-content">
			<ul class="calculated-numbered">
				<li><span class="number">Table 8.</span><a href="/uranium/marketing/table8.php">Contracts signed in 2017 (Table 8)</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartable8.pdf"><span class="ico pdf"><span>PDF</span></span></a> <a href="/uranium/marketing/xls/umartable8.xls"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
			<ul class="calculated-numbered">
				<li><span class="number">Table 9.</span><a href="/uranium/marketing/table9.php">Signed in 2015, by delivery year,<brli>
							2018&ndash;27 (Table 9 and Figure 8)</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartable9figure8.pdf"><span class="ico pdf"><span>PDF</span></span></a> <a href="/uranium/marketing/xls/umartable9figure8.xls"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
		</div>

		<h3>Future deliveries</h3>

		<div class="accordion-content">
			<ul class="calculated-numbered">
				<li><span class="number">Table 10.</span><a href="/uranium/marketing/table10.php">In effect at the end 2015 (Table 10 and Figure 9)</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartable10figure9.pdf"><span class="ico pdf"><span>PDF</span></span></a> <a href="/uranium/marketing/xls/umartable10figure9.xls"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
			<ul class="calculated-numbered">
				<li><span class="number">Table 11.</span><a href="/uranium/marketing/table11.php">Unfilled requirements (Table 11 and Figure 10)</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartable11figure10.pdf"><span class="ico pdf"><span>PDF</span></span></a> <a href="/uranium/marketing/xls/umartable11figure10.xls"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
			<ul class="calculated-numbered">
				<li><span class="number">Table 12.</span><a href="/uranium/marketing/table12.php">Maximum anticipated market requirements (Table 12 and Figure 11)</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartable12figure11.pdf"><span class="ico pdf"><span>PDF</span></span></a><a href="/uranium/marketing/xls/umartable12figure11.xls"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
		</div>

		<h3>Feed for enrichment</h3>

		<div class="accordion-content">
			<ul class="calculated-numbered">
				<li><span class="number">Table 13.</span><a href="/uranium/marketing/table13.php">by enrichment country (Table 13 and Figure 12)</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartable13figure12.pdf"><span class="ico pdf"><span>PDF</span></span></a> <a href="/uranium/marketing/xls/umartable13figure12.xls"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
			<ul class="calculated-numbered">
				<li><span class="number">Table 14.</span><a href="/uranium/marketing/table14.php">by origin country (Table 14 and Figure 13)</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartable14figure13.pdf"><span class="ico pdf"><span>PDF</span></span></a> <a href="/uranium/marketing/xls/umartable14figure13.xls"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
			<ul class="calculated-numbered">
				<li><span class="number">Table 15.</span><a href="/uranium/marketing/table15.php">Shipments to enrichment suppliers, 2016-25 (Table 15 and Figure 14)</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartable15figure14.pdf"><span class="ico pdf"><span>PDF</span></span></a> <a href="/uranium/marketing/xls/umartable15figure14.xls"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
		</div>

		<h3>SWU</h3>

		<div class="accordion-content">
			<ul class="calculated-numbered">
				<li><span class="number">Table 16.</span><a href="/uranium/marketing/table16.php">Enrichment services by origin country (Table 16 and Figure 15)</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartable16figure15.pdf"><span class="ico pdf"><span>PDF</span></span></a> <a href="/uranium/marketing/xls/umartable16figure15.xls"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
			<ul class="calculated-numbered">
				<li><span class="number">Table 17.</span><a href="/uranium/marketing/table17.php">Enrichment services by contract type (Table 17)</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartable17.pdf"><span class="ico pdf"><span>PDF</span></span></a> <a href="/uranium/marketing/xls/umartable17.xls"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
		</div>

		<h3>Loaded uranium</h3>

		<div class="accordion-content">
			<ul class="calculated-numbered">
				<li><span class="number">Table 18.</span><a href="/uranium/marketing/table18.php">in fuel assemblies (Table 18 and Figure 16)</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartable18figure16.pdf"><span class="ico pdf"><span>PDF</span></span></a> <a href="/uranium/marketing/xls/umartable18figure16.xls"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
		</div>

		<h3>Foreign purchases and sales</h3>

		<div class="accordion-content">
			<ul class="calculated-numbered">
				<li><span class="number">Table 19.</span><a href="/uranium/marketing/table19.php">Foreign purchases (Table 19 and Figure 17)</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartable19figure17.pdf"><span class="ico pdf"><span>PDF</span></span></a> <a href="/uranium/marketing/xls/umartable19figure17.xls"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
			<ul class="calculated-numbered">
				<li><span class="number">Table 20.</span><a href="/uranium/marketing/table20.php">U.S. broker and trader purchases (Table 20 and Figure 18)</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartable20figure18.pdf"><span class="ico pdf"><span>PDF</span></span></a> <a href="/uranium/marketing/xls/umartable20figure18.xls"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
			<ul class="calculated-numbered">
				<li><span class="number">Table 21.</span><a href="/uranium/marketing/table21.php">Foreign sales (Table 21 and Figure 19)</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartable21figure19.pdf"><span class="ico pdf"><span>PDF</span></span></a> <a href="/uranium/marketing/xls/umartable21figure19.xls"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
		</div>

		<h3>Commercial inventories</h3>

		<div class="accordion-content">
			<ul class="calculated-numbered">
				<li><span class="number">Table 22.</span><a href="/uranium/marketing/table22.php">Natural and enriched (Table 22 and Figures 20 and 21)</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartable22figures20n21.pdf"><span class="ico pdf"><span>PDF</span></span></a> <a href="/uranium/marketing/xls/umartable22figures20n21.xls"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
			<ul class="calculated-numbered">
				<li><span class="number">Table 23.</span><a href="/uranium/marketing/table23.php">by owner (Table 23 and Figure 22)</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartable23.pdf"><span class="ico pdf"><span>PDF</span></span></a> <a href="/uranium/marketing/xls/umartable23.xls"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
		</div>

		<h3>Sellers</h3>

		<div class="accordion-content">
			<ul class="calculated-numbered">
				<li><span class="number">Table 24.</span><a href="/uranium/marketing/table24.php">of uranium</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartable24uransellers.pdf"><span class="ico pdf"><span>PDF</span></span></a> <a href="/uranium/marketing/xls/umartable24uransellers.xls"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
			<ul class="calculated-numbered">
				<li><span class="number">Table 25.</span><a href="/uranium/marketing/table25.php">of enrichment services</a></li>
				<li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartable25swusellers.pdf"><span class="ico pdf"><span>PDF</span></span></a> <a href="/uranium/marketing/xls/umartable25swusellers.xls"><span class="ico xls"><span>XLS</span></span></a></li>
			</ul>
		</div>
	</div>
</div>
</div>


<div class="secondary">
	<ul>
		<li class="head">More Uranium Reports</li>
		<li><a href="/cneaf/nuclear/dupr/qupd.html">Domestic Uranium Production Quarterly Report</a></li>
		<li><a href="/cneaf/nuclear/dupr/dupr.html">Domestic Uranium Production Report - Annual</a></li>
	</ul>
</div>