<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2016-08/fig_HL1coppwp2.png" class="lightbox"><img src="images/2016-08/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude Oil</h2>
            <ul>
                <li>Monthly average crude oil prices continued to rise in all categories of sale in May. The average domestic crude oil first purchase price increased $5.43 (15.3%), to $41.02 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil climbed $5.80 (17.7%) to $38.54 per barrel. The average landed cost of foreign crude oil rose $5.10 (14.5%), to $40.26 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil increased $5.40 (13.7%), to $44.70 per barrel. The average cost of imported crude oil rose $5.10 (14.2%), to $41.00 per barrel. The composite refiner acquisition cost for crude oil climbed $5.20 (13.8%), to $42.91 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>Monthly average prices for sales of motor gasoline by refiners increased in all sales categories during May. The average retail price climbed 14.4 cents to $1.869 per gallon, while the average wholesale price rose 13.7 cents to $1.613 per gallon.</li>
                <li>Refiner sales of finished motor gasoline rose in May. Total sales increased 3.4 million gallons per day (1.0%) to an average of 331.8 million gallons per day. Retail sales rose 100,000 gallons per day (0.4%), while wholesales climbed 3.3 million gallons per day (1.1%). DTW sales accounted for 7.8% of wholesales, while rack and bulk sales made up 85.2% and 7.1%, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>Monthly average prices for refiner sales of No. 2 distillates increased in May. The average price for No. 2 diesel fuel sold to end users climbed 16.8 cents to $1.554 per gallon, while the average wholesale price increased 18.3 cents to $1.434 per gallon. The average retail price for No. 2 fuel oil rose 10.2 cents to $1.733 per gallon, while the average wholesale price increased 17.8 cents to $1.291 per gallon.</li>
                <li>Refiner sales of No. 2 ultra-low sulfur diesel fuel varied in May. Retail sales rose 400,000 gallons per day (3.4%), while wholesales fell 2.4 million gallons per day (1.8%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Average prices for residual fuel oil sold by refiners increased during May. The wholesale price for low-sulfur residual fuel oil rose 9.6 cents to 72.9 cents per gallon. Prices for high-sulfur residual fuel oil climbed 13.4 cents to 86.8 cents per gallon at retail, while the wholesale price rose 11.0 cents to 72.4 cents per gallon.</li>
                <li>Sales of residual fuel oil by refiners rose overall in May. Retail sales fell 300,000 gallons per day (7.1%), while wholesales increased 1.0 million gallons per day (11.1%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>Monthly average prices for refiner sales of the remaining surveyed products increased in May. Propane and kerosene-type jet fuel prices rose at both retail and wholesale. Prices for aviation gasoline, kerosene, No. 1 distillate, and No. 4 distillate also registered increases at the wholesale level.</li>
                <li>Refiner sales of these products were mixed during May. Sales of kerosene-type jet fuel rose at both retail and wholesale levels. Propane sales fell at retail, but rose at wholesale. Aviation gasoline, No. 1 distillate, and No. 4 distillate sales fell at the wholesale level, while kerosene sales increased in the same category.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div> */ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/petroleum/marketing/annual/archive/" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a></li>
    </ul>
</div>