<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong> Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2013-10/fig_HL1coppwp.jpg" class="lightbox"><img src="images/2013-10/fig_HL1_coppwp_sm.jpg" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3>Highlights</h3></li>
        <li class="header"><h2>Crude Oil</h2>
            <ul>
                <li>July monthly average prices for crude oil show firm increases in all categories of sales.  The average domestic crude oil first purchase price climbed $7.56 (8.0 percent), to $101.61 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil rose $4.83 (5.0 percent), to $101.11 per barrel.  The average landed cost of foreign crude oil increased $3.62 (3.8 percent), to $99.99 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil rose $5.93 (5.9 percent), to $106.19 per barrel.  The average cost of imported crude increased $4.39 (4.5 percent), to $101.56 per barrel.  The composite refiner acquisition cost for crude oil climbed $5.18 (5.2 percent), to $103.85 per barrel.</li>
            </ul>
        </li>
        <li class="header"><h2>Petroleum Products</h2></li>
                <li><h4>Motor Gasoline</h4>
            <ul>
                <li>Monthly average prices for sales of finished gasoline by refiners show mixed trends in July.  The average retail sales price for motor gasoline decreased 3.8 cents to $3.146 per gallon, while the average wholesale price increased 6.0 cents to $2.942 per gallon.</li>
                <li>Refiner sales of finished motor gasoline fell in July.  Total sales decreased 3.2 million gallons per day (1.0 percent) to an average of 319.1 million gallons per day.  Retail sales declined 500,000 gallons per day (2.1 percent), while wholesales fell 2.7 million gallons per day (0.9 percent).  DTW sales accounted for 9.9 percent of wholesales, while rack and bulk sales made up 82.2 percent and 8.0 percent, respectively.</li>
                    </ul>
        </li>
                <li><h4>No. 2 Distillate</h4>
            <ul>
                <li>Refiner monthly average prices for No. 2 distillates increased during July.  The average sales price for No. 2 diesel fuel to end users rose 7.1 cents to $3.099 per gallon, while the average wholesale price climbed 9.2 cents to $3.015 per gallon.  The average price for No. 2 fuel oil sales to end users increased 7.2 cents to $3.244 per gallon, while the average wholesale price rose 15.3 cents to $2.894 per gallon.</li>
                <li>In total, refiner sales of No. 2 distillates increased during July, rising 3.8 million gallons per day (2.4 percent), to 164.7 million gallons per day.  No. 2 fuel oil sales declined 100,000 gallons per day (2.5 percent), while sales of No. 2 diesel fuel climbed 3.9 million gallons per day (2.5 percent).</li>
                    </ul>
        </li>
                <li><h4>Residual Fuel Oil</h4>
            <ul>
                <li>Monthly average prices for refiner residual fuel oil sales were mixed in July.  Prices for low-sulfur residual fuel oil fell 1.7 cents to $2.768 per gallon at retail, and 0.3 cent to $2.282 per gallon at wholesale.  Prices for high-sulfur residual fuel oil dropped 10.5 cents to $2.280 per gallon at retail, but increased 1.1 cents to $2.225 per gallon at wholesale.</li>
                <li>Sales of residual fuel oil by refiners increased overall in July.  Low-sulfur residual fuel oil sales increased 400,000 gallons per day (11.1 percent), while high-sulfur residual fuel oil sales decreased 100,000 gallons per day (0.9 percent).</li>
                    </ul>
        </li>
                <li><h4>Other Products</h4>
            <ul>
                <li>Prices for the remaining surveyed products increased during July.  Prices for propane, kerosene-type jet fuel, aviation gasoline, kerosene and No. 1 distillate rose at both the retail and wholesale levels.  The price for No. 4 fuel oil also increased at the wholesale level.</li>
                <li>Refiner sales of these products varied in July.  Sales of kerosene-type jet fuel, kerosene, and No. 1 distillate increased at both retail and wholesale.  Propane sales declined at the retail level, but increased at wholesale, while aviation gasoline sales show the opposite trend. Sales of No. 4 distillate increased at wholesale.</li>
        </ul></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>