<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong> Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2014-04/fig_HL1coppwp.jpg" class="lightbox"><img src="images/2014-04/fig_HL1_coppwp_sm.jpg" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
        <li class="header"><h2>Crude Oil</h2>
            <ul>
                <li>Monthly average crude oil prices show mixed trends in January.  The average domestic crude oil first purchase price fell $2.26 (2.5 percent), to $89.59 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil increased 83 cents (0.9 percent), to $90.81 per barrel.  The average landed cost of foreign crude oil fell 8 cents (0.1 percent), to $89.32 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil declined $2.09 (2.1 percent), to $95.78 per barrel.  The average cost of imported crude oil fell 86 cents (0.9 percent), to $89.71 per barrel.  The composite refiner acquisition cost for crude oil decreased $1.50 (1.6 percent), to $92.82 per barrel.</li>
            </ul>
        </li>
        <li class="header"><h2>Petroleum Products</h2></li>
                <li><h4>Motor Gasoline</h4>
            <ul>
                <li>The January monthly average price for retail sales of  motor gasoline made by refiners rose 5.7 cents to $2.816 per gallon, while the average wholesale price increased 2.3 cents to $2.604 per gallon.</li>
                <li>Sales of finished motor gasoline by refiners declined in January.  Total sales fell 14.7 million gallons per day (4.8 percent) to an average of 289.4 million gallons per day.  Retail sales decreased 600,000 gallons per day (3.2 percent), while wholesales dropped 14.1 million gallons per day (4.9 percent).  DTW sales accounted for 9.7 percent of wholesales, while rack and bulk sales made up 82.2 percent and 8.1 percent, respectively</li>
                    </ul>
        </li>
                <li><h4>No. 2 Distillate</h4>
            <ul>
                <li>The direction of monthly average refiner prices for No. 2 distillates varied in January.  The average sales price for No. 2 diesel fuel to end users fell 3.0 cents to $3.025 per gallon, while the average wholesale price decreased 1.9 cents to $2.979 per gallon.  The average price for No. 2 fuel oil sales to end users increased 1.3 cents to $3.591 per gallon, while the average wholesale price for No. 2 fuel oil rose 4.8 cents to $3.059 per gallon.</li>
                <li>Refiner sales of No. 2 distillates reached 159.7 million gallons per day in January.  No. 2 fuel oil sales increased 1.1 million gallons per day (13.6 percent), while sales of No. 2 diesel fuel rose 1.2 million gallons per day (0.8 percent).</li>
                    </ul>
        </li>
                <li><h4>Residual Fuel Oil</h4>
            <ul>
                <li>Monthly average prices for residual fuel oil sales by refiners moved in different directions during January.  The price for low-sulfur residual fuel oil rose 2.2 cents to $2.337 per gallon at the wholesale level.  Prices for high-sulfur residual fuel oil increased 9.2 cents to $2.445 per gallon at retail, but declined 6.0 cents to $2.117 per gallon at wholesale</li>
                <li>Sales of residual fuel oil by refiners decreased in January, with total sales falling 800,000 gallons per day (5.6 percent) to an average of 13.5 million gallons per day.</li>
                    </ul>
        </li>
                <li><h4>Other Products</h4>
            <ul>
                <li>Prices for the remaining surveyed products increased for the most part during January.  Propane prices increased at both the retail and wholesale levels, while aviation gasoline and kerosene prices also climbed at wholesale.  Prices for No. 1 distillate remained flat at retail, but increased at the wholesale level.  Kerosene-type jet fuel prices declined at both levels.</li>
                <li>Refiner sales of propane were flat at retail, but fell at wholesale in January.  No. 1 distillate sales increased at both the retail and wholesale levels.  Kerosene-type jet fuel sales declined at retail, but increased at wholesale. Sales of aviation gasoline and kerosene rose at wholesale during January.</li>
            </ul>
        </li>
    </ul>
</div>

<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>