<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2017-05/fig_HL1coppwp2.png" class="lightbox"><img src="images/2017-05/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude oil</h2>
            <ul>Monthly average prices for crude oil increased in February. The average domestic crude oil first purchase price rose $1.22 (2.5%), to $49.41 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil climbed $1.57 (3.5%) to $46.18 per barrel. The average landed cost of foreign crude oil increased $1.01 (2.2%), to $47.90 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil rose $1.06 (2.0%), to $52.87 per barrel. The average cost of imported crude oil increased $1.26 (2.6%), to $49.38 per barrel. The composite refiner acquisition cost for crude oil climbed $1.12 (2.2%), to $51.11 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>Refiner monthly average prices for motor gasoline fell in February. The average retail price decreased 3.8 cents to $1.862 per gallon, while the average wholesale price changed 0.2 cent to $1.625 per gallon.</li>
                <li>Refiner sales of finished motor gasoline climbed in February. Total sales rose 14.4 million gallons per day (4.8%) to an average of 314.5 million gallons per day. Retail sales increased 900,000 gallons per day (3.9%), while wholesales rose 13.5 million gallons per day (4.9%). DTW sales made up 7.7% of wholesales, while rack and bulk sales accounted for 86.2% and 6.1%, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>Monthly average prices for refiner sales of No. 2 distillates show small changes in February. The average price for No. 2 diesel fuel sold to end users rose 0.8 cent to $1.755 per gallon, while the average wholesale price increased 0.5 cent to $1.641 per gallon. The wholesale price for No. 2 fuel oil decreased 0.7 cent to $1.553 per gallon.</li>
                <li>February refiner sales of No. 2 ultra-low sulfur diesel fuel rose 5.7 million gallons per day (4.1%) to 143.9 million gallons per day. While retail sales fell 400,000 gallons per day (3.3%), wholesales climbed 6.1 million gallons per day (4.8%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Refiner monthly average residual fuel oil prices show mixed trends in February. The wholesale price for low-sulfur residual fuel oil rose 7.5 cents to $1.174 per gallon. The price for high-sulfur residual fuel oil fell 0.6 cent to $1.243 per gallon at retail, while the wholesale price decreased 0.4 cent to $1.117 per gallon.</li>
                <li>Overall, sales of residual fuel oil by refiners increased in February. Retail sales rose 500,000 gallons per day (12.8%), while wholesales decreased 400,000 gallons per day (6.1%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>Price trends for refiner sales of remaining surveyed products varied during February. Propane and kerosene-type jet fuel prices increased at both the retail and wholesale levels, while prices for No. 1 distillate rose at retail but fell at wholesale. Prices for aviation gasoline and kerosene fell at the wholesale level.</li>
                <li>Movements in refiner sales of products included in this section were mixed in February. Kerosene-type jet fuel sales increased at both retail and wholesale, while sales No. 1 distillate did just the opposite. Propane sales rose at retail, but fell at wholesale. Sales of aviation gasoline increased at the wholesale level, while kerosene sales declined in the same category.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>*/ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/petroleum/marketing/annual/archive/" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a></li>
    </ul>
</div>