<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong> Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2013-02/fig_HL1coppwp.jpg" class="lightbox"><img src="images/2013-02/fig_HL1_coppwp_sm.jpg" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3>Highlights</h3></li>
                <li><p>The daily spot price for West Texas Intermediate (WTI)crude oil at Cushing, Oklahoma moved within a limitedrange during November. After opening at $86.23 perbarrel, the price dropped to the month's low of $84.50 perbarrel on November 7, pressured by a reported increasein crude oil stocks. Continuing to register only smallchanges through mid-month, the price reached themonth's high of $89.05 per barrel on November19 on avariety of economic and political issues. Showing littlechange during the remainder of the month, the priceclosed November at $88.54 per barrel, $2.31 below itsopening level for the month. Averaging $86.53 per barrelfor the month overall, the price fell $2.96 (3.3 percent)from October's average of $89.49 per barrel. TheNovember 2011 average price was $97.12 per barrel,$10.59 (10.9 percent) higher the current price.  ...</p></li>
                <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>