<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2016-09/fig_HL1coppwp2.png" class="lightbox"><img src="images/2016-09/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude Oil</h2>
            <ul>
                <li>Monthly average crude oil prices increased in June. The average domestic crude oil first purchase price rose $2.94 (7.2%), to $43.96 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil climbed $4.24 (11.1%) to $42.56 per barrel. The average landed cost of foreign crude oil increased $3.25 (8.0%), to $43.87 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil rose $2.78 (6.2%), to $47.55 per barrel. The average cost of imported crude oil climbed $3.24 (8.0%), to $44.13 per barrel. The composite refiner acquisition cost for crude oil increased $3.07 (7.2%), to $45.95 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>Monthly average prices for sales of motor gasoline by refiners rose in June. The average retail price climbed 9.2 cents to $1.961 per gallon, while the average wholesale price rose 3.0 cents to $1.643 per gallon.</li>
                <li>Refiner sales of finished motor gasoline increased in June. Total sales rose 9.8 million gallons per day (3.0%) to an average of 341.6 million gallons per day. Retail sales rose 700,000 gallons per day (2.7%), while wholesales increased 9.1 million gallons per day (3.0%). DTW sales accounted for 7.5% of wholesales, while rack and bulk sales made up 85.2% and 7.3%, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>Monthly average prices for refiner sales of No. 2 distillates increased in June. The average price for No. 2 diesel fuel sold to end users rose 11.0 cents to $1.665 per gallon, while the average wholesale price climbed 9.9 cents to $1.531 per gallon. The average retail price for No. 2 fuel oil increased 12.8 cents to $1.861 per gallon, while the average wholesale price rose 11.3 cents to $1.404 per gallon.</li>
                <li>Refiner sales of No. 2 ultra-low sulfur diesel fuel increased in June. Retail sales remained flat, while wholesales climbed 1.6 million gallons per day (1.1%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Monthly average prices for residual fuel oil sold by refiners increased during June. The wholesale price for low-sulfur residual fuel oil climbed 12.1 cents to 85.0 cents per gallon. Prices for high-sulfur residual fuel oil rose 4.3 cents to 91.1 cents per gallon at retail, while the wholesale price increased 10.1 cents to 82.3 cents per gallon.</li>
                <li>Sales of residual fuel oil by refiners decreased in June. Retail sales fell 100,000 gallons per day (2.6%), while wholesales declined 1.0 million gallons per day (10.1%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>Monthly average prices for refiner sales of the remaining surveyed products were mostly on the rise during June. While prices for propane fell at both retail and wholesale, kerosene-type jet fuel prices increased at both levels. Prices for aviation gasoline, kerosene, No. 1 distillate, and No. 4 distillate rose at wholesale.</li>
                <li>Trends in refiner sales of other products varied in June. Sales of propane and kerosene-type jet fuel rose at retail but fell at wholesale. Aviation gasoline sales increased at the wholesale level, while sales of kerosene, No. 1 distillate, and No. 4 distillate fell in the same category.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div> */ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/petroleum/marketing/annual/archive/" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a></li>
    </ul>
</div>