
<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong> Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2012-06/fig_HL1coppwp.jpg" class="lightbox"><img src="images/2012-06/fig_HL1_coppwp_sm.jpg" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3>Highlights</h3></li>
                <li><p>U.S. gasoline and diesel fuel prices continued to rise at the retail outlet level in March.  Based on data from EIA's weekly retail price surveys, monthly average prices (including taxes) for gasoline and on-highway diesel fuel show the monthly average price for the regular grade of gasoline jumped 27.3 cents (7.6 percent) to $3.852 per gallon at the U.S. level, while the retail on-highway diesel fuel price increased 17.4 cents (4.4 percent) to $4.127 per gallon. ...</p></li>
                <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>
    </ul>
</div>
