<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong> Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2014-03/fig_HL1coppwp.jpg" class="lightbox"><img src="images/2014-03/fig_HL1_coppwp_sm.jpg" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
        <li class="header"><h2>Crude Oil</h2>
            <ul>
                <li>December monthly average crude oil prices rose in most sales categories.  The average domestic crude oil first purchase price increased $3.11 (3.5 percent), to $91.81 per  barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil rose $1.88 (2.1 percent), to $90.37 per barrel.  The average landed cost of foreign crude oil fell 61 cents (0.7 percent), to $88.38 per  barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil climbed $1.85 (1.9 percent), to $97.94 per barrel.  The average cost of imported crude oil increased 21 cents (0.2 percent), to $90.57 per barrel.  The composite refiner acquisition cost for crude oil rose $1.04 (1.1 percent), to $94.36 per  barrel.</li>
            </ul>
        </li>
        <li class="header"><h2>Petroleum Products</h2></li>
                <li><h4>Motor Gasoline</h4>
            <ul>
                <li>The December monthly average price for retail sales of  motor gasoline made by refiners remained flat at $2.759 per gallon, while the average wholesale price increased 4.2 cents to $2.586 per gallon.</li>
                <li>Sales of finished motor gasoline by refiners fell in December.  Total sales declined 12.7 million gallons per day (4.0 percent) to an average of 304.2 million gallons per day.  Retail sales decreased 5.1 million gallons per day (21.5 percent), while wholesales dropped 7.6 million gallons per day (2.6 percent).  DTW sales made up 9.8 percent of wholesales, while rack and bulk sales accounted for 82.4 percent and 7.8 percent, respectively.</li>
                    </ul>
        </li>
                <li><h4>No. 2 Distillate</h4>
            <ul>
                <li>increased in December.  The average sales price for No. 2 diesel fuel to end users rose 2.5 cents to $3.055 per gallon, while the average wholesale price increased 4.9 cents to $2.998 per gallon.  The average wholesale price for No. 2 fuel oil climbed 10.1 cents to $3.011 per gallon.</li>
                <li>Refiner sales of No. 2 diesel fuel sales decreased 9.1 million gallons per day (5.7 percent) in December.  In contrast, sales of No. 2 fuel oil rose 1.3 million gallons per day at the wholesale level.</li>
                    </ul>
        </li>
                <li><h4>Residual Fuel Oil</h4>
            <ul>
                <li>Monthly average prices for residual fuel oil sales by refiners were mixed in December.  The price for low-sulfur residual fuel oil rose 1.9 cents to $2.315 per gallon at the wholesale level.  Prices for high-sulfur residual fuel oil increased 2.5 cents to $2.353 per gallon at retail, but fell 1.4 cents to $2.176 per gallon at  wholesale.</li>
                <li>Sales of residual fuel oil by refiners moved higher in December, with total sales rising 1.6 million gallons per day (12.6 percent).</li>
                    </ul>
        </li>
                <li><h4>Other Products</h4>
            <ul>
                <li>Price trends for the remaining surveyed products varied in December.  Propane, kerosene-type jet fuel, and aviation gasoline prices increased at both the retail and wholesale levels.  Prices for No. 1 distillates fell at retail, but rose at wholesale.  Kerosene and No. 4 distillate prices increased at the wholesale level.</li>
                <li>Refiner  sales of propane and No. 1 distillates increased at both retail and wholesale.  Kerosene-type jet fuel sales rose at the retail level, but fell at wholesale, while aviation gasoline sales decreased at both levels.  Sales of kerosene increased at wholesale, while No. 4 distillates wholesales fell during December.</li>
            </ul>
        </li>
    </ul>
</div>

<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>