<h4 style="margin-bottom:4px">Data Tables
<span style="font-weight:normal">(monthly, 2010-2016)</li>
    <ul>
        <li><a href="/dnav/pet/PET_MOVE_RAILNA_A_EPC0_RAIL_MBBL_M.htm">Movements of crude and select products by rail</a></li>
                <li><a href="/dnav/pet/PET_MOVE_RAIL_A_EPC0_RAIL_MBBL_M.htm">Movements by rail between PAD Districts </a></li>
                <li><a href="/dnav/pet/PET_MOVE_PTB_A_EPC0_TNR_MBBL_M.htm">Movements by pipeline, tanker, barge and rail between PAD Districts</a></li>
                <li><a href="/dnav/pet/PET_MOVE_NETR_A_EPC0_VNR_MBBL_M.htm">Net receipts  by pipeline, tanker, barge and rail between PAD Districts</a></li>
                <li><a href="/petroleum/supply/monthly/pdf/table60.pdf"><i class="ico pdf">PDF</i>Movements of crude oil by pipeline, tanker, barge, and rail between PAD Districts</a> (for current month)</li>
    </ul>
</div><h4 style="margin-bottom:4px">Methodology</li>
    <ul>
        <li><a href="/petroleum/transportation/methodology.pdf"><i class="ico pdf">PDF</i>U.S. energy-by-rail data methodology 6/22/16</a>
</li>
    </ul>
</div><h4 style="margin-bottom:4px">Press Release</li>
    <ul>
        <li><a href="/pressroom/releases/press418.cfm">March 30, 2015</a>
</li>
    </ul>
</div>
<h4 style="margin-bottom:4px">Related Articles</li>
    <ul>
<li style="margin-bottom:6px">        <li><a href="/todayinenergy/detail.php?id=27352">Crude-by-rail volumes to the East Coast are declining</a> - <li class="date">Today in Energy</span>, 8/3/16
<li style="margin-bottom:6px">        <li><a href="/petroleum/weekly/archive/2016/160707/includes/analysis_print.cfm">Crude-by-rail volumes to the East Coast drop as imports rise </a> - <li class="date">This Week in Petroleum</span>, 7/7/16
</li>
<li style="margin-bottom:6px">        <li><a href="/todayinenergy/detail.php?id=26512">Recent data show divergent trends for rail shipments of crude oil, ethanol, and biodiesel</a> - <li class="date">Today in Energy</span>, 6/3/16
<li style="margin-bottom:6px">        <li><a href="/todayinenergy/detail.cfm?id=25332">Crude oil shipments by rail from Midwest to coastal regions decline </a> - <li class="date">Today in Energy</span>, 3/11/16
</li>
<li style="margin-bottom:6px">        <li><a href="/petroleum/weekly/archive/2016/160302/includes/analysis_print.cfm">Rail still moves crude from the Midwest to coastal regions, but in smaller volumes</a> - <li class="date">This Week in Petroleum</span>, 3/2/16
</li>
<li style="margin-bottom:6px">        <li><a href="/todayinenergy/detail.cfm?id=23732">As total U.S. crude oil imports fall, Canada's import supply share rises</a> - <li class="date">Today in Energy</span>, 11/12/15
</li>
<li style="margin-bottom:6px">        <li><a href="/todayinenergy/detail.cfm?id=22432">Rail helps make Midwest a net shipper of crude oil</a> - <li class="date">Today in Energy</span>, 8/10/15
</li>
<li style="margin-bottom:6px">        <li><a href="/todayinenergy/detail.cfm?id=22072">In Rocky Mountain region, increased crude production is being shipped by pipeline, rail </a> - <li class="date">Today in Energy</span>, 7/15/15
</li>
<li style="margin-bottom:6px">        <li><a href="/todayinenergy/detail.cfm?id=21572">Crude by rail provides the West Coast with supply as regional crude oil production falls</a> - <li class="date">Today in Energy</span>, 6/9/15
</li>
<li style="margin-bottom:6px">        <li><a href="/petroleum/weekly/archive/2015/150528/includes/analysis_print.cfm">Crude by rail receipts continue to be an important source of supply for West Coast refiners</a> - <li class="date">This Week in Petroleum</span>, 5/28/15
</li>
<li style="margin-bottom:6px">        <li><a href="/todayinenergy/detail.cfm?id=21092">Crude by rail accounts for more than half of East Coast refinery supply in February</a> - <li class="date">Today in Energy</span>, 5/5/15
</li>
<li style="margin-bottom:6px">        <li><a href="/petroleum/weekly/archive/2015/150401/includes/analysis_print.cfm">New monthly data on crude by rail improves EIA regional petroleum balances</a> - <li class="date">This Week in Petroleum</span>, 4/1/15
</li>
<li style="margin-bottom:6px">        <li><a href="/todayinenergy/detail.cfm?id=20592">New EIA monthly data tracks crude oil movements by rail</a> - <li class="date">Today in Energy</span>, 3/31/15
</li>
<li style="margin-bottom:6px">        <li><a href="/todayinenergy/detail.cfm?id=18791">Rail shipments of oil and petroleum products through October up 13% over year-ago period</a> - <li class="date">Today in Energy</span>, 11/13/14
</li>
<li style="margin-bottom:6px">        <li><a href="/petroleum/weekly/archive/2014/141001/includes/analysis_print.cfm">Crude delivered by rail continues to supply West Coast refineries</a> - <li class="date">This Week in Petroleum</span>, 10/1/14
</li>
<li style="margin-bottom:6px">        <li><a href="/todayinenergy/detail.cfm?id=17751">Rail deliveries of U.S. oil continue to increase in 2014</a> - <li class="date">Today in Energy</span>, 8/28/14</li>
<li style="margin-bottom:6px">        <li><a href="/todayinenergy/detail.cfm?id=16631">Crude-by-rail transportation provides Bakken Shale production access to major markets</a> - <li class="date">Today in Energy</span>, 6/10/14</li>
<li style="margin-bottom:6px">        <li><a href="/petroleum/weekly/archive/2014/140123/twipprint.html">Crude Oil Imports Continue to Decline</a> - <li class="date">This Week in Petroleum</span>, 1/23/14
</li>
<li style="margin-bottom:6px">        <li><a href="/petroleum/weekly/archive/2013/130918/twipprint.html">Rail is Likely Supplying an Increasing Share of East Coast Crude Oil</a> - <li class="date">This Week in Petroleum</span>, 9/18/13
</li>
<li style="margin-bottom:6px">        <li><a href="/todayinenergy/detail.cfm?id=12031">Rail delivery of U.S. oil and petroleum products continues to increase, but pace slows</a> - <li class="date">Today in Energy</span>, 7/10/13</li>
<li style="margin-bottom:6px">        <li><a href="/todayinenergy/detail.cfm?id=9851">Rail traffic reflects more oil production, less coal-fired electricity generation</a> - <li class="date">Today in Energy</span>, 2/5/13</li>
    </ul>
</div>
<?php /*script>
$(document).ready(function() {
if ( $.browser.msie && parseInt($.browser.version, 10)<=8) {
$("a.ico_print").attr('target', '_blank');
}
else {
$("a.ico_print").fancybox({
'type' : 'iframe',
'autoScale' : 'false',
'width' : '980',
'height' : '600',
'hideOnOverlayClick' : 'true'
});
};
});