<span class="grey_side blue_top">
<h4>Most Requested Coal Data</h4>
<p class="no-border"><b><a href="/cneaf/coal/page/acr/table28.html" title="html format: ">Prices</a></b></p>
<ul>
  <li><a href="/cneaf/coal/page/acr/table33.html" title="html format: Average Sales Prices">Average Sales Prices</a></li>
  <li><a class="subcategory" href="/cneaf/coal/page/acr/table34.html" title="html format: Average Delivered Prices">Average Delivered Prices</a> </li>
</ul>
<p class="no-border"><b><a href="/cneaf/coal/quarterly/html/t1p01p1.html" title="html format: ">Production</a></b></p>
<ul>
  <li><a href="/cneaf/coal/page/acr/table1.html" title="html format: Production &amp; Number of Mines">Production &amp; Number of Mines</a> </li>
  <li><a href="/cneaf/coal/page/acr/table21.html" title="html format: Productivity & Employees">Productivity & Employees</a> </li>
</ul>
<p class="no-border"><b><a href="/cneaf/coal/reserves/reserves.html" title="html format: Reserves">Reserves</a></b></p>
<p class="no-border"><b>Consumption</b></p>
<ul>
  <li><a class="subcategory" href="/cneaf/coal/quarterly/html/t32p01p1.pdf" title="html format: Consumption by End-Use Sector">by End-Use Sector</a> </li>
  <li><a class="subcategory" href="/cneaf/coal/page/acr/table26.html" title="html format: by End-Use Sector for Census Division & State">by End-Use  Sector for Census Division & State</a></li>
  <li><a href="/cneaf/coal/quarterly/html/t35p01p1.pdf" title="html format: Consumption at Manufacturing Plants">at Manufacturing Plants</a> </li>
</ul>
<p class="no-border"><b><a href="/cneaf/coal/quarterly/html/t37p01p1.pdf" title="html format: ">Stocks</a></b>
<p class="no-border"><strong>Imports &amp; Exports</strong></p>
<ul>
  <li><a class="subcategory" href="/cneaf/coal/quarterly/html/t18p01p1.pdf" title="html format: Coal Imports">Coal Imports</a></li>
  <li><a class="subcategory" href="/cneaf/coal/quarterly/html/t7p01p1.pdf" title="html format: Coal Exports">Coal Exports</a> </li>
</ul>

</span>
<?php /*
cfinclude template="side_content.cfm"
<span class="dblue_side_top blue_top "><b>Regular Weekly Releases*</b></span>
  <span class="grey_side side_list2">
  <h4>Monday</h4>
  <p class="no-border"><a href="/cneaf/coal/page/nymex/nymex_report.html">Weekly NYMEX Coal Futures&rsaquo;</a></p>
  <p class="no-border"><a href="/cneaf/coal/page/coalnews/coalmar.html">Coal News &amp; Markets &rsaquo;</a></p>
  <br />
  <h4>Thursday</h4>
  <p class="no-border"><a href="/cneaf/coal/weekly/weekly_html/wcppage.html">Weekly Coal Production &rsaquo;</a></p>

  </span>
</span>*/ ?>
