<div class="content-container light-top-border-container grey-background">    <ul>
        <li class="header"><h2>Data Tables</h2></li>
<li class="sub-header">Sales of Fuel Oil and Kerosene</a>
<ul class="square">
        <li><a href="/dnav/pet/pet_cons_821dst_dcu_nus_a.htm">Sales of Distillate Fuel Oil by End Use</a></li>
                <li><a href="/dnav/pet/pet_cons_821rsd_dcu_nus_a.htm">Sales of Residual Fuel Oil by End Use</a></li>
                <li><a href="/dnav/pet/pet_cons_821ker_dcu_nus_a.htm">Sales of Kerosene by End Use</a></li>
                <li><a href="/dnav/pet/pet_cons_821use_dcu_nus_a.htm">Distillate Fuel Oil and Kerosene Sales by End Use</a></li>
    </ul></li>
<li class="sub-header">Adjusted Sales of Fuel Oil and Kerosene</a>
<ul class="square">
        <li><a href="/dnav/pet/pet_cons_821dsta_dcu_nus_a.htm">Adjusted Sales of Distillate Fuel Oil by End Use</a></li>
                <li><a href="/dnav/pet/pet_cons_821rsda_dcu_nus_a.htm">Adjusted Sales of Residual Fuel Oil by End Use</a></li>
                <li><a href="/dnav/pet/pet_cons_821kera_dcu_nus_a.htm">Adjusted Sales of Kerosene by End Use</a></li>
                <li><a href="/dnav/pet/pet_cons_821usea_dcu_nus_a.htm">Adjusted Distillate Fuel Oil and Kerosene Sales by End Use</li>
    </ul></li>
    </ul>
</div>
