<div class="l-row header report-details">
        <div class="l-two-third-column">
        
                <a href="/petroleum/reports.cfm">&lsaquo; See All Petrolem Reports</a>
                <h2><?php echo "$headtitle"?></h2>

                <div class="release-dates">
                        <div class="label-series"><?php echo "$data_series"?></div>
                        <div class="date-container">
                                <div class="label">Release Date:</div>
                                <div class="date"><?php echo "$release"?></div>
                        </div>
                        <div class="date-container">
                                <div class="label">Next Release Date:</div>
                                <div class="date"><?php echo "$next"?></div>
                        </div>
                        </div>
                </div>
        </div>
        <div class="l-one-third-column gradient">
                <span class="form-container-outer">
                        <h4>Previous Issues</h4>
                        <span class="form-container-inner">
                                <form name="form" id="form">
                                        <label>Year:</label>
                                        <select name="jumpMenu" id="jumpMenu">
                                                <option value="/petroleum/fueloilkerosene/archive/2015/foks_2015.cfm" selected="selected">2015</option>
                                                <option value="/petroleum/fueloilkerosene/archive/2014/foks_2014.cfm">2014</option>
                                                <option value="/petroleum/fueloilkerosene/archive/2013/foks_2013.cfm">2013</option>
                                                <option value="/petroleum/fueloilkerosene/archive/2012/foks_2012.cfm">2012</option>
                                                <option value="/petroleum/fueloilkerosene/archive/2011/foks_2011.cfm">2011</option>
                                                <option value="/petroleum/fueloilkerosene/archive/2010/foks_2010.cfm">2010</option>
                                                <option value="/petroleum/fueloilkerosene/archive/2009/foks_2009.html">2009</option>
                                                <option value="/petroleum/fueloilkerosene/archive/2008/foks_2008.html">2008</option>
                                                <option value="/petroleum/fueloilkerosene/archive/2007/foks_2007.html">2007</option>
                                                <option value="/petroleum/fueloilkerosene/archive/2006/foks_2006.html">2006</option>
                                                <option value="/petroleum/fueloilkerosene/archive/2005/foks_2005.html">2005</option>
                                                <option value="/petroleum/fueloilkerosene/archive/2004/foks_2004.html">2004</option>
                                                <option value="/petroleum/fueloilkerosene/archive/2003/foks_2003.html">2003</option>
                                                <option value="/petroleum/fueloilkerosene/archive/2002/foks_2002.html">2002</option>
                                                <option value="/petroleum/fueloilkerosene/archive/2001/foks_2001.html">2001</option>
                                                <option value="/petroleum/fueloilkerosene/archive/2000/foks_2000.html">2000</option>
                                                <option value="/petroleum/fueloilkerosene/archive/1999/foks_1999.html">1999</option>
                                                <option value="/petroleum/fueloilkerosene/archive/1998/foks_1998.html">1998</option>
                                                <option value="/petroleum/fueloilkerosene/archive/1997/foks_1997.html">1997</option>
                                                <option value="/petroleum/fueloilkerosene/archive/1996/foks_1996.html">1996</option>
                                                <option value="/petroleum/fueloilkerosene/archive/1995/foks_1995.html">1995</option>
                                        </select>
                                        <input type="button" name="go_button" class="arrow_go" id="go_button" value="Go" />
                                </form>
                        </span>
                </span>
        </div>
</div>

