<div class="l-row header report-details">
        <div class="l-full-width-column">
                <a href="/petroleum/reports.cfm">&lsaquo; See All Petrolem Reports</a>
                <h2><?php echo $headtitle; ?></h2>

                <div class="release-dates">
                        <                                <div class="date-container">
                                        <div class="label">Data for week ending September 8, 2017</div></div>
                        <div class="date-container">
                                <div class="label">Release Date:</div>
                                <div class="date">September 13, 2017</div>
                        </div>
                        <div class="date-container">
                                <div class="label">Next Release Date:</div>
                                <div class="date">September 20, 2017</div>
                        </div>
                        <div class="report-download-container">
                                <i class="ico pdf">PDF</i><a href="/petroleum/supply/weekly/pdf/wpsrall.pdf">full report</a></div>
                        </div>
                </div>
        </div>
        <div class="l-split-narrow gradient">
                <span class="form-container-outer">
                        <h4>Previous Issues</h4>
                        <span class="form-container-inner">
                                <form name="form" id="form">
                                                <label>Week:</label>
                                        <select name="jumpMenu" id="jumpMenu">
                                                <option value="/petroleum/supply/weekly/archive/2017/2017_09_13/wpsr_2017_09_13.php" selected="selected">September 13, 2017</option>
                                                <option value="/petroleum/supply/weekly/archive/2017/2017_09_07/wpsr_2017_09_07.php">September 7, 2017</option>
                                                <option value="/petroleum/supply/weekly/archive/2017/2017_08_30/wpsr_2017_08_30.php">August 30, 2017</option>
                                                <option value="/petroleum/supply/weekly/archive/2017/2017_08_23/wpsr_2017_08_23.php">August 23, 2017</option>
                                                <option value="/petroleum/supply/weekly/archive/2017/2017_08_16/wpsr_2017_08_16.php">August 16, 2017</option>
                                                <option value="/petroleum/supply/weekly/archive/2017/2017_08_09/wpsr_2017_08_09.php">August 9, 2017</option>
                                                <option value="/petroleum/supply/weekly/archive/2017/2017_08_02/wpsr_2017_08_02.php">August 2, 2017</option>
                                                <option value="/petroleum/supply/weekly/archive/2017/2017_07_26/wpsr_2017_07_26.php">July 26, 2017</option>
                                                <option value="/petroleum/supply/weekly/archive/2017/2017_07_19/wpsr_2017_07_19.php">July 19, 2017</option>
                                                <option value="/petroleum/supply/weekly/archive/2017/2017_07_12/wpsr_2017_07_12.php">July 12, 2017</option>
                                                <option value="/petroleum/supply/weekly/archive/2017/2017_07_06/wpsr_2017_07_06.php">July 6, 2017</option>
                                                <option value="/petroleum/supply/weekly/archive/2017/2017_06_28/wpsr_2017_06_28.php">June 28, 2017</option>
                                                <option value="/petroleum/supply/weekly/archive/2017/2017_06_21/wpsr_2017_06_21.php">June 21, 2017</option>
                                                <option value="/petroleum/supply/weekly/archive/2017/2017_06_14/wpsr_2017_06_14.php">June 14, 2017</option>
                                                <option value="/petroleum/supply/weekly/archive/2017/2017_06_07/wpsr_2017_06_07.php">June 7, 2017</option>
                                                <option value="/petroleum/supply/weekly/archive/2017/2017_06_01/wpsr_2017_06_01.php">June 1, 2017</option>
                                                <option value="/petroleum/supply/weekly/archive/">prior issues</option>
                                        </select>
                                        <input type="button" name="go_button" class="arrow_go" id="go_button" value="Go" />
                                </form>
                        </span>
                </span>
        </div>
</div>
