<div class="content-container"><ul class="resources">
        <li><a href="schedule.php">Release Schedule</a><i class="ico calendar"></i></li>
                <li><a href="/abouteia/privacy_security_policy.cfm">Automated Retrieval Policy</a><i class="ico blank"></i></li>
                <li><a href="/tools/emailupdates/#petroleum">Sign up for email updates</a><i class="ico email"></i></li>
    </ul>
</div>
