<h1>Hurricane Season 2011</h1>
      <p>The National Oceanic and Atmospheric Administration's  (NOAA) <em>Atlantic Hurricane Season Outlook</em>, released on May 19, 2011,  predicts that the Atlantic basin likely will experience above-normal tropical  weather activity during this year's hurricane season  (June 1 &mdash; November 30). NOAA  projects that 12 to 18 named storms will form within the Atlantic Basin over  the next 6 months, including 6 to 10 hurricanes of which 3 to 6 will be  intense.
      </p>
      

      <h1>Historical Distruptions</h1>
      <p><strong>Historical Disruptions</strong><br />
        In previous   years, the U.S. Energy Information Administration has tracked and published the   following special reports of selected significant energy disruption events:      
      <ul>
        <li><a href="/special/disruptions/ike/">Ike</a> &mdash; Landfall September 13, 2008 </li>
        <li><a href="/special/disruptions/gustav/">Gustav</a> &mdash; Landfall September 1,   2008 </li>
        <li><a href="/special/disruptions/rita/">Rita</a> &mdash; Landfall September 23, 2005 </li>
        <li><a href="/special/disruptions/katrina/">Katrina</a> &mdash; August 25, 2005 </li>
      </ul>
      </p>