<span class="grey_side blue_top">
<h4>Additional Resources</h4>
<br />
<p><a href="../disruptions/">Historical/Selected Significant Energy   Disruptions</a>&rsaquo;</p>
<p><a href="/tools/faqs/faq.cfm?id=1&amp;t=10"></a><a href="http://www.gomr.mms.gov/homepg/whatsnew/hurricane/index.html">Department of Interior Hurricane Info</a>&rsaquo;</p>
<p><a href="/tools/faqs/faq.cfm?id=3&amp;t=6"></a><a href="http://www.nhc.noaa.gov/">NOAA National Hurricane Center</a> &rsaquo;</p>
<p><a href="/tools/faqs/faq.cfm?id=21&amp;t=10 "></a><a href="http://www.oe.netl.doe.gov/emergency_sit_rpt.aspx">DOE Emergency   Situation Reports</a> &rsaquo;</p>
<p><a href="/tools/faqs/faq.cfm?id=22&amp;t=10 "></a><a href="/emeu/steo/pub/special/pdf/2010_sp_03.pdf">EIA Hurricane Outlook</a> (pdf) <a href="/tools/faqs/faq.cfm?id=2&amp;t=9"></a> &rsaquo; </p>
</span>
<?php /* Side Column */ ?>
<span class="grey_side blue_top">
<h4>Related State Energy Profiles</h4>
<br />
<p> <a href="/state/state-energy-profiles.cfm?sid=AL">Alabama</a> </p>
<p> <a href="/state/state-energy-profiles.cfm?sid=FL">Florida</a> </p>
<p> <a href="/state/state-energy-profiles.cfm?sid=LA">Louisiana</a> </p>
<p> <a href="/state/state-energy-profiles.cfm?sid=MS">Mississippi</a> </p>
<p> <a href="/state/state-energy-profiles.cfm?sid=TX">Texas</a> </p>
</span>