<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2014-06/fig_HL1coppwp.jpg" class="lightbox"><img src="images/2014-06/fig_HL1_coppwp_sm.jpg" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude Oil</h2>
            <ul>
                <li>Monthly average crude oil prices show a range of changes during March.  The average domestic crude oil first purchase price declined 71 cents (0.7 percent), to $96.18 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil rose $1.02 (1.1 percent), to $93.93 per barrel.  The average landed cost of foreign crude oil decreased 20 cents (0.2 percent), to $94.90 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil increased 28 cents (0.3 percent), to $102.61 per barrel.  The average cost of imported crude oil climbed $1.00 (1.0 percent), to $97.04 per barrel.  The composite refiner acquisition cost for crude oil increased 73 cents (0.7 percent), to $100.05 per barrel.</li>
            </ul>
        </li>
        <li class="header"><h2>Petroleum Products</h2></li>
                <li><h4>Motor Gasoline</h4>
            <ul>
                <li>Monthly average prices sales of motor gasoline made by refiners rose firmly in March.  The average retail price climbed 20.1 cents to $3.114 per gallon, while the average wholesale price increased 15.7 cents to $2.856 per gallon.</li>
                <li>Sales of finished motor gasoline by refiners declined modestly in March.  Total sales decreased 100,000 gallons per day (0.0 percent) to an average of 303.4 million gallons per day.  Retail sales were flat, while wholesales dropped 100,000 gallons per day (0.0 percent).  DTW sales accounted for 8.4 percent of wholesales, while rack and bulk sales made up 83.6 percent and 8.0 percent, respectively.</li>
                    </ul>
        </li>
                <li><h4>No. 2 Distillate</h4>
            <ul>
                <li>March monthly average refiner prices for No. 2 distillates declined from February levels.  The average sales price for No. 2 diesel fuel to end users fell 2.9 cents to $3.110 per gallon, while the average wholesale price decreased 6.0 cents to $3.031 per gallon.  The average price for No. 2 fuel oil sales to end users declined 6.6 cents to $3.621 per gallon, while the average wholesale price for No. 2 fuel oil fell 7.2 cents to $2.979 per gallon.</li>
                <li>Refiner sales of No. 2 ultra-low sulfur diesel fuel increased 1.4 million gallons per day (1.0 percent) to an average of 143.8 million gallons per day in March.  No. 2 fuel oil sales decreased 2.1 million gallons per day (18.8 percent) to an average of 9.1 million gallons per day.</li>
                    </ul>
        </li>
                <li><h4>Residual Fuel Oil</h4>
            <ul>
                <li>Monthly average prices for residual fuel oil sales by refiners show mixed trends in March.  The price for low-sulfur residual fuel oil rose 1.4 cents to $2.473 per gallon at the wholesale level.  Prices for high-sulfur residual fuel oil fell 8.3 cents to $2.376 per gallon at retail, but rose 3.6 cents to $2.175 per gallon at wholesale.</li>
                <li>Sales of residual fuel oil by refiners increased modestly in March, with total sales increasing 300,000 gallons per day (2.2 percent) to an average of 13.7 million gallons per day.</li>
                    </ul>
        </li>
                <li><h4>Other Products</h4>
            <ul>
                <li>Prices for other surveyed products largely decreased during March.  Propane and kerosene-type jet fuel prices fell at both the retail and wholesale levels.  Aviation gasoline prices fell at retail, but increased at wholesale, while prices for No. 1 distillate did just the opposite.  Wholesale prices for kerosene and No. 4 distillate declined during March.</li>
                <li>Refiner sales of propane, kerosene-type jet fuel, and No. 1 distillate declined at both the retail and wholesale levels during March, while aviation gasoline sales increased at both levels.  Sales of kerosene decreased at wholesale, while No. 4 distillate sales increased in the same category.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>*/ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum Administration for Defense District (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a>