<?php /* Sections Promo  */ ?><div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2016-05/fig_HL1coppwp2.png" class="lightbox"><img src="images/2016-05/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude Oil</h2>
            <ul>
                <li>The downward trend for monthly average crude oil prices continued in most categories of sales during February. The average domestic crude oil first purchase price fell $1.51 (5.6%), to $25.51 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil rose 75 cents (3.2%) to $24.28 per barrel. The average landed cost of foreign crude oil declined 84 cents (3.1%), to $25.95 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil fell $1.83 (5.7%), to $30.34 per barrel. The average cost of imported crude oil declined 81 cents (2.9%), to $26.67 per barrel. The composite refiner acquisition cost for crude oil decreased $1.42 (4.7%), to $28.57 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>Monthly average prices for sales of motor gasoline by refiners fell in all sales categories in February. The average retail price declined 17.3 cents to $1.332 per gallon, while the average wholesale price decreased 14.1 cents to $1.046 per gallon.</li>
                <li>Refiner sales of finished motor gasoline increased in February. Total sales rose 10.4 million gallons per day (3.4%) to an average of 320.1 million gallons per day. Retail sales increased 800,000 gallons per day (3.3%), while wholesales climbed 9.6 million gallons per day (3.4%). DTW sales accounted for 7.9% of wholesales, while rack and bulk sales made up 85.6% and 6.5%, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>Monthly average prices for refiner sales of No. 2 distillates fell in most categories of sales during February. The average price for No. 2 diesel fuel sold to end users decreased 1.2 cents to $1.186 per gallon, while the average wholesale price increased 2.8 cents to $1.043 per gallon. The average retail price for No. 2 fuel oil declined 4.3 cents to $1.407 per gallon, while the average wholesale price dropped 2.8 cents to 94.8 cents per gallon.</li>
                <li>Refiner sales of No. 2 ultra-low sulfur diesel fuel rose in February. Retail sales increased 300,000 gallons per day (2.5%), while wholesales climbed 3.0 million gallons per day (2.3%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Monthly average prices for residual fuel oil sales by refiners continued to fall in February. The wholesale price for low-sulfur residual fuel oil dropped 0.2 cent to 47.5 cents per gallon. Prices for high-sulfur residual fuel oil fell 3.3 cents to 60.8 cents per gallon at retail, while the wholesale price decreased 0.4 cent to 49.8 cents per gallon.</li>
                <li>Overall, sales of residual fuel oil by refiners declined in February. Retail sales were flat, while wholesales fell 100,000 gallons per day (1.1%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>The direction of prices for refiner sales of the remaining surveyed products varied in February. Propane prices increased at both retail and wholesale, while prices for kerosene-type jet fuel prices declined at both levels. Wholesale prices for aviation gasoline and kerosene decreased, while the price for No. 1 distillate increased at the wholesale level.</li>
                <li>Data for refiner sales of these products show mixed trends in February. Propane sales fell at both the retail and wholesale levels, while sales of kerosene-type jet fuel sales declined at retail but rose at wholesale. While sales of aviation gasoline increased at the wholesale level, sales of kerosene and No. 1 distillate fell in the same category.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div> */ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/petroleum/marketing/annual/archive/" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a></li>
    </ul>
</div>