<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong> Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2012-08/fig_HL1coppwp.jpg" class="lightbox"><img src="images/2012-08/fig_HL1_coppwp_sm.jpg" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3>Highlights</h3></li>
                <li><p>Monthly sales data show crude oil prices declined considerably during May, as did finished petroleum products prices in most U.S. regional markets.  Prime Supplier sales data show consumption of gasoline and diesel fuel were on the rise in May. ...</p></li>
                <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>