<?php $locale = 'cnm'; ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<?php include ('global/includes/eia_head_info.inc') ; ?>
</head>

<body>
<div id="outerX"><?php /* Outer Wrapper */ ?>
<?php include ('global/includes/eia_header.inc') ; ?>
<?php include ('file:///C|/Documents') ; ?>
<?php /* Page/Body Content */ ?>
    <div class="pagecontent mr_temp5">
      <div class="main_col">
      <?php /* Main Column */ ?>

<table width="560" border="0" align="left" cellpadding="1" cellspacing="1" summary="Table summaries spot coal prices by coal commodity regions (Central Appalachia (CAP), Northern Appalachia (NAP), Illinois Basin  (ILB), Power River Basin (PRB), and Uinta Basin (UIB).  Data are displayed in dollars per short ton.">   
    <tr>
      <td colspan="7" bgcolor="#FFFFFF" class="tabletitle" align="left">Average weekly coal commodity spot prices<br />
      (dollars per short ton)<br /></td>
    </tr>
    <tr>
      <td colspan="7" align="right" bgcolor="#FFFFFF" class="SubSection"><a href="/cneaf/coal/page/coalnews/cnmarchive.html" target="_parent">Previous Coal News and Markets Reports</a></td>
    </tr>
    <tr>
      <th width="71" align="center" class="SectionHead1">Week<br />
        Ended</th>
      <th width="84" align="center" class="SectionHead1">Central <br />
Appalachia<br />
12,500 Btu, <br />
1.2 SO2</th>
      <th width="102" align="center" class="SectionHead1">Northern <br />
        Appalachia<br />
        13,000 Btu, <br />
  &lt;3.0 SO2</th>
      <th width="96" align="center" class="SectionHead1">Illinois Basin<br />
        11,800 Btu, <br />
        5.0 SO2</th>
      <th width="95" align="center" class="SectionHead1">Powder <br />
        River Basin <br />
        8,800 Btu, <br />
        0.8 SO2</th>
      <th width="93" align="center" class="SectionHead1">Uinta Basin<br />
        11,700 Btu, <br />
        0.8 SO2 </th>
     </tr>
 <tr>
    <td class="lightrow" align="left">25-Feb-11</td>
    <td class="lightrow" align="right">$77.70</td>
    <td class="lightrow" align="right">$74.65</td>
    <td class="lightrow" align="right">$47.50</td>
    <td class="lightrow" align="right">$14.10</td>
    <td class="lightrow" align="right">$41.00</td>
  </tr>
 <tr>
    <td class="lightrow" align="left">04-Mar-11</td>
    <td class="lightrow" align="right">$77.70</td>
    <td class="lightrow" align="right">$74.65</td>
    <td class="lightrow" align="right">$47.50</td>
    <td class="lightrow" align="right">$13.95</td>
    <td class="lightrow" align="right">$41.00</td>
  </tr>
 <tr>
    <td class="lightrow" align="left">11-Mar-11</td>
    <td class="lightrow" align="right">$77.70</td>
    <td class="lightrow" align="right">$74.65</td>
    <td class="lightrow" align="right">$47.50</td>
    <td class="lightrow" align="right">$13.85</td>
    <td class="lightrow" align="right">$41.00</td>
  </tr>
 <tr>
    <td class="lightrow" align="left">18-Mar-11</td>
    <td class="lightrow" align="right">$77.70</td>
    <td class="lightrow" align="right">$74.65</td>
    <td class="lightrow" align="right">$47.50</td>
    <td class="lightrow" align="right">$13.65</td>
    <td class="lightrow" align="right">$41.00</td>
  </tr>
 <tr>
    <td class="lightrow" align="left">25-Mar-11</td>
    <td class="lightrow" align="right">$75.20</td>
    <td class="lightrow" align="right">$76.15</td>
    <td class="lightrow" align="right">$47.50</td>
    <td class="lightrow" align="right">$13.45</td>
    <td class="lightrow" align="right">$41.00</td>
  </tr>
 <tr>
    <td class="lightrow" align="left">01-Apr-11</td>
    <td class="lightrow" align="right">$78.85</td>
    <td class="lightrow" align="right">$76.15</td>
    <td class="lightrow" align="right">$47.75</td>
    <td class="lightrow" align="right">$13.25</td>
    <td class="lightrow" align="right">$41.00</td>
  </tr>
 <tr>
    <td class="lightrow" align="left">08-Apr-11</td>
    <td class="lightrow" align="right">$78.85</td>
    <td class="lightrow" align="right">$76.15</td>
    <td class="lightrow" align="right">$47.75</td>
    <td class="lightrow" align="right">$12.75</td>
    <td class="lightrow" align="right">$41.00</td>
  </tr>
   <tr class="footnotes" align="left" >
      <td colspan="7">
      <sup>1</sup>Coal prices shown are for a relatively high-Btu coal selected in each region, for delivery in the "prompt quarter.” The prompt quarter is the quarter following the current quarter. For example, from January through March, the 2nd quarter is the prompt quarter. Starting on April 1, July through September define the prompt quarter.<br>
<strong>Source:</strong> With permission, selected prices in Platts Coal Outlook, &quot;Weekly Price Survey.&quot; <br>
<strong>Note:</strong> The historical data file  of spot prices is proprietary and cannot be released  by EIA; see <a href="http://www.platts.com/InsightandAnalysis/Coal/" target="_blank" title="This will take you to another site. You are leaving EIA's website.">Coal News  and Prices</a>.</td>
      </tr>
</table>

</body>
</html>
