        <?php $what = 'coal'; ?>
        <?php include ('about/new/whatsnew_sitewide.php') ; ?>
       <?php /* Weekly Releases */ ?>
         <span class="grey_side blue_top">
        <h4>Regular Weekly Releases*</h4>
        <p><a href="/cneaf/coal/page/nymex/nymex_report.html">Weekly NYMEX Coal Futures &rsaquo;</a><br />
           <i>10:30 a.m. ET, Monday</i>
      <p><a href="/cneaf/coal/page/coalnews/coalmar.html">Coal News & Markets &rsaquo;</a><br />
           <i>5:00 p.m. ET, Monday</i>
        <p><a href="/cneaf/coal/weekly/weekly_html/wcppage.html">Weekly Coal Production &rsaquo;</a><br />
           <i>5:30 p.m. ET, Thursday</i>
            
         
        <p class="no-border"><i>*No releases: Tuesday, Wednesday or Friday. Releases change on weeks with Federal holidays.</i></p>
       
        </span> 
           <?php /* Survey */ ?>
         <span class="grey_side blue_top">
      <h4>Survey Forms, Changes & Announcements</h4>
            <p><a href="/cneaf/coal/page/coalforms.html">Coal survey forms &rsaquo;</a> </p>
          <?php /*  <p><a href="/cneaf/coal/page/surveys/coal_survey_auth.html">Coal survey authorization 2011-14 &rsaquo;</a></p>
       <p><a href="/cneaf/coal/page/schedule/product_description.html">Coal data & analysis products: descriptions & schedules &rsaquo;</a> </p> */ ?>
          </span>
       <span class="grey_side green_top">
            <h4>Coal Maps</h4>
            <p><a href="/energyexplained/index.cfm?page=coal_where">Coal Production by Coal-Producing Region, 2010</a></p>
          <p><a href="/energyexplained/index.cfm?page=coal_where"><img src="/coal/images/coal_regions_2009.jpg" ></a><br/><br/><a href="/maps#coal">See more coal maps &rsaquo;</a></p>
          </span>
        <?php /* FAQ Promo */ ?>
        <span class="blue_side">
          <h4 class="q_side"><a href="/tools/faqs/faq.cfm?id=69&t=2">Which States produce the most coal? &rsaquo;</a></h4>
          <p><a href="/tools/faqs/#coal">See all coal FAQs  &rsaquo;</a></p>
        </span>
         <?php /* Energy Explained Promo */ ?>
        
        <p><a href="/energyexplained/index.cfm?page=coal_home"><img src="/energyexplained/images/section-banners/coal.jpg" alt="Energy Explained - Coal" width="240" /></a></p>
        <?php /* Kids Promo */ ?>
        <p><a href="/kids/energy.cfm?page=coal_home-basics"><img src="/global/images/kids_promos/default.png" width="240" height="142" alt="Energy Kids" /></a></p>