<span class="grey_side blue_top">
<h4>Additional Resources</h4>
<p><a href="http://www.nhc.noaa.gov/refresh/graphics_at3+shtml/092341.shtml?gm_psurge#contents">NOAA Storm Surge Probabilities &rsaquo;</a></p>
<p><a href="http://onthemap.ces.census.gov/em.html">Census Emergency Map &rsaquo;</a></p>
<p><a href="/special/disruptions/">Historical/Selected Significant Energy Disruptions &rsaquo;</a></p>
<p><a href="http://www.bsee.gov/BSEE-Newsroom/Hurricanes/2012/Current-Season.aspx">Bureau of Safety and Environmental Enforcement &rsaquo;</a></p>
<p><a href="http://www.oe.netl.doe.gov/emergency_sit_rpt.aspx">DOE Emergency   Situation Reports &rsaquo;</a></p>
<p><a href="/outlooks/steo/special/pdf/2012_sp_01.pdf">EIA Hurricane Outlook (pdf) &rsaquo;</a></p>
<p class="no-border"><a href="http://www.nhc.noaa.gov/">NOAA National Hurricane Center &rsaquo;</a></p>

</span>
<?php /* Side Column */ ?>
