<?php $locale = 'spot_hist'; ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<?php include ('global/includes/eia_head_info.inc') ; ?>
</head>

<body>
<div id="outerX"><?php /* Outer Wrapper */ ?>
<?php include ('global/includes/eia_header.inc') ; ?>
<?php include ('../coal/includes/subnav_coal_cnm.inc') ; ?>
<?php /* Page/Body Content */ ?>
    <div class="pagecontent mr_temp5">
      <div class="main_col">
      <?php /* Main Column */ ?>
      
        <h2>The U.S. Energy Information Administration (EIA) collects, analyzes, and   disseminates independent and impartial energy information to promote sound policymaking, efficient markets, and public understanding of energy and its interaction with the economy and the environment.</h2>
        <div class="about_imgs">
          <p><img src="/global/images/photos/ourwork.jpg" /></p>
        </div>
        <div class="about_desc left">
          <p>
          <h2>Our Work</h2>
          </p>
          <p>EIA provides a wide range of information and data products covering energy production, stocks, demand, imports, exports, and prices; and prepares analyses and special reports on topics of current interest.</p>
          <ul class="split_2columns no_bullets">
            <li><a href="mission_overview.cfm">Mission & Overview &rsaquo;</a></li>
            <li><a href="products_services.cfm">Product & Services &rsaquo;</a></li>
            <li><a href="stakeholders.cfm">Customer & Stakeholder<br/> Engagement &rsaquo;</a></li>
          </ul>
        </div>
        <hr />
        <div class="about_imgs">
          <p><img src="/global/images/photos/org_chart_small.jpg" /></p>
        </div>
        <div class="about_desc left">
          <p><h2>Our Organization</h2></p>
          <p>EIA has four Assistant Administrators directing program functions for energy statistics, energy analysis, communications, and resource and technology management.</p>
          <ul class="split_2columns no_bullets">
            <li><a href="eia_offices.cfm">EIA Offices &rsaquo;</a></li>
            <li><a href="organization_chart.cfm">Organization Chart &rsaquo;</a></li>
            <li><a href="senior_executive_bios.cfm">Senior Executive Biographies &rsaquo;</a></li>
          </ul>
        </div>
        <hr />
        <div class="about_imgs">
          <p><img src="/global/images/photos/ourbudget_thumb.jpg" /></p>
        </div>
        <div class="about_desc left">
          <p><h2>Budget, Plans & Performance</h2></p>
          <p>EIA receives funding for its activities with an annual appropriation from the Congress. Find out about our current and requested budgets, how we measure performance, how to do business with us, and the changes we are planning for the next five years.</p>
          <ul class="split_2columns no_bullets">
            <li><a href="budget_performance.cfm">Budget & Performance &rsaquo;</a></li>
            <li><a href="strategic_plan.cfm">Strategic Plan &rsaquo;</a></li>
          </ul>
        </div>

        <hr />
        <div class="about_imgs">
          <p><img src="/global/images/photos/careers.jpg" /></p>
        </div>
        <div class="about_desc left">
          <p><h2>Careers at EIA</h2></p>
          <p>Explore the Careers section of our website to learn more about what it takes to join our team of professionals as either a full-time employee or an intern, as well as the benefits of working with us.</p>
          <ul class="split_2columns no_bullets">
            <li><a href="/about/careers/index.cfm#current_jobs">Current Job Openings &rsaquo;</a></li>	
            <li><a href="/about/careers/benefits.cfm#jobs">Benefits &rsaquo;</a></li>	
            <li><a href="/about/careers/whyichose.cfm">Why I Chose EIA &rsaquo;</a></li>	
            <li><a href="/about/careers/internships.cfm">Internships &rsaquo;</a></li>	
            <li><a href="/about/careers/tips.cfm">Application Tips and Contacts &rsaquo;</a></li>	
          </ul>
        </div>

        <hr />
        <div class="about_imgs">
          <p><img src="/global/images/photos/ourhistory.jpg" /></p>
        </div>
        <div class="about_desc left">
          <p><h2>Our History</h2></p>
          <p>EIA celebrated its 30th anniversary in April 2008. Watch our short EIA documentary video, learn more about the legislation that has shaped the agency, and review our past six Administrators.</p>
          <ul class="split_2columns no_bullets">
          <li><a href="/conf_videos/video/video.html">EIA Documentary (video)&rsaquo;</a></li>	
          <li><a href="previous_administrators.cfm">Previous Administrators &rsaquo;</a></li>	
          <li><a href="legislative_timeline.cfm">Legislative Timeline &rsaquo;</a></li>	
          </ul>
        </div>

        <hr />
        <div class="about_imgs">
          <p><img src="/global/images/photos/policies_procedures.jpg" /></p>
        </div>
        <div class="about_desc left">
          <p><h2>Policies & Procedures</h2></p>
          <p>EIA is your trusted source for reliable energy information. Read more about our information quality guidelines, Freedom of Information Act procedures, copyright and reuse policies, privacy and security policy, and other standards.</p>
          <ul class="split_2columns no_bullets">
<li><a href="/abouteia/information_quality_guidelines.cfm">Information Quality Guidelines&rsaquo;</a></li>	
<li><a href="/abouteia/eia_standards.cfm">EIA Standards Manual &rsaquo;</a></li>	
<li><a href="/abouteia/accessability.cfm">Accessibility &rsaquo;</a></li>	
<li><a href="/abouteia/copyrights_reuse.cfm">Copyrights and Reuse &rsaquo;</a></li>	
<li><a href="/abouteia/foia.cfm">Freedom of Information Act &rsaquo;</a></li>	
<li><a href="/abouteia/privacy_security_policy.cfm">Privacy Statement and Security Policy  &rsaquo;</a></li>	
<li><a href="/abouteia/publishing_priorities_schedule.cfm">Publishing Priorities and Schedule &rsaquo;</a></li>	
<li><a href="/abouteia/cipsea_reporting.cfm">CIPSEA Reporting &rsaquo;</a></li>          </ul>
        </div>

        <hr />  
        <div class="about_imgs">
          <p><img src="images/homepage-crop-150x99.jpg" /></p>
        </div>
        <div class="about_desc left">
          <p>
          <h2>Our Website</h2></p>
          <p>Learn more about <a href="www.eia.gov">EIA.gov</a>, which serves as EIA's primary communication channel and world-wide energy information point of contact.</p>
          <ul class="split_2columns no_bullets">
            <li><a href="eia_explained.cfm">About EIA.gov &rsaquo;</a></li>
            <li><a href="recruit.cfm">Help Improve Our Site &rsaquo;</a></li>
          </ul>
        </div>
        
        
      <?php /* Main Column */ ?>
      </div>
      <div class="side_col left">
		<?php /* Side Column */ ?>
		  <?php include ('includes/sidenav_about.inc') ; ?>
        <?php /* Side Column */ ?>
      </div>
    </div>
<?php /*/ Page/Body Content */ ?>
<?php include ('global/includes/eia_footer.inc') ; ?>
</div><?php /*/ Outer Wrapper */ ?>
</body>
</html>