<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2017-06/fig_HL1coppwp2.png" class="lightbox"><img src="images/2017-06/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude oil</h2>
            <ul>March monthly average crude oil prices declined from February levels. The average domestic crude oil first purchase price fell $3.02 (6.1%), to $46.39 per barrel.</li>
                <li>·	The average free-on-board (f.o.b.) cost of imported crude oil decreased $2.06 (4.5%) to $43.91 per barrel. The average landed cost of foreign crude oil declined $2.45 (5.1%), to $45.65 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil fell $2.54 (4.8%), to $50.61 per barrel. The average cost of imported crude oil decreased $2.80 (5.7%), to $46.58 per barrel. The composite refiner acquisition cost for crude oil dropped $2.54 (5.0%), to $48.70 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>Refiner monthly average prices for motor gasoline rose in March. The average retail price increased 4.2 cents to $1.904 per gallon, while the average wholesale price rose 0.9 cent to $1.634 per gallon.</li>
                <li>Refiner sales of finished motor gasoline continued to increase in March. Total sales climbed 7.8 million gallons per day (2.5%) to an average of 321.3 million gallons per day. Retail sales increased 700,000 gallons per day (2.9%), while wholesales rose 7.1 million gallons per day (2.5%). DTW sales made up 7.7% of wholesales, while rack and bulk sales accounted for 87.6% and 4.6%, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>March monthly average prices for refiner sales of No. 2 distillates show a decrease from February levels. The average price for No. 2 diesel fuel sold to end users fell 5.6 cents to $1.699 per gallon, while the average wholesale price declined 6.0 cents to $1.581 per gallon. The average retail price for No. fuel oil dropped 12.4 cents to $1.909, while the average wholesale price for No. 2 fuel oil decreased 5.8 cents to $1.495 per gallon.</li>
                <li>March refiner sales of No. 2 ultra-low sulfur diesel fuel climbed 2.8 million gallons per day (2.0%) to 145.5 million gallons per day. Retail sales rose 800,000 gallons per day (6.9%), wholesales increased 2.0 million gallons per day (1.5%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Refiner monthly average residual fuel oil prices were on the decline in March. The wholesale price for low-sulfur residual fuel oil fell 7.1 cents to $1.103 per gallon. The price for high-sulfur residual fuel oil decreased 5.7 cents to $1.186 per gallon at retail, while the wholesale price declined 4.1 cents to $1.074 per gallon.</li>
                <li>Sales of residual fuel oil by refiners decreased to 10.4 million gallons per day (0.2%) in March. Retail sales rose 200,000 gallons per day (4.5%), while wholesales decreased 400,000 gallons per day (6.5%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>March prices for refiner sales of the remaining surveyed products mostly show decreases from February levels. Propane, kerosene-type jet fuel, and No. 1 distillate prices fell at both the retail and wholesale levels. The price for aviation gasoline increased at wholesale, while the price for kerosene declined in the same category.</li>
                <li>Refiner sales of products included in this section show mixed trends in March. Propane and No. 1 distillate sales fell at both the retail and wholesale levels, while kerosene-type jet fuel sales rose at retail but declined at wholesale. Sales of aviation gasoline increased at the wholesale level, while kerosene sales fell in the same sales category.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>*/ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/petroleum/marketing/annual/archive/" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a></li>
    </ul>
</div>