<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong> Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2013-12/fig_HL1coppwp.jpg" class="lightbox"><img src="images/2013-12/fig_HL1_coppwp_sm.jpg" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3>Highlights</h3></li>
        <li class="header"><h2>Crude Oil</h2>
            <ul>
                <li>September monthly average prices for crude oil show modest declines from August levels.  The average domestic crude oil first purchase price fell 69 cents (0.7 percent), to $102.45 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil dropped 5 cents (0.0 percent), to $101.99 per barrel.  The average landed cost of foreign crude oil decreased $1.08 (1.0 percent), to $102.19 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil fell 34 cents (0.3 percent), to $107.96 per barrel.  The average cost of imported crude oil decreased 67 cents (0.6 percent), to $103.49 per barrel.  The composite refiner acquisition cost for crude oil dropped 50 cents  (0.5 percent), to $105.70 per barrel.</li>
            </ul>
        </li>
        <li class="header"><h2>Petroleum Products</h2></li>
                <li><h4>Motor Gasoline</h4>
            <ul>
                <li>Monthly average prices for sales of finished gasoline by refiners continued to fall during September.  The average retail sales price for motor gasoline decreased 3.9 cents to $3.058 per gallon, while the average wholesale price declined 9.8 cents to $2.792 per gallon.</li>
                <li>Refiner sales of finished motor gasoline decreased in September.  Total sales fell 11.7  million gallons per day (3.6 percent) to an average of 312.8 million gallons per day.  Retail sales declined 800,000 gallons per day (3.3 percent), while wholesales fell 10.9 million gallons per day (3.6 percent).  DTW sales accounted for 10.0 percent of wholesales, while rack and bulk sales made up 82.0 percent and 8.0 percent, respectively.       </li>
                    </ul>
        </li>
                <li><h4>No. 2 Distillate</h4>
            <ul>
                <li>Monthly average refiner prices for No. 2 distillates increased in September.  The average sales price for No. 2 diesel fuel to end users rose 1.2 cents to $3.181 per gallon, while the average wholesale price increased 1.1 cents to $3.095 per gallon.  The average price for No. 2 fuel oil sales to end users rose 1.3 cents to $3.327 per gallon, while the average wholesale price climbed 1.9 cents to $2.973 per gallon.</li>
                <li>Sales of No. 2 distillates by refiners were generally on the decline during September.  Overall, sales fell 3.8 million gallons per day (2.3 percent), to 160.5 million gallons per day.  No. 2 fuel oil sales rose 700,000 gallons per day (13.6 percent), while sales of No. 2 diesel fuel declined 4.5 million gallons per day (2.8 percent).</li>
                    </ul>
        </li>
                <li><h4>Residual Fuel Oil</h4>
            <ul>
                <li>Monthly average prices for refiner residual fuel oil sales increased in September.  Prices for low-sulfur residual fuel oil rose 8.0 cents to $2.839 per gallon at retail, and 2.8 cents to $2.359 per gallon at wholesale.  Prices for high-sulfur residual fuel oil inched up 0.1 cent to $2.412 per gallon at retail, and 0.7 cent to $2.265 per gallon at wholesale.</li>
                <li>Sales of residual fuel oil by refiners fell in September.  Total sales decreased 2.1 million gallons per day (14.5 percent).  Low-sulfur residual fuel oil sales declined 800,000 gallons per day (21.6 percent) while high-sulfur residual fuel oil sales fell 1.2 million gallons per day (11.1 percent).</li>
                    </ul>
        </li>
                <li><h4>Other Products</h4>
            <ul>
                <li>Price trends for the remaining surveyed products varied in September.  Prices for propane, kerosene-type jet fuel, kerosene, and No. 1 distillate increased at both retail and wholesale.  Aviation gasoline prices fell at both levels.  The price for No. 4 fuel oil decreased at the wholesale level.</li>
                <li>Refiner sales of propane and No. 1 distillate increased at both retail and wholesale, while kerosene-type jet fuel sales show the opposite trend.  Aviation gasoline sales climbed at retail, but fell at wholesale, while sales of kerosene rose at the retail level, but remained flat at wholesale.  Sales of No. 4 distillate increased at wholesale.</li>
            </ul>
        </li>
    </ul>
</div>

<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>