<!--[if lt IE 8]><link rel="stylesheet" href="styles/ie.css" type="text/css" media="screen, projection">
<![endif]-->
<!--begin content -->
<div class="tie">
<h2>
<span class="tie_date right">Posted March 21, 2016</span>Today in Energy</h2>
</div>
<div class="white_box no-border">
<!--<div class="tie_correction">         <li>
</p>
</div>-->
<h3>
<a href="/todayinenergy/detail.cfm?id=25452">
<strong>As coal stockpiles at power plants rise, shippers are reducing coal railcar loadings</strong>&nbsp;&rsaquo;</a>
</h3>
<li>Coal stockpiles at electric generating facilities totaled 197 million tons at the end of 2015, the highest level since June 2012 and the highest year-end inventories in at least 25 years. More than 40 million tons of coal were added to stockpiles at electric generating facilities from September-December, the largest build during that timespan in at least 15 years. In addition to relatively low overall electricity generation, coal-fired electricity has recently been losing market share to natural gas and renewable generation.  <a href="/todayinenergy/detail.cfm?id=25452">
<strong>More</strong>&rsaquo;</a> </p>
<a href="/todayinenergy/detail.cfm?id=25452" border="0">
<img src="/todayinenergy/images/2016.03.21/feature_p1.png" alt="">
</a>
<br clear="all">
<p style="font-size:11px;color:#999; line-height:1em;" id="TIEp1source">
<strong>Source: </strong>EIA,  <span class="date">Electric Power Monthly</span>, and Association of American Railroads
</span>
</p>
