<div class="l-row header report-details">
        <div class="l-split-wide">
        
                <a href="/petroleum/reports.cfm">&lsaquo; See All Petroleum & Other Liquids Reports</a>
                <h2><?php echo "$headtitle"?></h2>

                <div class="release-dates">
                        <div class="label-series"><?php echo "$data_series"?></div>
                        <div class="date-container">
                                <div class="label">Release Date:</div>
                                <div class="date"><?php echo "$release"?></div>
                        </div>
                        <div class="date-container">
                                <div class="label">Re-Release Dates:</div>
                                <div class="date">September 13, 2017</div>
                        </div>
                        <div class="date-container">
                                <div class="label">Next Release Date:</div>
                                <div class="date"><?php echo "$next"?></div>
                        </div>
                </div>
        </div>
        <div class="l-split-narrow gradient">
                <span class="form-wrapper-outer">
                        <h4>Previous Issues</h4>
                        <span class="form-wrapper-inner">
                                <form name="form" id="form">
                                        <label>Year:</label>
                                        <select name="jumpMenu" id="jumpMenu">
                                                <option value="/petroleum/supply/annual/volume1/archive/2015/psa_volume1_2015.cfm" selected="selected">2015</option>
                                                <option value="/petroleum/supply/annual/volume1/archive/2014/psa_volume1_2014.cfm">2014</option>
                                                <option value="/petroleum/supply/annual/volume1/archive/2013/psa_volume1_2013.cfm">2013</option>
                                                <option value="/petroleum/supply/annual/volume1/archive/2012/psa_volume1_2012.cfm">2012</option>
                                                <option value="/petroleum/supply/annual/volume1/archive/2011/psa_volume1_2011.cfm">2011</option>
                                                <option value="/petroleum/supply/annual/volume1/archive/2010/psa_volume1_2010.cfm">2010</option>
                                                <option value="/petroleum/supply/annual/volume1/archive/2009/psa_volume1_2009.html">2009</option>
                                                <option value="/petroleum/supply/annual/volume1/archive/2008/psa_volume1_2008.html">2008</option>
                                                <option value="/petroleum/supply/annual/volume1/archive/2007/psa_volume1_2007.html">2007</option>
                                                <option value="/petroleum/supply/annual/volume1/archive/2006/psa_volume1_2006.html">2006</option>
                                                <option value="/petroleum/supply/annual/volume1/archive/2005/psa_volume1_2005.html">2005</option>
                                                <option value="/petroleum/supply/annual/volume1/archive/2004/psa_volume1_2004.html">2004</option>
                                                <option value="/petroleum/supply/annual/volume1/archive/2003/psa_volume1_2003.html">2003</option>
                                                <option value="/petroleum/supply/annual/volume1/archive/2002/psa_volume1_2002.html">2002</option>
                                                <option value="/petroleum/supply/annual/volume1/archive/2001/psa_volume1_2001.html">2001</option>
                                                <option value="/petroleum/supply/annual/volume1/archive/2000/psa_volume1_2000.html">2000</option>
                                                <option value="/petroleum/supply/annual/volume1/archive/1999/psa_volume1_1999.html">1999</option>
                                                <option value="/petroleum/supply/annual/volume1/archive/1998/psa_volume1_1998.html">1998</option>
                                                <option value="/petroleum/supply/annual/volume1/archive/1997/psa_volume1_1997.html">1997</option>
                                                <option value="/petroleum/supply/annual/volume1/archive/1996/psa_volume1_1996.html">1996</option>
                                                <option value="/petroleum/supply/annual/volume1/archive/1995/psa_volume1_1995.html">1995</option>
                                        </select>
                                        <input type="button" name="go_button" class="arrow_go" id="go_button" value="Go" />
                                </form>
                        </span>
                </span>
        </div>
</div>

