<div class="l-row header report-details">
        <div class="l-split-wide">
</div>
<div class="l-split-narrow gradient">
                <span class="form-container-outer">
                        <h4>Previous Issues</h4>
                        <span class="form-container-inner">
                                <form name="form" id="form">
                                        <label>Month:</label>
<select name="jumpMenu" size="1" id="jumpMenu">
                                                <option value="/">prior issues</option>
                                        </select>
                                        <input type="button" name="go_button" class="arrow_go" id="go_button" value="Go" />
                                </form>
</span>
</span>
</div>
