<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2015-09/fig_HL1coppwp2.png" class="lightbox"><img src="images/2015-09/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude Oil</h2>
            <ul>
                <li>Monthly average crude oil prices continued to rise in June.  The average domestic crude oil first purchase price increased $1.50 (2.8%), to $55.88 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil rose $1.37 (2.6%) to $55.08 per barrel.  The average landed cost of foreign crude oil increased 49 cents (0.9%), to $57.43 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil climbed $1.68 (2.8%), to $61.07 per barrel.  The average cost of imported crude oil rose $1.31 (2.3%), to $58.97 per barrel.  The composite refiner acquisition cost for crude oil increased $1.49 (2.5%), to $60.15 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>Refiner monthly average prices for sales of motor gasoline rose in June.  The average retail price increased 5.2 cents to $2.374 per gallon, while the average wholesale price rose 4.1 cents to $2.121 per gallon.</li>
                <li>Refiner sales of finished motor gasoline increased in June.  Total sales rose 5.7 million gallons per day (1.7%) to an average of 331.6 million gallons per day.  Retail sales increased 100,000 gallons per day (0.4%), while wholesales climbed 5.6 million gallons per day (1.9%).  DTW sales accounted for 7.6% of wholesales, while rack and bulk sales made up 85.8% and 6.6%, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>Monthly average prices for sales of No. 2 distillates by refiners mostly declined in June.  The average sales price for No. 2 diesel fuel to end users fell 7.1 cents to $2.019 per gallon, while the average wholesale price decreased 9.2 cents to $1.881 per gallon.  The average sales price for No. 2 fuel oil to end users rose 1.3 cents to $2.321 per gallon, while the average wholesale price for No. 2 fuel oil declined 3.9 cents to $1.813 per gallon.</li>
                <li>Refiner sales of No. 2 ultra-low sulfur diesel fuel increased in June.  Retail sales rose 1.0 million gallons per day (8.8%), while wholesales climbed 11.1 million gallons per day (7.9%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Refiner monthly average prices for residual fuel oil show mixed trends in June.  The wholesale price for low-sulfur residual fuel oil decreased 2.3 cents to $1.175 per gallon.  Prices for high-sulfur residual fuel oil rose 3.1 cents to $1.474 per gallon at retail, while the wholesale price dropped 0.3 cent to $1.239 per gallon.</li>
                <li>Total sales of residual fuel oil by refiners rose during June.  Retail sales increased 700,000 gallons per day (17.9%), while wholesales climbed 900,000 gallons per day (11.3%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>Prices for the remaining surveyed products declined for the most part in June.  Propane and kerosene-type jet fuel prices fell at both retail and wholesale.  Prices for kerosene and No. 1 distillate fell at the wholesale level, while aviation gasoline and No. 4 distillate prices increased at wholesale.</li>
                <li>During June, refiner sales of propane fell at retail, but rose at wholesale, while sales of kerosene-type jet fuel increased at both levels.  Kerosene, No. 1 distillate, and No. 4 distillate sales decreased at wholesale, while sales of aviation gasoline increased in the same category.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>*/ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/petroleum/marketing/annual/archive/" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a></li>
    </ul>
</div>