<div class="content-container light-top-border-container grey-background">    <ul>
        <li><i class="ico pdf">PDF</i><a href="pdf/ndaa.pdf">Full report</a></li>
        <li class="header"><h2>Previous Issues</h2></li>
                <li><i class="ico pdf">PDF</i><a href="../ndaa/archive/pdf/ndaa_dec_20_2013.pdf">12-20-2013</a></li>
                <li><i class="ico pdf">PDF</i><a href="../ndaa/archive/pdf/ndaa_oct_31_2013.pdf">10-31-2013</a></li>
                <li><i class="ico pdf">PDF</i><a href="../ndaa/archive/pdf/ndaa_aug_29_2013.pdf">8-29-2013</a></li>
                <li><i class="ico pdf">PDF</i><a href="../ndaa/archive/pdf/ndaa_jun_27_2013.pdf">6-27-2013</a></li>
                <li><i class="ico pdf">PDF</i><a href="../ndaa/archive/pdf/ndaa_apr_25_2013.pdf">4-25-2013</a></li>
                <li><i class="ico pdf">PDF</i><a href="../ndaa/archive/pdf/ndaa_feb_28_2013.pdf">2-28-2013</a></li>
                <li><i class="ico pdf">PDF</i><a href="../ndaa/archive/pdf/ndaa_dec_20_2012.pdf">12-20-2012</a></li>
                <li><i class="ico pdf">PDF</i><a href="../ndaa/archive/pdf/ndaa_oct_25_2012.pdf">10-25-2012</a></li>
                <li><i class="ico pdf">PDF</i><a href="../ndaa/archive/pdf/ndaa_aug_24_2012.pdf">8-24-2012</a></li>
                <li><i class="ico pdf">PDF</i><a href="../ndaa/archive/pdf/ndaa_jun_26_2012.pdf">6-26-2012</a></li>
                <li><i class="ico pdf">PDF</i><a href="../ndaa/archive/pdf/ndaa_apr_27_2012.pdf">4-27-2012</a></li>
                <li><i class="ico pdf">PDF</i><a href="../ndaa/archive/pdf/ndaa_feb_29_2012.pdf">2-29-2012</a></li>
    </ul>
</div>
