<div class="content-container light-top-border-container grey-background">    <ul>
        <li><i class="ico pdf">PDF</i><a href="pdf/refinery_outage.pdf">Full report</a></li>
        <li class="header"><h2>Previous Issues</h2></li>
                <li><i class="ico pdf">PDF</i><a href="/petroleum/refinery/outage/archive/pdf/outage_nov2016.pdf">Fall 2016 (November 2016)</a></li>
                <li><i class="ico pdf">PDF</i><a href="/petroleum/refinery/outage/archive/pdf/outage_mar2016.pdf">First Half of 2016 (March 2016)</a></li>
                <li><i class="ico pdf">PDF</i><a href="/petroleum/refinery/outage/archive/pdf/outage_oct2015.pdf">Fourth-Quarter (October 2015)</a></li>
                <li><i class="ico pdf">PDF</i><a href="/petroleum/refinery/outage/archive/pdf/outage_feb2015.pdf">First Half of 2015 (February 2015)</a></li>
                <li><i class="ico pdf">PDF</i><a href="/petroleum/refinery/outage/archive/pdf/outage_nov2014.pdf">Fall 2014 (November 2014)</a></li>
                <li><i class="ico pdf">PDF</i><a href="/petroleum/refinery/outage/archive/pdf/outage_feb2014.pdf">First Half of 2014 (February 2014)</a></li>
                <li><i class="ico pdf">PDF</i><a href="/petroleum/refinery/outage/archive/pdf/outage2011a.pdf">March 2011 through June 2011 (April 2011)</a></li>
                <li><i class="ico pdf">PDF</i><a href="/petroleum/refinery/outage/archive/pdf/outage2010b.pdf">October 2010 through January 2011(November 2010)</a></li>
    </ul>
