<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2015-10/fig_HL1coppwp2.png" class="lightbox"><img src="images/2015-10/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude Oil</h2>
            <ul>
                <li>July monthly average crude oil prices declined in all sales categories.  The average domestic crude oil first purchase price fell $8.18 (14.6%), to $47.70 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil decreased $5.60 (10.4%) to $47.99 per barrel.  The average landed cost of foreign crude oil fell $5.87 (10.3%), to $51.07 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil decline $6.89 (11.3%), to $54.17 per barrel.  The average cost of imported crude oil fell $6.43 (10.9%), to $52.47 per barrel.  The composite refiner acquisition cost for crude oil decreased $6.68 (11.1%), to $53.44 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>Refiner monthly average prices for sales of motor gasoline fell in July.  The average retail price dropped 3.6 cents to $2.338 per gallon, while the average wholesale price decreased 4.9 cents to $2.072 per gallon.</li>
                <li>Refiner sales of finished motor gasoline rose in July.  Total sales increased 300,000 gallons per day (0.1%) to an average of 331.3 million gallons per day.  Retail sales climbed 300,000 gallons per day (1.2%), while wholesales remained flat.  DTW sales accounted for 7.4% of wholesales, while rack and bulk sales made up 86.5% and 6.1%, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>July monthly average prices for refiner sales of No. 2 distillates declined from June levels.  The average sales price for No. 2 diesel fuel to end users decreased 10.8 cents to $1.914 per gallon, while the average wholesale price fell 15.2 cents to $1.729 per gallon.  The average sales price for No. 2 fuel oil to end users declined 11.4 cents to $2.207 per gallon, while the average wholesale price for No. 2 fuel oil fell 16.8 cents to $1.645 per gallon.</li>
                <li>Refiner sales of No. 2 ultra-low sulfur diesel fuel decreased in July.  Retail sales fell 400,000 gallons per day (3.2%), while wholesales declined 4.1 million gallons per day (2.7%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Refiner monthly average prices for residual fuel oil decreased in July.  The wholesale price for low-sulfur residual fuel oil fell 9.5 cents to $1.080 per gallon.  Prices for high-sulfur residual fuel oil declined 22.9 cents to $1.245 per gallon at retail, while the wholesale price dropped 10.9 cents to $1.130 per gallon.</li>
                <li>Total sales of residual fuel oil by refiners declined in July.  Retail sales fell 1.0 million gallons per day (21.7%), while wholesales decreased 600,000 gallons per day (6.7%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>July prices for the remaining surveyed products generally declined from June levels.  Propane prices increased at retail, but remained flat at wholesale, while prices for kerosene-type jet fuel fell at both levels.  Wholesale prices for aviation gasoline, kerosene, No. 1 distillate, and No. 4 distillate declined in July.</li>
                <li>During July, refiner sales of propane increased at the retail level, but fell at wholesale.  Sales of kerosene-type jet fuel were flat at retail, and declined at wholesale.  Aviation gasoline, No. 1 distillate, and No. 4 distillate sales rose at the wholesale level, while kerosene sales declined in the same category.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>*/ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/petroleum/marketing/annual/archive/" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a></li>
    </ul>
</div>