<div class="l-row header report-details">
        <div class="l-full-width-column">
                <a href="/petroleum/reports.cfm">&lsaquo; All Petroleum and Other Liquids Reports</a>
                <h2>Petroleum Marketing Monthly   <?php /* | <em>August 2012</em>*/ ?></h2>

                <div class="release-dates">
                        <div class="label-series">Data for June 2012</div><!-- /label-series -->
<                                <div class="date-container">
                                        <div class="label">Release Date:</div><!-- /label -->
                                <div class="date">September 4, 2012</div><!-- /date -->
                        </div><!-- /date-container -->
                        <div class="report-download-container">
                                <a href="pdf/pmmall.pdf" class="pdf">full report<</a>
</div>
</div>

<div>
<div>
