<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2015-05/fig_HL1coppwp2.png" class="lightbox"><img src="images/2015-05/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude Oil</h2>
            <ul>
                <li>Monthly average crude oil prices increased in February.  The average domestic crude oil first purchase price rose $1.29 (3.0 percent), to $44.35 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil climbed $4.97 (12.4 percent), to $44.89 per barrel.  The average landed cost of foreign crude oil increased $2.72 (6.2 percent), to $46.57 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil rose $1.40 (2.9 percent), to $50.30 per barrel.  The average cost of imported crude oil increased $2.44 (5.5 percent), to $47.18 per barrel.  The composite refiner acquisition cost for crude oil rose $1.96 (4.2 percent), to $48.96 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>Monthly average prices for sales of motor gasoline by refiners moved higher during February.  The average retail price climbed 18.5 cents to $1.858 per gallon, while the average wholesale price rose 27.1 cents to $1.637 per gallon.</li>
                <li>Sales of finished motor gasoline by refiners increased in February.  Total sales rose 11.6 million gallons per day (3.8 percent) to an average of 317.1 million gallons per day.  Retail sales increased 400,000 gallons per day (1.7 percent), while wholesales climbed 11.2 million gallons per day (4.0 percent).  DTW sales made up 7.8 percent of wholesales, while rack and bulk sales accounted for 84.1 percent and 8.0 percent, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>Monthly average prices for sales of No. 2 distillates by refiners rose in February.  The average sales price for No. 2 diesel fuel to end users increased 16.3 cents to $1.982 per gallon, while the average wholesale price climbed 24.6 cents to $1.862 per gallon.  The average wholesale price for No. fuel oil rose 18.1 cents to $1.850 per gallon.</li>
                <li>Sales of No. 2 ultra-low sulfur diesel fuel by refiners increased during February.  Retail sales rose 100,000 gallons per day (0.8 percent), while wholesales increased 1.3 million gallons per day (0.9 percent).</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Monthly average prices for sales of residual fuel oil by refiners rose in February.  The wholesale price for low-sulfur residual fuel oil increased 21.4 cents to $1.150 per gallon.  Prices for high-sulfur residual fuel oil climbed 15.0 cents to $1.342 per gallon at retail, and 8.6 cents per gallon to $1.124 per gallon at wholesale.</li>
                <li>Refiner sales of residual fuel oil rose in February.  Total sales increased 1.3 million gallons per day (12.9 percent) to an average of 11.4 million gallons per day.</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>Prices for the remaining surveyed products rose in February.  Propane, kerosene-type jet fuel, and No. 1 distillate prices increased at both retail and wholesale, while prices for aviation gasoline, kerosene, and No. 4 distillate rose at the wholesale level.</li>
                <li>Refiner sales of propane and kerosene-type jet fuel increased at both retail and wholesale during February, while No. 1 distillate sales fell at both levels.  Sales of aviation gasoline rose at wholesale, while kerosene and No. 4 distillate sales decreased at the wholesale level.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>*/ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/oil_gas/petroleum/data_publications/petroleum_marketing_annual/pma_historical.html" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a>