<h1>Recent Analysis &amp; Projections</h1><div class="content-container">
<ul class="analysis-projections">
<li>
<img src="https://www.eia.gov/global/images/icons/dap/da.png">
</li>
<li class="header">
<h2>
<a href="/petroleum/drilling/">Drilling Productivity Report </a>
</h2>
</li>
<li class="tags">
<span class="date">Released July 17, 2017</span>
<a href="reports.cfm/#/T1073,T202,Z" class="capsule"
title="Bakken">Bakken</a>
<a href="reports.cfm/#/T1329,T202,Z" class="capsule" title="Eagle Ford">Eagle Ford</a>
<a href="reports.cfm/#/T1225,T202,Z" class="capsule" title="Haynesville">Haynesville</a>
<a href="reports.cfm/#/T1075,T202,Z"
class="capsule" title="Marcellus">Marcellus</a>
<a href="reports.cfm/#/T1659,T202,Z" class="capsule" title="Niobrara">Niobrara</a>
<a href="reports.cfm/#/T1661,T202,Z"
class="capsule" title="Permian">Permian</a>
<a href="reports.cfm/#/T1150,T202,Z" class="capsule" title="Utica">Utica</a>
<a
href="reports.cfm/#/T1255,T202,Z" class="capsule" title="crude oil">crude oil</a>
<a href="reports.cfm/#/T1326,T202,Z" class="capsule" title="drilling">drilling</a>
<a href="reports.cfm/#/T2019,T202,Z"
class="capsule" title="exploration">exploration</a>
<a href="reports.cfm/#/T198,T202,Z" class="capsule" title="monthly">monthly</a>
<a href="reports.cfm/#//,T202,Z"
class="capsule" title="most popular">most popular</a>
<a href="reports.cfm/#/T1288,T202,Z" class="capsule" title="oil/petroleum">oil/petroleum</a>
<a href="reports.cfm/#//,T202,Z"
class="capsule" title="production/supply">production/supply</a>
<a href="reports.cfm/#/T82,T202,Z" class="capsule" title="reserves">reserves</a>
<a href="reports.cfm/#/T1237,T202,Z"
class="capsule" title="resources">resources</a>
<a href="reports.cfm/#/T1228,T202,Z" class="capsule" title="rig count">rig count</a>
<a href="reports.cfm/#/T1072,T202,Z"
class="capsule" title="shale">shale</a>
<a href="reports.cfm/#/T1116,T202,Z" class="capsule" title="wells">wells</a>
</li>
</ul>
<ul class="analysis-projections">
<li>
<img src="https://www.eia.gov/global/images/icons/dap/da.png">
</li>
<li class="header">
<h2>
<a href="/petroleum/drilling/">Drilling Productivity Report </a>
</h2>
</li>
<li class="tags">
<span class="date">Released July 17, 2017</span>
<a href="reports.cfm/#/T1073,T202,Z" class="capsule"
title="Bakken">Bakken</a>
<a href="reports.cfm/#/T1329,T202,Z" class="capsule" title="Eagle Ford">Eagle Ford</a>
<a href="reports.cfm/#/T1225,T202,Z" class="capsule" title="Haynesville">Haynesville</a>
<a href="reports.cfm/#/T1075,T202,Z"
class="capsule" title="Marcellus">Marcellus</a>
<a href="reports.cfm/#/T1659,T202,Z" class="capsule" title="Niobrara">Niobrara</a>
<a href="reports.cfm/#/T1661,T202,Z"
class="capsule" title="Permian">Permian</a>
<a href="reports.cfm/#/T1150,T202,Z" class="capsule" title="Utica">Utica</a>
<a
href="reports.cfm/#/T1255,T202,Z" class="capsule" title="crude oil">crude oil</a>
<a href="reports.cfm/#/T1326,T202,Z" class="capsule" title="drilling">drilling</a>
<a href="reports.cfm/#/T2019,T202,Z"
class="capsule" title="exploration">exploration</a>
<a href="reports.cfm/#/T198,T202,Z" class="capsule" title="monthly">monthly</a>
<a href="reports.cfm/#//,T202,Z"
class="capsule" title="most popular">most popular</a>
<a href="reports.cfm/#/T1288,T202,Z" class="capsule" title="oil/petroleum">oil/petroleum</a>
<a href="reports.cfm/#//,T202,Z"
class="capsule" title="production/supply">production/supply</a>
<a href="reports.cfm/#/T82,T202,Z" class="capsule" title="reserves">reserves</a>
<a href="reports.cfm/#/T1237,T202,Z"
class="capsule" title="resources">resources</a>
<a href="reports.cfm/#/T1228,T202,Z" class="capsule" title="rig count">rig count</a>
<a href="reports.cfm/#/T1072,T202,Z"
class="capsule" title="shale">shale</a>
<a href="reports.cfm/#/T1116,T202,Z" class="capsule" title="wells">wells</a>
</li>
</ul>
<ul class="analysis-projections">
<li>
<img src="https://www.eia.gov/global/images/icons/dap/da.png">
</li>
<li class="header">
<h2>
<a href="/petroleum/drilling/">Drilling Productivity Report </a>
</h2>
</li>
<li class="tags">
<span class="date">Released July 17, 2017</span>
<a href="reports.cfm/#/T1073,T202,Z" class="capsule"
title="Bakken">Bakken</a>
<a href="reports.cfm/#/T1329,T202,Z" class="capsule" title="Eagle Ford">Eagle Ford</a>
<a href="reports.cfm/#/T1225,T202,Z" class="capsule" title="Haynesville">Haynesville</a>
<a href="reports.cfm/#/T1075,T202,Z"
class="capsule" title="Marcellus">Marcellus</a>
<a href="reports.cfm/#/T1659,T202,Z" class="capsule" title="Niobrara">Niobrara</a>
<a href="reports.cfm/#/T1661,T202,Z"
class="capsule" title="Permian">Permian</a>
<a href="reports.cfm/#/T1150,T202,Z" class="capsule" title="Utica">Utica</a>
<a
href="reports.cfm/#/T1255,T202,Z" class="capsule" title="crude oil">crude oil</a>
<a href="reports.cfm/#/T1326,T202,Z" class="capsule" title="drilling">drilling</a>
<a href="reports.cfm/#/T2019,T202,Z"
class="capsule" title="exploration">exploration</a>
<a href="reports.cfm/#/T198,T202,Z" class="capsule" title="monthly">monthly</a>
<a href="reports.cfm/#//,T202,Z"
class="capsule" title="most popular">most popular</a>
<a href="reports.cfm/#/T1288,T202,Z" class="capsule" title="oil/petroleum">oil/petroleum</a>
<a href="reports.cfm/#//,T202,Z"
class="capsule" title="production/supply">production/supply</a>
<a href="reports.cfm/#/T82,T202,Z" class="capsule" title="reserves">reserves</a>
<a href="reports.cfm/#/T1237,T202,Z"
class="capsule" title="resources">resources</a>
<a href="reports.cfm/#/T1228,T202,Z" class="capsule" title="rig count">rig count</a>
<a href="reports.cfm/#/T1072,T202,Z"
class="capsule" title="shale">shale</a>
<a href="reports.cfm/#/T1116,T202,Z" class="capsule" title="wells">wells</a>
</li>
</ul>
<ul class="analysis-projections">
<li class="footer">
<a href="/">See more analysis &amp; projections</a>
</li>
</ul>
</div>
