														<div class="content-container main-content-container">
															<h1>Today in Energy
																<span class="date">Posted September 14, 2017</span>
															</h1>
															<h2>
																<a href="/todayinenergy/detail.cfm?id=31677">
																	<strong>EIA projects 28% increase in world energy use by 2040</strong>&nbsp;&rsaquo;</a>
															</h2>
															<p>The U.S. Energy Information Administration's latest
																<em>International Energy Outlook 2017</em> (IEO2017) projects that world energy consumption will grow by 28%
																between 2015 and 2040. Most of this growth is expected to come from countries that are not in the Organization
																for Economic Cooperation and Development (OECD), and especially in countries where demand is driven by strong
																economic growth, particularly in Asia.
																<a href="/todayinenergy/detail.cfm?id=31677">
																	<strong>More &rsaquo;</a>
																</strong>
															</p>
															<div class="media">
																<a href="/todayinenergy/detail.cfm?id=31592" border="0">
																	<img src="https://www.eia.gov/todayinenergy/images/2017.06.12/feature_p1.png" alt="">
																</a>
															</div>
															<caption>
																<strong>Source:</strong> EIA,
																<em>International Energy Outlook 2017</em>
															</caption>
														</div>


