<!-- start module features-->
<!-- start module features-->
<!-- start module features-->

    <h2>Features</h2>

    <a href="https://www.eia.gov/beta/realtime_grid/">
        <img src="global/images/home_sm_features/electric_data_sys.jpg" alt="Electricity Data Browser" />
    </a>

    <a href="https://www.eia.gov/beta/realtime_grid/">Electric System Operating Data Tool</a>
    
    <p>Near real-time electricity operations data for the Lower 48 states.</p>

    <a href="http://www.noggateway.org">
        <img src="global/images/home_sm_features/gateway.jpg" alt="Gateway" />
    </a>
<a href="http://www.noggateway.org">National Oil &amp; Gas Gateway
</a>

    <p>Well-level data and maps now available</p>

  <a href="/state/maps.cfm">
    <img src="/global/images/home_sm_features/energy_mapping_system.jpg" alt="U.S. Energy Mapping System"/></a>
    
    <a href="/state/maps.cfm">U.S. Energy Mapping System</a>

    <p>Rankings, layers of energy information, and state comparisons.</p>

<!-- end module features-->
<!-- end module features-->
<!-- end module features-->
