<!-- start module especially for... -->
<!-- start module especially for... -->
<!-- start module especially for... -->

<h2>Especially For...</h2>
<h5><a href="about/careers/">Job Seekers &rsaquo;</a></h5>
<h5><a href="about/especiallyfor/analysts.cfm">Policy Analysts &rsaquo;</a></h5>
<h5><a href="pressroom/">Media &rsaquo;</a></h5>
<h5><a href="tools/models/">Researchers &rsaquo;</a></h5>
<h5><a href="/kids">Students &rsaquo;</a></h5>
<h5><a href="/kids/energy.cfm?page=6">Teachers &rsaquo;</a></h5>
<h5><a href="/survey/">Survey Respondents &rsaquo;</a></h5>
<h5><a href="about/especiallyfor/employees.cfm">EIA Employees &rsaquo;</a></h5>
<h5><a href="/developer/">Developers API &rsaquo;</a></h5><strong></strong>


<!-- end module especially for... -->
<!-- end module especially for... -->
<!-- end module especially for... -->
