<!-- start module top Picks -->
<!-- start module top Picks -->
<!-- start module top Picks -->
<h2>Top Picks</h2>
<h5><a href="/petroleum/gasdiesel/">Gasoline and Diesel Fuel Update &rsaquo;</a></h5>
<h5><a href="http://ir.eia.gov/ngs/ngs.html">Natural Gas Storage Report &rsaquo;</a></h5>
<h5><a href="/petroleum/weekly/">This Week in Petroleum &rsaquo;</a></h5>
<h5><a href="/petroleum/supply/weekly/">Weekly Petroleum Status Report &rsaquo;</a></h5>
<h5><a href="/countries">Profiles for countries &rsaquo;</a></h5>
<h5><a href="state">Profiles for U.S. states &rsaquo;</a></h5>
<h5><a href="/todayinenergy/">Today in Energy &rsaquo;</a></h5>
<!-- end module top Picks -->
<!-- end module top Picks -->
<!-- end module top Picks -->
