<div class="content-container features dark-top-border-container">
    <h2>Features</h2>
    <div class="l-one-third-column">
        <div class="content-container">
            <a href="/">
                <img src="http://via.placeholder.com/183x101" alt="">
            </a>
            <ul>
                <li class="header">
                    <h2>
                        <a href="/">Electric System Operating Data Tool</a>
                    </h2>
                </li>
                <li>Near real-time electricity operations data for the Lower 48 states.</li>
            </ul>
        </div>
    </div>
    <div class="l-one-third-column">
        <div class="content-container">
            <a href="/">
                <img src="http://via.placeholder.com/183x101" alt="">
            </a>
            <ul>
                <li class="header">
                    <h2>
                        <a href="/">Electric System Operating Data Tool</a>
                    </h2>
                </li>
                <li>Near real-time electricity operations data for the Lower 48 states.</li>
            </ul>
        </div>
    </div>
    <div class="l-one-third-column">
        <div class="content-container">
            <a href="/">
                <img src="http://via.placeholder.com/183x101" alt="">
            </a>
            <ul>
                <li class="header">
                    <h2>
                        <a href="/">Electric System Operating Data Tool</a>
                    </h2>
                </li>
                <li>Near real-time electricity operations data for the Lower 48 states.</li>
            </ul>
        </div>
    </div>
</div>
