<!--
<div class="form-wrapper">
    <form>
        <input class="fancy-search-box" type="text" maxlength="256" placeholder="Search survey forms by name or #" onfocus="this.placeholder=''" onblur="this.placeholder='Search survey forms by name or #'" id="survey">
        <a href="" id="SurveySearch">
            <button type="submit" class="search-submit">
                <i class="ico search-submit">Search</i>
            </button>
        </a>
    </form>
</div>
-->

<div class="form-wrapper">
    <form accept-charset="UTF-8" action="//search.usa.gov/search" id="search_form" method="get" _lpchecked="1">
        <input name="utf8" type="hidden" value="✓">
        <input id="affiliate" name="affiliate" type="hidden" value="eia.doe.gov">
        <input autocomplete="off" class="usagov-search-autocomplete ui-autocomplete-input" id="search-input" name="query" type="text" maxlength="256" placeholder="Search survey forms by name or #" onfocus="this.placeholder=''" onblur="this.placeholder='Search survey forms by name or #'">
        <button type="submit" class="search-submit"  name="search" alt="enter terms to search" border="0" title="Click to search EIA">
            <i class="ico search-submit">Search</i>
        </button>
    </form>
</div>

<!--
<input name="utf8" type="hidden" value="&#x2713;" />
<input id="affiliate" name="affiliate" type="hidden" value="eia.doe.gov" />
<input autocomplete="off" class="usagov-search-autocomplete fancy-search-box" name="query" type="text" maxlength="256" placeholder="Search survey forms by name or #" onfocus="this.placeholder=''" onblur="this.placeholder='Search survey forms by name or #'" />
<button type="submit" id="goBtn" class="search-submit">
<i class="ico search-submit">Search</i>
</button>
<a id="Go" href="" class="search-submit" input type="submit" name="search" alt="enter terms to search" class="arrow_go" border="0" title="Click to search EIA">
<i class="ico search-submit">Search</i>
</a>
input type="submit" name="search" alt="enter terms to search" class="arrow_go" border="0" title="Click to search EIA"
    </form>
</div>

--> 





