<!-- start module our experts speak -->
<!-- start module our experts speak -->
<!-- start module our experts speak -->

<h2>Our Experts Speak</h2>
<h5><a href="/pressroom/events/pdf/Propane_01102018.pdf">Rob Merriam, Office of Petroleum and Biofuels Statistics and Warren Wilczewski, Office of Petroleum, Natural Gas, and Biofuels Analysis, EIA presented EIA’s propane market indicators and measures of supply adequacy</em>&nbsp;&rsaquo;</a></h5>
<p>January 10, 2018</p>
<h5><a href="/pressroom/presentations/hess_10112017.pdf">Tim Hess, Office of Energy Analysis, presented EIA’s Winter Fuels Outlook</em>&nbsp;&rsaquo;</a></h5>
<p>October 11, 2017</p>    
<h5><b><a href="pressroom/">More</a></b></h5>

<!-- end module our experts speak -->
<!-- end module our experts speak -->
<!-- end module our experts speak -->
