<div class="content-container content-container-border">
    <div class="blue-background">
        <div class="header-style-guide">
            <h2>Data Highlights</h2>
        </div>
        <hr>
        <ul>
            <li class="title">
                <a href="http://www.eia.gov/petroleum/gasdiesel/">Retail gasoline price</a>
            </li>
            <li class="date">6/12/2017:
                <strong>$1.234/gal</strong>
            </li>
            <li>
                <span class="ico down">down</span>$0.123 from week earlier</li>
            <li>
                <span class="ico up">up</span>$0.456 from year earlier</li>
        </ul>
        <ul>
            <li class="title">
                <a href="http://www.eia.gov/petroleum/gasdiesel/">Retail gasoline price</a>
            </li>
            <li class="date">6/12/2017:
                <strong>$1.234/gal</strong>
            </li>
            <li>
                <span class="ico down">down</span>$0.123 from week earlier</li>
            <li>
                <span class="ico up">up</span>$0.456 from year earlier</li>
        </ul>
    </div>
</div>
