<div class="content-container dark-top-border-container">
<ul>
<li class="header"><h2>What's New</h2></li>
<li>
<a href="/">Drilling Productivity Report</a>
</li>
<span class="date">June 12</li>
<li>
<a href="/">Short-Term Energy Outlook</a>
</li>
<span class="date">June 12</li>
<li>
<a href="/">Petroleum Marketing Monthly</a>
<span class="date">June 12</li>
<li class="footer">
<a href="/" class="strong">More</a>
</li>
</ul>
</div>    <hr>
<ul>
<li class="header">
<h2>Coming Up</h2>
</li>
<li>
<a href="/">Refinery Capacity Report</a>
</li>
<li>
<a href="/">U.S. Natural Gas Imports &amp; Exports</a>
</li>
<li>
<a href="/">Uranium Marketing Annual</a>
</li>
<li class="footer">
<a href="/" class="strong">More</a>
</li>
</ul>
</div>

