<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Language" content="en-us" />
<meta name="robots" content="all" />
<meta name="agency" content="EIA - Energy Information Administration" />
<meta name="subject" content="official energy statistics, data, analysis and forecasting" />
<meta name="description" content="Energy Information Administration - EIA - Official Energy Statistics from the U.S. Government" />

<script src='http://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

<link href='<?php print HTTP; ?>global/styles/eia-styles.css' rel='stylesheet' type='text/css'>
<link rel="shortcut icon" href="<?php print HTTP; ?>favicon.ico" />
<link rel="icon" href="<?php print HTTP; ?>favicon.ico" type="image/x-icon">
<link rel="shortcut icon" type="image/vnd.microsoft.icon" href="<?php print HTTP; ?>favicon.ico" />

