														<div class="content-container dark-top-border-container">
															<ul>
																<li class="header">
																	<h2>Top Picks</h2>
																</li>
																<li>
																	<a href="/petroleum/gasdiesel/">Gasoline and Diesel Fuel Update</a>
																</li>
																<li>
																	<a href="http://ir.eia.gov/ngs/ngs.html">Natural Gas Storage Report</a>
																</li>
																<li>
																	<a href="/petroleum/weekly/">This Week in Petroleum</a>
																</li>
																<li>
																	<a href="/petroleum/supply/weekly/">Weekly Petroleum Status Report</a>
																</li>
																<li>
																	<a href="/countries">Profiles for countries</a>
																</li>
																<li>
																	<a href="state">Profiles for U.S. states</a>
																</li>
																<li>
																	<a href="/todayinenergy/">Today in Energy</a>
																</li>
															</ul>
														</div>
