<div class="content-container dark-top-border-container">
    <ul>
        <li class="header">
            <h2>Our Experts Speak</h2>
        </li>
        <li>
            <a href="/pressroom/presentations/gruenspecht_05032017.pdf">Acting EIA Administrator Howard Gruenspecht presented the outlook for natural gas production, demand, and
                trade</a>
        </li>
        <li class="date">January 31, 2017</li>
        <li>
            <a href="/pressroom/presentations/gruenspecht_04252017.pdf">Acting EIA Administrator Howard Gruenspecht presented the outlook for oil and natural gas production in
                the United States</a>
        </li>
        <li class="date">January 5, 2017</li>
        <li class="footer">
            <a href="pressroom/">More</a>
        </li>
    </ul>
</div>
