<!-- start module learn about energy -->
<!-- start module learn about energy -->
<!-- start module learn about energy -->

  <h4>Learn About Energy</h4>
    <p><a href="/energyexplained">Energy Explained</a></p>
    <p class="no_btm_border"><a href="tools/faqs/">Frequently Asked Questions</a></p>

<!-- end module learn about energy -->
<!-- end module learn about energy -->
<!-- end module learn about energy -->
