            <!-- start footer -->
            </div>
        </div>
    </div>
</section>
<footer class="clearfix footer">
    <div class="l-row address-bar">
        <div class="l-two-third-column">
            <ul class="above-address-links">
                <li><a href="/about/">About EIA</a><div class="arrow-right"></div></li>
                <li><a href="/beta/api/">Open Data</a><div class="arrow-right"></div></li>
                <li><a href="/pressroom/">Press Room</a><div class="arrow-right"></div></li>
                <li><a href="/about/careers/">Careers</a><div class="arrow-right"></div></li>
                <li><a href="/about/contact/">Contact Us</a><div class="arrow-right"></div></li>
            </ul>
        </div>
        <div class="l-one-third-column">
            <div class="address">Energy Information Agency<br />1000 Independence Ave., SW <br />Washington, DC 20585</div>
        </div>
    </div>
    <div class="l-row footer-links">
        <ul class="l-column">
            <li>Sources &amp; Uses</li>
            <li><a href="/petroleum/">Petroleum</a></li>
            <li><a href="/coal/">Coal</a></li>
            <li><a href="/naturalgas/">Natural Gas</a></li>
            <li><a href="/renewable/">Renewable</a></li>
            <li><a href="/nuclear/">Nuclear</a></li>
            <li><a href="/electricity/">Electricity</a></li>
            <li><a href="/consumption/">Consumption</a></li>
            <li><a href="/totalenergy/">Total Energy</a></li>
        </ul>
        <ul class="l-column">
            <li>Topics</li>
            <li><a href="/analysis/">Analysis &amp; Projections</a></li>
            <li><a href="/environment">Environment</a></li>
            <li><a href="/finance/">Markets &amp; Finance</a></li>
            <li><a href="/todayinenergy/">Today in Energy</a></li>
            <li><br /></li>
            <li>Geography</li>
            <li><a href="/state/">States</a></li>
            <li><a href="/countries/">Countries</a></li>
            <li><a href="/maps/">Maps</a></li>
        </ul>
        <ul class="l-column">
            <li>Tools</li>
            <li><a href="/tools/a-z/">A-Z Index</a></li>
            <li><a href="/reports/"><span class="line-break">All Reports &amp;</span> <span class="line-break">Publications</span></a></li>
            <li><a href="/tools/"><span class="line-break">Data Tools, Apps,</span> <span class="line-break">and Maps</span></a></li>
            <li><a href="/survey/">EIA Survey Forms</a></li>
            <li><a href="/beta/">EIA Beta</a></li>
        </ul>
        <ul class="l-column">
            <li>Policies</li>
            <li><a href="/about/privacy_security_policy.cfm">Privacy/Security</a></li>
            <li><a href="/about/copyrights_reuse.cfm">Copyright &amp; Reuse</a></li>
            <li><a href="/about/accessability.cfm">Accessibility</a></li>
        </ul>
        <ul class="l-column">
            <li>Related Sites</li>
            <li><a href="https://www.energy.gov/">U.S. Department of Energy</a></li>
            <li><a href="https://www.usa.gov/">USA.gov</a></li>
            <li><a href="https://fedstats.sites.usa.gov/">FedStats</a></li>
        </ul>
        <ul class="l-column">
            <li>Stay Connected</li>
            <li><a href="http://facebook.com/eiagov/" target="_blank"><i class="ico-footer facebook"></i>Facebook</a></li>
            <li><a href="http://twitter.com/eiagov/" target="_blank"><i class="ico-footer twitter"></i>Twitter</a></li>
            <li><a href="http://youtube.com/eiagov/" target="_blank"><i class="ico-footer youtube"></i>Youtube</a></li>
            <li><a href="https://www.flickr.com/photos/eiagov/" target="_blank"><i class="ico-footer flickr"></i>Flickr</a></li>
            <li><a href="http://linkedin.com/company/u-s-energy-information-administration" target="_blank"><i class="ico-footer linkedin"></i>LinkedIn</a></li>
            <li><a href="/tools/emailupdates/" target="_blank"><i class="ico-footer email"></i>Email Updates</a></li>
            <li><a href="/tools/rssfeeds/" target="_blank"><i class="ico-footer rss"></i>RSS Feeds</a></li>
        </ul>
    </div>
</footer>
<script>
$('#outerX').removeAttr('id');
$('.l-outer-wrapper').attr('id', 'outerX');
/*
$(document).ready(function(){
    $(".page_tabs").tabs();
    $(".page_tabs").localScroll({
        target:".page_tabs",
        duration:0,
        hash:true
    });
});
*/
</script>

<script src='/global/scripts/eia-scripts.min.js'></script>
