<link type="text/css" href="/global/scripts/jquery/datepicker/jquery-ui-dp.custom.css" rel="stylesheet"><script src="/global/scripts/jquery/jquery-1.11.1.min.js">
</script>
<script type="text/javascript" src="/global/scripts/jquery/jquery-migrate-1.2.1.min.js">
</script>
<script type="text/javascript" src="/global/scripts/jquery/ui/1.10.3/js/jquery-ui-1.10.3.custom.min.js">
</script>
<script type="text/javascript" src="/global/scripts/jquery/touch-punch/jquery.ui.touch-punch.min.js">
</script>
<link rel="stylesheet" href="/global/styles/screen.css" type="text/css" media="screen, projection">
<link rel="stylesheet" href="/global/styles/EIA_global.css" type="text/css" media="screen, projection">
<link rel="stylesheet" href="/global/styles/print.css" type="text/css" media="print">
<link rel="stylesheet" href="../css/styles.css" type="text/css" media="all">
<style>
body, html {
background-color: #ffffff;
margin-bottom: 0;
overflow-y: auto;
}