<div class="aeo_footer blue_top"><div class="aeo_inner">
<span class="left_box">
<li class="header">
<h2>About the Annual Energy Outlook</h2>
</li>
<ul class="no-liststyle">
<li>
<a href="#">Report Overview (Preface)</a>
</li>
<li>
<a href="#">Contact Information and Staff</a>
</li>
<li>
<a href="#">Press Releases</a>
</li>
<li>
<a href="#">Ordering Information</a>
</li>
</ul>
</div>              </span>
<span class="mid_box">
<li class="header">
<h2>Previous Editions of the Annual Energy Outlook</h2>
</li>
<form>
<label>Year:</label>
<select name="country" size="1">
<option>2009</option>
</select>&nbsp;
<input type="submit" name="search" alt="Go" class="arrow_go" title="Go">
</form>
</span>
<span class="right_box">
<li class="header">
<h2>Documnetation and Assumptions</h2>
</li>
<ul class="split_2columns no-liststyle">
<li>
<a href="#">Complete Report (PDF)</a>
</li>
<li>
<a href="#">Report by Chatpers (PDF)</a>
</li>
<li>
<a href="#">Assumptions Report</a>
</li>
<li>
<a href="#">Appendices (PDF)</a>
</li>
<li>
<a href="#">About the National<br />Energy Modeling<br />System (NEMS)</a>
</li>
<li>
<a href="#">List of Acronyms</a>
</li>
<li>
<a href="#">Notes and Sources</a>
</li>
</ul>
</div>              </span>
</div>
</div>
