<div class="aeo_footer blue_top"><div class="aeo_inner">
<span class="left_box">
<li class="header">
<h2>About the Annual Energy Outlook</h2>
</li>
<ul class="no-liststyle">
<li>
<a href="/about/contact/forecasting.cfm#longterm">Contact information and staff</a>
</li>
<li>
<a href="/pressroom/releases/press371.cfm">Press release</a>
</li>
<li>
<a href="/pressroom/presentations/howard_01232012.pdf">
<i class="ico pdf">pdf</i>Press conference presentation</a>
</li>
</ul>
</div>              </span>
<span class="mid_box">
<li class="header">
<h2>Previous Editions of the AEO</h2>
</li>
<form name="form" id="form">
<select name="jumpMenu" id="jumpMenu" style="width:110px">
<option value="/outlooks/archive/aeo11/index.cfm">2011</option>
<option value="/oiaf/archive/aeo10/index.html">2010</option>
<option value="/oiaf/archive/aeo09/index.html">2009</option>
<option value="/oiaf/archive/aeo08/index.html">2008</option>
<option value="/oiaf/archive/aeo07/index.html">2007</option>
<option value="/oiaf/archive/aeo06/index.html">2006</option>
<option value="/outlooks/aeo/archive.cfm">See all</option>
</select>
<input type="button" name="go_button" class="arrow_go" id= "go_button" value="Go" onclick="MM_jumpMenuGo('jumpMenu','parent',1)" />
</form>
</span>
<span class="right_box">
<li class="header">
<h2>Documentation and Assumptions</h2>
</li>
<ul class="split_2columns no-liststyle">
<!--        <li>Notes and Sources</li>-->
<li>
<a href="acronyms.cfm">Acronyms</a>
</li>
<li>
<a href="http://www.eia.gov/outlooks/aeo/assumptions/index.cfm">Assumptions report (2012)</a>
</li>
<li>
<a href="http://www.eia.gov/outlooks/aeo/pdf/nerc_map.pdf">
<i class="ico pdf">pdf</i>NERC Region map</a>
</li>
<li>
<a href="http://www.eia.gov/outlooks/aeo/electricity_generation.cfm">Levelized generation costs</a>
</li>
<li>
<a href="http://www.eia.gov/oiaf/aeo/overview/index.html">About the National<br />
Energy Modeling<br />
System (NEMS)</a>
</li>
</ul>
</div>              </span>
</div>
</div>
