<div class="title bg_electricity"><h1>Electricity</h1>
</div>
<div id="subnav">
<span class="right">
<a href="<?php echo "$glossary_path"?>">Glossary &rsaquo;</a> <a href="<?php echo "$faqs_path"?>">FAQS &rsaquo;</a>
</span>
<ul>
<li class="subnav-overview">
<a href="/electricity/">Overview</a>
</li>
<li class="subnav-data">Data</li>
<div class="data_block">
<div class="data_block_content">
<ul>
<li>
<a href="summarydata.cfm">Summary Data</a>
</li>
<li>
<a href="salesrevenueprices.cfm">Sales, Revenue & Prices</a>
</li>
<li>
<a href="#">Generation</a>
</li>
<li>
<a href="#">Electric Power Plants</a>
</li>
<li>
<a href="#">Fuel Used in Electric Generation</a>
</li>
<li>
<a href="#">Costs</a>
</li>
<li>
<a href="#">Trade and Reliability</a>
</li>
<li>
<a href="#">Demand</a>
</li>
<li>
<a href="#" class="no-border">Electricity and the Environment</a>
</li>
</ul>
</div>
<li class="subnav-analysis">
<a href="#">Analysis & Projections</a>
</li>
</ul>
