<div class="pub_title bg_aeo"><a href="http://www.eia.gov/environment">&lsaquo; Environment</a>
<h1>Emissions of Greenhouse Gases in the U. S.</h1>
<li>
<strong>Release Date:</strong> March 31, 2011 &nbsp; | &nbsp;<strong>Next Release Date:</strong> Report Discontinued &nbsp; | &nbsp; <a href="/environment/emissions/ghg_report/pdf/0573%282009%29.pdf" class="pdf">Report Number: DOE/EIA-0573(2009)</a>
</p>
</div>
