<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong> Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2013-01/fig_HL1coppwp.jpg" class="lightbox"><img src="images/2013-01/fig_HL1_coppwp_sm.jpg" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3>Highlights</h3></li>
                <li><p>The daily spot price for West Texas Intermediate (WTI) crude oil declined during October.  Opening at $92.18 per barrel, the price immediately marked the month's high of $92.44 per barrel on October 1.  Concerns about global economic activity coupled with ample supplies weighed on the price during the coming weeks, pulling it down to its lowest level in several months.  The month's low, $85.39 per barrel, was struck on October 24 following a reported larger-than-expected increase in crude oil stocks.  Closing the October at $86.23 per barrel, the price was $5.95 below its opening level for the month.  Averaging $89.49 per barrel for October in total, the price was $5.02 (5.3 percent) lower than September's average of $94.51 per barrel.  Compared with the average price for October 2011, $86.32 per barrel, the current price is $3.17 (3.7 percent) higher.  ...</p></li>
                <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>