<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2017-09/fig_HL1coppwp2.png" class="lightbox"><img src="images/2017-09/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude oil</h2>
            <ul>
                <li>June monthly average crude oil prices declined from May levels. The average domestic crude oil first purchase price fell $3.00 (6.6%), to $42.19 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil dropped $2.36 (5.4%) to $41.57 per barrel. The average landed cost of foreign crude oil fell $2.57 (5.6%), to $43.54 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil decreased $3.41 (6.9%), to $46.17 per barrel. The average cost of imported crude oil declined $3.01 (6.4%), to $43.93 per barrel. The composite refiner acquisition cost for crude oil dropped $3.17 (6.6%), to $45.17 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>Refiner monthly average prices for motor gasoline continued on a downward path in June. The average retail price decreased 5.7 cents to $1.906 per gallon, while the average wholesale price fell 9.4 cents to $1.574 per gallon.</li>
                <li>Refiner sales of finished motor gasoline increased again in June. Total sales rose 4.5 million gallons per day (1.4%) to an average of 335.4 million gallons per day. Retail sales increased 800,000 gallons per day (3.2%), while wholesales climbed 3.7 million gallons per day (1.2%). DTW sales accounted for 7.4% of wholesales, while rack and bulk sales made up 87.9% and 4.8%, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>Monthly average prices for refiner sales of No. 2 distillates fell in June. The average price for No. 2 diesel fuel sold to end users declined 7.6 cents to $1.617 per gallon, while the average wholesale price decreased 8.7 cents to $1.465 per gallon. The average wholesale price for No. 2 fuel oil fell 7.2 cents to $1.375 per gallon.</li>
                <li>Refiner sales of No. 2 ultra-low sulfur diesel fuel climbed 4.0 million gallons per day (2.5%) to 163.9 million gallons per day in June. Retail sales dropped 100,000 gallons per day (0.8%), while wholesales rose 4.1 million gallons per day (2.8%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Refiner monthly average prices for sales of residual fuel oil declined in June. The wholesale price for low-sulfur residual fuel oil dropped 4.9 cents to $0.937 per gallon. The price for high-sulfur residual fuel oil decreased 2.4 cents to $1.129 per gallon at retail, while the wholesale price declined 5.2 cents to $.995 per gallon.</li>
                <li>Refiner residual fuel oil sales increased 2.2 million gallons per day (22.7%) to 11.9 million gallons per day in June. Retail sales fell 100,000 gallons per day (2.6%), while wholesales rose 2.3 million gallons per day (39.0%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>Refiner prices for sales of the remaining surveyed products followed the general downward trend seen in the market during June. Prices for propane, kerosene-type jet fuel, and kerosene fell at both the retail and wholesale levels. Aviation gasoline and No. 1 distillate prices also declined at wholesale.</li>
                <li>Refiner sales of products included in this section show mixed changes in June. Kerosene-type jet fuel sales increased in both categories, while kerosene sales declined at both retail and wholesale. Sales of propane fell at retail but increased at the wholesale level. Aviation gasoline and No. 1 distillate sales rose at wholesale.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>*/ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/petroleum/marketing/annual/archive/" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a></li>
    </ul>
</div>