<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2015-02/fig_HL1coppwp2.png" class="lightbox"><img src="images/2015-02/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude Oil</h2>
            <ul>
                <li>Monthly average crude oil prices continued to decline during November.  The average domestic crude oil first purchase price fell $7.76 (9.8 percent), to $71.07 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil dropped $6.04 (7.9 percent), to $70.80 per barrel.  The average landed cost of foreign crude oil declined $7.35 (9.1 percent), to $73.48 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil fell $9.65 (11.1 percent), to $77.08 per barrel.  The average cost of imported crude oil decreased $8.85 (10.7 percent), to $73.90 per barrel.  The composite refiner acquisition cost for crude oil declined $9.30 (10.9 percent), to $75.69 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>Refiner monthly average prices for sales of motor gasoline continued to register substantial decreases in November.  The average retail price fell 26.6 cents to $2.404 per gallon, while the average wholesale price dropped 22.2 cents to $2.111 per gallon.</li>
                <li>Sales of finished motor gasoline by refiners decreased in November, with total sales falling 4.2 million gallons per day (1.3 percent) to an average of 316.7 million gallons per day.  Retail sales dropped 700,000 gallons per day (2.6 percent), while wholesales declined 3.5 million gallons per day (1.2 percent).  DTW sales accounted for 7.9 percent of wholesales, while rack and bulk sales made up 84.5 percent and 7.7 percent, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>Monthly average prices for sales of No. 2 distillates by refiners fell in most sales categories.  The average sales price for No. 2 diesel fuel to end users declined 10.4 cents to $2.698 per gallon, while the average wholesale price decreased 8.1 cents to $2.558 per gallon.  The average No. 2 fuel oil wholesale price dropped 10.5 cents to $2.371 per gallon.</li>
                <li>Refiner sales of No. 2 ultra-low sulfur diesel fuel fell 11.6 million gallons per day (7.0 percent) to an average of 155.2 million gallons per day in November.  Total No. 2 fuel oil sales increased 1.5 million gallons per day (22.0 percent) to an average of 8.3 million gallons per day.</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Monthly average prices for sales of residual fuel oil by refiners decreased in November.  The retail price for low-sulfur residual fuel oil fell 27.9 cents to $2.294 per gallon, while the wholesale price dropped 24.9 cents to 1.644 per gallon.  Prices for high-sulfur residual fuel oil declined 25.1 cents to $1.848 per gallon at retail, while the wholesale price fell 24.3 cents to $1.605 per gallon.</li>
                <li>Refiner sales of residual fuel oil declined in November, with total sales falling 1.2 million gallons per day (8.9 percent) to an average of 12.3 million gallons per day.</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>Prices for the remaining surveyed products generally experienced decreases during November.  Propane and kerosene-type jet fuel prices declined at both the retail and wholesale.  Prices for aviation gasoline and kerosene fell at wholesale, while the wholesale price for No. 1 distillate increased.</li>
                <li>During November, refiner sales of propane declined at both the retail and wholesale levels.   Kerosene-type jet fuel sales were flat at retail but rose at wholesale.  Sales of aviation gasoline decreased at wholesale, while kerosene and No. 1 distillate rose at the same level.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>*/ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/oil_gas/petroleum/data_publications/petroleum_marketing_annual/pma_historical.html" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a>