
<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong> Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2013-11/fig_HL1coppwp.jpg" class="lightbox"><img src="images/2013-11/fig_HL1_coppwp_sm.jpg" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3>Highlights</h3></li>
        <li class="header"><h2>Crude Oil</h2>
            <ul>
                <li>Monthly average prices for crude oil continued to increase in August.  The average domestic crude oil first purchase price rose $1.52 (1.5 percent), to $103.13 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil increased $1.04 (1.0 percent), to $102.50 per barrel.  The average landed cost of foreign crude oil rose $1.83 (1.8 percent), to $102.86 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil rose $2.11 (2.0 percent), to $108.30 per barrel.  The average cost of imported crude oil climbed $2.60 (2.6 percent), to $104.16 per barrel.  The composite refiner acquisition cost for crude oil increased $2.35 (2.3 percent), to $106.20 per barrel.</li>
            </ul>
        </li>
        <li class="header"><h2>Petroleum Products</h2></li>
                <li><h4>Motor Gasoline</h4>
            <ul>
                <li>Monthly average prices for sales of finished gasoline by refiners declined during August.  The average retail sales price for motor gasoline fell 4.9 cents to $3.097 per gallon, while the average wholesale price decreased 5.2 cents to $2.890 per gallon.</li>
                <li>Refiner sales of finished motor gasoline increased in August.  Total sales climbed 4.4  million gallons per day (1.4 percent) to an average of 324.5 million gallons per day.  Retail sales rose 500,000 gallons per day (2.1 percent), while wholesales increased 3.9 million gallons per day (1.3 percent).  DTW sales accounted for 10.0 percent of wholesales, while rack and bulk sales made up 82.8 percent and 7.2 percent, respectively.</li>
                    </ul>
        </li>
                <li><h4>No. 2 Distillate</h4>
            <ul>
                <li>Refiner monthly average prices for No. 2 distillates rose again during August.  The average sales price for No. 2 diesel fuel to end users climbed 7.0 cents to $3.169 per gallon, while the average wholesale price increased 6.9 cents to $3.084 per gallon.  The average price for No. 2 fuel oil sales to end users increased 7.0 cents to $3.314 per gallon, while the average wholesale price rose 6.0 cents to $2.954 per gallon.</li>
                <li>Sales of No. 2 distillates by refiners were mixed in August.  Overall, sales fell 1.2 million gallons per day (0.8 percent), to 163.8 million gallons per day.  No. 2 fuel oil sales increased 1.2 million gallons per day (28.9 percent), while sales of No. 2 diesel fuel dropped 2.4 million gallons per day (1.5 percent).</li>
                    </ul>
        </li>
                <li><h4>Residual Fuel Oil</h4>
            <ul>
                <li>Monthly average prices for refiner residual fuel oil sales varied in August.  Prices for low-sulfur residual fuel oil fell 0.9 cent to $2.759 per gallon at retail, but rose 4.9 cents to $2.331 per gallon at wholesale.  Prices for high-sulfur residual fuel oil climbed 13.1 cents to $2.411 per gallon at retail, and 3.3 cents to $2.258 per gallon at wholesale.</li>
                <li>August sales of residual fuel oil by refiners fell from July levels.  Low-sulfur residual fuel oil sales decreased 300,000 gallons per day (7.5 percent), while high-sulfur residual fuel oil sales declined 200,000 gallons per day (1.8 percent).</li>
                    </ul>
        </li>
                <li><h4>Other Products</h4>
            <ul>
                <li>August price trends for the remaining surveyed products were mixed.  Prices for propane, kerosene-type jet fuel, and aviation gasoline increased at both retail and wholesale.  Kerosene prices fell at retail but increased at wholesale, while prices for No. 1 distillate did the opposite.  The price for No. 4 fuel oil decreased at the wholesale level.</li>
                <li>Refiner sales of propane increased at both retail and wholesale, while kerosene-type jet fuel sales show the opposite trend.  Sales of kerosene and No. 1 distillate retreated at the retail level, but rose at wholesale, while aviation gasoline sales moved in the opposite direction. Sales of No. 4 distillate declined at wholesale.</li>
            </ul>
        </li>
    </ul>
</div>

<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>

        <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>
    </ul>
</div>
