<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2016-11/fig_HL1coppwp2.png" class="lightbox"><img src="images/2016-11/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude Oil</h2>
            <ul>
                <li>Monthly average crude oil prices continued to fall in August. The average domestic crude oil first purchase price declined 24 cents (0.6%), to $40.46 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil fell 52 cents (1.3%) to $38.28 per barrel. The average landed cost of foreign crude oil dropped $1.13 (2.8%), to $39.89 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil decreased 70 cents (1.6%), to $44.18 per barrel. The average cost of imported crude oil fell 27 cents (0.7%), to $41.21 per barrel. The composite refiner acquisition cost for crude oil declined 56 cents (1.3%), to $42.70 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>August monthly average prices for refiner sales of motor gasoline show mixed trends. The average retail price dropped 5.0 cents to $1.754 per gallon, while the average wholesale price increased 1.8 cents to $1.508 per gallon.</li>
                <li>Refiner sales of finished motor gasoline declined in August. Total sales fell 1.0 million gallons per day (0.3%) to an average of 341.2 million gallons per day. Retail sales rose 200,000 gallons per day (0.8%), while wholesales decreased 1.2 million gallons per day (0.4%). DTW sales accounted for 7.6% of wholesales, while rack and bulk sales made up 84.9% and 7.5%, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>August monthly average prices for refiner sales of No. 2 distillates show small changes from July levels. The average price for No. 2 diesel fuel sold to end users remained flat at $1.577 per gallon, while the average wholesale price rose 1.4 cents to $1.440 per gallon. The average wholesale price for No. 2 fuel oil increased 0.2 cent to $1.307 per gallon.</li>
                <li>Refiner sales of No. 2 ultra-low sulfur diesel fuel rose in August. Retail sales rose 1.0 million gallons per day (8.1%), while wholesales increased 11.5 million gallons per day (8.9%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Monthly average prices for residual fuel oil sold by refiners fell in August. The wholesale price for low-sulfur residual fuel oil declined 3.4 cents to 84.2 cents per gallon. Prices for high-sulfur residual fuel oil dropped 2.4 cents to 92.4 cents per gallon at retail, while the wholesale price fell 2.3 cents to 81.1 cents per gallon.</li>
                <li>Sales of residual fuel oil by refiners increased in August. Retail sales rose 100,000 gallons per day (2.3%), while wholesales increased 500,000 gallons per day (6.6%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>August monthly average prices for refiner sales of the remaining surveyed products generally declined. Propane and kerosene-type jet fuel prices fell at both the retail and wholesale levels. No. 1 distillate prices fell at retail, but increased at wholesale. Prices for aviation gasoline declined at wholesale, while the price for kerosene increased in the same category.</li>
                <li>Refiner sales of products included in this section mostly increased during August. Propane and kerosene-type jet fuel sales rose at both the retail and wholesale levels. Sales of No. 1 distillate dropped at retail, but increased at wholesale. Aviation gasoline and kerosene sales also increased at the wholesale level.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div> */ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/petroleum/marketing/annual/archive/" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a></li>
    </ul>
</div>