<div class="l-row header report-details">
        <div class="l-split-wide">
        
                <a href="/petroleum/reports.cfm">&lsaquo; All Petroleum and Other Liquids Reports</a>
                <h2>Petroleum Marketing Monthly</h2>

                <div class="release-dates">
                        <div class="label-series">Data for August 2016</div><!-- /label-series -->
<div class="date-container">
                                <div class="label">Release Date:</div><!-- /label -->
                                <div class="date">November 1, 2016</div><!-- /date -->
                        </div><!-- /date-container -->
                        <div class="report-download-container">
                                <a href="pdf/pmmall.pdf"><i class="ico pdf"></i>full report</a></div>
                        </div>
                </div>
        </div>
        <div class="l-split-narrow gradient">
                <span class="form-wrapper-outer">
                        <h4>Previous Issues</h4>
                        <span class="form-wrapper-inner">
                                <form name="form" id="form">
                                        <label>Month:</label>
                                        <select name="jumpMenu" id="jumpMenu">
                                                <option value="/petroleum/marketing/monthly/archive/2016/2016_10/pmm_2016_10.cfm" selected="selected">October 2016</option>
<!--                                                <option value="/petroleum/marketing/monthly/archive/2011/2011_11/pmm_2011_11.html">November 2012</option>-->
                                                <option value="/petroleum/marketing/monthly/archive/2016/2016_09/pmm_2016_09.cfm">September 2016</option>
                                                <option value="/petroleum/marketing/monthly/archive/2016/2016_08/pmm_2016_08.cfm">August 2016</option>
                                                <option value="/petroleum/marketing/monthly/archive/2016/2016_07/pmm_2016_07.cfm">July 2016</option>
                                                <option value="/petroleum/marketing/monthly/archive/2016/2016_06/pmm_2016_06.cfm">June 2016</option>
                                                <option value="/petroleum/marketing/monthly/archive/2016/2016_05/pmm_2016_05.cfm">May 2016</option>
                                                <option value="/petroleum/marketing/monthly/archive/2016/2016_04/pmm_2016_04.cfm">April 2016</option>
                                                <option value="/petroleum/marketing/monthly/archive/2016/2016_03/pmm_2016_03.cfm">March 2016</option>
                                                <option value="/petroleum/marketing/monthly/archive/2016/2016_02/pmm_2016_02.cfm">February 2016</option>
                                                <option value="/petroleum/marketing/monthly/archive/2016/2016_01/pmm_2016_01.cfm">January 2016</option>
                                                <option value="/petroleum/marketing/monthly/archive/2015/2015_12/pmm_2015_12.cfm">December 2015</option>
                                                <option value="/petroleum/marketing/monthly/archive/2015/2015_11/pmm_2015_11.cfm">November 2015</option>
                                                <option value="/petroleum/marketing/monthly/archive/2015/2015_10/pmm_2015_10.cfm">October 2015</option>
                                                <option value="/petroleum/marketing/monthly/archive/">prior issues</option>
                                        </select>
                                        <input type="button" name="go_button" class="arrow_go" id="go_button" value="Go" />
                                </form>
                        </span>
                </span>
        </div>
</div>
