<div class="l-row header report-details">
        <div class="l-split-wide">
        
                <a href="/petroleum/reports.cfm">&lsaquo; All Petroleum and Other Liquids Reports</a>
                <h2>Petroleum Marketing Monthly   <?php /* | <em>August 2012</em>*/ ?></h2>

                <div class="release-dates">
                        <div class="label-series">Data for January 2017</div><!-- /label-series -->
<                                <div class="date-container">
                                        <div class="label">Release Date:</div><!-- /label -->
                                <div class="date">April 3, 2017</div><!-- /date -->
                        </div><!-- /date-container -->
                        <div class="report-download-container">
                                <a href="pdf/pmmall.pdf"><i class="ico pdf"></i>full report</a>
                                </div>
                        </div>
                </div>
        </div>
        <div class="l-split-narrow gradient">
                <span class="form-container-outer">
                        <h4>Previous Issues</h4>
                        <span class="form-container-inner">

                                <form name="form" id="form">
                                        <label>Month:</label>
                                        <select name="jumpMenu" id="jumpMenu">
                                                <option value="/petroleum/marketing/monthly/archive/2017/2017_04/pmm_2017_04.cfm" selected="selected">April 2017</option>
<!--                                                <option value="/petroleum/marketing/monthly/archive/2011/2011_11/pmm_2011_11.html">November 2012</option>-->
                                                <option value="/petroleum/marketing/monthly/archive/2017/2017_03/pmm_2017_03.cfm">March 2017</option>
                                                <option value="/petroleum/marketing/monthly/archive/2017/2017_02/pmm_2017_02.cfm">February 2017</option>
                                                <option value="/petroleum/marketing/monthly/archive/2017/2017_01/pmm_2017_01.cfm">January 2017</option>
                                                <option value="/petroleum/marketing/monthly/archive/2016/2016_12/pmm_2016_12.cfm">December 2016</option>
                                                <option value="/petroleum/marketing/monthly/archive/2016/2016_11/pmm_2016_11.cfm">November 2016</option>
                                                <option value="/petroleum/marketing/monthly/archive/2016/2016_10/pmm_2016_10.cfm">October 2016</option>
                                                <option value="/petroleum/marketing/monthly/archive/2016/2016_09/pmm_2016_09.cfm">September 2016</option>
                                                <option value="/petroleum/marketing/monthly/archive/2016/2016_08/pmm_2016_08.cfm">August 2016</option>
                                                <option value="/petroleum/marketing/monthly/archive/2016/2016_07/pmm_2016_07.cfm">July 2016</option>
                                                <option value="/petroleum/marketing/monthly/archive/2016/2016_06/pmm_2016_06.cfm">June 2016</option>
                                                <option value="/petroleum/marketing/monthly/archive/2016/2016_05/pmm_2016_05.cfm">May 2016</option>
                                                <option value="/petroleum/marketing/monthly/archive/2016/2016_04/pmm_2016_04.cfm">April 2016</option>
                                                <option value="/petroleum/marketing/monthly/archive/">prior issues</option>
                                        </select>
                                        <input type="button" name="go_button" class="arrow_go" id="go_button" value="Go" />
                                </form>
                        </span>
                </span>
        </div>
</div>

