<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2017-04/fig_HL1coppwp2.png" class="lightbox"><img src="images/2017-04/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude oil</h2>
            <ul>
                <li>Monthly average prices for crude oil rose in January. The average domestic crude oil first purchase price increased $1.07 (2.3%), to $48.19 per barrel..</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil rose 18 cents (0.4%) to $44.74 per barrel. The average landed cost of foreign crude oil increased 20 cents (0.4%), to $46.53 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil climbed $1.36 (2.7%), to $51.81 per barrel. The average cost of imported crude oil increased $1.40 (3.0%), to $48.12 per barrel. The composite refiner acquisition cost for crude oil rose $1.33 (2.7%), to $49.99 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>Refiner monthly average prices for motor gasoline increased during January. The average retail price rose 5.1 cents to $1.900 per gallon, while the average wholesale price increased 4.3 cents to $1.628 per gallon.</li>
                <li>Refiner sales of finished motor gasoline decreased in January. Total sales fell 22.5 million gallons per day (7.0%) to an average of 300.1 million gallons per day. Retail sales declined 1.2 million gallons per day (5.0%), while wholesales fell 21.3 million gallons per day (7.1%). DTW sales accounted for 7.6% of wholesales, while rack and bulk sales made up 86.2% and 6.2%, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>Monthly average prices for refiner sales of No. 2 distillates increased in January. The average price for No. 2 diesel fuel sold to end users rose 3.0 cents to $1.748 per gallon, while the average wholesale price also increased 3.0 cents to $1.636 per gallon. The wholesale price for No. 2 fuel oil climbed 5.3 cents to $1.560 per gallon.</li>
                <li>Refiner sales of No. 2 ultra-low sulfur diesel fuel declined in January. Overall, sales decreased 11.1 million gallons per day (7.4%) to an average of 138.2 million gallons per day. Retail sales rose 500,000 gallons per day (4.3%), while wholesales declined 11.6 million gallons per day (8.4%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Refiner monthly average residual fuel oil prices climbed in January. The wholesale price for low-sulfur residual fuel oil rose 7.5 cents to $1.099 per gallon. Prices for high-sulfur residual fuel oil increased 4.3 cents to $1.249 per gallon at retail, while the wholesale price rose 9.0 cents to $1.121 per gallon.</li>
                <li>Sales of residual fuel oil by refiners declined in January. Retail sales fell 300,000 gallons per day (7.1%), while wholesales dropped 1.0 million gallons per day (13.2%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>Refiner prices for remaining surveyed products increased in January. Propane and kerosene-type jet fuel prices climbed at both the retail and wholesale levels, while prices for aviation gasoline, kerosene, and No. 1 distillate prices rose at wholesale.</li>
                <li>Refiner sales of products included in this section fell in January. Propane and kerosene-type jet fuel sales dropped at both retail and wholesale, while sales of aviation gasoline, kerosene, and No. 1 distillate also declined at the wholesale level.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>*/ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/petroleum/marketing/annual/archive/" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a></li>
    </ul>
</div>