
<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li>strong>Figure HL1.</strong> Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2014-02/fig_HL1coppwp.jpg" class="lightbox"><img src="images/2014-02/fig_HL1_coppwp_sm.jpg" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
        <li class="header"><h2>Crude Oil</h2>
            <ul>
                <li>Monthly average crude oil prices continued to decline in November.  The average domestic crude oil first purchase price fell $7.47 (7.8 percent), to $88.71 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil dropped $3.15 (3.4 percent), to $89.97 per barrel.  The average landed cost of foreign crude oil decreased $6.21 (6.5 percent), to $88.79 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil declined $6.91 (6.7 percent), to $96.09 per barrel.  The average cost of imported crude oil dropped $7.52 (7.7 percent), to $90.32 per barrel.  The composite refiner acquisition cost for crude oil decreased $7.11 (7.1 percent), to $93.30 per barrel.</li>
            </ul>
        </li>
        <li class="header"><h2>Petroleum Products</h2></li>
        <li><h4>Motor Gasoline</h4>
            <ul>
                <li>November monthly average prices for sales of finished gasoline by refiners show significant decreases from October levels.  The average retail sales price for motor gasoline declined 13.4 cents to $2.759 per gallon, while the average wholesale price fell 8.7 cents to $2.545 per gallon.</li>
                <li>The volume of finished motor gasoline sales by refiners increased modestly in November.  Total sales rose 900,000 gallons per day (0.3 percent) to an average of 316.4 million gallons per day.  Retail sales were flat, while wholesales increased 900,000 gallons per day (0.3 percent).  DTW sales made up 9.8 percent of wholesales, while rack and bulk sales accounted for 81.8 percent and 8.4 percent, respectively.</li>
            </ul>
        </li>
        <li><h4>No. 2 Distillate</h4>
            <ul>
                <li>Monthly average refiner prices for No. 2 distillates decreased in November.  The average sales price for No. 2 diesel fuel to end users fell 5.5 cents to $3.030 per gallon, while the average wholesale price dropped 5.7 cents to $2.949 per gallon.  The average wholesale price for No. 2 fuel oil declined 4.5 cents to $2.910 per gallon.</li>
                <li>Refiner sales of No. 2 diesel fuel sales decreased 10.5 million gallons per day (6.2 percent) in November.  In contrast, sales of No. 2 fuel oil rose 2.5 million gallons per day at the wholesale level.</li>
            </ul>
        </li>
        <li><h4>Residual Fuel Oil</h4>
            <ul>
                <li>Monthly average prices for refiner residual fuel oil sales fell in November.  The price for low-sulfur residual fuel oil decreased 4.2 cents to $2.296 per gallon at the wholesale level.  Prices for high-sulfur residual fuel oil declined 3.6 cents to $2.328 per gallon at retail, and 4.2 cents to $2.190 per gallon at wholesale.</li>
                <li>Sales of residual fuel oil by refiners edged lower in November, with total sales falling 100,000 gallons per day (0.8 percent).</li>
            </ul>
        </li>
        <li><h4>Other Products</h4>
            <ul>
                <li>Price trends for the remaining surveyed products were mixed in November.  Propane prices increased at both the retail and wholesale levels, while kerosene-type jet fuel and kerosene prices fell at both levels.  Prices for aviation gasoline increased at retail, but fell at wholesale, while No. 1 distillate prices show the opposite trend.   The wholesale price for No. 4 fuel oil decreased during November.</li>
                <li>Refiner sales of propane, kerosene, and No. 1 distillates increased at both retail and wholesale.  Kerosene-type jet fuel remained flat at the retail level, but fell at wholesale.  Aviation gasoline sales fell at retail, but increased at wholesale.  Sales of No. 4 distillate rose at wholesale during November.</li>
            </ul>
        </li>
    </ul>
</div>

<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
        <li><a href="pdf/preface.pdf">Preface</a></li>
        <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
        <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
        <li><a href="pdf/pguide.pdf">Product Guide</a></li>
        <li><a href="pdf/glossary.pdf">Glossary</a></li>
        <li><a href="pdf/artlist.pdf">List of Articles</a></li>
    </ul>
</div>
