<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2016-12/fig_HL1coppwp2.png" class="lightbox"><img src="images/2016-12/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude Oil</h2>
            <ul>
                <li>Monthly average crude oil prices show mixed changes in September. The average domestic crude oil first purchase price rose 8 cents (0.2%), to $40.54 per barrel..</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil fell 4 cents (0.1%) to $38.18 per barrel. The average landed cost of foreign crude oil decreased 12 cents (0.3%), to $39.99 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil rose 36 cents (0.8%), to $44.54 per barrel. The average cost of imported crude oil declined 39 cents (0.9%), to $40.82 per barrel. The composite refiner acquisition cost for crude oil increased 4 cents (0.1%), to $42.74 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>September monthly average prices for refiner sales of motor gasoline rose from August levels. The average retail price rose 3.4 cents to $1.788 per gallon, while the average wholesale price increased 0.6 cent to $1.514 per gallon.</li>
                <li>Refiner sales of finished motor gasoline fell in September. Total sales declined 7.1 million gallons per day (2.1%) to an average of 334.2 million gallons per day. Retail sales decreased 100,000 gallons per day (0.4%), while wholesales fell 7.0 million gallons per day (2.2%). DTW sales accounted for 7.6% of wholesales, while rack and bulk sales made up 85.0% and 7.5%, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>Monthly average prices for refiner sales of No. 2 distillates increased in September. The average price for No. 2 diesel fuel sold to end users rose 2.5 cents to $1.602 per gallon, while the average wholesale price increased 3.1 cents to $1.471 per gallon. The average wholesale price for No. 2 fuel oil climbed 3.4 cents to $1.341 per gallon.</li>
                <li>Refiner sales of No. 2 ultra-low sulfur diesel fuel dropped in September. Retail sales fell 400,000 gallons per day (3.0%), while wholesales decreased 700,000 gallons per day (0.5%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Monthly average prices for residual fuel oil sold by refiners climbed in September. The wholesale price for low-sulfur residual fuel oil rose 1.0 cent to 85.2 cents per gallon. Prices for high-sulfur residual fuel oil increased 13.3 cents to $1.057 per gallon at retail, while the wholesale price rose 4.0 cents to 85.1 cents per gallon.</li>
                <li>Sales of residual fuel oil by refiners were mixed in September. Retail sales rose 400,000 gallons per day (9.1%), while wholesales declined 1.0 million gallons per day (12.3%).</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>Changes in monthly average prices for refiner sales of the remaining surveyed products varied in September. Propane and kerosene-type jet fuel prices increased at both the retail and wholesale levels. No. 1 distillate prices also rose at retail, but fell at wholesale. The wholesale price for aviation gasoline increased, while the price for kerosene eased in the same sales category.</li>
                <li>Refiner sales of products included in this section show mixed trends in September. Propane sales fell at both the retail and wholesale levels, while sales of No. 1 distillate did the opposite. Kerosene-type jet fuel sales declined at the retail, but rose at wholesale. Aviation gasoline and kerosene sales fell at the wholesale level.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div> */ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a></li>
                <li><a href="http://www.eia.gov/petroleum/marketing/annual/archive/" ><i class="ico csv">CSV</i>Petroleum Marketing Annual Archives</a></li>
    </ul>
</div>