<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong> Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2014-01/fig_HL1coppwp.jpg" class="lightbox"><img src="images/2014-01/fig_HL1_coppwp_sm.jpg" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3>Highlights</h3></li>
        <li class="header"><h2>Crude Oil</h2>
            <ul>
                <li>Monthly average prices for crude oil show firm decreases in October.  The average domestic crude oil first purchase price declined $6.21 (6.1 percent), to $96.24 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil fell $5.93 (5.9 percent), to $95.04 per barrel.  The average landed cost of foreign crude oil declined $6.31 (6.2 percent), to $95.74 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil decreased $4.61 (4.3 percent), to $103.35 per barrel.  The average cost of imported crude oil dropped $5.52 (5.3 percent), to $97.97 per barrel.  The composite refiner acquisition cost for crude oil fell $5.18 (4.9 percent), to $100.52 per barrel.</li>
            </ul>
        </li>
        <li class="header"><h2>Petroleum Products</h2></li>
                <li><h4>Motor Gasoline</h4>
            <ul>
                <li>October monthly average prices for sales of finished gasoline by refiners show significant decreases from September levels.  The average retail sales price for motor gasoline fell 16.4 cents to $2.895 per gallon, while the average wholesale price declined 15.9 cents to $2.633 per gallon.</li>
                <li>Refiner sales of finished motor gasoline rose in October.  Total sales increased 2.5  million gallons per day (0.8 percent) to an average of 315.2 million gallons per day.  Retail sales rose 400,000 gallons per day (1.7 percent), while wholesales climbed 2.1 million gallons per day (0.7 percent).  DTW sales accounted for 9.8 percent of wholesales, while rack and bulk sales made up 82.9 percent and 7.3 percent, respectively.</li>
                    </ul>
        </li>
                <li><h4>No. 2 Distillate</h4>
            <ul>
                <li>Monthly average refiner prices for No. 2 distillates fell in October.  The average sales price for No. 2 diesel fuel to end users decreased 9.9 cents to $3.085 per gallon, while the average wholesale price declined 8.9 cents to $3.006 per gallon.  The average wholesale price for No. 2 fuel oil decreased 2.2 cents to $2.951 per gallon.</li>
                <li>Sales of No. 2 distillates by refiners were mostly on the increase during October.  No. 2 diesel fuel sales climbed 14.0 million gallons per day (9.1 percent).</li>
                    </ul>
        </li>
                <li><h4>Residual Fuel Oil</h4>
            <ul>
                <li>Monthly average prices for refiner residual fuel oil sales were on the decrease in October.  The price for low-sulfur residual fuel oil fell 1.5 cents to $2.344 per gallon at the wholesale level.  Prices for high-sulfur residual fuel oil declined 4.8 cents to $2.364 per gallon at retail, and 3.3 cents to $2.232 per gallon at wholesale.</li>
                <li>Sales of residual fuel oil by refiners rose in October, with total sales increasing 300,000 gallons per day (2.4 percent).</li>
                    </ul>
        </li>
                <li><h4>Other Products</h4>
            <ul>
                <li>Prices for many of the other surveyed products declined during October.  While propane prices rose at both retail and wholesale, prices for kerosene-type jet fuel, aviation gasoline, and No. 1 distillate fell at both levels.   Kerosene prices increased slightly at retail but declined at wholesale.  The wholesale price for No. 4 fuel oil also decreased.</li>
                <li>Refiner sales of propane and kerosene-type jet fuel fell at the retail level but increased at wholesale in October.  Aviation gasoline, kerosene, and No. 1 distillate climbed at both levels.  Sales of No. 4 distillate decreased at wholesale during October.</li>
            </ul>
        </li>
    </ul>
</div>

<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>