<div class="content-container">
    <ul class="resources">
        <li><i class="ico telephone"></i> 24-hour hotline: 202-586-6966</li>
        <li><i class="ico email"></i><a href="/tools/emailupdates/#petroleum">Sign up for email updates</a></li>
        <li><i class="ico rss"></i><a href="includes/gas_diesel_rss.xml">Get the RSS feed</a></li>
        <li><i class="ico calendar"></i> <a href="schedule.php">Release Schedule</a></li>
        <li><i class="ico radio"></i><a href="/radio/">Radio spots</a></li>
    </ul>
</div>
<?php include ('highchart_gdu.php') ; ?>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Details...</h2></li>
        <li class="sub-header">Procedures, Methodology &amp; CV's</li>
        <li><a href="/petroleum/gasdiesel/gas_proc-methods.php">Gasoline</a></li>
        <li><a href="/petroleum/gasdiesel/diesel_proc-methods.php">Diesel fuel</a></li>
        <li class="sub-header">Geographical</li>
        <li>Gasoline:
            <ul>
                <li><a href="/petroleum/gasdiesel/gas_geographies.php#pricesbyregion">Gasoline prices by region</a></li>
                <li><a href="/petroleum/gasdiesel/gas_geographies.php#reformulatedmap">Reformulated gasoline map</a></li>
                <li><a href="/petroleum/gasdiesel/gas_geographies.php#statesmap">Map of states in each region</a></li>
                <li><a href="/petroleum/gasdiesel/gas_geographies.php#city-county">Gasoline city definitions</a></li>
            </ul>
        </li>
        <li>Diesel Fuel:
            <ul>
                <li><a href="diesel_map.php">Map of states in each region</a></li>
            </ul>
        </li>
        <li class="sub-header">Other</li>
        <li><a href="/petroleum/gasdiesel/pump_methodology.php">Pump methodology and data history</a></li>
        <li><a href="/petroleum/marketing/monthly/xls/fueltaxes.xls"><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
        <li class="footer"><a href="/petroleum/gasdiesel/learnmore.php">Learn more</a></li>
    </ul>
</div>





<div class="content-container faq">
    <ul>
        <li class="header"><h2><a href="/tools/faqs/faq.cfm?id=1&t=10">What's up (and down) with gasoline prices?</a></h2></li>
        <li><li class="sub-header">See all FAQs on Gasoline</a></li>
        <li><li class="sub-header">FAQs for EIA-878 survey</a></li>
    </ul>
</div>
<div class="content-container faq">
    <ul>
        <li class="header"><h2><a href="/tools/faqs/faq.cfm?id=2&t=9">How do I calculate/find diesel fuel surcharges?</a></h2></li>
        <li><li class="sub-header">See all FAQs on Diesel Fuel</a></li>
        <li><li class="sub-header">FAQs for EIA-888 survey</a></li>
    </ul>
</div>
