<div class="content-container light-top-border-container grey-background">    <ul>
        <li class="header"><h2>Procedures &amp; Methodology</h2></li>
<li class="sub-header"> Gasoline</li>
                <li><a href="gas_procedure.php">Data collection procedures</a></li>
                <li><a href="gas_methodology.php">Sampling methodology</a>  </li>
                <li><a href="sampling_error_report.php">Coefficient of variation</a></li>
                <li><a href="reformulated_map.php#reformulatedmap">Map of reformulated gasoline</a></li>
                <li><a href="reformulated_map.php#statesmap">Map of states in each region</a></li>
                <li><a href="gas_nyc_counties.php">NYC Metro Area Counties</a></li>
<li class="sub-header">Diesel</li>
                <li><a href="diesel_procedure.php">Data collection procedures</a></li>
                <li><a href="diesel_methodology.php">Sampling methodology</a></li>
                <li><a href="sampling_error.php">Coefficient of variation</a></li>
                <li><a href="diesel_map.php">Map of states in each region</a></li>
<li class="sub-header">Gasoline and Diesel</li>
                <li><i class="ico xls">XLS</i><a href="/petroleum/marketing/monthly/xls/fueltaxes.xls">Federal and state motor fuel taxes</a></li>
                <li><a href="pump_methodology.php">Pump methodology</a></li>
                <li><a href="gaspump_hist.php">Gasoline pump data history</a></li>
                <li><a href="dieselpump_hist.php">Diesel fuel pump data history</a></li>
    </ul>
