<div class="content-container light-top-border-container grey-background"><ul class="resources">
        <li><i class="ico telephone"></i>24-hour hotline: 202-586-6966</li>
                <li><i class="ico email"></i> <a href="/tools/emailupdates/#petroleum">Sign up for email updates</a></li>
                <li><i class="ico rss"></i> <a href="includes/gas_diesel_rss.xml">Get the RSS feed</a></li>
                <li><i class="ico calendar"></i> <a href="schedule.php">Release Schedule</a></li>
    </ul>
</div>
<?php include ('../highchart_gdu.php') ; ?>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Procedures &amp; Methodology</h2></li>
<li class="sub-header"> Gasoline</li>
                <li><a href="gas_procedure.php">Data collection procedures</a></li>
                <li><a href="gas_methodology.php">Sampling methodology</a> </li>
                <li><a href="sampling_error_report.php">Coefficient of variation</a></li>
                <li><a href="reformulated_map.php#reformulatedmap">Map of reformulated gasoline</a></li>
                <li><a href="reformulated_map.php#statesmap">Map of states in each region</a></li>
                <li><a href="gas_nyc_counties.php">NYC Metro Area Counties</a></li>
<li class="sub-header">Diesel</li>
                <li><a href="diesel_procedure.php">Data collection procedures</a></li>
                <li><a href="diesel_methodology.php">Sampling methodology</a> </li>
                <li><a href="sampling_error.php">Coefficient of variation</a></li>
                <li><a href="diesel_map.php">Map of states in each region</a></li>
<li class="sub-header">Gasoline and Diesel</li>
                <li><a href="/petroleum/marketing/monthly/xls/fueltaxes.xls"><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pump_methodology.php">Pump methodology</a></li>
                <li><a href="gaspump_hist.php">Gasoline pump data history</a></li>
                <li><a href="dieselpump_hist.php">Diesel fuel pump data history</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related Links</h2></li>
                <li><a href="/energyexplained/index.cfm?page=gasoline_factors_affecting_prices">Gasoline Explained</a></li>
                <li><a href="/energyexplained/index.cfm?page=diesel_prices">Diesel Fuel Explained</a></li>
                <li><a href="/energyexplained/index.cfm?page=gasoline_where">Where Our Gasoline Comes From</a></li>
                <li><a href="/outlooks/steo/realprices/">Real Petroleum Prices</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>        <li><a href="/tools/faqs/index.cfm">Frequently Asked Questions</a></h2></li>
                <li><a href="/tools/faqs/faq.cfm?id=21&t=10">Can I tell where the gasoline at my local station comes from?</a></li>
                <li><a href="/tools/faqs/faq.cfm?id=2&t=9">Does EIA calculate diesel fuel surcharges?</a></li>
    </ul>
</div>
