<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Details...</h2></li>
        <li class="sub-header"> Procedures, Methodology &amp; CV's</li>
        <li><a href="/petroleum/gasdiesel/gas_proc-methods.php">Gasoline</a></li>
        <li><a href="/petroleum/gasdiesel/diesel_proc-methods.php">Diesel fuel</a></li>
        <li class="sub-header"> Geographical</li>
        <li>Gasoline:
            <ul class="square">
                <li><a href="/petroleum/gasdiesel/gas_geographies.php#pricesbyregion">Gasoline prices by region</a></li>
                <li><a href="/petroleum/gasdiesel/gas_geographies.php#reformulatedmap">Reformulated gasoline map</a></li>
                <li><a href="/petroleum/gasdiesel/gas_geographies.php#statesmap">Map of states in each region</a></li>
                <li><a href="/petroleum/gasdiesel/gas_geographies.php#city-county">Gasoline city definitions</a></li>
            </ul>
        </li>
        <li>Diesel Fuel:
            <ul class="square">
                <li><a href="diesel_map.php">Map of states in each region</a></li>
            </ul>
        </li>
        <li class="sub-header">Other</li>
        <li><a href="/petroleum/gasdiesel/pump_methodology.php">Pump methodology and data history</a></li>
        <li><a href="/petroleum/marketing/monthly/xls/fueltaxes.xls"><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
        <li class="footer"><a href="/petroleum/gasdiesel/learnmore.php">Learn more</a></li>
    </ul>
</div>





<div class="content-container faq">
    <ul>
        <li class="header"><h2><a href="/tools/faqs/faq.cfm?id=1&t=10">What's up (and down) with gasoline prices?</a></h2></li>
        <li class="sub-header"><a href="/tools/faqs/#gasoline">See all FAQs on Gasoline</a></li>
        <li class="sub-header"><a href="/survey/#eia-878">FAQs for EIA-878 survey</a></li>
    </ul>
</div>
<div class="content-container faq">
    <ul>
        <li class="header"><h2><a href="/tools/faqs/faq.cfm?id=2&t=9">How do I calculate/find diesel fuel surcharges?</a></h2></li>
        <li class="sub-header"><a href="/tools/faqs/#diesel">See all FAQs on Diesel Fuel</a></li>
        <li class="sub-header"><a href="/survey/#eia-888">FAQs for EIA-888 survey</a></li>
    </ul>
</div>
