<div class="l-row header report-details">
        <div class="l-split-wide">
        
                <a href="/petroleum/reports.cfm">&lsaquo; See all Petroleum Reports</a>
                <h2>Gasoline and Diesel Fuel Update Notice</h2>

                <div class="release-dates">
                        <div class="date-container">
                                <div class="label">Released:</div>
                                <div class="date">October 31, 2011</div>
                        </div>
                </div>
        </div>
        <div class="l-split-narrow gradient">
                <span class="form-wrapper-outer">
                        <h4>Previous Issues</h4>
                        <span class="form-wrapper-inner">
                                <form name="form" id="form">
<label>historical data (XLS):</label>
                                        <select name="jumpMenu" id="jumpMenu">
                                                <option value="archive/afvs2008.xls" selected="selected">2008</option>
                                                <option value="archive/afvs2007.xls">2007</option>
                                                <option value="archive/afvs2006.xls">2006</option>
                                                <option value="archive/afvs2005.xls">2005</option>
                                                <option value="archive/afvs2004.xls">2004</option>
                                                <option value="archive/afvs2003.xls">2003</option>
                                                <option value="archive/afvs2002.xls">2002</option>
                                                <option value="archive/afvs2001.xls">2001</option>
                                                <option value="archive/afvs2000.xls">2000</option>
                                                <option value="archive/afvs1999.xls">1999</option>
                                                <option value="archive/afvs1998.xls">1998</option>
                                                <option value="archive/afvs1997.xls">1997</option>
                                                <option value="archive/afvs1996.xls">1996</option>
                                                <option value="archive/afvs1995.xls">1995</option>
                                                <option value="archive/afvs1994.xls">1994</option>
                                        </select>
                                        <input type="button" name="go_button" class="arrow_go" id="go_button" value="Go" />
                                </form>
                        </span>
                </span>
        </div>
</div>

