<div class="l-row header report-details">
        <div class="l-full-width-column">
                <a href="/petroleum/reports.cfm">&lsaquo; See all petroleum reports</a>
                <h2>Gasoline and Diesel Fuel Update</h2>

                <div class="release-dates">
                        <div class="date-container">
                                <div class="label">Gasoline Release Date:</div>
                                <div class="date">September 11, 2017</div>
</div>	<div class="date-container">
                                <div class="label">Next Release Date:</div>
                                <div class="date">September 18, 2017</div>
                        </div>
                        <div class="date-container">
                                <div class="label">Diesel Fuel Release Date:</div>
                                <div class="date">September 11, 2017</div>
</div>	<div class="date-container">
                                <div class="label">Next Release Date:</div>
                                <div class="date">September 18, 2017</div>
</div>
</div>
</div>
</div>
<script>
$(document).ready(function() {
var patCfm = /\.cfm/i;
var patPhp = /\.php/i;
var patIndex = /\/index/i;
if ((patCfm.test(window.location.href) || patPhp.test(window.location.href)) && !patIndex.test(window.location.href)) {
$('.report-details a:first')
.html('&lsaquo; Gasoline and Diesel Fuel Update HOME')
.attr('href', '/petroleum/gasdiesel/');
}
});
</script>
