<div class="l-row header report-details">
        <div class="l-full-width-column">
                <a href="/petroleum/gasdiesel/">&lsaquo; Gasoline and Diesel Fuel Update</a>
                <h2>Gasoline and Diesel Fuel Update Data Revision Notice</h2>

                <div class="release-dates">
                        <div class="date-container">
                                <div class="label">Release Date:</div>
                                <div class="date">June 18, 2012</div>
</div>
</div>
</div>
</div>
