      <br />
<div class="side_col right">
        <?php /* Side Column */ ?>
        <span class="grey_side blue_top">
        <p class="no_btm_border"><a class="ico_pdf" href="pdf/energy_market_alert_Jan_9_2014.pdf">Full report</a></p>
        <br /><br />
        <h4>Previous alerts</h4>
         <p class="no_btm_border"><a class="ico_pdf" href="pdf/energy_market_alert_Jan_8_2014.pdf">January 8, 2014</a></p>
         <p><a class="ico_pdf" href="pdf/energy_market_alert_Jan_7_2014.pdf">January 7, 2014</a></p>
        <br />
        
        Northeastern Summer Electricity Market Alerts 2013
        <p class="no_btm_border"><a class="ico_pdf" href="pdf/energy_market_alert_July_19_2013.pdf">July 19, 2013</a></p>
        <p class="no_btm_border"><a class="ico_pdf" href="pdf/energy_market_alert_July_18_2013.pdf">July 18, 2013</a></p>
         <p><a class="ico_pdf" href="pdf/energy_market_alert_July_17_2013.pdf">July 17, 2013</a></p>  
   
        <br />
        Northeastern Winter Natural Gas and Electricity Alerts 2013
        <p class="no_btm_border"><a class="ico_pdf" href="pdf/energy_market_alert_Jan_25_2013.pdf">January 25, 2013</a></p>
        <p class="no_btm_border"><a class="ico_pdf" href="pdf/energy_market_alert_Jan_24_2013.pdf">January 24, 2013</a></p>
        <p class="no_btm_border"><a class="ico_pdf" href="pdf/energy_market_alert_Jan_23_2013.pdf">January 23, 2013</a></p>
        <p><a class="ico_pdf" href="pdf/energy_market_alert_Jan_22_2013.pdf">January 22, 2013</a></p>
        <br /><br />
  <?php /*<h4>Related report</h4>
         <p class="no_btm_border"><a class="ico_pdf" href="/forecasts/steo/special/pdf/2013_sp_01.pdf">Short-Term Energy Outlook Supplement:
Constraints in New England likely to affect regional energy prices
this winter</a></p>*/ ?></span><br />
          <?php /*<a class="ico_pdf" href="../fe/pdf/appa.pdf">Appendix A-Request Letter</a><br />
        <a class="ico_pdf" href="../fe/pdf/appb.pdf">Appendix B-Summary Tables</a> <br />*/ ?>
          <?php /* <a class="ico_pdf" href="../ces_bingaman/pdf/appc.pdf">Appendix C-Map of NEMS Electricity Market Module Regions</a><br />*/ ?>
          <?php /*<a class="ico_pdf" href="../ces_hall/pdf/errata.pdf">Updates</a>*/ ?></p>
</div>

      <?php /*/ Side Content */ ?>

