<div class="content-container">
    <ul>
        <li><h2>Highlights</h2></li>
        <li><strong>Figure HL1.</strong>Crude Oil and Petroleum Product Wholesale Prices</li>
                <li><div class="image-container"><a href="images/2014-08/fig_HL1coppwp2.png" class="lightbox"><img src="images/2014-08/fig_HL1_coppwp_sm2.png" /></a></li>
                <li><a href="pdf/pmmgraphic.pdf" ><i class="ico pdf">PDF</i>Download Figure Data</a></li>
    </ul>
</div>
<div class="content-container">
    <ul>
        <li class="sub-header"><h3><strong>Highlights</strong></h3></li>
                <li><h2 class="strong">Crude Oil</h2>
            <ul>
                <li>Monthly average crude oil prices experienced a range of changes during May.  The average domestic crude oil first purchase price fell 73 cents (0.8 percent), to $95.74 per barrel.</li>
                <li>The average free-on-board (f.o.b.) cost of imported crude oil increased $1.90 (2.0 percent), to $96.62 per barrel.  The average landed cost of foreign crude oil rose $1.19 (1.2 percent), to $97.36 per barrel.</li>
                <li>The average refiner acquisition cost for domestic crude oil rose 9 cents (0.1 percent), to $102.51 per barrel.  The average cost of imported crude oil climbed $1.49 (1.5 percent), to $98.79 per barrel.  The composite refiner acquisition cost for crude oil rose 74 cents (0.7 percent), to $100.81 per barrel.</li>    </ul><br /><h2>Petroleum products</h2><h5 style="margin-bottom:-8px">Motor gasoline</h5>    <ul>        <li>May monthly average prices for refiner sales of motor gasoline show mixed trends.  The average retail price rose 2.5 cents to $3.239 per gallon, while the average wholesale price declined 3.0 cents to $2.951 per gallon.</li>
                <li>Sales of finished motor gasoline by refiners increased again during May.  Total sales rose 4.6 million gallons per day (1.5 percent) to an average of 313.7 million gallons per day.  Retail sales increased 400,000 gallons per day (2.0 percent), while wholesales climbed 4.2 million gallons per day (1.5 percent).  DTW sales accounted for 7.9 percent of wholesales, while rack and bulk sales made up 85.5 percent and 6.5 percent, respectively.</li>    </ul><br /><h5 style="margin-bottom:-8px">No. 2 distillate</h5>    <ul>        <li>Monthly average refiner prices for No. 2 distillates continued to decline in May.  The average sales price for No. 2 diesel fuel to end users fell 2.7 cents to $3.082 per gallon, while the average wholesale price decreased 4.0 cents to $2.987 per gallon.  The average price for No. 2 fuel oil sales to end users declined 2.6 cents to $3.546 per gallon, while the average wholesale price dropped 2.2 cents to $2.889 per gallon.</li>
                <li>Refiner sales of No. 2 ultra-low sulfur diesel fuel increased 5.2 million gallons per day (3.4 percent) to an average of 156.0 million gallons per day in May.  No. 2 fuel oil sales increased 700,000 gallons per day (15.5 percent) to an average of 5.2 million gallons per day.</li>    </ul><br /><h5 style="margin-bottom:-8px">Residual fuel oil</h5>    <ul>        <li>Monthly average prices for residual fuel oil sales by refiners varied during May.  The wholesale price for low-sulfur residual fuel oil decreased 5.1 cents to $2.350 per gallon.  Prices for high-sulfur residual fuel oil decreased 2.3 cents to $2.300 per gallon at retail, but rose 4.9 cents to $2.198 per gallon at wholesale</li>
                <li>Refiner sales of residual fuel oil declined in May.  Total sales fell 3.3 million gallons per day (23.1 percent) to an average of 11.0 million gallons per day.</li>    </ul><br /><h5 style="margin-bottom:-8px">Other products</h5>    <ul>        <li>Price trends for other surveyed products were mixed in May.  Propane prices decreased at both the retail and wholesale levels, while kerosene-type jet fuel prices moved in the opposite direction.  Prices for kerosene fell at retail, but show a slight increase at wholesale.  The price for No. 1 distillate increased at wholesale, while the aviation gasoline wholesale price declined during May.</li>
                <li>Refiner sales of propane increased at retail, but fell at wholesale.  Kerosene-type jet fuel sales declined at retail and remained flat at wholesale, while kerosene sales decreased at both levels.  No. 1 distillate sales fell at wholesale.</li>
    </ul>
</div><?php /*        <li><a href="pdf/hilites.pdf">Read all highlights...</a></li>
    </ul>
</div>
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Sections</h2></li>
                <li><a href="pdf/pmmall.pdf">Full Report</a></li>
                <li><a href="#">Feature Article</a></li>
                <li><a href="pdf/preface.pdf">Preface</a></li>
                <li><a href="pdf/enote.pdf">Explanatory Notes</a></li>
                <li><a href="pdf/mgt.pdf">Motor Fuel Taxes</a></li>
                <li><a href="pdf/pguide.pdf">Product Guide</a></li>
                <li><a href="pdf/glossary.pdf">Glossary</a></li>
                <li><a href="pdf/artlist.pdf">List of Articles</a></li>    </ul>
</div>*/ ?><br />
<div class="content-container light-top-border-container grey-background">
    <ul>
        <li class="header"><h2>Related information</h2></li>
                <li><a href="pdf/enote.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing explanatory notes</a></li>
                <li><a href="xls/fueltaxes.xls" ><i class="ico xls">XLS</i>Federal and state motor fuel taxes</a></li>
                <li><a href="pdf/paddmap.pdf" ><i class="ico pdf">PDF</i>Petroleum administration for defense district (PADD) map</a></li>
                <li><a href="pdf/pguide.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing product guide</a></li>
                <li><a href="pdf/glossary.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing glossary</a></li>
                <li><a href="pdf/artlist.pdf" ><i class="ico pdf">PDF</i>Petroleum marketing list of articles</a>